LABEL batocera.linux
    LINUX /boot/linux
    FDT /boot/rk3568-anbernic-rg-ds.dtb
    APPEND initrd=/boot/initrd.lz4 label=BATOCERA rootwait quiet loglevel=0 console=tty3 console=ttyS2,1500000n8 vt.global_cursor_default=0
