#!/bin/bash

if test "$1" = "start"
then
    amixer sset 'FRDDR_A SINK 1 SEL' 'OUT 1'
    amixer sset 'FRDDR_A SRC 1 EN' 'on'
    amixer sset 'TDMOUT_B SRC SEL' 'IN 0'
    amixer sset 'TOHDMITX I2S SRC' 'I2S B'
    amixer sset 'TOHDMITX' 'on'
fi
