#!/bin/bash

case "${1}" in
start)
  ds4drv --hidraw --daemon --daemon-pid /var/run/ds4drv.pid --daemon-log /var/log/ds4drv.log
;;
stop)
  NPID=$(cat /var/run/ds4drv.pid)
  kill -9 "${NPID}"
  rm -f /var/run/ds4drv.pid
;;
esac
