#!/usr/bin/python

import sys
import pyudev
import evdev
import hashlib
import re
from os.path import basename
from os.path import dirname

def findParentAny(device):
    p = device.find_parent('bluetooth')
    if p is None:
        p = device.find_parent('usb')
    return p

def findUsbParentInputs(ctx, event):
    for device in ctx.list_devices(subsystem='input'):
        if basename(device.device_path) == event:
            return findParentAny(device)
    raise Exception("unable to find the usb parent for " + event)

def findUsbParentVideos(ctx, video):
    for device in ctx.list_devices(subsystem='video4linux'):
        if basename(device.device_path) == video:
            return findParentAny(device)
    raise Exception("unable to find the usb parent for " + video)

def findChildrenInputs(ctx, parenthash):
    children = []
    for device in ctx.list_devices(subsystem='input'):
        if basename(device.device_path)[0:5] == "event":
            curparent = findParentAny(device)
            if curparent is not None:
                if parent2hash(curparent) == parenthash:
                    event = evdev.InputDevice('/dev/input/' + basename(device.device_path))
                    children.append({ "event": "/dev/input/"+basename(device.device_path), "name": event.name })
    return children

def findChildrenVideos(ctx, parenthash):
    children = []
    for device in ctx.list_devices(subsystem='video4linux'):
        if basename(device.device_path)[0:5] == "video":
            curparent = findParentAny(device)
            if curparent is not None:
                if parent2hash(curparent) == parenthash:
                    children.append({ "video": "/dev/"+basename(device.device_path)})
    return children

def parent2hash(parent):
    return hashlib.md5(devicepathWithoutConf(parent.device_path).encode('utf-8')).hexdigest()

def devicepathWithoutConf(path):
    return dirname(path)

def do_help():
    print("evsieve-helper parent-inputs <event>", file=sys.stderr)
    print("evsieve-helper parent-videos <event>", file=sys.stderr)
    print("evsieve-helper children-inputs <parent>", file=sys.stderr)
    print("evsieve-helper children-videos <parent>", file=sys.stderr)

if len(sys.argv) != 3:
    do_help()
    sys.exit(1)

ctx = pyudev.Context()

if sys.argv[1] == "parent-inputs":
    event = sys.argv[2]
    print(parent2hash(findUsbParentInputs(ctx, basename(event))))
    exit(0)
elif sys.argv[1] == "parent-inputs-raw":
    event = sys.argv[2]
    parent = findUsbParentInputs(ctx, basename(event))
    print(devicepathWithoutConf(parent.device_path))
    exit(0)
elif sys.argv[1] == "parent-videos":
    event = sys.argv[2]
    print(parent2hash(findUsbParentVideos(ctx, basename(event))))
    exit(0)
elif sys.argv[1] == "parent-videos-raw":
    event = sys.argv[2]
    parent = findUsbParentVideos(ctx, basename(event))
    print(devicepathWithoutConf(parent.device_path))
    exit(0)

elif sys.argv[1] == "children-inputs":
    parenthash = sys.argv[2]
    children = findChildrenInputs(ctx, parenthash)
    for child in children:
        print("{}\t{}".format(child["event"], child["name"]))
    exit(0)
elif sys.argv[1] == "children-videos":
    parenthash = sys.argv[2]
    children = findChildrenVideos(ctx, parenthash)
    for child in children:
        print("{}".format(child["video"]))
    exit(0)
else:
    do_help()
    sys.exit(1)
