#!/bin/bash -e

if [ "$USER" != "root" ]; then
    echo "This script must be runned as root user."
    exit 1
fi

SDCARD_IMG_FILE_PATH="${1}"
SDCARD_DEVICE_FILE_PATH="${2}"

if [[ -z "${SDCARD_IMG_FILE_PATH}" || "${SDCARD_IMG_FILE_PATH}" != *.zip ]]; then
    echo "Invalid sdcard img, it must be a zip file generated by mk-sdcard-img.sh."
    exit 1
fi

if [ -z "${SDCARD_DEVICE_FILE_PATH}" ]; then
    echo "Invalid block device."
    exit 1
fi

echo "Writing ${SDCARD_IMG_FILE_PATH} to ${SDCARD_DEVICE_FILE_PATH}..."
unzip -p "${SDCARD_IMG_FILE_PATH}" | dd of="${SDCARD_DEVICE_FILE_PATH}" bs=4M || exit 1
sync

echo
echo "Done."
