[retropad]
AnalogDeadzone = "0,0"
AnalogPeak = "32768,32768"
l3 = "Mempak switch"
r3 = "Rumblepak switch"
a = "C Button R"
b = "A Button"
x = "C Button U"
y = "B Button"
start = "Start"
select = ""
pageup = "L Trig"
pagedown = "R Trig"
l2 = "Z Trig"
r2 = ""
up = "DPad U"
down = "DPad D"
right = "DPad R"
left = "DPad L"
joystick1up = "Y Axis"
joystick1down = "Y Axis"
joystick1left = "X Axis"
joystick1right = "X Axis"
joystick2up = "C Button U"
joystick2down = "C Button D"
joystick2left = "C Button L"
joystick2right = "C Button R"

[n64]
AnalogDeadzone = "0,0"
AnalogPeak = "32768,32768"
l3 = "Mempak switch"
r3 = "Rumblepak switch"
a = "B Button"
b = "A Button"
x = "C Button U"
y = "C Button L"
start = "Start"
select = "Z Trig"
pageup = "L Trig"
pagedown = "R Trig"
l2 = "C Button D"
r2 = "C Button R"
up = "DPad U"
down = "DPad D"
right = "DPad R"
left = "DPad L"
joystick1up = "Y Axis"
joystick1down = "Y Axis"
joystick1left = "X Axis"
joystick1right = "X Axis"
joystick2up = ""
joystick2down = ""
joystick2left = ""
joystick2right = ""
