from ctypes import _CData, _Pointer
from typing import Any

class AttributeDict(dict[str, Any]):
    def __getattr__(self, key: str) -> Any: ...

def get_pointer[T: _CData](ctypes_obj: T) -> _Pointer[T]: ...
def prettywarn(msg: str, warntype: type[Warning]) -> None: ...
