__all__ = [
    'SDL_GetClipboardText',
    'SDL_GetPrimarySelectionText',
    'SDL_HasClipboardText',
    'SDL_HasPrimarySelectionText',
    'SDL_SetClipboardText',
    'SDL_SetPrimarySelectionText',
]

def SDL_SetClipboardText(text: bytes | None, /) -> int: ...
def SDL_GetClipboardText() -> bytes | None: ...
def SDL_HasClipboardText() -> int: ...
def SDL_SetPrimarySelectionText(text: bytes | None, /) -> int: ...
def SDL_GetPrimarySelectionText() -> bytes | None: ...
def SDL_HasPrimarySelectionText() -> int: ...
