from ctypes import c_void_p

__all__ = [
    'SDL_CACHELINE_SIZE',
    'SDL_GetCPUCacheLineSize',
    'SDL_GetCPUCount',
    'SDL_GetSystemRAM',
    'SDL_Has3DNow',
    'SDL_HasARMSIMD',
    'SDL_HasAVX',
    'SDL_HasAVX2',
    'SDL_HasAVX512F',
    'SDL_HasAltiVec',
    'SDL_HasLASX',
    'SDL_HasLSX',
    'SDL_HasMMX',
    'SDL_HasNEON',
    'SDL_HasRDTSC',
    'SDL_HasSSE',
    'SDL_HasSSE2',
    'SDL_HasSSE3',
    'SDL_HasSSE41',
    'SDL_HasSSE42',
    'SDL_SIMDAlloc',
    'SDL_SIMDFree',
    'SDL_SIMDGetAlignment',
    'SDL_SIMDRealloc',
]

SDL_CACHELINE_SIZE: int

def SDL_GetCPUCount() -> int: ...
def SDL_GetCPUCacheLineSize() -> int: ...
def SDL_HasRDTSC() -> int: ...
def SDL_HasAltiVec() -> int: ...
def SDL_HasMMX() -> int: ...
def SDL_Has3DNow() -> int: ...
def SDL_HasSSE() -> int: ...
def SDL_HasSSE2() -> int: ...
def SDL_HasSSE3() -> int: ...
def SDL_HasSSE41() -> int: ...
def SDL_HasSSE42() -> int: ...
def SDL_GetSystemRAM() -> int: ...
def SDL_HasAVX() -> int: ...
def SDL_HasAVX2() -> int: ...
def SDL_HasAVX512F() -> int: ...
def SDL_HasARMSIMD() -> int: ...
def SDL_HasNEON() -> int: ...
def SDL_HasLSX() -> int: ...
def SDL_HasLASX() -> int: ...
def SDL_SIMDGetAlignment() -> int: ...
def SDL_SIMDAlloc(length: int, /) -> int | None: ...
def SDL_SIMDRealloc(mem: c_void_p | int | None, length: int, /) -> int | None: ...
def SDL_SIMDFree(ptr: c_void_p | int | None, /) -> None: ...
