__all__ = [
    'SDL_BIG_ENDIAN',
    'SDL_BYTEORDER',
    'SDL_LIL_ENDIAN',
    'SDL_Swap16',
    'SDL_Swap32',
    'SDL_Swap64',
    'SDL_SwapBE16',
    'SDL_SwapBE32',
    'SDL_SwapBE64',
    'SDL_SwapFloat',
    'SDL_SwapFloatBE',
    'SDL_SwapFloatLE',
    'SDL_SwapLE16',
    'SDL_SwapLE32',
    'SDL_SwapLE64',
]

SDL_LIL_ENDIAN: int
SDL_BIG_ENDIAN: int
SDL_BYTEORDER: int

def SDL_Swap16(x: int) -> int: ...
def SDL_Swap32(x: int) -> int: ...
def SDL_Swap64(x: int) -> int: ...
def SDL_SwapFloat(x: float) -> float: ...
def SDL_SwapLE16(x: int) -> int: ...
def SDL_SwapLE32(x: int) -> int: ...
def SDL_SwapLE64(x: int) -> int: ...
def SDL_SwapFloatLE(x: float) -> float: ...
def SDL_SwapBE16(x: int) -> int: ...
def SDL_SwapBE32(x: int) -> int: ...
def SDL_SwapBE64(x: int) -> int: ...
def SDL_SwapFloatBE(x: float) -> float: ...
