from ctypes import _CFuncPtr, c_int

__all__ = [
    'SDL_HINT_ACCELEROMETER_AS_JOYSTICK',
    'SDL_HINT_ALLOW_ALT_TAB_WHILE_GRABBED',
    'SDL_HINT_ALLOW_TOPMOST',
    'SDL_HINT_ANDROID_APK_EXPANSION_MAIN_FILE_VERSION',
    'SDL_HINT_ANDROID_APK_EXPANSION_PATCH_FILE_VERSION',
    'SDL_HINT_ANDROID_BLOCK_ON_PAUSE',
    'SDL_HINT_ANDROID_BLOCK_ON_PAUSE_PAUSEAUDIO',
    'SDL_HINT_ANDROID_SEPARATE_MOUSE_AND_TOUCH',
    'SDL_HINT_ANDROID_TRAP_BACK_BUTTON',
    'SDL_HINT_APPLE_TV_CONTROLLER_UI_EVENTS',
    'SDL_HINT_APPLE_TV_REMOTE_ALLOW_ROTATION',
    'SDL_HINT_APP_NAME',
    'SDL_HINT_AUDIODRIVER',
    'SDL_HINT_AUDIO_CATEGORY',
    'SDL_HINT_AUDIO_DEVICE_APP_NAME',
    'SDL_HINT_AUDIO_DEVICE_STREAM_NAME',
    'SDL_HINT_AUDIO_DEVICE_STREAM_ROLE',
    'SDL_HINT_AUDIO_INCLUDE_MONITORS',
    'SDL_HINT_AUDIO_RESAMPLING_MODE',
    'SDL_HINT_AUTO_UPDATE_JOYSTICKS',
    'SDL_HINT_AUTO_UPDATE_SENSORS',
    'SDL_HINT_BMP_SAVE_LEGACY_FORMAT',
    'SDL_HINT_DEFAULT',
    'SDL_HINT_DIRECTINPUT_ENABLED',
    'SDL_HINT_DISPLAY_USABLE_BOUNDS',
    'SDL_HINT_EMSCRIPTEN_ASYNCIFY',
    'SDL_HINT_EMSCRIPTEN_KEYBOARD_ELEMENT',
    'SDL_HINT_ENABLE_SCREEN_KEYBOARD',
    'SDL_HINT_ENABLE_STEAM_CONTROLLERS',
    'SDL_HINT_EVENT_LOGGING',
    'SDL_HINT_FORCE_RAISEWINDOW',
    'SDL_HINT_FRAMEBUFFER_ACCELERATION',
    'SDL_HINT_GAMECONTROLLERCONFIG',
    'SDL_HINT_GAMECONTROLLERCONFIG_FILE',
    'SDL_HINT_GAMECONTROLLERTYPE',
    'SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES',
    'SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT',
    'SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS',
    'SDL_HINT_GRAB_KEYBOARD',
    'SDL_HINT_HIDAPI_IGNORE_DEVICES',
    'SDL_HINT_IDLE_TIMER_DISABLED',
    'SDL_HINT_IME_INTERNAL_EDITING',
    'SDL_HINT_IME_SHOW_UI',
    'SDL_HINT_IME_SUPPORT_EXTENDED_TEXT',
    'SDL_HINT_IOS_HIDE_HOME_INDICATOR',
    'SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS',
    'SDL_HINT_JOYSTICK_ARCADESTICK_DEVICES',
    'SDL_HINT_JOYSTICK_ARCADESTICK_DEVICES_EXCLUDED',
    'SDL_HINT_JOYSTICK_BLACKLIST_DEVICES',
    'SDL_HINT_JOYSTICK_BLACKLIST_DEVICES_EXCLUDED',
    'SDL_HINT_JOYSTICK_DEVICE',
    'SDL_HINT_JOYSTICK_FLIGHTSTICK_DEVICES',
    'SDL_HINT_JOYSTICK_FLIGHTSTICK_DEVICES_EXCLUDED',
    'SDL_HINT_JOYSTICK_GAMECUBE_DEVICES',
    'SDL_HINT_JOYSTICK_GAMECUBE_DEVICES_EXCLUDED',
    'SDL_HINT_JOYSTICK_GAMECUBE_RUMBLE_BRAKE',
    'SDL_HINT_JOYSTICK_HIDAPI',
    'SDL_HINT_JOYSTICK_HIDAPI_COMBINE_JOY_CONS',
    'SDL_HINT_JOYSTICK_HIDAPI_CORRELATE_XINPUT',
    'SDL_HINT_JOYSTICK_HIDAPI_GAMECUBE',
    'SDL_HINT_JOYSTICK_HIDAPI_JOYCON_HOME_LED',
    'SDL_HINT_JOYSTICK_HIDAPI_JOY_CONS',
    'SDL_HINT_JOYSTICK_HIDAPI_LUNA',
    'SDL_HINT_JOYSTICK_HIDAPI_NINTENDO_CLASSIC',
    'SDL_HINT_JOYSTICK_HIDAPI_PS3',
    'SDL_HINT_JOYSTICK_HIDAPI_PS4',
    'SDL_HINT_JOYSTICK_HIDAPI_PS4_RUMBLE',
    'SDL_HINT_JOYSTICK_HIDAPI_PS5',
    'SDL_HINT_JOYSTICK_HIDAPI_PS5_PLAYER_LED',
    'SDL_HINT_JOYSTICK_HIDAPI_PS5_RUMBLE',
    'SDL_HINT_JOYSTICK_HIDAPI_SHIELD',
    'SDL_HINT_JOYSTICK_HIDAPI_STADIA',
    'SDL_HINT_JOYSTICK_HIDAPI_STEAM',
    'SDL_HINT_JOYSTICK_HIDAPI_STEAMDECK',
    'SDL_HINT_JOYSTICK_HIDAPI_SWITCH',
    'SDL_HINT_JOYSTICK_HIDAPI_SWITCH_HOME_LED',
    'SDL_HINT_JOYSTICK_HIDAPI_SWITCH_PLAYER_LED',
    'SDL_HINT_JOYSTICK_HIDAPI_VERTICAL_JOY_CONS',
    'SDL_HINT_JOYSTICK_HIDAPI_WII',
    'SDL_HINT_JOYSTICK_HIDAPI_WII_PLAYER_LED',
    'SDL_HINT_JOYSTICK_HIDAPI_XBOX',
    'SDL_HINT_JOYSTICK_HIDAPI_XBOX_360',
    'SDL_HINT_JOYSTICK_HIDAPI_XBOX_360_PLAYER_LED',
    'SDL_HINT_JOYSTICK_HIDAPI_XBOX_360_WIRELESS',
    'SDL_HINT_JOYSTICK_HIDAPI_XBOX_ONE',
    'SDL_HINT_JOYSTICK_HIDAPI_XBOX_ONE_HOME_LED',
    'SDL_HINT_JOYSTICK_IOKIT',
    'SDL_HINT_JOYSTICK_MFI',
    'SDL_HINT_JOYSTICK_RAWINPUT',
    'SDL_HINT_JOYSTICK_RAWINPUT_CORRELATE_XINPUT',
    'SDL_HINT_JOYSTICK_ROG_CHAKRAM',
    'SDL_HINT_JOYSTICK_THREAD',
    'SDL_HINT_JOYSTICK_THROTTLE_DEVICES',
    'SDL_HINT_JOYSTICK_THROTTLE_DEVICES_EXCLUDED',
    'SDL_HINT_JOYSTICK_WGI',
    'SDL_HINT_JOYSTICK_WHEEL_DEVICES',
    'SDL_HINT_JOYSTICK_WHEEL_DEVICES_EXCLUDED',
    'SDL_HINT_JOYSTICK_ZERO_CENTERED_DEVICES',
    'SDL_HINT_KMSDRM_DEVICE_INDEX',
    'SDL_HINT_KMSDRM_REQUIRE_DRM_MASTER',
    'SDL_HINT_LINUX_DIGITAL_HATS',
    'SDL_HINT_LINUX_HAT_DEADZONES',
    'SDL_HINT_LINUX_JOYSTICK_CLASSIC',
    'SDL_HINT_LINUX_JOYSTICK_DEADZONES',
    'SDL_HINT_LOGGING',
    'SDL_HINT_MAC_BACKGROUND_APP',
    'SDL_HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK',
    'SDL_HINT_MAC_OPENGL_ASYNC_DISPATCH',
    'SDL_HINT_MOUSE_AUTO_CAPTURE',
    'SDL_HINT_MOUSE_DOUBLE_CLICK_RADIUS',
    'SDL_HINT_MOUSE_DOUBLE_CLICK_TIME',
    'SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH',
    'SDL_HINT_MOUSE_NORMAL_SPEED_SCALE',
    'SDL_HINT_MOUSE_RELATIVE_CURSOR_VISIBLE',
    'SDL_HINT_MOUSE_RELATIVE_MODE_CENTER',
    'SDL_HINT_MOUSE_RELATIVE_MODE_WARP',
    'SDL_HINT_MOUSE_RELATIVE_SCALING',
    'SDL_HINT_MOUSE_RELATIVE_SPEED_SCALE',
    'SDL_HINT_MOUSE_RELATIVE_SYSTEM_SCALE',
    'SDL_HINT_MOUSE_RELATIVE_WARP_MOTION',
    'SDL_HINT_MOUSE_TOUCH_EVENTS',
    'SDL_HINT_NORMAL',
    'SDL_HINT_NO_SIGNAL_HANDLERS',
    'SDL_HINT_OPENGL_ES_DRIVER',
    'SDL_HINT_ORIENTATIONS',
    'SDL_HINT_OVERRIDE',
    'SDL_HINT_POLL_SENTINEL',
    'SDL_HINT_PREFERRED_LOCALES',
    'SDL_HINT_PS2_DYNAMIC_VSYNC',
    'SDL_HINT_QTWAYLAND_CONTENT_ORIENTATION',
    'SDL_HINT_QTWAYLAND_WINDOW_FLAGS',
    'SDL_HINT_QUIT_ON_LAST_WINDOW_CLOSE',
    'SDL_HINT_RENDER_BATCHING',
    'SDL_HINT_RENDER_DIRECT3D11_DEBUG',
    'SDL_HINT_RENDER_DIRECT3D_THREADSAFE',
    'SDL_HINT_RENDER_DRIVER',
    'SDL_HINT_RENDER_LINE_METHOD',
    'SDL_HINT_RENDER_LOGICAL_SIZE_MODE',
    'SDL_HINT_RENDER_METAL_PREFER_LOW_POWER_DEVICE',
    'SDL_HINT_RENDER_OPENGL_SHADERS',
    'SDL_HINT_RENDER_SCALE_QUALITY',
    'SDL_HINT_RENDER_VSYNC',
    'SDL_HINT_RETURN_KEY_HIDES_IME',
    'SDL_HINT_ROG_GAMEPAD_MICE',
    'SDL_HINT_ROG_GAMEPAD_MICE_EXCLUDED',
    'SDL_HINT_RPI_VIDEO_LAYER',
    'SDL_HINT_SCREENSAVER_INHIBIT_ACTIVITY_NAME',
    'SDL_HINT_SHUTDOWN_DBUS_ON_QUIT',
    'SDL_HINT_THREAD_FORCE_REALTIME_TIME_CRITICAL',
    'SDL_HINT_THREAD_PRIORITY_POLICY',
    'SDL_HINT_THREAD_STACK_SIZE',
    'SDL_HINT_TIMER_RESOLUTION',
    'SDL_HINT_TOUCH_MOUSE_EVENTS',
    'SDL_HINT_TRACKPAD_IS_TOUCH_ONLY',
    'SDL_HINT_TV_REMOTE_AS_JOYSTICK',
    'SDL_HINT_VIDEODRIVER',
    'SDL_HINT_VIDEO_ALLOW_SCREENSAVER',
    'SDL_HINT_VIDEO_DOUBLE_BUFFER',
    'SDL_HINT_VIDEO_EGL_ALLOW_TRANSPARENCY',
    'SDL_HINT_VIDEO_EXTERNAL_CONTEXT',
    'SDL_HINT_VIDEO_FOREIGN_WINDOW_OPENGL',
    'SDL_HINT_VIDEO_FOREIGN_WINDOW_VULKAN',
    'SDL_HINT_VIDEO_HIGHDPI_DISABLED',
    'SDL_HINT_VIDEO_MAC_FULLSCREEN_SPACES',
    'SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS',
    'SDL_HINT_VIDEO_WAYLAND_ALLOW_LIBDECOR',
    'SDL_HINT_VIDEO_WAYLAND_EMULATE_MOUSE_WARP',
    'SDL_HINT_VIDEO_WAYLAND_MODE_EMULATION',
    'SDL_HINT_VIDEO_WAYLAND_PREFER_LIBDECOR',
    'SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT',
    'SDL_HINT_VIDEO_WIN_D3DCOMPILER',
    'SDL_HINT_VIDEO_X11_FORCE_EGL',
    'SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR',
    'SDL_HINT_VIDEO_X11_NET_WM_PING',
    'SDL_HINT_VIDEO_X11_WINDOW_VISUALID',
    'SDL_HINT_VIDEO_X11_XINERAMA',
    'SDL_HINT_VIDEO_X11_XRANDR',
    'SDL_HINT_VIDEO_X11_XVIDMODE',
    'SDL_HINT_VITA_TOUCH_MOUSE_DEVICE',
    'SDL_HINT_WAVE_FACT_CHUNK',
    'SDL_HINT_WAVE_RIFF_CHUNK_SIZE',
    'SDL_HINT_WAVE_TRUNCATION',
    'SDL_HINT_WINDOWS_DISABLE_THREAD_NAMING',
    'SDL_HINT_WINDOWS_DPI_AWARENESS',
    'SDL_HINT_WINDOWS_DPI_SCALING',
    'SDL_HINT_WINDOWS_ENABLE_MENU_MNEMONICS',
    'SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP',
    'SDL_HINT_WINDOWS_FORCE_MUTEX_CRITICAL_SECTIONS',
    'SDL_HINT_WINDOWS_FORCE_SEMAPHORE_KERNEL',
    'SDL_HINT_WINDOWS_INTRESOURCE_ICON',
    'SDL_HINT_WINDOWS_INTRESOURCE_ICON_SMALL',
    'SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4',
    'SDL_HINT_WINDOWS_USE_D3D9EX',
    'SDL_HINT_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN',
    'SDL_HINT_WINDOW_NO_ACTIVATION_WHEN_SHOWN',
    'SDL_HINT_WINRT_HANDLE_BACK_BUTTON',
    'SDL_HINT_WINRT_PRIVACY_POLICY_LABEL',
    'SDL_HINT_WINRT_PRIVACY_POLICY_URL',
    'SDL_HINT_X11_FORCE_OVERRIDE_REDIRECT',
    'SDL_HINT_X11_WINDOW_TYPE',
    'SDL_HINT_XINPUT_ENABLED',
    'SDL_HINT_XINPUT_USE_OLD_JOYSTICK_MAPPING',
    'SDL_AddHintCallback',
    'SDL_ClearHints',
    'SDL_DelHintCallback',
    'SDL_GetHint',
    'SDL_GetHintBoolean',
    'SDL_HintCallback',
    'SDL_HintPriority',
    'SDL_ResetHint',
    'SDL_ResetHints',
    'SDL_SetHint',
    'SDL_SetHintWithPriority',
]

SDL_HINT_APP_NAME: bytes
SDL_HINT_BMP_SAVE_LEGACY_FORMAT: bytes
SDL_HINT_EVENT_LOGGING: bytes
SDL_HINT_LOGGING: bytes
SDL_HINT_NO_SIGNAL_HANDLERS: bytes
SDL_HINT_POLL_SENTINEL: bytes
SDL_HINT_PREFERRED_LOCALES: bytes
SDL_HINT_QUIT_ON_LAST_WINDOW_CLOSE: bytes
SDL_HINT_SCREENSAVER_INHIBIT_ACTIVITY_NAME: bytes
SDL_HINT_THREAD_FORCE_REALTIME_TIME_CRITICAL: bytes
SDL_HINT_THREAD_PRIORITY_POLICY: bytes
SDL_HINT_THREAD_STACK_SIZE: bytes
SDL_HINT_TIMER_RESOLUTION: bytes
SDL_HINT_FRAMEBUFFER_ACCELERATION: bytes
SDL_HINT_OPENGL_ES_DRIVER: bytes
SDL_HINT_RENDER_BATCHING: bytes
SDL_HINT_RENDER_LINE_METHOD: bytes
SDL_HINT_RENDER_DRIVER: bytes
SDL_HINT_RENDER_LOGICAL_SIZE_MODE: bytes
SDL_HINT_RENDER_METAL_PREFER_LOW_POWER_DEVICE: bytes
SDL_HINT_RENDER_OPENGL_SHADERS: bytes
SDL_HINT_RENDER_SCALE_QUALITY: bytes
SDL_HINT_RENDER_VSYNC: bytes
SDL_HINT_VIDEODRIVER: bytes
SDL_HINT_VIDEO_ALLOW_SCREENSAVER: bytes
SDL_HINT_VIDEO_DOUBLE_BUFFER: bytes
SDL_HINT_VIDEO_EGL_ALLOW_TRANSPARENCY: bytes
SDL_HINT_VIDEO_EXTERNAL_CONTEXT: bytes
SDL_HINT_VIDEO_FOREIGN_WINDOW_OPENGL: bytes
SDL_HINT_VIDEO_FOREIGN_WINDOW_VULKAN: bytes
SDL_HINT_VIDEO_WAYLAND_ALLOW_LIBDECOR: bytes
SDL_HINT_VIDEO_WAYLAND_PREFER_LIBDECOR: bytes
SDL_HINT_VIDEO_WAYLAND_EMULATE_MOUSE_WARP: bytes
SDL_HINT_VIDEO_WAYLAND_MODE_EMULATION: bytes
SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT: bytes
SDL_HINT_VIDEO_X11_FORCE_EGL: bytes
SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR: bytes
SDL_HINT_VIDEO_X11_NET_WM_PING: bytes
SDL_HINT_VIDEO_X11_WINDOW_VISUALID: bytes
SDL_HINT_VIDEO_X11_XINERAMA: bytes
SDL_HINT_VIDEO_X11_XRANDR: bytes
SDL_HINT_VIDEO_X11_XVIDMODE: bytes
SDL_HINT_X11_FORCE_OVERRIDE_REDIRECT: bytes
SDL_HINT_X11_WINDOW_TYPE: bytes
SDL_HINT_AUDIODRIVER: bytes
SDL_HINT_AUDIO_CATEGORY: bytes
SDL_HINT_AUDIO_DEVICE_APP_NAME: bytes
SDL_HINT_AUDIO_DEVICE_STREAM_NAME: bytes
SDL_HINT_AUDIO_DEVICE_STREAM_ROLE: bytes
SDL_HINT_AUDIO_INCLUDE_MONITORS: bytes
SDL_HINT_AUDIO_RESAMPLING_MODE: bytes
SDL_HINT_WAVE_FACT_CHUNK: bytes
SDL_HINT_WAVE_RIFF_CHUNK_SIZE: bytes
SDL_HINT_WAVE_TRUNCATION: bytes
SDL_HINT_ALLOW_ALT_TAB_WHILE_GRABBED: bytes
SDL_HINT_ALLOW_TOPMOST: bytes
SDL_HINT_DISPLAY_USABLE_BOUNDS: bytes
SDL_HINT_FORCE_RAISEWINDOW: bytes
SDL_HINT_QTWAYLAND_CONTENT_ORIENTATION: bytes
SDL_HINT_QTWAYLAND_WINDOW_FLAGS: bytes
SDL_HINT_VIDEO_HIGHDPI_DISABLED: bytes
SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS: bytes
SDL_HINT_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN: bytes
SDL_HINT_WINDOW_NO_ACTIVATION_WHEN_SHOWN: bytes
SDL_HINT_GRAB_KEYBOARD: bytes
SDL_HINT_IME_INTERNAL_EDITING: bytes
SDL_HINT_IME_SHOW_UI: bytes
SDL_HINT_IME_SUPPORT_EXTENDED_TEXT: bytes
SDL_HINT_MOUSE_AUTO_CAPTURE: bytes
SDL_HINT_MOUSE_DOUBLE_CLICK_RADIUS: bytes
SDL_HINT_MOUSE_DOUBLE_CLICK_TIME: bytes
SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH: bytes
SDL_HINT_MOUSE_NORMAL_SPEED_SCALE: bytes
SDL_HINT_MOUSE_RELATIVE_CURSOR_VISIBLE: bytes
SDL_HINT_MOUSE_RELATIVE_MODE_CENTER: bytes
SDL_HINT_MOUSE_RELATIVE_MODE_WARP: bytes
SDL_HINT_MOUSE_RELATIVE_SCALING: bytes
SDL_HINT_MOUSE_RELATIVE_SPEED_SCALE: bytes
SDL_HINT_MOUSE_RELATIVE_SYSTEM_SCALE: bytes
SDL_HINT_MOUSE_RELATIVE_WARP_MOTION: bytes
SDL_HINT_MOUSE_TOUCH_EVENTS: bytes
SDL_HINT_ROG_GAMEPAD_MICE: bytes
SDL_HINT_ROG_GAMEPAD_MICE_EXCLUDED: bytes
SDL_HINT_TOUCH_MOUSE_EVENTS: bytes
SDL_HINT_TRACKPAD_IS_TOUCH_ONLY: bytes
SDL_HINT_AUTO_UPDATE_JOYSTICKS: bytes
SDL_HINT_AUTO_UPDATE_SENSORS: bytes
SDL_HINT_ENABLE_STEAM_CONTROLLERS: bytes
SDL_HINT_GAMECONTROLLERCONFIG: bytes
SDL_HINT_GAMECONTROLLERCONFIG_FILE: bytes
SDL_HINT_GAMECONTROLLERTYPE: bytes
SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES: bytes
SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT: bytes
SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS: bytes
SDL_HINT_HIDAPI_IGNORE_DEVICES: bytes
SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS: bytes
SDL_HINT_JOYSTICK_ARCADESTICK_DEVICES: bytes
SDL_HINT_JOYSTICK_ARCADESTICK_DEVICES_EXCLUDED: bytes
SDL_HINT_JOYSTICK_BLACKLIST_DEVICES: bytes
SDL_HINT_JOYSTICK_BLACKLIST_DEVICES_EXCLUDED: bytes
SDL_HINT_JOYSTICK_FLIGHTSTICK_DEVICES: bytes
SDL_HINT_JOYSTICK_FLIGHTSTICK_DEVICES_EXCLUDED: bytes
SDL_HINT_JOYSTICK_GAMECUBE_DEVICES: bytes
SDL_HINT_JOYSTICK_GAMECUBE_DEVICES_EXCLUDED: bytes
SDL_HINT_JOYSTICK_HIDAPI: bytes
SDL_HINT_JOYSTICK_HIDAPI_CORRELATE_XINPUT: bytes
SDL_HINT_JOYSTICK_HIDAPI_GAMECUBE: bytes
SDL_HINT_JOYSTICK_GAMECUBE_RUMBLE_BRAKE: bytes
SDL_HINT_JOYSTICK_HIDAPI_JOY_CONS: bytes
SDL_HINT_JOYSTICK_HIDAPI_JOYCON_HOME_LED: bytes
SDL_HINT_JOYSTICK_HIDAPI_COMBINE_JOY_CONS: bytes
SDL_HINT_JOYSTICK_HIDAPI_VERTICAL_JOY_CONS: bytes
SDL_HINT_JOYSTICK_HIDAPI_LUNA: bytes
SDL_HINT_JOYSTICK_HIDAPI_NINTENDO_CLASSIC: bytes
SDL_HINT_JOYSTICK_HIDAPI_SHIELD: bytes
SDL_HINT_JOYSTICK_HIDAPI_PS3: bytes
SDL_HINT_JOYSTICK_HIDAPI_PS4: bytes
SDL_HINT_JOYSTICK_HIDAPI_PS4_RUMBLE: bytes
SDL_HINT_JOYSTICK_HIDAPI_PS5: bytes
SDL_HINT_JOYSTICK_HIDAPI_PS5_PLAYER_LED: bytes
SDL_HINT_JOYSTICK_HIDAPI_PS5_RUMBLE: bytes
SDL_HINT_JOYSTICK_HIDAPI_STADIA: bytes
SDL_HINT_JOYSTICK_HIDAPI_STEAM: bytes
SDL_HINT_JOYSTICK_HIDAPI_STEAMDECK: bytes
SDL_HINT_JOYSTICK_HIDAPI_SWITCH: bytes
SDL_HINT_JOYSTICK_HIDAPI_SWITCH_HOME_LED: bytes
SDL_HINT_JOYSTICK_HIDAPI_SWITCH_PLAYER_LED: bytes
SDL_HINT_JOYSTICK_HIDAPI_WII: bytes
SDL_HINT_JOYSTICK_HIDAPI_WII_PLAYER_LED: bytes
SDL_HINT_JOYSTICK_HIDAPI_XBOX: bytes
SDL_HINT_JOYSTICK_HIDAPI_XBOX_360: bytes
SDL_HINT_JOYSTICK_HIDAPI_XBOX_360_PLAYER_LED: bytes
SDL_HINT_JOYSTICK_HIDAPI_XBOX_360_WIRELESS: bytes
SDL_HINT_JOYSTICK_HIDAPI_XBOX_ONE: bytes
SDL_HINT_JOYSTICK_HIDAPI_XBOX_ONE_HOME_LED: bytes
SDL_HINT_JOYSTICK_RAWINPUT: bytes
SDL_HINT_JOYSTICK_RAWINPUT_CORRELATE_XINPUT: bytes
SDL_HINT_JOYSTICK_ROG_CHAKRAM: bytes
SDL_HINT_JOYSTICK_THREAD: bytes
SDL_HINT_JOYSTICK_THROTTLE_DEVICES: bytes
SDL_HINT_JOYSTICK_THROTTLE_DEVICES_EXCLUDED: bytes
SDL_HINT_JOYSTICK_WGI: bytes
SDL_HINT_JOYSTICK_WHEEL_DEVICES: bytes
SDL_HINT_JOYSTICK_WHEEL_DEVICES_EXCLUDED: bytes
SDL_HINT_JOYSTICK_DEVICE: bytes
SDL_HINT_JOYSTICK_ZERO_CENTERED_DEVICES: bytes
SDL_HINT_DIRECTINPUT_ENABLED: bytes
SDL_HINT_EMSCRIPTEN_ASYNCIFY: bytes
SDL_HINT_EMSCRIPTEN_KEYBOARD_ELEMENT: bytes
SDL_HINT_JOYSTICK_IOKIT: bytes
SDL_HINT_KMSDRM_DEVICE_INDEX: bytes
SDL_HINT_KMSDRM_REQUIRE_DRM_MASTER: bytes
SDL_HINT_LINUX_DIGITAL_HATS: bytes
SDL_HINT_LINUX_HAT_DEADZONES: bytes
SDL_HINT_LINUX_JOYSTICK_CLASSIC: bytes
SDL_HINT_LINUX_JOYSTICK_DEADZONES: bytes
SDL_HINT_MAC_BACKGROUND_APP: bytes
SDL_HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK: bytes
SDL_HINT_MAC_OPENGL_ASYNC_DISPATCH: bytes
SDL_HINT_PS2_DYNAMIC_VSYNC: bytes
SDL_HINT_RPI_VIDEO_LAYER: bytes
SDL_HINT_RENDER_DIRECT3D11_DEBUG: bytes
SDL_HINT_RENDER_DIRECT3D_THREADSAFE: bytes
SDL_HINT_SHUTDOWN_DBUS_ON_QUIT: bytes
SDL_HINT_VIDEO_MAC_FULLSCREEN_SPACES: bytes
SDL_HINT_VIDEO_WIN_D3DCOMPILER: bytes
SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4: bytes
SDL_HINT_WINDOWS_DISABLE_THREAD_NAMING: bytes
SDL_HINT_WINDOWS_ENABLE_MENU_MNEMONICS: bytes
SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP: bytes
SDL_HINT_WINDOWS_FORCE_MUTEX_CRITICAL_SECTIONS: bytes
SDL_HINT_WINDOWS_FORCE_SEMAPHORE_KERNEL: bytes
SDL_HINT_WINDOWS_INTRESOURCE_ICON: bytes
SDL_HINT_WINDOWS_INTRESOURCE_ICON_SMALL: bytes
SDL_HINT_WINDOWS_USE_D3D9EX: bytes
SDL_HINT_WINDOWS_DPI_AWARENESS: bytes
SDL_HINT_WINDOWS_DPI_SCALING: bytes
SDL_HINT_XINPUT_ENABLED: bytes
SDL_HINT_XINPUT_USE_OLD_JOYSTICK_MAPPING: bytes
SDL_HINT_ACCELEROMETER_AS_JOYSTICK: bytes
SDL_HINT_TV_REMOTE_AS_JOYSTICK: bytes
SDL_HINT_ORIENTATIONS: bytes
SDL_HINT_RETURN_KEY_HIDES_IME: bytes
SDL_HINT_ANDROID_APK_EXPANSION_MAIN_FILE_VERSION: bytes
SDL_HINT_ANDROID_APK_EXPANSION_PATCH_FILE_VERSION: bytes
SDL_HINT_ANDROID_SEPARATE_MOUSE_AND_TOUCH: bytes
SDL_HINT_ANDROID_TRAP_BACK_BUTTON: bytes
SDL_HINT_ANDROID_BLOCK_ON_PAUSE: bytes
SDL_HINT_ANDROID_BLOCK_ON_PAUSE_PAUSEAUDIO: bytes
SDL_HINT_APPLE_TV_CONTROLLER_UI_EVENTS: bytes
SDL_HINT_APPLE_TV_REMOTE_ALLOW_ROTATION: bytes
SDL_HINT_ENABLE_SCREEN_KEYBOARD: bytes
SDL_HINT_IDLE_TIMER_DISABLED: bytes
SDL_HINT_IOS_HIDE_HOME_INDICATOR: str
SDL_HINT_JOYSTICK_MFI: bytes
SDL_HINT_VITA_TOUCH_MOUSE_DEVICE: bytes
SDL_HINT_WINRT_PRIVACY_POLICY_URL: bytes
SDL_HINT_WINRT_PRIVACY_POLICY_LABEL: bytes
SDL_HINT_WINRT_HANDLE_BACK_BUTTON: bytes
SDL_HintPriority = c_int
SDL_HINT_DEFAULT: int
SDL_HINT_NORMAL: int
SDL_HINT_OVERRIDE: int
SDL_HintCallback: type[_CFuncPtr]

def SDL_SetHintWithPriority(name: bytes | None, value: bytes | None, priority: int, /) -> int: ...
def SDL_SetHint(name: bytes | None, value: bytes | None, /) -> int: ...
def SDL_GetHint(name: bytes | None, /) -> bytes | None: ...
def SDL_ResetHint(name: bytes | None, /) -> int: ...
def SDL_ResetHints() -> None: ...
def SDL_GetHintBoolean(name: bytes | None, default_value: int, /) -> int: ...
def SDL_ClearHints() -> None: ...
def SDL_AddHintCallback(name: bytes | None, callback: _CFuncPtr, userdata: int | None, /) -> None: ...
def SDL_DelHintCallback(name: bytes | None, callback: _CFuncPtr, userdata: int | None, /) -> None: ...
