from ctypes import Structure, _Pointer, c_int

from .rect import SDL_Rect
from .stdinc import Uint8
from .video import SDL_Window

__all__ = [
    'SDL_ClearComposition',
    'SDL_GetKeyFromName',
    'SDL_GetKeyFromScancode',
    'SDL_GetKeyName',
    'SDL_GetKeyboardFocus',
    'SDL_GetKeyboardState',
    'SDL_GetModState',
    'SDL_GetScancodeFromKey',
    'SDL_GetScancodeFromName',
    'SDL_GetScancodeName',
    'SDL_HasScreenKeyboardSupport',
    'SDL_IsScreenKeyboardShown',
    'SDL_IsTextInputActive',
    'SDL_IsTextInputShown',
    'SDL_Keysym',
    'SDL_ResetKeyboard',
    'SDL_SetModState',
    'SDL_SetTextInputRect',
    'SDL_StartTextInput',
    'SDL_StopTextInput',
]

class SDL_Keysym(Structure):
    scancode: int
    sym: int
    mod: int
    unused: int

def SDL_GetKeyboardFocus() -> _Pointer[SDL_Window]: ...
def SDL_GetKeyboardState(numkeys: _Pointer[c_int], /) -> _Pointer[Uint8]: ...
def SDL_ResetKeyboard() -> None: ...
def SDL_GetModState() -> int: ...
def SDL_SetModState(modstate: int, /) -> None: ...
def SDL_GetKeyFromScancode(scancode: int, /) -> int: ...
def SDL_GetScancodeFromKey(key: int, /) -> int: ...
def SDL_GetScancodeName(scancode: int, /) -> bytes | None: ...
def SDL_GetScancodeFromName(name: bytes | None, /) -> int: ...
def SDL_GetKeyName(key: int, /) -> bytes | None: ...
def SDL_GetKeyFromName(name: bytes | None, /) -> int: ...
def SDL_StartTextInput() -> None: ...
def SDL_IsTextInputActive() -> int: ...
def SDL_StopTextInput() -> None: ...
def SDL_ClearComposition() -> None: ...
def SDL_IsTextInputShown() -> int: ...
def SDL_SetTextInputRect(rect: _Pointer[SDL_Rect], /) -> None: ...
def SDL_HasScreenKeyboardSupport() -> int: ...
def SDL_IsScreenKeyboardShown(window: _Pointer[SDL_Window], /) -> int: ...
