__all__ = ['SDL_LoadFunction', 'SDL_LoadObject', 'SDL_UnloadObject']

def SDL_LoadObject(sofile: bytes | None, /) -> int | None: ...
def SDL_LoadFunction(handle: int | None, name: bytes | None, /) -> int | None: ...
def SDL_UnloadObject(handle: int | None, /) -> None: ...
