from ctypes import Structure, _Pointer, c_float, c_int
from typing import Any

__all__ = [
    'SDL_EncloseFPoints',
    'SDL_EnclosePoints',
    'SDL_FPoint',
    'SDL_FRect',
    'SDL_FRectEmpty',
    'SDL_FRectEquals',
    'SDL_FRectEqualsEpsilon',
    'SDL_HasIntersection',
    'SDL_HasIntersectionF',
    'SDL_IntersectFRect',
    'SDL_IntersectFRectAndLine',
    'SDL_IntersectRect',
    'SDL_IntersectRectAndLine',
    'SDL_Point',
    'SDL_PointInFRect',
    'SDL_PointInRect',
    'SDL_Rect',
    'SDL_RectEmpty',
    'SDL_RectEquals',
    'SDL_UnionFRect',
    'SDL_UnionRect',
]

class SDL_Point(Structure):
    x: int
    y: int
    def __init__(self, x: int = 0, y: int = 0) -> None: ...
    def __copy__(self) -> SDL_Point: ...
    def __deepcopy__(self, memo: Any) -> SDL_Point: ...
    def __eq__(self, pt: object) -> bool: ...
    def __ne__(self, pt: object) -> bool: ...
    def __getitem__(self, i: int) -> int: ...

class SDL_FPoint(Structure):
    x: float
    y: float
    def __init__(self, x: float = 0.0, y: float = 0.0) -> None: ...
    def __copy__(self) -> SDL_FPoint: ...
    def __deepcopy__(self, memo: Any) -> SDL_FPoint: ...
    def __eq__(self, pt: object) -> bool: ...
    def __ne__(self, pt: object) -> bool: ...
    def __getitem__(self, i: int) -> float: ...

class SDL_Rect(Structure):
    x: int
    y: int
    w: int
    h: int
    def __init__(self, x: int = 0, y: int = 0, w: int = 0, h: int = 0) -> None: ...
    def __copy__(self) -> SDL_Rect: ...
    def __deepcopy__(self, memo: Any) -> SDL_Rect: ...
    def __eq__(self, rt: object) -> bool: ...
    def __ne__(self, rt: object) -> bool: ...
    def __getitem__(self, i: int) -> int: ...

class SDL_FRect(Structure):
    x: float
    y: float
    w: float
    h: float
    def __init__(self, x: float = 0.0, y: float = 0.0, w: float = 0.0, h: float = 0.0) -> None: ...
    def __copy__(self) -> SDL_FRect: ...
    def __deepcopy__(self, memo: Any) -> SDL_FRect: ...
    def __eq__(self, rt: object) -> bool: ...
    def __ne__(self, rt: object) -> bool: ...
    def __getitem__(self, i: int) -> float: ...

def SDL_RectEmpty(x: SDL_Rect | None) -> bool: ...
def SDL_RectEquals(a: SDL_Rect, b: SDL_Rect) -> bool: ...
def SDL_PointInRect(p: SDL_Point, r: SDL_Rect) -> bool: ...

SDL_PointInFRect = SDL_PointInRect
SDL_FRectEmpty = SDL_RectEmpty

def SDL_FRectEqualsEpsilon(a: SDL_FRect, b: SDL_FRect, epsilon: float) -> bool: ...
def SDL_FRectEquals(a: SDL_FRect, b: SDL_FRect) -> bool: ...
def SDL_HasIntersection(A: _Pointer[SDL_Rect], B: _Pointer[SDL_Rect], /) -> int: ...
def SDL_IntersectRect(A: _Pointer[SDL_Rect], B: _Pointer[SDL_Rect], result: _Pointer[SDL_Rect], /) -> int: ...
def SDL_UnionRect(A: _Pointer[SDL_Rect], B: _Pointer[SDL_Rect], result: _Pointer[SDL_Rect], /) -> None: ...
def SDL_EnclosePoints(
    points: _Pointer[SDL_Point], count: int, clip: _Pointer[SDL_Rect], result: _Pointer[SDL_Rect], /
) -> int: ...
def SDL_IntersectRectAndLine(
    rect: _Pointer[SDL_Rect],
    X1: _Pointer[c_int],
    Y1: _Pointer[c_int],
    X2: _Pointer[c_int],
    Y2: _Pointer[c_int],
    /,
) -> int: ...
def SDL_HasIntersectionF(A: _Pointer[SDL_FRect], B: _Pointer[SDL_FRect], /) -> int: ...
def SDL_IntersectFRect(A: _Pointer[SDL_FRect], B: _Pointer[SDL_FRect], result: _Pointer[SDL_FRect], /) -> int: ...
def SDL_UnionFRect(A: _Pointer[SDL_FRect], B: _Pointer[SDL_FRect], result: _Pointer[SDL_FRect], /) -> None: ...
def SDL_EncloseFPoints(
    points: _Pointer[SDL_FPoint],
    count: int,
    clip: _Pointer[SDL_FRect],
    result: _Pointer[SDL_FRect],
    /,
) -> int: ...
def SDL_IntersectFRectAndLine(
    rect: _Pointer[SDL_FRect],
    X1: _Pointer[c_float],
    Y1: _Pointer[c_float],
    X2: _Pointer[c_float],
    Y2: _Pointer[c_float],
    /,
) -> int: ...
