from ctypes import Structure, Union, _CFuncPtr, _Pointer, c_size_t, c_void_p
from typing import Any

__all__ = [
    'RW_SEEK_CUR',
    'RW_SEEK_END',
    'RW_SEEK_SET',
    'SDL_RWOPS_JNIFILE',
    'SDL_RWOPS_MEMORY',
    'SDL_RWOPS_MEMORY_RO',
    'SDL_RWOPS_STDFILE',
    'SDL_RWOPS_UNKNOWN',
    'SDL_RWOPS_WINFILE',
    'SDL_AllocRW',
    'SDL_FreeRW',
    'SDL_LoadFile',
    'SDL_LoadFile_RW',
    'SDL_RWFromConstMem',
    'SDL_RWFromFP',
    'SDL_RWFromFile',
    'SDL_RWFromMem',
    'SDL_RWclose',
    'SDL_RWops',
    'SDL_RWread',
    'SDL_RWseek',
    'SDL_RWsize',
    'SDL_RWtell',
    'SDL_RWwrite',
    'SDL_ReadBE16',
    'SDL_ReadBE32',
    'SDL_ReadBE64',
    'SDL_ReadLE16',
    'SDL_ReadLE32',
    'SDL_ReadLE64',
    'SDL_ReadU8',
    'SDL_WriteBE16',
    'SDL_WriteBE32',
    'SDL_WriteBE64',
    'SDL_WriteLE16',
    'SDL_WriteLE32',
    'SDL_WriteLE64',
    'SDL_WriteU8',
    'rw_from_object',
]

SDL_RWOPS_UNKNOWN: int
SDL_RWOPS_WINFILE: int
SDL_RWOPS_STDFILE: int
SDL_RWOPS_JNIFILE: int
SDL_RWOPS_MEMORY: int
SDL_RWOPS_MEMORY_RO: int
RW_SEEK_SET: int
RW_SEEK_CUR: int
RW_SEEK_END: int

class _hidden(Union): ...

class SDL_RWops(Structure):
    size: _CFuncPtr
    seek: _CFuncPtr
    read: _CFuncPtr
    write: _CFuncPtr
    close: _CFuncPtr
    type: int
    hidden: _hidden

def SDL_RWFromFile(file: bytes | None, mode: bytes | None, /) -> _Pointer[SDL_RWops]: ...
def SDL_RWFromFP(fp: c_void_p | int | None, autoclose: int, /) -> _Pointer[SDL_RWops]: ...
def SDL_RWFromMem(mem: c_void_p | int | None, size: int, /) -> _Pointer[SDL_RWops]: ...
def SDL_RWFromConstMem(mem: c_void_p | int | None, size: int, /) -> _Pointer[SDL_RWops]: ...
def SDL_AllocRW() -> _Pointer[SDL_RWops]: ...
def SDL_FreeRW(area: _Pointer[SDL_RWops], /) -> None: ...
def SDL_LoadFile_RW(src: _Pointer[SDL_RWops], datasize: _Pointer[c_size_t], freesrc: int, /) -> int | None: ...
def SDL_LoadFile(file: bytes | None, datasize: _Pointer[c_size_t], /) -> int | None: ...
def SDL_RWsize(context: _Pointer[SDL_RWops], /) -> int: ...
def SDL_RWseek(context: _Pointer[SDL_RWops], offset: int, whence: int, /) -> int: ...
def SDL_RWtell(context: _Pointer[SDL_RWops], /) -> int: ...
def SDL_RWread(context: _Pointer[SDL_RWops], ptr: c_void_p | int | None, size: int, maxnum: int, /) -> int: ...
def SDL_RWwrite(context: _Pointer[SDL_RWops], ptr: c_void_p | int | None, size: int, num: int, /) -> int: ...
def SDL_RWclose(context: _Pointer[SDL_RWops], /) -> int: ...
def SDL_ReadU8(src: _Pointer[SDL_RWops], /) -> int: ...
def SDL_ReadLE16(src: _Pointer[SDL_RWops], /) -> int: ...
def SDL_ReadBE16(src: _Pointer[SDL_RWops], /) -> int: ...
def SDL_ReadLE32(src: _Pointer[SDL_RWops], /) -> int: ...
def SDL_ReadBE32(src: _Pointer[SDL_RWops], /) -> int: ...
def SDL_ReadLE64(src: _Pointer[SDL_RWops], /) -> int: ...
def SDL_ReadBE64(src: _Pointer[SDL_RWops], /) -> int: ...
def SDL_WriteU8(dst: _Pointer[SDL_RWops], value: int, /) -> int: ...
def SDL_WriteLE16(dst: _Pointer[SDL_RWops], value: int, /) -> int: ...
def SDL_WriteBE16(dst: _Pointer[SDL_RWops], value: int, /) -> int: ...
def SDL_WriteLE32(dst: _Pointer[SDL_RWops], value: int, /) -> int: ...
def SDL_WriteBE32(dst: _Pointer[SDL_RWops], value: int, /) -> int: ...
def SDL_WriteLE64(dst: _Pointer[SDL_RWops], value: int, /) -> int: ...
def SDL_WriteBE64(dst: _Pointer[SDL_RWops], value: int, /) -> int: ...
def rw_from_object(obj: Any) -> SDL_RWops: ...
