from ctypes import Structure, _Pointer, c_char_p, c_int

from .error import SDL_GetError, SDL_SetError
from .render import SDL_Renderer, SDL_Texture
from .rwops import SDL_RWops
from .surface import SDL_Surface
from .version import SDL_version

__all__ = [
    'IMG_INIT_AVIF',
    'IMG_INIT_JPG',
    'IMG_INIT_JXL',
    'IMG_INIT_PNG',
    'IMG_INIT_TIF',
    'IMG_INIT_WEBP',
    'SDL_IMAGE_COMPILEDVERSION',
    'SDL_IMAGE_MAJOR_VERSION',
    'SDL_IMAGE_MINOR_VERSION',
    'SDL_IMAGE_PATCHLEVEL',
    'SDL_IMAGE_VERSION',
    'SDL_IMAGE_VERSION_ATLEAST',
    'IMG_Animation',
    'IMG_FreeAnimation',
    'IMG_GetError',
    'IMG_Init',
    'IMG_InitFlags',
    'IMG_Linked_Version',
    'IMG_Load',
    'IMG_LoadAVIF_RW',
    'IMG_LoadAnimation',
    'IMG_LoadAnimationTyped_RW',
    'IMG_LoadAnimation_RW',
    'IMG_LoadBMP_RW',
    'IMG_LoadCUR_RW',
    'IMG_LoadGIFAnimation_RW',
    'IMG_LoadGIF_RW',
    'IMG_LoadICO_RW',
    'IMG_LoadJPG_RW',
    'IMG_LoadJXL_RW',
    'IMG_LoadLBM_RW',
    'IMG_LoadPCX_RW',
    'IMG_LoadPNG_RW',
    'IMG_LoadPNM_RW',
    'IMG_LoadQOI_RW',
    'IMG_LoadSVG_RW',
    'IMG_LoadSizedSVG_RW',
    'IMG_LoadTGA_RW',
    'IMG_LoadTIF_RW',
    'IMG_LoadTexture',
    'IMG_LoadTextureTyped_RW',
    'IMG_LoadTexture_RW',
    'IMG_LoadTyped_RW',
    'IMG_LoadWEBPAnimation_RW',
    'IMG_LoadWEBP_RW',
    'IMG_LoadXCF_RW',
    'IMG_LoadXPM_RW',
    'IMG_LoadXV_RW',
    'IMG_Load_RW',
    'IMG_Quit',
    'IMG_ReadXPMFromArray',
    'IMG_ReadXPMFromArrayToRGB888',
    'IMG_SaveJPG',
    'IMG_SaveJPG_RW',
    'IMG_SavePNG',
    'IMG_SavePNG_RW',
    'IMG_SetError',
    'IMG_isAVIF',
    'IMG_isBMP',
    'IMG_isCUR',
    'IMG_isGIF',
    'IMG_isICO',
    'IMG_isJPG',
    'IMG_isJXL',
    'IMG_isLBM',
    'IMG_isPCX',
    'IMG_isPNG',
    'IMG_isPNM',
    'IMG_isQOI',
    'IMG_isSVG',
    'IMG_isTIF',
    'IMG_isWEBP',
    'IMG_isXCF',
    'IMG_isXPM',
    'IMG_isXV',
    'get_dll_file',
]

def get_dll_file() -> str: ...

SDL_IMAGE_MAJOR_VERSION: int
SDL_IMAGE_MINOR_VERSION: int
SDL_IMAGE_PATCHLEVEL: int

def SDL_IMAGE_VERSION(x: object, /) -> None: ...

SDL_IMAGE_COMPILEDVERSION: int

def SDL_IMAGE_VERSION_ATLEAST(x: int, y: int, z: int, /) -> bool: ...

IMG_InitFlags = c_int
IMG_INIT_JPG: int
IMG_INIT_PNG: int
IMG_INIT_TIF: int
IMG_INIT_WEBP: int
IMG_INIT_JXL: int
IMG_INIT_AVIF: int

class IMG_Animation(Structure):
    w: int
    h: int
    count: int
    frames: _Pointer[_Pointer[SDL_Surface]]
    delays: _Pointer[c_int]

def IMG_Linked_Version() -> _Pointer[SDL_version]: ...
def IMG_Init(flags: int, /) -> int: ...
def IMG_Quit() -> None: ...
def IMG_LoadTyped_RW(src: _Pointer[SDL_RWops], freesrc: int, type: bytes | None, /) -> _Pointer[SDL_Surface]: ...
def IMG_Load(file: bytes | None, /) -> _Pointer[SDL_Surface]: ...
def IMG_Load_RW(src: _Pointer[SDL_RWops], freesrc: int, /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadTexture(renderer: _Pointer[SDL_Renderer], file: bytes | None, /) -> _Pointer[SDL_Texture]: ...
def IMG_LoadTexture_RW(
    renderer: _Pointer[SDL_Renderer], src: _Pointer[SDL_RWops], freesrc: int, /
) -> _Pointer[SDL_Texture]: ...
def IMG_LoadTextureTyped_RW(
    renderer: _Pointer[SDL_Renderer],
    src: _Pointer[SDL_RWops],
    freesrc: int,
    type: bytes | None,
    /,
) -> _Pointer[SDL_Texture]: ...
def IMG_isAVIF(src: _Pointer[SDL_RWops], /) -> int: ...
def IMG_isICO(src: _Pointer[SDL_RWops], /) -> int: ...
def IMG_isCUR(src: _Pointer[SDL_RWops], /) -> int: ...
def IMG_isBMP(src: _Pointer[SDL_RWops], /) -> int: ...
def IMG_isGIF(src: _Pointer[SDL_RWops], /) -> int: ...
def IMG_isJPG(src: _Pointer[SDL_RWops], /) -> int: ...
def IMG_isJXL(src: _Pointer[SDL_RWops], /) -> int: ...
def IMG_isLBM(src: _Pointer[SDL_RWops], /) -> int: ...
def IMG_isPCX(src: _Pointer[SDL_RWops], /) -> int: ...
def IMG_isPNG(src: _Pointer[SDL_RWops], /) -> int: ...
def IMG_isPNM(src: _Pointer[SDL_RWops], /) -> int: ...
def IMG_isSVG(src: _Pointer[SDL_RWops], /) -> int: ...
def IMG_isQOI(src: _Pointer[SDL_RWops], /) -> int: ...
def IMG_isTIF(src: _Pointer[SDL_RWops], /) -> int: ...
def IMG_isXCF(src: _Pointer[SDL_RWops], /) -> int: ...
def IMG_isXPM(src: _Pointer[SDL_RWops], /) -> int: ...
def IMG_isXV(src: _Pointer[SDL_RWops], /) -> int: ...
def IMG_isWEBP(src: _Pointer[SDL_RWops], /) -> int: ...
def IMG_LoadAVIF_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadICO_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadCUR_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadBMP_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadGIF_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadJPG_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadJXL_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadLBM_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadPCX_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadPNG_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadPNM_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadSVG_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadQOI_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadTGA_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadTIF_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadXCF_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadXPM_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadXV_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadWEBP_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[SDL_Surface]: ...
def IMG_LoadSizedSVG_RW(src: _Pointer[SDL_RWops], width: int, height: int, /) -> _Pointer[SDL_Surface]: ...
def IMG_ReadXPMFromArray(xpm: _Pointer[c_char_p], /) -> _Pointer[SDL_Surface]: ...
def IMG_ReadXPMFromArrayToRGB888(xpm: _Pointer[c_char_p], /) -> _Pointer[SDL_Surface]: ...
def IMG_SaveJPG(surface: _Pointer[SDL_Surface], file: bytes | None, quality: int, /) -> int: ...
def IMG_SaveJPG_RW(surface: _Pointer[SDL_Surface], dst: _Pointer[SDL_RWops], freedst: int, quality: int, /) -> int: ...
def IMG_SavePNG(surface: _Pointer[SDL_Surface], file: bytes | None, /) -> int: ...
def IMG_SavePNG_RW(surface: _Pointer[SDL_Surface], dst: _Pointer[SDL_RWops], freedst: int, /) -> int: ...
def IMG_LoadAnimation(file: bytes | None, /) -> _Pointer[IMG_Animation]: ...
def IMG_LoadAnimation_RW(src: _Pointer[SDL_RWops], freesrc: int, /) -> _Pointer[IMG_Animation]: ...
def IMG_LoadAnimationTyped_RW(
    src: _Pointer[SDL_RWops], freesrc: int, type: bytes | None, /
) -> _Pointer[IMG_Animation]: ...
def IMG_FreeAnimation(anim: _Pointer[IMG_Animation], /) -> None: ...
def IMG_LoadGIFAnimation_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[IMG_Animation]: ...
def IMG_LoadWEBPAnimation_RW(src: _Pointer[SDL_RWops], /) -> _Pointer[IMG_Animation]: ...

IMG_SetError = SDL_SetError
IMG_GetError = SDL_GetError
