#!/bin/bash

# Turn back on the bottom display
mkdir -p /tmp
touch /tmp/no-hotplug
# Avoid screen corruption on boot 
echo "off" > /sys/class/drm/card0-DSI-2/status
sleep 0.1
echo "on" > /sys/class/drm/card0-DSI-2/status
sleep 0.1
echo "on" > /sys/class/drm/card0-DSI-1/status
