import batoceraFiles
import Command
import controllersConfig
from generators.Generator import Generator
import os
from utils.buildargs import parse_args


class RazeGenerator(Generator):
    config_dir = f"{batoceraFiles.CONF}/raze"
    saves_dir = f"{batoceraFiles.SAVES}/raze"
    # The main config file, which is emitted with duplicate keys and makes working with ConfigParser very annoying
    config_file = f"{config_dir}/raze.ini"
    # A script file with console commands that are always ran when a game starts
    script_file = f"{config_dir}/raze.cfg"
    # Names that Raze uses for game series specific sections in the config file
    game_names = [
        "Blood",
        "Duke",
        "Exhumed",
        "Nam",
        "Redneck",
        "ShadowWarrior",
        "WW2GI",
    ]
    # Options for config file that has more sensible controls and defaults, but only on first boot so overrides persist
    # Raze does not support global bindings; set defaults for each game series
    config_defaults = {}
    for name in game_names:
        config_defaults[f"{name}.ConsoleVariables"] = {
            "hud_size": 8,  # fullscreen / minimal HUD
            "m_sensitivity_x": 6.0,  # speed up movement and look slightly; its a bit slow as default
            "m_sensitivity_y": 5.5,
        }
        # ESC cannot be rebound, which is fine, we override in raze.keys
        config_defaults[f"{name}.Bindings"] = {
            "F6": "quicksave",  # F-keys accessed via raze.keys bindings
            "F9": "quickload",
            "F12": "screenshot",
            "C": "toggleconsole",  # useful for debugging and testing
            "Tab": "togglemap",
            "E": "+Move_Forward",
            "D": "+Move_Backward",
            "S": "+Strafe_Left",
            "F": "+Strafe_Right",
            "PgUp": "+Quick_Kick",  # used in several games
            "PgDn": "+Alt_Fire",  # used in Blood
            "End": "+Crouch",
            "Home": "+Fire",
            "Del": "toggle cl_autorun",
            "Ins": "+toggle_crouch",
            "UpArrow": "weapprev",
            "DownArrow": "weapnext",
            "LeftArrow": "invprev",
            "RightArrow": "invnext",
            "X": "invuse",
            "B": "+jump",
            "Y": "+open",
            "A": "+open",
        }
        config_defaults[f"{name}.AutomapBindings"] = {
            "PgUp": "+Shrink_Screen",
            "PgDn": "+Enlarge_Screen",
            "UpArrow": "+am_panup",
            "DownArrow": "+am_pandown",
            "LeftArrow": "+am_panleft",
            "RightArrow": "+am_panright",
            "Del": "togglefollow",
            "Ins": "togglerotate",
        }

    def generate(self, system, rom, playersControllers, guns, gameResolution):
        for path in [self.config_dir, self.saves_dir]:
            if not os.path.exists(path):
                os.mkdir(path)
        if not os.path.exists(self.config_file):
            with open(self.config_file, "w") as config:
                for section in self.config_defaults:
                    config.write(f"[{section}]\n")
                    for key, value in self.config_defaults[section].items():
                        config.write(f"{key}={value}\n")
                    config.write("\n")
        with open(self.script_file, "w") as script:
            script.write(
                "# This file is automatically generated by razeGenerator.py\n"
                f"vid_fps {'true' if system.getOptBoolean('showFPS') else 'false'}\n"
                "echo BATOCERA\n"  # easy check that script ran in console
            )
        launch_args = ["raze"]
        result = parse_args(launch_args, rom)
        if not result.okay:
            raise Exception(result.message)
        launch_args += [
            "-exec", self.script_file,
            # Disable controllers because support is poor; use evmapy instead
            "-nojoy",
            "-width", str(gameResolution["width"]),
            "-height", str(gameResolution["height"]),
            "-nologo" if system.getOptBoolean("nologo") else "",
        ]
        return Command.Command(
            array=launch_args,
            env={
                'SDL_GAMECONTROLLERCONFIG': controllersConfig.generateSdlGameControllerConfig(playersControllers)
            }
        )
