#!/bin/bash

test "${ACTION}" = "add" || exit 0
echo "${DEVNAME}" | grep -E "^/dev/input/event[0-9]+$" || exit 0

BASEFILE="/var/run/anbernic-pad-devices"
PIDFILE="${BASEFILE}.pid"
LOCKFILE="${BASEFILE}.lock"
LOGFILE="${BASEFILE}.log"
DEVSFILE="${BASEFILE}.devs"

unlockAndExit() {
    rmdir "${LOCKFILE}"
    exit "${1}"
}

checkRunningPIDAndExit1() {
    test ! -e "${PIDFILE}" && return 0
    LPID=$(cat "${PIDFILE}")
    if ! test -d "/proc/${LPID}"; then
        rm -f "${PIDFILE}"
        return 0
    fi
    unlockAndExit 1
}

trylock() {
    # lock
    N=0
    while ! mkdir "${LOCKFILE}"
    do
	sleep 1
	let N++
	test "${N}" -gt 30 && exit 1 # give up
    done
}

EXPECTED_DEVS=3
VIRTUAL_PAD_NAME="Anbernic pad"
EVS_DEVICE_ID_ARG=()

# Get the device model
MODEL=$(batocera-model)

# Check the model and set device-specific variables
case "${MODEL}" in
    Powkiddy_x55)
        # This model expects 2 devices.
        EXPECTED_DEVS=2
        VIRTUAL_PAD_NAME="Powkiddy pad"
        EVS_DEVICE_ID_ARG=( "device-id=ba10:c37a" )
        ;;
    Anbernic_RG35XX*|Anbernic_RG28XX*|Anbernic_RG34XX*|Anbernic_RG40XX*|Anbernic_RGCUBEXX*)
        # These models expect 2 devices for the "RG35xx" virtual pad.
        EXPECTED_DEVS=2
        VIRTUAL_PAD_NAME="Anbernic RG35XX pad"
        EVS_DEVICE_ID_ARG=( "device-id=ba10:c37a" )
        ;;
esac

trylock
checkRunningPIDAndExit1

grep -qF "${DEVNAME}" "${DEVSFILE}" || echo "${DEVNAME}" >> "${DEVSFILE}"

NDEVS=$(cat "${DEVSFILE}" | wc -l)

if [ "${NDEVS}" -eq "${EXPECTED_DEVS}" ]; then
    EVS_ARGS=$(cat "${DEVSFILE}" | xargs -I {} echo --input "{}")
    nohup evsieve ${EVS_ARGS} persist=exit --output name="${VIRTUAL_PAD_NAME}" "${EVS_DEVICE_ID_ARG[@]}" >/dev/null 2>"${LOGFILE}" &

    echo $! > "${PIDFILE}"
    unlockAndExit 0
else
    # This is a safety measure. Clean up and exit with an error.
    if [ "${NDEVS}" -gt "${EXPECTED_DEVS}" ]; then
        rm -f "${DEVSFILE}"
        unlockAndExit 1
    fi

    unlockAndExit 0
fi
