#!/bin/bash
# RetroLX poor man's makedb
# lightweight pacman database creation
# @rtissera
#
# 20210629 - Initial revision

HOST_DIR="$1"

#PATH="${HOST_DIR}/usr/bin:${PATH}" rm retrolx*
PATH="${HOST_DIR}/usr/bin:${PATH}" repo-add "retrolx.db.tar.gz" *.pkg.tar.zst

