#!/bin/bash

test "${ACTION}" = "add" || exit 0
echo "${DEVNAME}" | grep -E "^/dev/input/event[0-9]+$" || exit 0

USBPATHHASH=$(echo "${ID_PATH}" | sed -e s+"\.[0-9]*$"++ | md5sum | cut -c 0-8)

cleanAndExit() {
    rmdir "/var/run/virtual-sindenlightgun-devices.${USBPATHHASH}.lock"
    exit "${1}"
}

# lock
N=0
while ! mkdir "/var/run/virtual-sindenlightgun-devices.${USBPATHHASH}.lock"
do
    sleep 1
    let N++
    test "${N}" -gt 30 && exit 1 # give up
done

NDEVS=$(cat "/var/run/virtual-sindenlightgun-devices.${USBPATHHASH}" | wc -l)

if test "${NDEVS}" = 1
then
    DEV1=$(head -1 "/var/run/virtual-sindenlightgun-devices.${USBPATHHASH}")
    rm "/var/run/virtual-sindenlightgun-devices.${USBPATHHASH}" || cleanAndExit 1

    # 1:     left     / b
    # 2:     right    / a
    # 3:     middle   / home
    # -:     button_1 / select
    # 1:     button_2 / a
    # 2:     button_3 / b
    # +:     button_4 / c
    # up:    button_5 / up
    # down:  button_6 / down
    # left:  button_7 / left
    # right: button_8 / right
    nohup evsieve --input "${DEV1}" "${DEVNAME}" persist=exit --map key:1 btn:1 --map key:2 btn:2 --map key:up btn:5 --map key:down btn:6 --map key:left btn:7 --map key:right btn:8 --output name="Sinden lightgun" >/dev/null 2>"/var/log/virtual-sindenlightgun-devices.${USBPATHHASH}.log" &
    echo $! > "/var/run/virtual-sindenlightgun-devices.${USBPATHHASH}.pid"

    # ttyACM
    ACMSEARCHDIR=/sys$(echo "${DEVPATH}" | cut -d / -f 1-7) # 1-7 ? sure ? no, not sure
    ACM=$(find "${ACMSEARCHDIR}" -name "ttyACM*" | head -1)
    ACMDEV=/dev/$(basename "${ACM}")
    if test -n "${ACMDEV}"
    then
    	mkdir -p "/var/run/sinden" || cleanAndExit 1

	CONFIGFILE="/var/run/sinden/p${USBPATHHASH}/LightgunMono-${USBPATHHASH}.exe.config"

	if ! test -e "/var/run/sinden/p${USBPATHHASH}"
	then
    	    cp -pr /usr/share/sinden "/var/run/sinden/p${USBPATHHASH}" || cleanAndExit 1
	    # mono-service seems to be needed (otherwise, udev won't release, and at batocera statup, it takes long)
	    # but mono-service seems to want a distinguish exe name
	    mv "/var/run/sinden/p${USBPATHHASH}/LightgunMono.exe" "/var/run/sinden/p${USBPATHHASH}/LightgunMono-${USBPATHHASH}.exe" || cleanAndExit 1
	    mv "/var/run/sinden/p${USBPATHHASH}/LightgunMono.exe.config" "${CONFIGFILE}" || cleanAndExit 1
	fi

	# parameters
	RECOIL_MODE=$(batocera-settings-get controllers.guns.recoil)
	case "${RECOIL_MODE}" in
	    "machinegun")
		RECOIL_ENABLED=1
		RECOIL_NORMALORREPEAT=1
		RECOIL_STRENGTH=100
		RECOIL_STARTDELAY=1
		RECOIL_PULSEDELAY=10
	    ;;
	    "machinegun-quiet")
		RECOIL_ENABLED=1
		RECOIL_NORMALORREPEAT=1
		RECOIL_STRENGTH=40
		RECOIL_STARTDELAY=1
		RECOIL_PULSEDELAY=10
	    ;;
	    "gun")
		RECOIL_ENABLED=1
		RECOIL_NORMALORREPEAT=1
		RECOIL_STRENGTH=100
		RECOIL_STARTDELAY=150
		RECOIL_PULSEDELAY=10
	    ;;
	    "gun-quiet")
		RECOIL_ENABLED=1
		RECOIL_NORMALORREPEAT=1
		RECOIL_STRENGTH=40
		RECOIL_STARTDELAY=150
		RECOIL_PULSEDELAY=10
	    ;;
	    *)
		RECOIL_ENABLED=0
		RECOIL_NORMALORREPEAT=1
		RECOIL_STRENGTH=100
		RECOIL_STARTDELAY=150
		RECOIL_PULSEDELAY=10
	    ;;
	esac

	# recoil
	sed -i -e s+'\(key="EnableRecoil"[ ]*value="\)[^"]*"'+'\1'${RECOIL_ENABLED}'"'+ "${CONFIGFILE}" # no exit for that
	sed -i -e s+'\(key="TriggerRecoilNormalOrRepeat"[ ]*value="\)[^"]*"'+'\1'${RECOIL_NORMALORREPEAT}'"'+ "${CONFIGFILE}" # no exit for that
	sed -i -e s+'\(key="AutoRecoilStrength"[ ]*value="\)[^"]*"'+'\1'${RECOIL_STRENGTH}'"'+ "${CONFIGFILE}" # no exit for that
	sed -i -e s+'\(key="AutoRecoilStartDelay"[ ]*value="\)[^"]*"'+'\1'${RECOIL_STARTDELAY}'"'+ "${CONFIGFILE}" # no exit for that
	sed -i -e s+'\(key="AutoRecoilDelayBetweenPulses"[ ]*value="\)[^"]*"'+'\1'${RECOIL_PULSEDELAY}'"'+ "${CONFIGFILE}" # no exit for that

	sed -i -e s+'\(key="SerialPortWrite"[ ]*value="\)[^"]*"'+'\1'${ACMDEV}'"'+ "${CONFIGFILE}" || cleanAndExit 1
	rm -f "/var/run/sinden/p${USBPATHHASH}/lockfile"
	PATH=/bin:/sbin:/usr/bin:/usr/sbin nohup mono-service -l:"/var/run/sinden/p${USBPATHHASH}/lockfile" -d:"/var/run/sinden/p${USBPATHHASH}" --no-daemon "./LightgunMono-${USBPATHHASH}.exe" > "/var/run/sinden/p${USBPATHHASH}/sinden-${USBPATHHASH}.log" &
    fi
    
else
    echo "${DEVNAME}" >> "/var/run/virtual-sindenlightgun-devices.${USBPATHHASH}" || cleanAndExit 1
fi

# unlock
cleanAndExit 0
