#!/bin/bash

test "${ACTION}" = "add" || exit 0
echo "${DEVNAME}" | grep -E "^/dev/input/event[0-9]+$" || exit 0

PARENTHASH=$(evsieve-helper parent "${DEVNAME}")
BASEFILE="/var/run/virtual-sindenlightgun-devices.${PARENTHASH}"
PIDFILE="${BASEFILE}.pid"
LOCKFILE="${BASEFILE}.lock"
LOGFILE="${BASEFILE}.log"
LOGFILE2="${BASEFILE}.log2"

unlockAndExit() {
    rmdir "${LOCKFILE}"
    exit "${1}"
}

checkRunningPIDAndExit1() {
    test ! -e "${PIDFILE}" && return 0
    LPID=$(cat "${PIDFILE}")
    test ! -d "/proc/${LPID}" && return 0
    unlockAndExit 1
}

trylock() {
    # lock
    N=0
    while ! mkdir "${LOCKFILE}"
    do
	sleep 1
	let N++
	test "${N}" -gt 30 && exit 1 # give up
    done
}

trylock
checkRunningPIDAndExit1

CHILDREN=$(evsieve-helper children "${PARENTHASH}")
NDEVS=$(echo "${CHILDREN}" | wc -l)

if test "${NDEVS}" = 2
then
    DEV1=$(echo "${CHILDREN}" | head -1           | cut -f 1)
    DEV2=$(echo "${CHILDREN}" | head -2 | tail -1 | cut -f 1)
    # 1:     left     / b
    # 2:     right    / a
    # 3:     middle   / home
    # -:     button_1 / select
    # 1:     button_2 / a
    # 2:     button_3 / b
    # +:     button_4 / c
    # up:    button_5 / up
    # down:  button_6 / down
    # left:  button_7 / left
    # right: button_8 / right
    nohup evsieve --input "${DEV1}" "${DEV2}" persist=exit --map key:1 btn:1 --map key:2 btn:2 --map key:up btn:5 --map key:down btn:6 --map key:left btn:7 --map key:right btn:8 --output name="Sinden lightgun" >/dev/null 2>"${LOGFILE}" &
    echo $! > "${PIDFILE}"

    # ttyACM
    ACMSEARCHDIR=/sys$(echo "${DEVPATH}" | cut -d / -f 1-8) # 1-7 ? sure ? no, not sure
    ACM=$(find "${ACMSEARCHDIR}" -name "ttyACM*" | head -1)
    ACMDEV=/dev/$(basename "${ACM}")
    if test -n "${ACMDEV}"
    then
    	mkdir -p "/var/run/sinden" || unlockAndExit 1

	CONFIGFILE="/var/run/sinden/p${PARENTHASH}/LightgunMono-${PARENTHASH}.exe.config"

	if ! test -e "/var/run/sinden/p${PARENTHASH}"
	then
    	    cp -pr /usr/share/sinden "/var/run/sinden/p${PARENTHASH}" || unlockAndExit 1
	    # mono-service seems to be needed (otherwise, udev won't release, and at batocera statup, it takes long)
	    # but mono-service seems to want a distinguish exe name
	    mv "/var/run/sinden/p${PARENTHASH}/LightgunMono.exe" "/var/run/sinden/p${PARENTHASH}/LightgunMono-${PARENTHASH}.exe" || unlockAndExit 1
	    mv "/var/run/sinden/p${PARENTHASH}/LightgunMono.exe.config" "${CONFIGFILE}" || unlockAndExit 1
	fi

	# parameters
	RECOIL_MODE=$(batocera-settings-get controllers.guns.recoil)
	case "${RECOIL_MODE}" in
	    "machinegun")
		RECOIL_ENABLED=1
		RECOIL_NORMALORREPEAT=1
		RECOIL_STRENGTH=100
		RECOIL_STARTDELAY=1
		RECOIL_PULSEDELAY=10
	    ;;
	    "machinegun-quiet")
		RECOIL_ENABLED=1
		RECOIL_NORMALORREPEAT=1
		RECOIL_STRENGTH=40
		RECOIL_STARTDELAY=1
		RECOIL_PULSEDELAY=10
	    ;;
	    "gun")
		RECOIL_ENABLED=1
		RECOIL_NORMALORREPEAT=1
		RECOIL_STRENGTH=100
		RECOIL_STARTDELAY=150
		RECOIL_PULSEDELAY=10
	    ;;
	    "gun-quiet")
		RECOIL_ENABLED=1
		RECOIL_NORMALORREPEAT=1
		RECOIL_STRENGTH=40
		RECOIL_STARTDELAY=150
		RECOIL_PULSEDELAY=10
	    ;;
	    *)
		RECOIL_ENABLED=0
		RECOIL_NORMALORREPEAT=1
		RECOIL_STRENGTH=100
		RECOIL_STARTDELAY=150
		RECOIL_PULSEDELAY=10
	    ;;
	esac

	# recoil
	sed -i -e s+'\(key="EnableRecoil"[ ]*value="\)[^"]*"'+'\1'${RECOIL_ENABLED}'"'+ "${CONFIGFILE}" # no exit for that
	sed -i -e s+'\(key="TriggerRecoilNormalOrRepeat"[ ]*value="\)[^"]*"'+'\1'${RECOIL_NORMALORREPEAT}'"'+ "${CONFIGFILE}" # no exit for that
	sed -i -e s+'\(key="AutoRecoilStrength"[ ]*value="\)[^"]*"'+'\1'${RECOIL_STRENGTH}'"'+ "${CONFIGFILE}" # no exit for that
	sed -i -e s+'\(key="AutoRecoilStartDelay"[ ]*value="\)[^"]*"'+'\1'${RECOIL_STARTDELAY}'"'+ "${CONFIGFILE}" # no exit for that
	sed -i -e s+'\(key="AutoRecoilDelayBetweenPulses"[ ]*value="\)[^"]*"'+'\1'${RECOIL_PULSEDELAY}'"'+ "${CONFIGFILE}" # no exit for that

	sed -i -e s+'\(key="SerialPortWrite"[ ]*value="\)[^"]*"'+'\1'${ACMDEV}'"'+ "${CONFIGFILE}" || unlockAndExit 1
	rm -f "/var/run/sinden/p${PARENTHASH}/lockfile"
	PATH=/bin:/sbin:/usr/bin:/usr/sbin nohup mono-service -l:"/var/run/sinden/p${PARENTHASH}/lockfile" -d:"/var/run/sinden/p${PARENTHASH}" --no-daemon "./LightgunMono-${PARENTHASH}.exe" > "${LOGFILE2}" &
    fi
else
    unlockAndExit 1
fi

unlockAndExit 0
