#!/bin/bash

test "${ACTION}" = "add" || exit 0
echo "${DEVNAME}" | grep -E "^/dev/input/event[0-9]+$" || exit 0

USBPATHHASH=$(echo "${ID_PATH}" | sed -e s+"\.[0-9]*$"++ | md5sum | cut -c 0-8)

cleanAndExit() {
    rmdir "/var/run/virtual-sindenlightgun-devices.${USBPATHHASH}.lock"
    exit "${1}"
}

# lock
N=0
while ! mkdir "/var/run/virtual-sindenlightgun-devices.${USBPATHHASH}.lock"
do
    sleep 1
    let N++
    test "${N}" -gt 30 && exit 1 # give up
done

NDEVS=$(cat "/var/run/virtual-sindenlightgun-devices.${USBPATHHASH}" | wc -l)

echo "${DEVNAME} ${USBPATHHASH} ${ID_PATH}" >> /var/run/virtual-sindenlightgun-devices.seen || cleanAndExit 1

if test "${NDEVS}" = 1
then
    DEV1=$(head -1 "/var/run/virtual-sindenlightgun-devices.${USBPATHHASH}")
    rm "/var/run/virtual-sindenlightgun-devices.${USBPATHHASH}" || cleanAndExit 1

    # 1:     left     / b
    # 2:     right    / a
    # 3:     middle   / home
    # -:     button_1 / select
    # 1:     button_2 / a
    # 2:     button_3 / b
    # +:     button_4 / c
    # up:    button_5 / up
    # down:  button_6 / down
    # left:  button_7 / left
    # right: button_8 / right
    nohup evsieve --input "${DEV1}" "${DEVNAME}" persist=exit --map key:1 btn:1 --map key:leftalt btn:2 --output name="Sinden lightgun" >/dev/null 2>"/var/log/virtual-sindenlightgun-devices.${USBPATHHASH}.log" &
    echo $! > "/var/run/virtual-sindenlightgun-devices.${USBPATHHASH}.pid"

    # ttyACM
    ACMSEARCHDIR=/sys$(echo "${DEVPATH}" | cut -d / -f 1-7) # 1-7 ? sure ? no, not sure
    ACM=$(find "${ACMSEARCHDIR}" -name "ttyACM*" | head -1)
    ACMDEV=/dev/$(basename "${ACM}")
    if test -n "${ACMDEV}"
    then
    	mkdir -p "/var/run/sinden" || cleanAndExit 1
	if ! test -e "/var/run/sinden/p${USBPATHHASH}"
	then
    	    cp -pr /usr/share/sinden "/var/run/sinden/p${USBPATHHASH}" || cleanAndExit 1
	fi

	# parameters
	sed -i -e s+'\(key="SerialPortWrite"[ ]*value="\)[^"]*"'+'\1'${ACMDEV}'"'+ "/var/run/sinden/p${USBPATHHASH}/LightgunMono.exe.config" || cleanAndExit 1
	
	(cd "/var/run/sinden/p${USBPATHHASH}" && PATH=/bin:/sbin:/usr/bin:/usr/sbin nohup mono-service ./LightgunMono.exe >"/var/log/sinden.${USBPATHHASH}.out" 2>"/var/log/sinden.${USBPATHHASH}.log" &)
    fi
    
else
    echo "${DEVNAME}" >> "/var/run/virtual-sindenlightgun-devices.${USBPATHHASH}" || cleanAndExit 1
fi

# unlock
cleanAndExit 0
