#!/bin/bash

if test "$1" = start
then
    systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/batoceraSettings.py"
    powerswitch="`$systemsetting  -command load -key system.power.switch`"
    if test "${powerswitch}" = "RETROFLAG"
    then
	python /usr/bin/retroflag_SafeShutdown.py &
    fi
fi

if test "$1" = stop
then
    BTD_PID=$(ps -eo pid,args | grep "python /usr/bin/retroflag_SafeShutdown.py" | grep -v grep | awk '{print $1}')
    if [ ! -z "$BTD_PID" ]; then
        kill $BTD_PID
    fi
fi
