import batoceraFiles
import Command
import controllersConfig
from generators.Generator import Generator
import os


# NOTE: gzdoom.ini is emitted with duplicate keys and makes working with ConfigParser very annoying
class GZDoomGenerator(Generator):
    def generate(self, system, rom, playersControllers, guns, gameResolution):
        config_dir = f"{batoceraFiles.CONF}/gzdoom"
        if not os.path.exists(config_dir):
            os.mkdir(config_dir)

        have_gles = os.path.exists('/usr/lib/libGLESv2_CM.so') or os.path.exists('/usr/lib/libGLESv2.so')
        have_opengl = os.path.exists('/usr/lib/libGL.so')

        extra_config = ''
        if have_gles and not have_opengl:
            extra_config += (
                # Use the actual GLES context, not an OpenGL one:
                "gl_es 1\n"
                "vid_preferbackend 3\n"
                # This setting greatly improves performance:
                "gles_use_mapped_buffer true\n"
            )

        # A script file with console commands that are always ran when a game starts
        script_file = f"{config_dir}/gzdoom.cfg"
        with open(script_file, "w") as script:
            script.write(
                "# This file is automatically generated by gzdoomGenerator.py\n"
                # In the code, logfile does not appear to be created unless done so explicitly
                f"logfile {batoceraFiles.logdir}/gzdoom.log\n"
                f"vid_fps {'true' if system.getOptBoolean('showFPS') else 'false'}\n"
                f"{extra_config}"
                "echo BATOCERA\n"  # easy check that script ran in console
            )
        return Command.Command(
            array=[
                "gzdoom",
                "-iwad", rom,
                "-exec", script_file,
                # Disable controllers because support is poor; use evmapy instead
                "-nojoy",
                "-width", str(gameResolution["width"]),
                "-height", str(gameResolution["height"]),
                "-nologo" if system.getOptBoolean("nologo") else "",
            ],
            env={
                'SDL_GAMECONTROLLERCONFIG': controllersConfig.generateSdlGameControllerConfig(playersControllers)
            }
        )
