################################################################################
#
# azahar
#
################################################################################
# Version: Commits on Mar 13, 2025
AZAHAR_VERSION = 58b2ebd5cd14eb49ecdd153224e9a07c9c51a423
AZAHAR_SITE = https://github.com/azahar-emu/azahar.git
AZAHAR_SITE_METHOD=git
AZAHAR_GIT_SUBMODULES = YES
AZAHAR_LICENSE = GPLv2
AZAHAR_SUPPORTS_IN_SOURCE_BUILD = NO

AZAHAR_DEPENDENCIES += boost fdk-aac ffmpeg fmt openal sdl2

AZAHAR_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
AZAHAR_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
AZAHAR_CONF_OPTS += -DENABLE_TESTS=OFF
AZAHAR_CONF_OPTS += -DENABLE_DEDICATED_ROOM=OFF
AZAHAR_CONF_OPTS += -DCITRA_WARNINGS_AS_ERRORS=OFF
AZAHAR_CONF_OPTS += -DCITRA_ENABLE_COMPATIBILITY_REPORTING=ON
AZAHAR_CONF_OPTS += -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON
AZAHAR_CONF_OPTS += -DENABLE_WEB_SERVICE=OFF
AZAHAR_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF
AZAHAR_CONF_OPTS += -DENABLE_SOFTWARE_RENDERER=OFF
AZAHAR_CONF_OPTS += -DENABLE_OPENAL=ON
AZAHAR_CONF_OPTS += -DUSE_SYSTEM_OPENAL=ON
AZAHAR_CONF_OPTS += -DUSE_SYSTEM_BOOST=OFF
AZAHAR_CONF_OPTS += -DENABLE_SDL2=ON
AZAHAR_CONF_OPTS += -DUSE_SYSTEM_SDL2=ON    # important to avoid HIDAPI
AZAHAR_CONF_OPTS += -DENABLE_LTO=OFF

ifeq ($(BR2_PACKAGE_QT6),y)
    AZAHAR_DEPENDENCIES += qt6base qt6tools qt6multimedia
    AZAHAR_CONF_OPTS += -DENABLE_QT=ON
    AZAHAR_CONF_OPTS += -DENABLE_QT_TRANSLATION=ON
    AZAHAR_CONF_OPTS += -DENABLE_QT_UPDATER=OFF
else
    AZAHAR_CONF_OPTS += -DENABLE_QT=OFF
    AZAHAR_CONF_OPTS += -DENABLE_SDL2_FRONTEND=ON
endif

ifeq ($(BR2_PACKAGE_BATOCERA_VULKAN),y)
    AZAHAR_CONF_OPTS += -DENABLE_VULKAN=ON
    AZAHAR_DEPENDENCIES += vulkan-headers vulkan-loader
else
    AZAHAR_CONF_OPTS += -DENABLE_VULKAN=OFF
endif

AZAHAR_CONF_ENV += LDFLAGS=-lpthread

define AZAHAR_INSTALL_TARGET_CMDS
    mkdir -p $(TARGET_DIR)/usr/bin
	$(INSTALL) -D $(@D)/buildroot-build/bin/Release/azahar \
		$(TARGET_DIR)/usr/bin/
endef

define AZAHAR_EVMAPY
	mkdir -p $(TARGET_DIR)/usr/share/evmapy
	cp -prn $(BR2_EXTERNAL_BATOCERA_PATH)/package/batocera/emulators/azahar/3ds.azahar.keys \
		$(TARGET_DIR)/usr/share/evmapy
endef

AZAHAR_POST_INSTALL_TARGET_HOOKS = AZAHAR_EVMAPY

$(eval $(cmake-package))
