gamecube:
  emulator: dolphin
  core:     dolphin
  options:
    gfxbackend: Vulkan
    dual_core: true
nds:
  emulator: drastic
  core:     drastic
wii:
  emulator: dolphin
  core:     dolphin
  options:
    gfxbackend: Vulkan
    dual_core: true
fmtowns:
  emulator: libretro
  core:     mame
psx:
  options:
    hud_support: false # duckstation doesn't like it
ps2:
  emulator: libretro
  core:     play
flash:
  emulator: lightspark
  core:     lightspark
