SectionDevice."Headphones" {
	Comment "Headphones"

	EnableSequence [
		cset "name='Playback Mux' HP"
	]

	Value {
		PlaybackMixerElem "Master Playback Volume"
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId}"
		JackControl "Headphones Jack"
	}
}

SectionDevice."Mic" {
	Comment "Microphone"

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId}"
		CaptureMixerElem "Mic Capture Gain"
		CaptureMasterElem "Master Capture Volume"
	}
}
