#!/bin/bash

test "${1}" = "start" || exit 0

# disable low cores
echo "0" > /sys/devices/system/cpu/cpu0/online
echo "0" > /sys/devices/system/cpu/cpu1/online
echo "0" > /sys/devices/system/cpu/cpu2/online
echo "0" > /sys/devices/system/cpu/cpu3/online
