# Use case configuration for devices using the ES8388 codec via simple-audio-card
# Device(s): Anbernic RG Vita Pro (RK3576)

SectionDevice."Speaker" {
	Comment "Internal Speakers"

	EnableSequence [
		cset "name='Internal Speakers Switch' on"
	]

	DisableSequence [
		cset "name='Internal Speakers Switch' off"
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixerElem "Internal Speakers"
	}

	ConflictingDevice [
		"Headphones"
	]
}

SectionDevice."Headphones" {
	Comment "Headphones"

	EnableSequence [
		cset "name='Headphones Switch' on"
	]

	DisableSequence [
		cset "name='Headphones Switch' off"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixerElem "Headphones"
		JackControl "Headphones Jack"
		JackHWMute "Speaker"
	}

	ConflictingDevice [
		"Speaker"
	]
}

SectionDevice."Mic" {
	Comment "Microphone"

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId},0"
	}
}
