################################################################################
#
# LIBRETRO-FLYCASTVL
#
################################################################################
# version.: Commits on Oct 04, 2021
LIBRETRO_FLYCASTVL_VERSION = 4a913e063c95d1fae98afc64645831de0bcad57e
LIBRETRO_FLYCASTVL_SITE = $(call github,libretro,flycast,$(LIBRETRO_FLYCASTVL_VERSION))
LIBRETRO_FLYCASTVL_LICENSE = GPLv2
LIBRETRO_FLYCASTVL_DEPENDENCIES = retroarch

LIBRETRO_FLYCASTVL_PLATFORM = $(LIBRETRO_PLATFORM)
LIBRETRO_FLYCASTVL_EXTRA_ARGS = HAVE_OPENMP=1

# LIBRETRO_PLATFORM is not good for this core, because
# for rpi, it contains "unix rpi" and this core do an "if unix elif rpi ..."

# special cases for special plateform then...
# an other proper way may be to redo the Makefile to do "if rpi elif unix ..." (from specific to general)
# the Makefile imposes that the platform has gles (or force FORCE_GLES is set) to not link with lGL

ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_BCM2711),y)
LIBRETRO_FLYCASTVL_PLATFORM = rpi4_64-neon
LIBRETRO_FLYCASTVL_EXTRA_ARGS += FORCE_GLES=1 ARCH=arm64 LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_BCM2837),y)
LIBRETRO_FLYCASTVL_PLATFORM = rpi3_64-neon
LIBRETRO_FLYCASTVL_EXTRA_ARGS += FORCE_GLES=1 ARCH=arm64 LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_XU4),y)
LIBRETRO_FLYCASTVL_PLATFORM = odroid
LIBRETRO_FLYCASTVL_EXTRA_ARGS += BOARD=ODROID-XU4 FORCE_GLES=1 ARCH=arm LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_TRITIUM_H5),y)
LIBRETRO_FLYCASTVL_PLATFORM = h5
LIBRETRO_FLYCASTVL_EXTRA_ARGS += ARCH=arm64 FORCE_GLES=1 LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_ORANGEPI_ZERO2),y)
LIBRETRO_FLYCASTVL_PLATFORM = h616
LIBRETRO_FLYCASTVL_EXTRA_ARGS += ARCH=arm64 FORCE_GLES=1 LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_S905),y)
LIBRETRO_FLYCASTVL_PLATFORM = AMLGX
LIBRETRO_FLYCASTVL_EXTRA_ARGS += ARCH=arm64 FORCE_GLES=1 LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_S912),y)
LIBRETRO_FLYCASTVL_PLATFORM = AMLGXM
LIBRETRO_FLYCASTVL_EXTRA_ARGS += ARCH=arm64 FORCE_GLES=1 LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_S905GEN2),y)
LIBRETRO_FLYCASTVL_PLATFORM = mali-drm-gles2
LIBRETRO_FLYCASTVL_EXTRA_ARGS += ARCH=arm64 FORCE_GLES=1 LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_S905GEN3),y)
LIBRETRO_FLYCASTVL_PLATFORM = odroidc4
LIBRETRO_FLYCASTVL_EXTRA_ARGS += ARCH=arm64 FORCE_GLES=1 LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_RK3399),y)
LIBRETRO_FLYCASTVL_PLATFORM = rpi-rpi4_64
LIBRETRO_FLYCASTVL_EXTRA_ARGS += ARCH=arm64 FORCE_GLES=1 LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_S922X),y)
LIBRETRO_FLYCASTVL_PLATFORM = odroid-n2
LIBRETRO_FLYCASTVL_EXTRA_ARGS += ARCH=arm64 FORCE_GLES=1 LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_RK3326_ANY),y)
LIBRETRO_FLYCASTVL_PLATFORM = arm64
LIBRETRO_FLYCASTVL_EXTRA_ARGS += ARCH=arm64 FORCE_GLES=1 LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_ORANGEPI_PC),y)
LIBRETRO_FLYCASTVL_PLATFORM = sun8i
LIBRETRO_FLYCASTVL_EXTRA_ARGS += ARCH=arm FORCE_GLES=1 LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_S812),y)
LIBRETRO_FLYCASTVL_PLATFORM = odroid
LIBRETRO_FLYCASTVL_EXTRA_ARGS += ARCH=arm FORCE_GLES=1 LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_RK3288),y)
LIBRETRO_FLYCASTVL_PLATFORM = tinkerboard
LIBRETRO_FLYCASTVL_EXTRA_ARGS += ARCH=arm

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_X86),y)
LIBRETRO_FLYCASTVL_EXTRA_ARGS += ARCH=x86
endif

# Define the info files here because you can't do that in target_cmd.
ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_X86)$(BR2_PACKAGE_BATOCERA_TARGET_RK3288),y)
	LIBRETRO_FLYCASTVL_INFO_FILE = flycastvl_libretro.info
else
	LIBRETRO_FLYCASTVL_INFO_FILE = flycastvl_gles2_libretro.info
endif

define LIBRETRO_FLYCASTVL_BUILD_CMDS
    $(TARGET_CONFIGURE_OPTS) $(MAKE) CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" -C $(@D)/ -f Makefile \
		platform="$(LIBRETRO_FLYCASTVL_PLATFORM)" $(LIBRETRO_FLYCASTVL_EXTRA_ARGS) \
        GIT_VERSION="-$(shell echo $(LIBRETRO_FLYCASTVL_VERSION) | cut -c 1-7)"
endef

define LIBRETRO_FLYCASTVL_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/flycast_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/flycastvl_libretro.so
	cp "$(BR2_EXTERNAL_BATOCERA_PATH)/package/batocera/emulators/retroarch/libretro/libretro-flycastvl/$(LIBRETRO_FLYCASTVL_INFO_FILE)" "$(TARGET_DIR)/usr/share/libretro/info/flycastvl_libretro.info"
endef

$(eval $(generic-package))
