#!/bin/bash

ACTION=$1
shift

#Started from Terminal/SSH or from Emulationstation?
[ -t 1 ] && TERMINAL=1 || TERMINAL=0

case "${ACTION}" in
    "install")
	PKG=$1
	pacman --noconfirm -S "${PKG}"
	RET=$?
	if [ ${RET} -eq 1 ]; then
		sleep 1
		pgrep pacman >/dev/null || rm -f /userdata/system/pacman/db/db.lck
	fi
	exit ${RET}
	;;
    "remove")
	PKG=$1
	pacman --noconfirm -R "${PKG}"
	RET=$?
	if [ ${RET} -eq 1 ]; then
		sleep 1
		pgrep pacman >/dev/null || rm -f /userdata/system/pacman/db/db.lck
	fi
	exit ${RET}
	;;
    "list")
	if test ! -e /userdata/system/pacman/db/sync/batocera.db
	then
		pacman --noconfirm -Syu
	fi
	if [ $TERMINAL -eq 1 ]; then
		pacman --noconfirm -Ss
		RET=$?
	else
		pacman --noconfirm -Ss --xml
		RET=$?
	fi
	exit ${RET}
	;;
    "update")
	pacman --noconfirm -Syu
	exit $?
	;;
    *)
	echo "${0} install <package>" >&2
	echo "${0} remove  <package>" >&2
	echo "${0} list" >&2
	echo "${0} update" >&2
esac
