#!/usr/bin/env python
import os
import sys
import re
import time
import subprocess

def closeMainApp():
	# Select Frame 0, close app if open
	try:
		frameReturn = getRatpoisonCommand('fselect 0')
	except:
		return False
	runRatpoisonCommand('delete')

def restoreFrameset():
	# Load saved ES frame info from env variable
	savedFrameset = getRatpoisonCommand('getenv frameset')
	runRatpoisonCommand(f'frestore {savedFrameset}')

def clearHooks():
	# Clear window management hooks
	runRatpoisonCommand('remhook deletewindow exec batocera-ratpoison reset')
	runRatpoisonCommand('remhook newwindow focus')

def redrawWindow():
	# Just in case ES isn't displaying
	runRatpoisonCommand('only')
	runRatpoisonCommand('redisplay')

def runRatpoisonCommand(command):
	print(f'Running ratpoison command {command}')
	try:
		subprocess.call(f'LC_ALL=C ratpoison -c "{command}"', shell=True)
	except:
		return False

def getRatpoisonCommand(command):
	print(f'Running ratpoison command {command}')
	try:
		return subprocess.check_output(f'LC_ALL=C ratpoison -c "{command}"', shell=True).decode(sys.stdout.encoding)
	except:
		return False

if __name__ == '__main__':
	if len(sys.argv) == 1:
		print('Error, command needed.')
	if sys.argv[1] == 'reset':
		clearHooks()
		# closeMainApp()
		restoreFrameset()
		redrawWindow()

