#!/bin/bash

ACTION=$1

case "${ACTION}" in
	"unlock-volume")
		amixer set 'FRDDR_A SRC 1 EN' on
		amixer set "FRDDR_A SINK 1 SEL" "OUT 1"
		amixer set "FRDDR_B SRC 1 EN" on
		amixer set "FRDDR_B SINK 1 SEL" "OUT 1"
		amixer set "FRDDR_C SRC 1 EN" on
		amixer set "FRDDR_C SINK 1 SEL" "OUT 1"
		amixer set "TOHDMITX I2S SRC" "I2S B"
		amixer set "TDMOUT_B SRC SEL" "IN 0"
		amixer set "TOHDMITX" on
	;;

	"list")
		echo "auto (=hdmi)"
		echo "hdmi"
	;;

	"get")
		batocera-settings -command load -key audio.device
	;;

	"set")
	;;
esac
