#!/bin/bash

ACTION=$1

MODEL=$(cat /sys/firmware/devicetree/base/model)

# specific action related to rg552
if test "${MODEL}" = "Anbernic RG552"
then
    if test "${ACTION}" = "setOutput"
    then
	# force no hdmi if it is unplugged
	NEWCONN=$(cat /var/run/drmConn)
	HDMISTATUS=$(cat /sys/class/gpio/gpio54/value)
	if test "${NEWCONN}" = 1 -a "${HDMISTATUS}" = 1
	then
	    # force 0 which is supposed to be the internal device
	    echo 0 > /var/run/drmConn
	fi

	# rotation : force rotation for the internal device
	NEWCONN=$(cat /var/run/drmConn)
	if test "${NEWCONN}" = 0
	then
	    touch /var/run/rk-rotation
	else
	    rm -f /var/run/rk-rotation
	fi

	# force audio associated with the device
	if test "${NEWCONN}" = 0
	then
	    INTERNAL_AUDIO=$(batocera-audio list | grep -E "^[^ ]* ES8316 " | head -1 | cut -d ' ' -f 1)
	    if test -n "${INTERNAL_AUDIO}"
	    then
		batocera-audio set "${INTERNAL_AUDIO}"
	    fi
	else
	    HDMI_AUDIO=$(batocera-audio list | grep -E "^[^ ]* HDMI " | head -1 | cut -d ' ' -f 1)
	    if test -n "${HDMI_AUDIO}"
	    then
		batocera-audio set "${HDMI_AUDIO}"
	    fi
	fi
    fi
fi
