#!/bin/sh

# batocera-nvidia applies either the installed production or legacy driver(s)
# this is detected at boot in S04populate
# configuration can also be set using batoceta-boot.conf

# kernel version
LINUX_VER=$(uname -r)
# production driver version
BATOCERA_NVIDIA_DRIVER_VERSION=$(cat /usr/share/nvidia/production.version)
# legacy driver versions
BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION=$(cat /usr/share/nvidia/legacy.version) # currently 470.xx.xx
BATOCERA_NVIDIA390_LEGACY_DRIVER_VERSION=$(cat /usr/share/nvidia/legacy390.version)
#BATOCERA_NVIDIA340_LEGACY_DRIVER_VERSION=$(cat /usr/share/nvidia/legacy340.version)

if test "$1" = "production"
then
	echo "Using NVIDIA Production driver - ${BATOCERA_NVIDIA_DRIVER_VERSION}"
	echo
	echo "blacklist nouveau" > /etc/modprobe.d/blacklist-nouveau.conf
	echo "options nvidia-drm modeset=1" > /etc/modprobe.d/nvidia-drm.conf
	# symbolic link 64-bit library files
	mkdir -p /var/run/lib
	# libGLX_nvidia.so
	ln -sf /usr/lib/libGLX_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libGLX_nvidia.so
	ln -sf /var/run/lib/libGLX_nvidia.so /usr/lib/libGLX_nvidia.so
	ln -sf /usr/lib/libGLX_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libGLX_nvidia.so.0
	ln -sf /var/run/lib/libGLX_nvidia.so.0 /usr/lib/libGLX_nvidia.so.0
	# libEGL_nvidia.so
	ln -sf /usr/lib/libEGL_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libEGL_nvidia.so
	ln -sf /var/run/lib/libEGL_nvidia.so /usr/lib/libEGL_nvidia.so
	ln -sf /usr/lib/libEGL_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libEGL_nvidia.so.0
	ln -sf /var/run/lib/libEGL_nvidia.so.0 /usr/lib/libEGL_nvidia.so.0
	# libGLESv1_CM_nvidia.so
	ln -sf /usr/lib/libGLESv1_CM_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libGLESv1_CM_nvidia.so
	ln -sf /var/run/lib/libGLESv1_CM_nvidia.so /usr/lib/libGLESv1_CM_nvidia.so
	ln -sf /usr/lib/libGLESv1_CM_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libGLESv1_CM_nvidia.so.1
	ln -sf /var/run/lib/libGLESv1_CM_nvidia.so.1 /usr/lib/libGLESv1_CM_nvidia.so.1
	# libGLESv2_nvidia.so
	ln -sf /usr/lib/libGLESv2_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libGLESv2_nvidia.so
	ln -sf /var/run/lib/libGLESv2_nvidia.so /usr/lib/libGLESv2_nvidia.so
	ln -sf /usr/lib/libGLESv2_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libGLESv2_nvidia.so.2
	ln -sf /var/run/lib/libGLESv2_nvidia.so.2 /usr/lib/libGLESv2_nvidia.so.2
	# libnvidia-eglcore.so
	ln -sf /usr/lib/libnvidia-eglcore.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libnvidia-eglcore.so
	ln -sf /var/run/lib/libnvidia-eglcore.so /usr/lib/libnvidia-eglcore.so
	# libnvidia-glcore.so
	ln -sf /usr/lib/libnvidia-glcore.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libnvidia-glcore.so
	ln -sf /var/run/lib/libnvidia-glcore.so /usr/lib/libnvidia-glcore.so
	# libnvidia-glsi.so
	ln -sf /usr/lib/libnvidia-glsi.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libnvidia-glsi.so
	ln -sf /var/run/lib/libnvidia-glsi.so /usr/lib/libnvidia-glsi.so
	# libnvidia-tls.so
	ln -sf /usr/lib/libnvidia-tls.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libnvidia-tls.so
	ln -sf /var/run/lib/libnvidia-tls.so /usr/lib/libnvidia-tls.so
	# libvdpau_nvidia.so
	ln -sf /usr/lib/libvdpau_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libvdpau_nvidia.so
	ln -sf /var/run/lib/libvdpau_nvidia.so /usr/lib/libvdpau_nvidia.so
	ln -sf /usr/lib/libvdpau_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libvdpau_nvidia.so.1
	ln -sf /var/run/lib/libvdpau_nvidia.so.1 /usr/lib/libvdpau_nvidia.so.1
	# libnvidia-ml.so
	ln -sf /usr/lib/libnvidia-ml.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libnvidia-ml.so
	ln -sf /var/run/lib/libnvidia-ml.so /usr/lib/libnvidia-ml.so
	ln -sf /usr/lib/libnvidia-ml.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libnvidia-ml.so.1
	ln -sf /var/run/lib/libnvidia-ml.so.1 /usr/lib/libnvidia-ml.so.1
	# libnvidia-glvkspirv.so
	ln -sf /usr/lib/libnvidia-glvkspirv.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libnvidia-glvkspirv.so
	ln -sf /var/run/lib/libnvidia-glvkspirv.so /usr/lib/libnvidia-glvkspirv.so
	# [symbolic link 32-bit library files]
	mkdir -p /var/run/lib32
	# libGLX_nvidia.so
	ln -sf /lib32/libGLX_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib32/libGLX_nvidia.so
	ln -sf /var/run/lib32/libGLX_nvidia.so /lib32/libGLX_nvidia.so
	ln -sf /lib32/libGLX_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib32/libGLX_nvidia.so.0
	ln -sf /var/run/lib32/libGLX_nvidia.so.0 /lib32/libGLX_nvidia.so.0
	# libEGL_nvidia.so
	ln -sf /lib32/libEGL_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib32/libEGL_nvidia.so
	ln -sf /var/run/lib32/libEGL_nvidia.so /lib32/libEGL_nvidia.so
	ln -sf /lib32/libEGL_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib32/libEGL_nvidia.so.0
	ln -sf /var/run/lib32/libEGL_nvidia.so.0 /lib32/libEGL_nvidia.so.0
	# libGLESv1_CM_nvidia.so
	ln -sf /lib32/libGLESv1_CM_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib32/libGLESv1_CM_nvidia.so
	ln -sf /var/run/lib32/libGLESv1_CM_nvidia.so /lib32/libGLESv1_CM_nvidia.so
	ln -sf /lib32/libGLESv1_CM_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib32/libGLESv1_CM_nvidia.so.1
	ln -sf /var/run/lib32/libGLESv1_CM_nvidia.so.1 /lib32/libGLESv1_CM_nvidia.so.1
	# libGLESv2_nvidia.so
	ln -sf /lib32/libGLESv2_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib32/libGLESv2_nvidia.so
	ln -sf /var/run/lib32/libGLESv2_nvidia.so /lib32/libGLESv2_nvidia.so
	ln -sf /lib32/libGLESv2_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib32/libGLESv2_nvidia.so.2
	ln -sf /var/run/lib32/libGLESv2_nvidia.so.2 /lib32/libGLESv2_nvidia.so.2
	# libnvidia-eglcore.so
	ln -sf /lib32/libnvidia-eglcore.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib32/libnvidia-eglcore.so
	ln -sf /var/run/lib32/libnvidia-eglcore.so /lib32/libnvidia-eglcore.so
	# libnvidia-glcore.so
	ln -sf /lib32/libnvidia-glcore.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib32/libnvidia-glcore.so
	ln -sf /var/run/lib32/libnvidia-glcore.so /lib32/libnvidia-glcore.so
	# libnvidia-glsi.so
	ln -sf /lib32/libnvidia-glsi.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib32/libnvidia-glsi.so
	ln -sf /var/run/lib32/libnvidia-glsi.so /lib32/libnvidia-glsi.so
	# libnvidia-tls.so
	ln -sf /lib32/libnvidia-tls.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib32/libnvidia-tls.so
	ln -sf /var/run/lib32/libnvidia-tls.so /lib32/libnvidia-tls.so
	# libvdpau_nvidia.so
	ln -sf /lib32/libvdpau_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib32/libvdpau_nvidia.so
	ln -sf /var/run/lib32/libvdpau_nvidia.so /lib32/libvdpau_nvidia.so
	ln -sf /lib32/libvdpau_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib32/libvdpau_nvidia.so.1
	ln -sf /var/run/lib32/libvdpau_nvidia.so.1 /lib32/libvdpau_nvidia.so.1
	# libnvidia-ml.so
	ln -sf /lib32/libnvidia-ml.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib32/libnvidia-ml.so
	ln -sf /var/run/lib32/libnvidia-ml.so /lib32/libnvidia-ml.so
	ln -sf /lib32/libnvidia-ml.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib32/libnvidia-ml.so.1
	ln -sf /var/run/lib32/libnvidia-ml.so.1 /lib32/libnvidia-ml.so.1
	# libnvidia-glvkspirv.so
	ln -sf /lib32/libnvidia-glvkspirv.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib32/libnvidia-glvkspirv.so
	ln -sf /var/run/lib32/libnvidia-glvkspirv.so /lib32/libnvidia-glvkspirv.so
	# sym link Xorg libraries too
	ln -sf /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libglxserver_nvidia.so
	ln -sf /var/run/lib/libglxserver_nvidia.so /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so
	ln -sf /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/lib/libglxserver_nvidia.so.1
	ln -sf /var/run/lib/libglxserver_nvidia.so.1 /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so.1
	# link Xorg driver
	ln -sf /usr/lib/xorg/modules/drivers/nvidia_production_drv.so /var/run/lib/nvidia_drv.so
	ln -sf /var/run/lib/nvidia_drv.so /usr/lib/xorg/modules/drivers/nvidia_drv.so
	# link GL config files
	mkdir -p /var/run/configs
	ln -sf /usr/share/vulkan/implicit_layer.d/nvidia_production_layers.json /var/run/configs/nvidia_layers.json
	ln -sf /var/run/configs/nvidia_layers.json /usr/share/vulkan/implicit_layer.d/nvidia_layers.json
	ln -sf /usr/share/glvnd/egl_vendor.d/10_nvidia_production.json /var/run/configs/10_nvidia.json
	ln -sf /var/run/configs/10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json
	ln -sf /usr/share/X11/xorg.conf.d/10-nvidia-production-drm-outputclass.conf /var/run/configs/10-nvidia-drm-outputclass.conf
	ln -sf /var/run/configs/10-nvidia-drm-outputclass.conf /usr/share/X11/xorg.conf.d/10-nvidia-drm-outputclass.conf
	# link Vulkan icd files
	ln -sf /usr/share/vulkan/icd.d/nvidia_production_icd.x86_64.json /var/run/configs/nvidia_icd.x86_64.json
	ln -sf /var/run/configs/nvidia_icd.x86_64.json /usr/share/vulkan/icd.d/nvidia_icd.x86_64.json
	ln -sf /usr/share/vulkan/icd.d/nvidia_production_icd.i686.json /var/run/configs/nvidia_icd.i686.json
	ln -sf /var/run/configs/nvidia_icd.i686.json /usr/share/vulkan/icd.d/nvidia_icd.i686.json
	# finally copy kernel modules & run them
	cp -fp /lib/modules/$LINUX_VER/extra/nvidia-production.ko /lib/modules/$LINUX_VER/extra/nvidia.ko
	cp -fp /lib/modules/$LINUX_VER/extra/nvidia-modeset-production.ko /lib/modules/$LINUX_VER/extra/nvidia-modeset.ko
	cp -fp /lib/modules/$LINUX_VER/extra/nvidia-drm-production.ko /lib/modules/$LINUX_VER/extra/nvidia-drm.ko
	cp -fp /lib/modules/$LINUX_VER/extra/nvidia-uvm-production.ko /lib/modules/$LINUX_VER/extra/nvidia-uvm.ko	
	for m in nvidia nvidia_modeset nvidia_uvm nvidia_drm ; do modprobe $m ; done
elif [[ "$1" == *"legacy"* ]]
then
    if [[ "$1" == *"340"* ]]
	then
	    BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION=$BATOCERA_NVIDIA340_LEGACY_DRIVER_VERSION
	elif [[ "$1" == *"390"* ]]
	then
	    BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION=$BATOCERA_NVIDIA390_LEGACY_DRIVER_VERSION
	fi
    echo "Using NVIDIA Legacy driver version - ${BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION}"
	echo
	echo "blacklist nouveau" > /etc/modprobe.d/blacklist-nouveau.conf
	echo "options nvidia-drm modeset=1" > /etc/modprobe.d/nvidia-drm.conf
	# symbolic link 64-bit library files
	mkdir -p /var/run/lib
	# libGLX_nvidia.so
	ln -sf /usr/lib/libGLX_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libGLX_nvidia.so
	ln -sf /var/run/lib/libGLX_nvidia.so /usr/lib/libGLX_nvidia.so
	ln -sf /usr/lib/libGLX_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libGLX_nvidia.so.0
	ln -sf /var/run/lib/libGLX_nvidia.so.0 /usr/lib/libGLX_nvidia.so.0
	# libEGL_nvidia.so
	ln -sf /usr/lib/libEGL_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libEGL_nvidia.so
	ln -sf /var/run/lib/libEGL_nvidia.so /usr/lib/libEGL_nvidia.so
	ln -sf /usr/lib/libEGL_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libEGL_nvidia.so.0
	ln -sf /var/run/lib/libEGL_nvidia.so.0 /usr/lib/libEGL_nvidia.so.0
	# libGLESv1_CM_nvidia.so
	ln -sf /usr/lib/libGLESv1_CM_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libGLESv1_CM_nvidia.so
	ln -sf /var/run/lib/libGLESv1_CM_nvidia.so /usr/lib/libGLESv1_CM_nvidia.so
	ln -sf /usr/lib/libGLESv1_CM_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libGLESv1_CM_nvidia.so.1
	ln -sf /var/run/lib/libGLESv1_CM_nvidia.so.1 /usr/lib/libGLESv1_CM_nvidia.so.1
	# libGLESv2_nvidia.so
	ln -sf /usr/lib/libGLESv2_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libGLESv2_nvidia.so
	ln -sf /var/run/lib/libGLESv2_nvidia.so /usr/lib/libGLESv2_nvidia.so
	ln -sf /usr/lib/libGLESv2_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libGLESv2_nvidia.so.2
	ln -sf /var/run/lib/libGLESv2_nvidia.so.2 /usr/lib/libGLESv2_nvidia.so.2
	# libnvidia-eglcore.so
	ln -sf /usr/lib/libnvidia-eglcore.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libnvidia-eglcore.so
	ln -sf /var/run/lib/libnvidia-eglcore.so /usr/lib/libnvidia-eglcore.so
	# libnvidia-glcore.so
	ln -sf /usr/lib/libnvidia-glcore.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libnvidia-glcore.so
	ln -sf /var/run/lib/libnvidia-glcore.so /usr/lib/libnvidia-glcore.so
	# libnvidia-glsi.so
	ln -sf /usr/lib/libnvidia-glsi.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libnvidia-glsi.so
	ln -sf /var/run/lib/libnvidia-glsi.so /usr/lib/libnvidia-glsi.so
	# libnvidia-tls.so
	ln -sf /usr/lib/libnvidia-tls.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libnvidia-tls.so
	ln -sf /var/run/lib/libnvidia-tls.so /usr/lib/libnvidia-tls.so
	# libvdpau_nvidia.so
	ln -sf /usr/lib/libvdpau_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libvdpau_nvidia.so
	ln -sf /var/run/lib/libvdpau_nvidia.so /usr/lib/libvdpau_nvidia.so
	ln -sf /usr/lib/libvdpau_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libvdpau_nvidia.so.1
	ln -sf /var/run/lib/libvdpau_nvidia.so.1 /usr/lib/libvdpau_nvidia.so.1
	# libnvidia-ml.so
	ln -sf /usr/lib/libnvidia-ml.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libnvidia-ml.so
	ln -sf /var/run/lib/libnvidia-ml.so /usr/lib/libnvidia-ml.so
	ln -sf /usr/lib/libnvidia-ml.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libnvidia-ml.so.1
	ln -sf /var/run/lib/libnvidia-ml.so.1 /usr/lib/libnvidia-ml.so.1
	# libnvidia-glvkspirv.so
	ln -sf /usr/lib/libnvidia-glvkspirv.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libnvidia-glvkspirv.so
	ln -sf /var/run/lib/libnvidia-glvkspirv.so /usr/lib/libnvidia-glvkspirv.so
	# [symbolic link 32-bit library files]
	mkdir -p /var/run/lib32
	# libGLX_nvidia.so
	ln -sf /lib32/libGLX_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib32/libGLX_nvidia.so
	ln -sf /var/run/lib32/libGLX_nvidia.so /lib32/libGLX_nvidia.so
	ln -sf /lib32/libGLX_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib32/libGLX_nvidia.so.0
	ln -sf /var/run/lib32/libGLX_nvidia.so.0 /lib32/libGLX_nvidia.so.0
	# libEGL_nvidia.so
	ln -sf /lib32/libEGL_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib32/libEGL_nvidia.so
	ln -sf /var/run/lib32/libEGL_nvidia.so /lib32/libEGL_nvidia.so
	ln -sf /lib32/libEGL_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib32/libEGL_nvidia.so.0
	ln -sf /var/run/lib32/libEGL_nvidia.so.0 /lib32/libEGL_nvidia.so.0
	# libGLESv1_CM_nvidia.so
	ln -sf /lib32/libGLESv1_CM_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib32/libGLESv1_CM_nvidia.so
	ln -sf /var/run/lib32/libGLESv1_CM_nvidia.so /lib32/libGLESv1_CM_nvidia.so
	ln -sf /lib32/libGLESv1_CM_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib32/libGLESv1_CM_nvidia.so.1
	ln -sf /var/run/lib32/libGLESv1_CM_nvidia.so.1 /lib32/libGLESv1_CM_nvidia.so.1
	# libGLESv2_nvidia.so
	ln -sf /lib32/libGLESv2_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib32/libGLESv2_nvidia.so
	ln -sf /var/run/lib32/libGLESv2_nvidia.so /lib32/libGLESv2_nvidia.so
	ln -sf /lib32/libGLESv2_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib32/libGLESv2_nvidia.so.2
	ln -sf /var/run/lib32/libGLESv2_nvidia.so.2 /lib32/libGLESv2_nvidia.so.2
	# libnvidia-eglcore.so
	ln -sf /lib32/libnvidia-eglcore.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib32/libnvidia-eglcore.so
	ln -sf /var/run/lib32/libnvidia-eglcore.so /lib32/libnvidia-eglcore.so
	# libnvidia-glcore.so
	ln -sf /lib32/libnvidia-glcore.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib32/libnvidia-glcore.so
	ln -sf /var/run/lib32/libnvidia-glcore.so /lib32/libnvidia-glcore.so
	# libnvidia-glsi.so
	ln -sf /lib32/libnvidia-glsi.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib32/libnvidia-glsi.so
	ln -sf /var/run/lib32/libnvidia-glsi.so /lib32/libnvidia-glsi.so
	# libnvidia-tls.so
	ln -sf /lib32/libnvidia-tls.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib32/libnvidia-tls.so
	ln -sf /var/run/lib32/libnvidia-tls.so /lib32/libnvidia-tls.so
	# libvdpau_nvidia.so
	ln -sf /lib32/libvdpau_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib32/libvdpau_nvidia.so
	ln -sf /var/run/lib32/libvdpau_nvidia.so /lib32/libvdpau_nvidia.so
	ln -sf /lib32/libvdpau_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib32/libvdpau_nvidia.so.1
	ln -sf /var/run/lib32/libvdpau_nvidia.so.1 /lib32/libvdpau_nvidia.so.1
	# libnvidia-ml.so
	ln -sf /lib32/libnvidia-ml.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib32/libnvidia-ml.so
	ln -sf /var/run/lib32/libnvidia-ml.so /lib32/libnvidia-ml.so
	ln -sf /lib32/libnvidia-ml.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib32/libnvidia-ml.so.1
	ln -sf /var/run/lib32/libnvidia-ml.so.1 /lib32/libnvidia-ml.so.1
	# libnvidia-glvkspirv.so
	ln -sf /lib32/libnvidia-glvkspirv.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib32/libnvidia-glvkspirv.so
	ln -sf /var/run/lib32/libnvidia-glvkspirv.so /lib32/libnvidia-glvkspirv.so
	# sym link Xorg libraries too
	ln -sf /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libglxserver_nvidia.so
	ln -sf /var/run/lib/libglxserver_nvidia.so /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so
	ln -sf /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/lib/libglxserver_nvidia.so.1
	ln -sf /var/run/lib/libglxserver_nvidia.so.1 /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so.1
	# [variations per legacy version]
	# 340 version
	if [[ "$1" == *"340"* ]]
	then
	    # link Xorg driver
		ln -sf /usr/lib/xorg/modules/drivers/nvidia340_legacy_drv.so /var/run/lib/nvidia_drv.so
		ln -sf /var/run/lib/nvidia_drv.so /usr/lib/xorg/modules/drivers/nvidia_drv.so
		ln -sf /usr/lib/xorg/modules/extensions/libglx.so.$BATOCERA_NVIDIA340_LEGACY_DRIVER_VERSION /usr/lib/xorg/modules/extensions/libglx.so
		# link GL config files
		mkdir -p /var/run/configs
		ln -sf /usr/share/vulkan/implicit_layer.d/nvidia340_legacy_layers.json /var/run/configs/nvidia_layers.json
		ln -sf /var/run/configs/nvidia_layers.json /usr/share/vulkan/implicit_layer.d/nvidia_layers.json
		ln -sf /usr/share/glvnd/egl_vendor.d/10_nvidia340_legacy.json /var/run/configs/10_nvidia.json
		ln -sf /var/run/configs/10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json
		ln -sf /usr/share/X11/xorg.conf.d/10-nvidia340-legacy-drm-outputclass.conf /var/run/configs/10-nvidia-drm-outputclass.conf
		ln -sf /var/run/configs/10-nvidia-drm-outputclass.conf /usr/share/X11/xorg.conf.d/10-nvidia-drm-outputclass.conf
		# link Vulkan icd files
		ln -sf /usr/share/vulkan/icd.d/nvidia340_legacy_icd.x86_64.json /var/run/configs/nvidia_icd.x86_64.json
		ln -sf /var/run/configs/nvidia_icd.x86_64.json /usr/share/vulkan/icd.d/nvidia_icd.x86_64.json
		ln -sf /usr/share/vulkan/icd.d/nvidia340_legacy_icd.i686.json /var/run/configs/nvidia_icd.i686.json
		ln -sf /var/run/configs/nvidia_icd.i686.json /usr/share/vulkan/icd.d/nvidia_icd.i686.json
		# finally copy kernel modules & run them
		cp -fp /lib/modules/$LINUX_VER/extra/nvidia340-legacy.ko /lib/modules/$LINUX_VER/extra/nvidia.ko
		cp -fp /lib/modules/$LINUX_VER/extra/nvidia340-modeset-legacy.ko /lib/modules/$LINUX_VER/extra/nvidia-modeset.ko
		cp -fp /lib/modules/$LINUX_VER/extra/nvidia340-drm-legacy.ko /lib/modules/$LINUX_VER/extra/nvidia-drm.ko
		cp -fp /lib/modules/$LINUX_VER/extra/nvidia340-uvm-legacy.ko /lib/modules/$LINUX_VER/extra/nvidia-uvm.ko
	# 390 version
	elif [[ "$1" == *"390"* ]]
	then
	    # link Xorg driver
		ln -sf /usr/lib/xorg/modules/drivers/nvidia390_legacy_drv.so /var/run/lib/nvidia_drv.so
		ln -sf /var/run/lib/nvidia_drv.so /usr/lib/xorg/modules/drivers/nvidia_drv.so
		ln -sf /usr/lib/xorg/modules/extensions/libglx.so.$BATOCERA_NVIDIA390_LEGACY_DRIVER_VERSION /usr/lib/xorg/modules/extensions/libglx.so
		# link GL config files
		mkdir -p /var/run/configs
		ln -sf /usr/share/vulkan/implicit_layer.d/nvidia390_legacy_layers.json /var/run/configs/nvidia_layers.json
		ln -sf /var/run/configs/nvidia_layers.json /usr/share/vulkan/implicit_layer.d/nvidia_layers.json
		ln -sf /usr/share/glvnd/egl_vendor.d/10_nvidia390_legacy.json /var/run/configs/10_nvidia.json
		ln -sf /var/run/configs/10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json
		ln -sf /usr/share/X11/xorg.conf.d/10-nvidia390-legacy-drm-outputclass.conf /var/run/configs/10-nvidia-drm-outputclass.conf
		ln -sf /var/run/configs/10-nvidia-drm-outputclass.conf /usr/share/X11/xorg.conf.d/10-nvidia-drm-outputclass.conf
		# link Vulkan icd files
		ln -sf /usr/share/vulkan/icd.d/nvidia390_legacy_icd.x86_64.json /var/run/configs/nvidia_icd.x86_64.json
		ln -sf /var/run/configs/nvidia_icd.x86_64.json /usr/share/vulkan/icd.d/nvidia_icd.x86_64.json
		ln -sf /usr/share/vulkan/icd.d/nvidia390_legacy_icd.i686.json /var/run/configs/nvidia_icd.i686.json
		ln -sf /var/run/configs/nvidia_icd.i686.json /usr/share/vulkan/icd.d/nvidia_icd.i686.json
		# finally copy kernel modules & run them
		cp -fp /lib/modules/$LINUX_VER/extra/nvidia390-legacy.ko /lib/modules/$LINUX_VER/extra/nvidia.ko
		cp -fp /lib/modules/$LINUX_VER/extra/nvidia390-modeset-legacy.ko /lib/modules/$LINUX_VER/extra/nvidia-modeset.ko
		cp -fp /lib/modules/$LINUX_VER/extra/nvidia390-drm-legacy.ko /lib/modules/$LINUX_VER/extra/nvidia-drm.ko
		cp -fp /lib/modules/$LINUX_VER/extra/nvidia390-uvm-legacy.ko /lib/modules/$LINUX_VER/extra/nvidia-uvm.ko
	# 470 version
	else
	    # link Xorg driver
		ln -sf /usr/lib/xorg/modules/drivers/nvidia_legacy_drv.so /var/run/lib/nvidia_drv.so
		ln -sf /var/run/lib/nvidia_drv.so /usr/lib/xorg/modules/drivers/nvidia_drv.so
		# link GL config files
		mkdir -p /var/run/configs
		ln -sf /usr/share/vulkan/implicit_layer.d/nvidia_legacy_layers.json /var/run/configs/nvidia_layers.json
		ln -sf /var/run/configs/nvidia_layers.json /usr/share/vulkan/implicit_layer.d/nvidia_layers.json
		ln -sf /usr/share/glvnd/egl_vendor.d/10_nvidia_legacy.json /var/run/configs/10_nvidia.json
		ln -sf /var/run/configs/10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json
		ln -sf /usr/share/X11/xorg.conf.d/10-nvidia-legacy-drm-outputclass.conf /var/run/configs/10-nvidia-drm-outputclass.conf
		ln -sf /var/run/configs/10-nvidia-drm-outputclass.conf /usr/share/X11/xorg.conf.d/10-nvidia-drm-outputclass.conf
		# link Vulkan icd files
		ln -sf /usr/share/vulkan/icd.d/nvidia_legacy_icd.x86_64.json /var/run/configs/nvidia_icd.x86_64.json
		ln -sf /var/run/configs/nvidia_icd.x86_64.json /usr/share/vulkan/icd.d/nvidia_icd.x86_64.json
		ln -sf /usr/share/vulkan/icd.d/nvidia_legacy_icd.i686.json /var/run/configs/nvidia_icd.i686.json
		ln -sf /var/run/configs/nvidia_icd.i686.json /usr/share/vulkan/icd.d/nvidia_icd.i686.json
		# finally copy kernel modules & run them
		cp -fp /lib/modules/$LINUX_VER/extra/nvidia-legacy.ko /lib/modules/$LINUX_VER/extra/nvidia.ko
		cp -fp /lib/modules/$LINUX_VER/extra/nvidia-modeset-legacy.ko /lib/modules/$LINUX_VER/extra/nvidia-modeset.ko
		cp -fp /lib/modules/$LINUX_VER/extra/nvidia-drm-legacy.ko /lib/modules/$LINUX_VER/extra/nvidia-drm.ko
		cp -fp /lib/modules/$LINUX_VER/extra/nvidia-uvm-legacy.ko /lib/modules/$LINUX_VER/extra/nvidia-uvm.ko
	fi
	for m in nvidia nvidia_modeset nvidia_uvm nvidia_drm ; do modprobe $m ; done
fi