#!/bin/bash

ACTION=$1

case "${ACTION}" in
    "unlock-volume")
     	# on my pc, the master is turned off at boot
	# i don't know what are the rules to set here.
	amixer set Master unmute || exit 1
	;;

    "list")
	echo "hdmi"
	echo "jack"
	echo "auto"
	;;

    "get")
	batocera-settings -command load -key audio.device
	;;

    "set")
	MODE=$1
	# this is specific to the rpi
	cmdVal="0"
	if [ "${MODE}" == "hdmi" ];then
	    cmdVal="2"
	elif [ "${MODE}" == "jack" ];then
	    cmdVal="1"
	fi
        echo "setting audio output mode : ${MODE}" >> $log
	amixer cset numid=3 $cmdVal || exit 1
	;;
esac
