#!/bin/bash

# Bash script to get the latest Nvidia driver lists
# which may add new boards in between versions.

GITHUB_URL="https://raw.githubusercontent.com/batocera-linux/nvidia-lists/main/"
DEST_DIR="/userdata/system/.nvidia"
LOG_DIR="/userdata/system/logs"
LOG_FILE="$LOG_DIR/nvidia.log"

# Create directories if they do not exist
mkdir -p "$DEST_DIR"
mkdir -p "$LOG_DIR"

# Function to check internet connectivity using multiple methods
check_internet() {
    if ping -q -w 1 -c 1 github.com > /dev/null || 
       curl -s --max-time 2 -I http://github.com | grep -q "HTTP/[12].[01] [23].." ||
       wget -q --spider http://github.com; then
        return 0
    else
        return 1
    fi
}

# Function to download a file
download_file() {
    local filename=$1
    wget -q --tries=5 --timeout=1 --no-check-certificate --no-cache --no-cookies -O "$DEST_DIR/$filename" "${GITHUB_URL}$filename" &&
    echo "Download of $filename successful. File saved to $DEST_DIR/$filename" >> "$LOG_FILE"
}

# Check for an internet connection
if check_internet; then
    echo "Internet connection detected, downloading Nvidia driver lists..." >> "$LOG_FILE"
    
    # Download lists in parallel
    download_file "production.list" &
    download_file "legacy390.list" &
    download_file "legacy340.list" &
    download_file "legacy.list" &
    wait
else
    echo "No internet connection detected, could not download Nvidia driver lists." >> "$LOG_FILE"
fi
