#!/bin/bash

ACTION=$1

case "${ACTION}" in
    "unlock-volume")
	;;

    "list")
	echo "auto"
	echo "speakers"
	echo "headphone"
	;;

    "get")
	batocera-settings -command load -key audio.device
	;;

    "set")
	MODE=$1
	case "${MODE}" in
	    "auto"|"speakers")
		amixer cset name='Playback Path' SPK
		;;
	    "headphone")
		amixer cset name='Playback Path' HP
		;;
	esac
	;;
esac
