#!/bin/sh
# LED Rainbow effect when retroachievement unlocked
#
# To enable it, SSH into Batocera and type the 3 commands:
#   mkdir -p /userdata/system/configs/emulationstation/scripts/achievements/
#   echo "/usr/bin/batocera-led-effects" > /userdata/system/configs/emulationstation/scripts/achievements/leds.sh
#   chmod +x /userdata/system/configs/emulationstation/scripts/achievements/leds.sh
# 

# Function to check if led module is loaded
is_module_loaded() {
    lsmod | grep -q "^$1 "
}

# Functions to set the LED mode parameters
# ayn-platform
set_ayn_led_effect() {
    # turn off rainbow effect if enabled
    echo 1 | tee /sys/class/leds/multicolor:chassis/device/led_mode
    current_color="$(cat /sys/class/leds/multicolor:chassis/multi_intensity)"
    for i in $(seq 1 26); do 
	    r=$(($i * 10))
	    g=$(($i * 10))
	    b=$(($i * 10))
	    echo "$r $b $g" | tee /sys/class/leds/multicolor:chassis/multi_intensity
    done
    for i in $(seq 1 26); do 
	    r=$(($i * 4 + 125))
	    g=0
		b=0
	    echo "$r $g $b" | tee /sys/class/leds/multicolor:chassis/multi_intensity
    done
    for i in $(seq 1 26); do 
	    r=0
	    g=$(($i * 4 + 125))
	    b=0
	    echo "$r $g $b" | tee /sys/class/leds/multicolor:chassis/multi_intensity
    done
    for i in $(seq 1 26); do 
	    r=0
	    g=0
		b=$(($i * 4 + 125))
	    echo "$r $g $b" | tee /sys/class/leds/multicolor:chassis/multi_intensity
    done
    for i in $(seq 1 25); do 
	    r=$((250 - $i * 10))
	    g=$((250 - $i * 10))
	    b=$((250 - $i * 10))
	    echo "$r $g $b" | tee /sys/class/leds/multicolor:chassis/multi_intensity
    done
    echo "$current_color" | tee /sys/class/leds/multicolor:chassis/multi_intensity
    
}

# Currently only Ayn Loki Zero but can be extended in the future to other devices
if is_module_loaded ayn_platform; then
	set_ayn_led_effect
fi

exit 0
