#!/bin/sh


GTMP="/tmp"
DHOME="/userdata/system"

# to be callable by any external tool
if test $# -eq 1
then
    REPORTNAME=$(basename "$1" | sed -e s+'^\([^.]*\)\..*$'+'\1'+)
    OUTPUTFILE=$1
else
    REPORTNAME="batocera-support-"$(date +%Y%m%d%H%M%S)
    OUTPUTFILE="/userdata/saves/${REPORTNAME}.tar.gz"
fi

TMPDIR="${GTMP}/${REPORTNAME}"

f_cp() {
    test -e "$1" && cp "$1" "$2"
}

d_cp() {
    test -d "$1" && cp -pr "$1" "$2"
}


if mkdir "${TMPDIR}" && mkdir "${TMPDIR}/system" "${TMPDIR}/joysticks" "${TMPDIR}/lirc" "${TMPDIR}/kodi" "${TMPDIR}/coredumps"
then
    if ! cd "${TMPDIR}"
    then
	echo "Change directory failed" >&2
	exit 1
    fi
else
    echo "Reporting directory creation failed" >&2
    exit 1
fi

# in case xorg is in use
export DISPLAY=:0.0

# SYSTEM
DSYSTEM="${TMPDIR}/system"
dmesg 	         	> "${DSYSTEM}/dmesg.txt"
lsmod 	         	> "${DSYSTEM}/lsmod.txt"
ps    	         	> "${DSYSTEM}/ps.txt"
df -h 	         	> "${DSYSTEM}/df.txt"
netstat -tuan    	> "${DSYSTEM}/netstat.txt"
lsusb -v         	> "${DSYSTEM}/lsusb.txt" 2>/dev/null
which tvservice >/dev/null && tvservice -m CEA 	> "${DSYSTEM}/tvservice-CEA.txt"
which tvservice >/dev/null && tvservice -m DMT 	> "${DSYSTEM}/tvservice-DMT.txt"
ifconfig -a             > "${DSYSTEM}/ifconfig.txt"
lspci                   > "${DSYSTEM}/lspci.txt"
amixer                  > "${DSYSTEM}/amixer.txt"
aplay -l                > "${DSYSTEM}/aplay-l.txt"
which glxinfo >/dev/null && glxinfo    > "${DSYSTEM}/glxinfo.txt"
which xrandr  >/dev/null && xrandr     > "${DSYSTEM}/xrandr.txt"
blkid                   > "${DSYSTEM}/disks.txt"
connmanctl technologies > "${DSYSTEM}/connman-technologies.txt"
connmanctl services     > "${DSYSTEM}/connman-services.txt"
batocera-systems        > "${DSYSTEM}/bios.txt"
f_cp /usr/share/batocera/batocera.version                     "${DSYSTEM}"
f_cp /usr/share/batocera/batocera.arch                        "${DSYSTEM}"
f_cp /boot/config.txt                                         "${DSYSTEM}"
grep -vE '^[ #]*global.retroachievements.password[ ]*=' /userdata/system/batocera.conf > "${DSYSTEM}/batocera.conf"
d_cp /userdata/system/logs                              "${DSYSTEM}"
f_cp /var/log/messages                                        "${DSYSTEM}"
f_cp /userdata/system/configs/emulationstation/es_settings.cfg "${DSYSTEM}"
f_cp /userdata/system/configs/emulationstation/es_log.txt      "${DSYSTEM}"
f_cp /userdata/system/configs/emulationstation/es_input.cfg    "${DSYSTEM}"
f_cp /userdata/system/logs/es_launch_stdout.log         "${DSYSTEM}"
f_cp /userdata/system/logs/es_launch_stderr.log         "${DSYSTEM}"
f_cp /boot/batocera-boot.conf                                 "${DSYSTEM}"
f_cp /var/log/Xorg.0.log                                      "${DSYSTEM}"

# Emulators configs
d_cp /userdata/system/configs                           "${TMPDIR}/configs"

# joysticks
DJOYS="${TMPDIR}/joysticks"
find /dev/input > "${DJOYS}/inputs.txt"
for J in /dev/input/event*
do
    N=$(basename ${J})
    evtest --info "${J}"          > "${DJOYS}/evtest.${N}.txt"
    udevadm info -q all -n "${J}" > "${DJOYS}/udevadm.${N}.txt"
done
sdl2-jstest -l > "${DJOYS}/sdl2-jstest.txt"

# lirc
DLIRC="${TMPDIR}/lirc"
f_cp "${DHOME}/.config/lirc/lircd.conf" "${DLIRC}"

# kodi
DKODI="${TMPDIR}/kodi"
f_cp "${DHOME}/.kodi/userdata/Lircmap.xml"          	      "${DKODI}"
d_cp "${DHOME}/.kodi/userdata/addon_data/peripheral.joystick" "${DKODI}"
d_cp "${DHOME}/.kodi/userdata/remotes"              	      "${DKODI}"
f_cp "${DHOME}/.kodi/temp/kodi.log"                 	      "${DKODI}"

# core dumps
DCORE="${TMPDIR}/coredumps"
for C in /userdata/system/logs/core.*
do
    f_cp "${C}" "${DCORE}"
done

if ! (cd "${GTMP}" && tar cf -  "${REPORTNAME}" | gzip -c > "${OUTPUTFILE}")
then
    echo "Reporting zip creation failed" >&2
    exit 1
fi

rm -rf "${TMPDIR}"
echo "${OUTPUTFILE}"
exit 0
