#!/bin/bash

# Detect battery
BATT=$(cat /sys/class/power_supply/{BAT,bat}*/uevent 2>/dev/null | grep -E "^POWER_SUPPLY_CAPACITY=" | sed -e s+'^POWER_SUPPLY_CAPACITY='++ | sort -rn | head -1)
if ! test -n "${BATT}"
then
    NOW=$(cat /sys/class/power_supply/{FUEL,fuel}*/uevent 2>/dev/null | grep -E "^POWER_SUPPLY_CHARGE_NOW=" | sed -e s+'^POWER_SUPPLY_CHARGE_NOW='++ | sort -rn | head -1)
    MAX=$(cat /sys/class/power_supply/{FUEL,fuel}*/uevent 2>/dev/null | grep -E "^POWER_SUPPLY_CHARGE_FULL=" | sed -e s+'^POWER_SUPPLY_CHARGE_FULL='++ | sort -rn | head -1)
    if [ ! -z "$NOW" ] && [ ! -z "$MAX" ] && [ "$MAX" != 0 ]
    then
        BATT=$((200*$NOW/$MAX % 2 + 100*$NOW/$MAX))
    fi
fi

### short version (for osd)
if test "$1" = "--short"
then
    DT=$(date +%H:%M)
    if test -n "${BATT}"
    then
        echo "Battery: ${BATT}% - ${DT}"
    else
        echo "${DT}"
    fi
    exit 0
fi
###
### full version (not on login, otherwise you can't log when OpenGL/Vulkan are out of order)
if test "$1" = "--full"
then
	FULL_DISPLAY=1
else
	FULL_DISPLAY=0
fi
###

getCpu() {
    test -e "${1}/cpufreq/scaling_max_freq" || return 0

    if test -e "${1}/online"
    then
	OL=$(cat "${CPU}/online")
	test "${OL}" = 1 || return 0
    fi
    cat "${CPU}/cpufreq/scaling_max_freq"
}

V_BOARD=$(cat /boot/boot/batocera.board)
V_CPUNB=$(grep -E $'^processor\t:' /proc/cpuinfo | wc -l)
V_CPUMAXNB=$(ls /sys/devices/system/cpu | grep -E '^cpu[0-9]*$' | wc -l)
V_CPUMODEL1=$(grep -E $'^model name\t:' /proc/cpuinfo | head -1 | sed -e s+'^model name\t: '++)
V_SYSTEM=$(uname -rs)
# min freq : minimum freq among the max cpus ; consider only online cpus
V_CPUMINFREQ=$(for CPU in /sys/devices/system/cpu/cpu*; do getCpu "${CPU}"; done | sort -n  | head -1)
V_CPUMAXFREQ=$(for CPU in /sys/devices/system/cpu/cpu*; do getCpu "${CPU}"; done | sort -rn | head -1)
let V_CPUMINFREQ=${V_CPUMINFREQ}/1000
let V_CPUMAXFREQ=${V_CPUMAXFREQ}/1000

# userdata type
INTERNALDEVICE=$(batocera-part "share")
INTERNALDEVICETYPE=$(blkid "${INTERNALDEVICE}" | sed -e s+'^.* TYPE="\([^"]*\)\".*'+'\1'+)
echo "Disk format: ${INTERNALDEVICETYPE}"


# battery
if test -n "${BATT}"
then
    echo "Battery: ${BATT}%"
fi

# PAD Battery
for PADBAT in /sys/class/power_supply/*/device/uevent
do
    if test -e "${PADBAT}" # when nothing is found, the expression is return
    then
	# HID devices only
	PADNAME=$(grep -E '^HID_NAME=' "${PADBAT}" | sed -e s+'^HID_NAME='++)
	if test -n "${PADNAME}"
	then
	    # parent of parent / uevent
	    BATTUEVENT=$(dirname "${PADBAT}")
	    BATTUEVENT=$(dirname "${BATTUEVENT}")/uevent
	    BATT=$(grep -E "^POWER_SUPPLY_CAPACITY=" "${BATTUEVENT}" | sed -e s+'^POWER_SUPPLY_CAPACITY='++ | sort -rn | head -1)
	    echo "${PADNAME}: ${BATT}%"
	fi
    fi
done

# temperature
# Unit: millidegree Celsius
TEMPE=$(cat /sys/devices/virtual/thermal/thermal_zone*/temp 2>/dev/null | sort -rn | head -1 | sed -e s+"[0-9][0-9][0-9]$"++)
if test -n "${TEMPE}"
then
    echo "Temperature: ${TEMPE}°C"
fi

echo "Architecture: ${V_BOARD}"
V_BOARD_MODEL=$(cat /sys/firmware/devicetree/base/model 2>/dev/null | tr -d '\0' | sed -e s+"[^A-Za-z0-9]"+"_"+g)
if test -z "${V_BOARD_MODEL}"
then
    # give an other chance with dmi
    V_BOARD_MODEL=$(cat /sys/devices/virtual/dmi/id/board_name 2>/dev/null | tr -d '\0' | sed -e s+"[^A-Za-z0-9]"+"_"+g)
fi
if test -n "${V_BOARD_MODEL}"
then
    echo "Model: ${V_BOARD_MODEL}"
fi

if echo "${V_BOARD}" | grep -qE "^rpi[0-9]$"
then
    REVISION=$(grep -E $'^Revision\t:' /proc/cpuinfo | head -1 | sed -e s+'^Revision\t: '++)
    test -n "${REVISION}" && echo "Revision: ${REVISION}"
fi
echo "System: ${V_SYSTEM}"

MEM_TOTAL_KB=$(head /proc/meminfo | grep -E "^MemTotal:" | sed -e s+"^MemTotal:[ ]*\([0-9]*\) kB$"+"\\1"+)
MEM_AVAILABLE_KB=$(head /proc/meminfo | grep -E "^MemAvailable:" | sed -e s+"^MemAvailable:[ ]*\([0-9]*\) kB$"+"\\1"+)
MEM_TOTAL_MB=$(expr "${MEM_TOTAL_KB}" / 1024)
MEM_AVAILABLE_MB=$(expr "${MEM_AVAILABLE_KB}" / 1024)
echo "Available memory: ${MEM_AVAILABLE_MB}/${MEM_TOTAL_MB} MB"

if [[ "${FULL_DISPLAY}" != 0 ]]; then
	# OPENGL
	if test "${V_BOARD}" = "x86" -o "${V_BOARD}" = "x86_64"
	then
	    V_OPENGLVERSION=$(DISPLAY=:0.0 glxinfo 2>/dev/null | grep -E '^OpenGL core profile version string:' | sed -e s+'^OpenGL core profile version string:[ ]*'++)
	    if test -z "${V_OPENGLVERSION}"
	    then
		V_OPENGLVERSION=$(DISPLAY=:0.0 glxinfo 2>/dev/null | grep -E '^OpenGL version string:' | sed -e s+'^OpenGL version string:[ ]*'++)
	    fi
	    echo "OpenGL: ${V_OPENGLVERSION}"
	fi

	# VULKAN
	if test -e /var/run/vulkaninfo.version
	then
	    APIVERSION=$(cat /var/run/vulkaninfo.version)
	    if test -n "${APIVERSION}"
	    then
		let "APIVERSION_MAJOR=${APIVERSION} >> 22"
		let "APIVERSION_MINOR=(${APIVERSION} >> 12) & 0x3ff"
		let "APIVERSION_PATCH=${APIVERSION} & 0xfff"
		echo "Vulkan: ${APIVERSION_MAJOR}.${APIVERSION_MINOR}.${APIVERSION_PATCH}"
	    else
		echo "Vulkan: none"
	    fi
	fi
fi

[[ -z ${V_CPUMODEL1} ]] || echo "Cpu model: ${V_CPUMODEL1}"

if test "${V_CPUMAXNB}" = "${V_CPUNB}"
then
    echo "Cpu number: ${V_CPUNB}"
else
        echo "Cpu number: ${V_CPUNB}/${V_CPUMAXNB}"
fi
if test "${V_CPUMINFREQ}" != "${V_CPUMAXFREQ}"
then
    echo "Cpu frequency: ${V_CPUMINFREQ}/${V_CPUMAXFREQ} MHz"
else
    echo "Cpu max frequency: ${V_CPUMAXFREQ} MHz"
fi
if grep -q " avx2" /proc/cpuinfo
then
    echo "Cpu feature: avx2"
fi
