#!/bin/bash

systemsetting="batocera-settings"
WAITMODE="`$systemsetting  -command load -key kodi.network.waitmode`"

# if the mode is required or wish,
# kodi waits for the network before starting
# in fact, it waits that an ip is available (such as a db service for example)
if test "${WAITMODE}" = "required" -o "${WAITMODE}" = "wish"
then
    WAITTIME="`$systemsetting  -command load -key kodi.network.waittime`"
    WAITHOST="`$systemsetting  -command load -key kodi.network.waithost`"

    DOCONT=1
    NWAITED=0
    while test "${DOCONT}" = 1
    do
	if ping -c 1 "${WAITHOST}" -W 3
	then
	    DOCONT=0
	else
	    sleep 1 # wait, in case the host is not correct
	    let NWAITED=$NWAITED+4
	    if test "${NWAITED}" -gt "${WAITTIME}"
	    then
		DOCONT=0
		if test "${WAITMODE}" = "required"
		then
		    exit 1
		fi
	    fi
	fi
    done
fi

# recreate a fifo to get kodi events and be sure it's empty
rm -f /var/run/kodi.msg
if ! mkfifo /var/run/kodi.msg
then
    exit 1 # code for error
fi

(
    LD_LIBRARY_PATH="/usr/lib/mysql" /usr/lib/kodi/kodi.bin --standalone -fs -l /var/run/lirc/lircd 
    echo "Kodi process ended." >&2
    echo "EXIT" >> /var/run/kodi.msg # in case of normal, but mainly anormal end of kodi, send a message to signal the end
)&

kodiLastChance() {
    sleep 3 # kodi, please take less than X seconds to quit
    if ps -o comm | grep -qE '^kodi.bin$'
    then
	sleep 2 # let some other seconds to kodi to quit
	killall -9 kodi.bin
    fi
}

while read EVENT
do
    echo "Kodi event : ${EVENT}" >&2
    case "$EVENT" in
	"EXIT")
	    kodiLastChance
	    wait
	    exit 0 # code for success
	    ;;
	"RESTART")
	    kodiLastChance
	    wait
	    exit 10 # code to reboot
	    ;;
	"SHUTDOWN")
	    kodiLastChance
	    wait
	    exit 11 # code to shutdown
	    ;;
    esac
done < /var/run/kodi.msg

rm -f /var/run/kodi.msg
echo "Kodi launcher ended without event." >&2
exit 1
### end ###
