#!/bin/sh

D=$(find /sys/class/backlight/* 2>/dev/null | grep backlight | head -n1)

if test ! -e "${D}"/brightness
then
    echo "no brightness found" >&2
    exit 1
else
    B="${D}"/brightness
fi

setValue() {
    NEWVAL=$1
    XMAX=$2

    test "${NEWVAL}" -lt 0         && NEWVAL=0
    test "${NEWVAL}" -gt "${XMAX}" && NEWVAL="${XMAX}"
    
    echo "${NEWVAL}" > "${B}"
}

# get
if test $# = 0
then
    X=$(cat "${B}")
    XMAX=$(cat "${D}"/max_brightness)
    FVALUE=$(echo "scale=3;${X}" "*" "100" / "${XMAX}" | bc)
    LC_ALL=C printf '%.*f\n' 0 "${FVALUE}" # round
    exit 0
fi

# set
if test $# = 1
then
    XMAX=$(cat "${D}"/max_brightness)
    NEWVAL=$(expr "${1}" "*" "${XMAX}" / 100)
    setValue "${NEWVAL}" "${XMAX}"
    exit 0
fi

# set +
if test $# = 2
then
    X=$(cat "${B}")
    XMAX=$(cat "${D}"/max_brightness)
    DELTA=$(expr "${2}" '*' ${XMAX} / 100)
    NEWVAL=$(expr "${X}" "${1}" "${DELTA}")
    setValue "${NEWVAL}" "${XMAX}"
    exit 0
fi

# help
echo "${0}"      >&2
echo "${0} + 10" >&2
echo "${0} - 20" >&2
exit 1
