#!/bin/bash

ACTION=$1

case "${ACTION}" in
    "unlock-volume")
     	# on my pc, the master is turned off at boot
	# i don't know what are the rules to set here.
	amixer set Master unmute || exit 1
	;;

    "list")
	echo "auto"
	echo "custom"
	LANG=C aplay -l | grep -E '^card [0-9]*:' | sed -e s+'^card \([0-9]*\): \(.*\), device \([0-9]*\): [^\[]* \[\([^]]*\)].*$'+'\1,\3 \4 \2'+
	;;

    "get")
	batocera-settings -command load -key audio.device
	;;

    "set")
	MODE=$2

	# auto: no .asoundrc file
	# custom: don't touch the .asoundrc file
	# any other, create the .asoundrd file
	if [ "${MODE}" == "auto" ];then
	    rm -rf /userdata/system/.asoundrc || exit 1
	elif [ "${MODE}" != "custom" ];then
	    if echo "${MODE}" | grep -qE '^[0-9]*,[0-9]* '
	    then
		cardnb=$(echo "${MODE}" | sed -e s+'^\([0-9]*\),.*$'+'\1'+)
		devicenb=$(echo "${MODE}" | sed -e s+'^[0-9]*,\([0-9]*\) .*$'+'\1'+)

		cat > /userdata/system/.asoundrc <<EOF
pcm.!default {
	type plug
	slave.pcm "dmixer"
}

# configuration de Dmix
pcm.dmixer  {
	type dmix
	ipc_key 1024
	slave {
	    pcm "hw:${cardnb},${devicenb}"
	    period_time 0
	    period_size 1024
	    buffer_size 4096
	    rate 44100
	}
	bindings {
	    0 0
	    1 1
	}
}

ctl.!default { type hw card ${cardnb} }
EOF
		aplay "/usr/share/sounds/Mallet.wav"
		fi
	fi
	;;
esac
