#!/usr/bin/env python
import os
import sys
import re
import time
import subprocess

def killRatpoison():
	runRatpoisonCommand('quit')

def launchRatpoison():
	subprocess.call(f'LC_ALL=C startx /usr/bin/ratpoison -- :1', shell=True)

def altTab():
	runRatpoisonCommand('next')
	showMessage(getRatpoisonCommand('windows %s %n:%t (%a)'))

def showMessage(message):
	runRatpoisonCommand(f'echo {message}')

def runRatpoisonCommand(command):
	print(f'Running ratpoison command {command}')
	try:
		subprocess.call(f'LC_ALL=C ratpoison -d :1 -c "{command}"', shell=True)
	except:
		print('Command returned an error.')
		return False

def getRatpoisonCommand(command):
	print(f'Running ratpoison command {command} (Expecting output)')
	try:
		tempVar = subprocess.check_output(f'LC_ALL=C ratpoison -d :1 -c "{command}"', shell=True).decode(sys.stdout.encoding)
	except:
		return False
	print(f'Ratpoison Output = {tempVar}')
	return tempVar.strip()

if __name__ == '__main__':
	if len(sys.argv) == 1:
		print('Error, command needed.')
	elif sys.argv[1] == 'launch':
		launchRatpoison()
	elif sys.argv[1] == 'reset':
		killRatpoison()
	elif sys.argv[1] == 'switchapp':
		altTab()
	elif sys.argv[1] == 'message':
		showMessage(sys.argv[2])