#!/bin/bash

# Bash script to get the latest Nvidia driver lists
# which may add new boards in between versions.

LOG_DIR="/userdata/system/logs"
LOG_FILE="$LOG_DIR/nvidia.log"
DEST_DIR="/userdata/system/.nvidia"

# Function to ensure the destination directory exists
ensure_directory() {
    mkdir -p "$1"
}

# Function to check internet connectivity
check_internet() {
    # Method 1
    if ping -c 1 1.1.1.1 &> /dev/null; then
        return 0
    fi
    # Method 2
    if curl -IsSf https://www.google.com >/dev/null; then
        return 0
    fi
    return 1
}

# Function to download files
download_file() {
    curl -sSf "$1" -o "$2"
    return $?
}

# Ensure log directories exist
ensure_directory "$LOG_DIR"
ensure_directory "$DEST_DIR"

# Try to check for an internet connection up to 6 times, with a 5-second delay
tries=6
while [ $tries -gt 0 ]; do
    if check_internet; then
        echo "Internet connection detected, downloading Nvidia driver lists..." >> "$LOG_FILE"
        break
    else
        sleep 5s
        tries=$((tries - 1))
    fi
done

# Check if the download was successful
if [ $tries -gt 0 ]; then
    # Array of files to download
    files=("production.list" "legacy.list" "legacy390.list" "legacy340.list")

    # Loop through the files and download them
    for file in "${files[@]}"; do
        download_file "https://raw.githubusercontent.com/batocera-linux/nvidia-lists/main/$file" "$DEST_DIR/$file"
        if [ $? -eq 0 ]; then
            echo "Download of $file successful. File saved to $DEST_DIR/$file" >> "$LOG_FILE"
        else
            echo "Download of $file failed." >> "$LOG_FILE"
        fi
    done
else
    echo "Maximum retries reached. Could not establish an internet connection for the Nvidia driver lists" >> "$LOG_FILE"
fi
