#!/usr/bin/env python

import sys
import os
import shutil

def printUsage(errorMessage = None):
	if errorMessage != None:
		print(errorMessage)
	print("Usage: batocera-gcgbaprep [gamecube rom] [gba rom] [slot number] -c (optional)")
	print("Use just the filename for ROMs, if it is in a subfolder, use subfolder/filename.")
	print("Slot number should be 1-4.")
	print("If you are using a filesystem that does not allow symlinks, use the -c option to copy instead.")
	quit()

def removeExisting(fileName):
	if os.path.exists(fileName):
		if os.path.isfile(fileName):
			os.remove(fileName)
		elif os.path.islink(fileName):
			os.unlink(fileName)

if __name__ == '__main__':
	if len(sys.argv) < 4:
		printUsage()

	copyMode = False
	if len(sys.argv) == 5:
		if sys.argv[4].lower() == "-c":
			copyMode = True

	romFullPath = '/userdata/roms/gamecube/' + sys.argv[1]
	if os.path.exists(romFullPath):
		baseFileName = os.path.splitext(os.path.basename(romFullPath))[0]
		baseFilePath = os.path.dirname(romFullPath)
	else:
		printUsage(f"File {romFullPath} does not exist - filenames are case sensitive.")

	gbaFullPath = '/userdata/roms/gba/' + sys.argv[2]
	if os.path.exists(gbaFullPath):
		baseGBAName = os.path.splitext(os.path.basename(gbaFullPath))
		gbaSaveFile = '/userdata/saves/gba/' + baseGBAName[0] + '.sav'
		if not os.path.exists(gbaSaveFile):
			copySave = False
			print(f"No save file for {sys.argv[2]}, only copying the ROM file.")
		else:
			copySave = True
	else:
		printUsage(f"File {gbaFullPath} does not exist - filenames are case sensitive.")

	gbaSlot = int(sys.argv[3])
	if gbaSlot < 1 or gbaSlot > 4:
		printUsage('Invalid slot number.')

	gbaFileDest = f"{baseFilePath}/{baseFileName}-{gbaSlot}{baseGBAName[1]}"
	gbaSavePath = "/userdata/saves/gamecube/gba/"
	gbaSaveDest = f"{gbaSavePath}{baseFileName}-{gbaSlot}-{gbaSlot}.sav"

	if not os.path.exists(gbaSavePath):
		os.makedirs(gbaSavePath)

	removeExisting(gbaFileDest)
	removeExisting(gbaSaveDest)

	if copyMode:
		shutil.copy2(gbaFullPath, gbaFileDest)
		print(f"Copied {gbaFullPath} to {gbaFileDest}")
		if copySave:
			shutil.copy2(gbaSaveFile, gbaSaveDest)
			print(f"Copied {gbaSaveFile} to {gbaSaveDest}")
	else:
		os.symlink(gbaFullPath, gbaFileDest)
		print(f"Linked {gbaFullPath} to {gbaFileDest}")
		if copySave:
			os.symlink(gbaSaveFile, gbaSaveDest)
			print(f"Linked {gbaSaveFile} to {gbaSaveDest}")