#!/bin/bash
#
# Get RetroAchievements information for Batocera
#
# @lbrpdx on Batocera Forums and Discord
#
# Usage:
# batocera-retroachievements-info
#
CONFIGFILE="/userdata/system/batocera.conf"
TIMEOUT=4 # seconds before timeout (>2 sec)
USER=""

###############################
#
function usage() {
	echo "$0 username"
	echo " - where username is the RetroAchievements username you want to check out"
	exit 1
}

###############################
#
function process() {
	fn=$(date +"%s")
	tmpfile=/tmp/ra_$fn
	curl -m "$TIMEOUT" -o $tmpfile https://retroachievements.org/user/$USER 2>/dev/null
	if [ x"$?" != x0 ]; then
		echo "RetroAchievements website is too slow to respond, please check your Internet connection."
		exit 1;
	fi
	cat $tmpfile |  awk -v FS="(<div class='username'><span class='username'>|</div><div class='userpage recentlyplayed' >)" '{print $2}' | uniq > "$tmpfile"_2
	points=$(cat "$tmpfile"_2 | sed -e "/^[[:blank:]]*$/d" | awk -v FS="(</strong></a>&nbsp;|<span class='TrueRatio'>)" '{print $2}')
	rank=$(cat "$tmpfile"_2  | sed -e "/^[[:blank:]]*$/d" | awk -v FS="(userList.php|<br/><br/>)" '{print $3}' | sed -e "s/\?s=2'>//" -e "s;<.*a>;;" )
	if  [ x"$rank" != x ]; then
		## For future use: UserPic is RetroAchievements' user avatar
		# UserPic=$(cat $tmpfile | grep 'meta property=.og:image. content=' | cut -d= -f3 | awk -F\' '{print $2}')
		echo "Player $USER $points is $rank"
		echo "Last RetroAchievements games played:"
		cat $tmpfile | awk '{match($0,/Game.*points.<br\/>/); s=substr($0, RSTART, RLENGTH); printf "%s",s }' | sed -e "/^[[:blank:]]*$/d" | sed -e 's/points.<br\/>/points\@\\\n/g;' > "$tmpfile"_2
		cat "$tmpfile"_2 | awk -v FS="(Game/[0-9]*'>|@)" '{print $2}' | sed -e "s;</a><br/>\(Last played[ 0-9:-]*\)<br/>\(.*\);@\2@\1;" | sed -e "s;achievements, ;achievements@;" | sed -e "s;Earned ;;"
	else
		echo "Player $USER not found on https://retroachievements.org"
	fi
	rm "$tmpfile" "$tmpfile"_2
}

#### Main loop
#
if [ $# -lt 1 ]; then
	[ -f "$CONFIGFILE" ] && USER=$(grep -E "^[ \t]*global.retroachievements.username=" "$CONFIGFILE" | cut -d= -f2 | uniq)
else
	tmp="$1"
	[ x"${tmp::1}" == "x-" ] && usage || USER="$1"
fi

[ x"$USER" == x ] && usage || process

