#!/bin/bash

# Early script to set the TDP
# We should call / set the TDP per emulator based on user selection

log="/userdata/system/logs/amd-tdp.log"

TDP_MIN=5
TDP_MAX=100

TDP=$1

# Check we have a ryzenadj supported CPU
ryzenadj_output=$(ryzenadj -i)
if [[ $ryzenadj_output =~ "unsupported model" ]]; then
  echo "Unsupported CPU for RyzenAdj"
  exit 1
fi

# Handle various AMD handhelds
info_output=$(batocera-info | grep "Model:" | awk -F": " '{print $2}' | head -n 1)

if [[ $info_output == "Loki_Zero" ]]; then
    # Set the TDP range to 2-20w
    # We need vendor guidance to get accurate values
    TDP_MIN=5
    TDP_MAX=20
    echo "Handheld AYN Loki Zero detected. Minumum TDP: $TDP_MIN Watts. Maximum TDP: $TDP_MAX Watts" >> $log
fi

# Legion Go
if [[ $info_output == "LNVNB161216" ]]; then
    # Set the TDP range to 2-20w
    # We need vendor guidance to get accurate values
    TDP_MIN=5
    TDP_MAX=30
    echo "Handheld Lenovo Legion Go detected. Minumum TDP: $TDP_MIN Watts. Maximum TDP: $TDP_MAX Watts" >> $log
fi

# Check if TDP is null or not provided. If so, set to 10w
if [ -z "$TDP" ]; then
    TDP=10
    echo "No TDP detected, using TDP of $TDP Watts" >> $log
fi

# Align to the TDP_MIN if it's below it
if (( TDP < TDP_MIN )); then
    echo "Requested TDP of $TDP Watts is below the minimum" >> $log
    TDP=$TDP_MIN
    echo "Using TDP of $TDP" >> $log
fi
# Cap TDP at TDP_MAX if it exceeds it
if (( TDP > TDP_MAX )); then
    echo "Requested TDP of $TDP Watts is above the maximum" >> $log
    TDP=$TDP_MAX
    echo "Using TDP of $TDP Watts" >> $log
fi

if (( TDP >= TDP_MIN && TDP <= TDP_MAX )); then
    # Calculate WATTS based on TDP
    WATTS=$((TDP * 1000))
fi

if /usr/bin/ryzenadj --stapm-limit="${WATTS}" --fast-limit="${WATTS}" --slow-limit="$((WATTS * 80 / 100))" --tctl-temp=95; then
    echo "TDP of $TDP Watts has been set" >> $log
else
    echo "Error setting TDP. Please check the logs for more information." >> $log
    exit 1
fi

echo "" >> $log
echo "*** ------------------------------------- ***" >> $log
echo "" >> $log

batocera-settings-set amd.tdp ${TDP}
