#!/bin/bash

DAEMON="splash-omx"
DEFAULT="/usr/share/batocera/splash/splash.mp4"
SPLASH_DIR=/userdata/splash

FM_IMAGE=".*\.\(jpg\|jpeg\|png\)"
FM_VIDEO=".*\.\(mp4\|MP4\)"

. /etc/profile.d/xdg.sh
. /etc/profile.d/dbus.sh

do_angels_conversion ()
{
    [[ $1 -lt 0 || $1 -gt 3 ]] && echo 0 || echo $(($1*90))
    return $?
}

do_filerandomize ()
{
    local array
    [[ -d "$SPLASH_DIR" ]] || return 1
    readarray -t array < <(find "$SPLASH_DIR" -maxdepth 1 -regex "$1" -type f)
    if [[ ${#array[@]} -gt 0 ]]; then
        echo "${array[$RANDOM % ${#array[@]}]}"
    fi
}

do_start()
{
    video_file=$(do_filerandomize "$FM_VIDEO")
    image_file=$(do_filerandomize "$FM_IMAGE")

    if [[ -n "$video_file" ]]; then
        do_videostart "$video_file"
    elif [[ -n "$image_file" ]]; then
        do_imagestart "$image_file"
    else
        do_videostart "$DEFAULT"
    fi
}

do_imagestart()
{
    image="$1"
    printf 'Image: %s: ' "$image"
    if test -e /dev/fb0
    then
        start-stop-daemon -S -b -q -m -p /var/run/user-splash-image.pid --exec fbv -- -f -i "$image"
    fi
}

do_videostart ()
{
    video="$1"
    printf 'Video: %s: ' "$video"
    omx_fnt="--font=/usr/share/fonts/dejavu/DejaVuSans-BoldOblique.ttf"
    omx_opt="--no-keys --layer=10000 --aspect-mode=fill"
    omx_srt="--no-ghost-box --lines=1 --align=left $omx_fnt --font-size=20 --subtitles=/usr/share/batocera/splash/splash.srt"

    omx_nosound=
    soundDisabled=$(batocera-settings-get splash.screen.sound)
    if [[ $? -eq 0 ]]; then
	if test "${soundDisabled}" = 0
	then
	    omx_nosound="-n -1"
	fi
    fi

    start-stop-daemon -S -b -q -m -p /var/run/user-splash.pid --exec /usr/bin/omxplayer -- -o both $omx_opt $omx_srt $omx_nosound "$video"
}

case "$1" in
    start)
        printf 'Starting %s: ' "$DAEMON"
        if grep -qE '^[ ]*splash.screen.enabled[ ]*=[ ]*1[ ]*$' "/boot/batocera-boot.conf"
        then
            do_start
            echo "OK"
	else
	    echo "SKIPPED"
        fi
        ;;
    stop)
        start-stop-daemon -K -q -p /var/run/user-splash.pid
        ;;
    restart|reload)
        ;;
    *)
esac

exit $?
