#!/bin/bash

DAEMON="splash-image"
DEFAULT="/usr/share/batocera/splash/logo-version.png"
SPLASH_DIR=/userdata/splash

FM_IMAGE=".*\.\(jpg\|jpeg\|png\)"

do_filerandomize ()
{
    local array
    [[ -d "$SPLASH_DIR" ]] || return 1
    readarray -t array < <(find "$SPLASH_DIR" -regex "$1" -maxdepth 1 -type f)
    if [[ ${#array[@]} -gt 0 ]]; then
        echo "${array[$RANDOM % ${#array[@]}]}"
    fi
}

do_start ()
{
    # no image => for ogoa (or any other), logo-version-wxh.png
    if ! test -e "$DEFAULT"
    then
        DEFAULT="/usr/share/batocera/splash/logo-version-"$(batocera-resolution currentResolution)".png"
    fi

    image_file=$(do_filerandomize "$FM_IMAGE")

    if [[ -n "$image_file" ]]; then
        do_imagestart "$image_file"
    else
        do_imagestart "$DEFAULT"
    fi
}

do_imagestart ()
{
    image="$1"
    printf 'Image: %s: ' "$image"
    if test -e /dev/fb0
    then
        start-stop-daemon -S -b -q -m -p /var/run/user-splash-image.pid --exec fbv -- -f -i "$image"
    fi
}

do_imageplatform()
{
    BOARD_MODEL=$(cat /sys/firmware/devicetree/base/model 2>/dev/null | sed -e s+"[^A-Za-z0-9]"+"_"+g)

    if [[ ${BOARD_MODEL} = "Hardkernel_ODROID_GO2" ]]; then
        ln -sf /usr/share/batocera/splash/logo-version-320x480.png /usr/share/batocera/splash/boot-logo.png
        ln -sf /usr/share/batocera/splash/logo-version-320x480.png /usr/share/batocera/splash/logo-version.png
    elif [[ ${BOARD_MODEL} = "Hardkernel_ODROID_GO3" ]]; then
        ln -sf /usr/share/batocera/splash/logo-version-480x854.png /usr/share/batocera/splash/boot-logo.png
        ln -sf /usr/share/batocera/splash/logo-version-480x854.png /usr/share/batocera/splash/logo-version.png
    elif [[ ${BOARD_MODEL} = "Anbernic_RG351P" ]]; then
        ln -sf /usr/share/batocera/splash/logo-version-320x480.png /usr/share/batocera/splash/boot-logo.png
        ln -sf /usr/share/batocera/splash/logo-version-320x480.png /usr/share/batocera/splash/logo-version.png
    elif [[ ${BOARD_MODEL} = "Golden_GameForce" ]]; then
        ln -sf /usr/share/batocera/splash/logo-version-480p.png /usr/share/batocera/splash/boot-logo.png
        ln -sf /usr/share/batocera/splash/logo-version-480p.png /usr/share/batocera/splash/logo-version.png
    fi
}

case "$1" in
    start)
        printf 'Starting %s: ' "$DAEMON"
        if grep -qE '^[ ]*splash.screen.enabled[ ]*=[ ]*0[ ]*$' "/boot/batocera-boot.conf"
        then
            echo "SKIPPED"
            exit 0
        fi
        do_imageplatform
        do_start
        echo "OK"
        ;;
    stop)
        start-stop-daemon -K -q -p /var/run/user-splash.pid
        ;;
    restart|reload)
        ;;
    *)
esac

exit $?
