#!/bin/sh

case "$1" in
    start)
	systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/recalboxSettings.py"
	enabled="`$systemsetting  -command load -key system.es.atstartup`"
        if [ "$enabled" != "0" ];then
		settings_lang="`$systemsetting -command load -key system.language`"
		# HOME is important to be able to call ~/.xinitrc
                HOME=/userdata/system startx &
	fi
	;;
  stop)
	killall emulationstation
	;;
  restart|reload)
        "$0" stop
        "$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


