#!/bin/sh

# Function to check if led module is loaded
is_module_loaded() {
    lsmod | grep -q "^$1 "
}

# Functions to set the LED mode parameters
# [ ayn-platform ]
set_led_mode() {
    # turn off rainbow effect if enabled
    echo 1 | tee /sys/class/leds/multicolor:chassis/device/led_mode
    led_colour="$(/usr/bin/batocera-settings-get led.colour)"
    led_brightness="$(/usr/bin/batocera-settings-get led.brightness)"
    # Set the colour
    if [ -n "$led_colour" ]; then
        echo $led_colour | tee /sys/class/leds/multicolor:chassis/multi_intensity
    else
        # Set hot pink colour as default
        echo 255 0 165 | tee /sys/class/leds/multicolor:chassis/multi_intensity
    fi
    # Set the brightness
    if [ -n "$led_brightness" ]; then
        led_max_brightness=$(cat /sys/class/leds/multicolor:chassis/max_brightness)
        led_brightness=$(echo "scale=0; ($led_brightness * $led_max_brightness + 50) / 100" | bc)
        echo $led_brightness | tee /sys/class/leds/multicolor:chassis/brightness
    else
        # Set max brightness as default
        echo 255 | tee /sys/class/leds/multicolor:chassis/brightness
    fi
}

case "$1" in
    start)
        # ayn-platform is used for ayn handhelds
        if is_module_loaded ayn_platform || is_module_loaded ayaneo_platform; then
            set_led_mode
        fi
        ;;
    stop)
        ;;
    restart)
        # Add any restart logic if needed later
		stop
		start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
