#!/bin/bash

case "$1" in
  start)
    if [ -f "/var/tmp/nvidia.detected" ]; then
        # copy nvidia log to userdata
        cp -f /var/log/nvidia.log /userdata/system/logs/nvidia.log
        # get the latest nvidia list files
        batocera-get-nvidia-list &
    fi
    ;;
  stop)
    # No stop behavior necessary
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
