#!/bin/bash

case "$1" in
  start)
    if ! lscpu | grep -q AuthenticAMD; then
        echo "Authentic AMD CPU not found, exiting TDP..."
        exit 1
    else
        # check if tdp capable processor exists for Ryzen Mobile Processor
        if ! ryzenadj -i | head -n 1 | grep -q "unsupported model"; then
            echo "Supported Ryzen Mobile Processor found for TDP..."
            MAX_TDP=$(ryzenadj -i | grep 'PPT LIMIT FAST' | awk '{printf "%.0f\n", $6}')
            /usr/bin/batocera-settings-set system.cpu.tdp "${MAX_TDP}"
            # set the global TDP if set
            TDP_PERCENTAGE="$(/usr/bin/batocera-settings-get global.tdp)"
            if ! [ -z "${TDP_PERCENTAGE}" ] && [ "$TDP_PERCENTAGE" -ge 10 ]; then
                TDP_VALUE=$(awk -v max_tdp="$MAX_TDP" -v tdp_percentage="$TDP_PERCENTAGE" 'BEGIN { printf("%.0f\n", max_tdp * tdp_percentage / 100) }')
                echo "Setting Ryzen Mobile Processor TDP to $TDP_VALUE"
                /usr/bin/batocera-amd-tdp $TDP_VALUE
            fi
        else
            echo "Supported AMD Processor NOT found for TDP..."
            exit 1
        fi
    fi
    ;;
  stop)
    # no stop behavior necessary
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
