#!/usr/bin/python

#
# This file is part of the batocera distribution (https://batocera.org).
# Copyright (c) 2022 Nicolas Adenis-Lamarre.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# YOU MUST KEEP THIS HEADER AS IT IS
#
#

import evdev
from evdev import ecodes
import select
import sys
import time
import os
import hashlib
import math

if len(sys.argv) != 2 and len(sys.argv) != 3:
    print("mising device argument")
    exit(1)

if len(sys.argv) == 3:
    bCalibration = int(sys.argv[2])
else:
    bCalibration = ecodes.BTN_RIGHT

# input
devpath = sys.argv[1]
input = evdev.InputDevice(devpath)
absVals = [[0, 100], [0, 100]] # input rectangle
for (code, inf) in input.capabilities()[ecodes.EV_ABS]:
    if code == ecodes.ABS_X:
        absVals[0] = [inf.min, inf.max]
    if code == ecodes.ABS_Y:
        absVals[1] = [inf.min, inf.max]
poll = select.poll()
poll.register(input.fd, select.POLLIN)
inputkey = hashlib.md5(input.name.encode()).hexdigest()[0:8]

# output
outputSize = [1000, 1000] # output rectangle
evkeys = []
for x in range(ecodes.KEY_MAX):
    if x not in [
            ecodes.BTN_DIGI,
            ecodes.BTN_TOOL_PEN,
            ecodes.BTN_TOOL_RUBBER,
            ecodes.BTN_TOOL_BRUSH,
            ecodes.BTN_TOOL_PENCIL,
            ecodes.BTN_TOOL_AIRBRUSH,
            ecodes.BTN_TOOL_FINGER,
            ecodes.BTN_TOOL_MOUSE,
            ecodes.BTN_TOOL_LENS,
            ecodes.BTN_TOUCH,
            ecodes.BTN_STYLUS,
            ecodes.BTN_STYLUS2,
            ecodes.BTN_TOOL_DOUBLETAP,
            ecodes.BTN_TOOL_TRIPLETAP,
            ecodes.BTN_TOOL_QUADTAP]: # avoid some buttons causing issues to libinput
        evkeys.append(x)

target = evdev.UInput(name=input.name+" calibrated", events={
    ecodes.EV_ABS: [
        (ecodes.ABS_X, evdev.AbsInfo(value=0, min=0, max=outputSize[0], fuzz=0, flat=0, resolution=0)),
        (ecodes.ABS_Y, evdev.AbsInfo(value=0, min=0, max=outputSize[1], fuzz=0, flat=0, resolution=0))
    ],
    ecodes.EV_KEY: evkeys})

needSync = False
calibration_timeChecker = None
calibration_mode = False
calibration_step = 0    # 0=idle, 1=center, 2..(1+len(CALIB_POINTS))=one of CALIB_POINTS
calibration_retry = False
pLast = [0, 0]
pCenter = [0, 0]
# per-axis, per-side half-window in raw units: pWindow[axis][side], axis 0=x/1=y, side 0=negative(up/left)/1=positive(down/right)
# kept independent per side because the reachable aiming range is rarely symmetric around
# the screen center (sensor bar placement, seating distance, IR camera's narrow vertical
# field of view when tilted down, ...): a single symmetric window under- or over-shoots
# one side, which is what made parts of the screen (typically low on the screen) unreachable
pWindow = [
    [(absVals[0][1]-absVals[0][0])//2, (absVals[0][1]-absVals[0][0])//2], # x: left, right
    [(absVals[1][1]-absVals[1][0])//2, (absVals[1][1]-absVals[1][0])//2], # y: up, down
]

# name, axis, side, primary target (output position shown to the player), retry target (closer to center, for small rooms)
CALIB_POINTS = [
    ("top",    1, 0, [outputSize[0]//2, 0],             [outputSize[0]//2, outputSize[1]//4]),
    ("bottom", 1, 1, [outputSize[0]//2, outputSize[1]],  [outputSize[0]//2, outputSize[1]*3//4]),
    ("left",   0, 0, [0, outputSize[1]//2],              [outputSize[0]//4, outputSize[1]//2]),
    ("right",  0, 1, [outputSize[0], outputSize[1]//2],  [outputSize[0]*3//4, outputSize[1]//2]),
]

def moveTargetTo(fromPosition, toPosition):
    currentPosition = list(fromPosition)
    while currentPosition[0] != toPosition[0] or currentPosition[1] != toPosition[1] :
        if currentPosition[0] < toPosition[0]:
            currentPosition[0] = currentPosition[0] +1
        if currentPosition[0] > toPosition[0]:
            currentPosition[0] = currentPosition[0] -1
        if currentPosition[1] < toPosition[1]:
            currentPosition[1] = currentPosition[1] +1
        if currentPosition[1] > toPosition[1]:
            currentPosition[1] = currentPosition[1] -1
        target.write(ecodes.EV_ABS, ecodes.ABS_X, currentPosition[0])
        target.write(ecodes.EV_ABS, ecodes.ABS_Y, currentPosition[1])
        target.syn()
        time.sleep(0.001) # x1000 = 1 second

def failAnimation(originalPosition):
    for i in range(0, 50):
        target.write(ecodes.EV_ABS, ecodes.ABS_X, originalPosition[0]+int(20*math.cos(i)))
        target.write(ecodes.EV_ABS, ecodes.ABS_Y, originalPosition[1]+int(20*math.sin(i)))
        target.syn()
        time.sleep(0.01) # x1000 = 1 second

def saveCalibration(devpath, key, pCenter, pWindow):
    content = "{} {} {} {} {} {}".format(pCenter[0], pCenter[1], pWindow[0][0], pWindow[0][1], pWindow[1][0], pWindow[1][1])
    # save a general file, available after boot
    if not os.path.exists("/userdata/system/configs/gun-calibrator"):
        os.makedirs("/userdata/system/configs/gun-calibrator")
    with open('/userdata/system/configs/gun-calibrator/{}.conf'.format(key), 'w') as fd:
        fd.write(content)
    # save for multiple guns, not available after boot
    with open('/var/run/gun-calibrator.conf.{}'.format(os.path.basename(devpath)), 'w') as fd:
        fd.write(content)

def readCalibration(devpath, key, pCenter, pWindow):
    try:
        path = None
        # prefer the on configured for the given input
        # otherwise prefer the system one (common in case you've several same devices)
        pathLast   = '/var/run/gun-calibrator.conf.{}'.format(os.path.basename(devpath))
        pathSystem = '/userdata/system/configs/gun-calibrator/{}.conf'.format(key)
        if os.path.exists(pathLast):
            path = pathLast
        elif os.path.exists(pathSystem):
            path = pathSystem
        else:
            return pCenter, pWindow

        with open(path, 'r') as fd:
            content = fd.readlines()
        vals = [int(v) for v in content[0].split()]

        if len(vals) != 6 or 0 in vals[2:6]: # invalid, or written by an older (symmetric-only) calibrator
            return pCenter, pWindow

        return [vals[0], vals[1]], [[vals[2], vals[3]], [vals[4], vals[5]]]
    except:
        return pCenter, pWindow

pCenter, pWindow = readCalibration(devpath, inputkey, pCenter, pWindow)

def calibrationFailed(val):
    if (val[0] == 1 and val[1] == 1023) or (val[0] == 0 and val[1] == 0): # generally, what we get meaning nothing : no point detected
        print("Calibration failed")
        return True
    # should we care about other points if too distant from the first one ?
    print("calibration with x={}, y={}".format(val[0], val[1]))
    return False

def rawCenter(axis):
    return absVals[axis][0] + (absVals[axis][1]-absVals[axis][0])//2 + pCenter[axis]

def advanceToNextPoint(pointIndex):
    global calibration_step, calibration_mode
    nextIndex = pointIndex + 1
    if nextIndex < len(CALIB_POINTS):
        calibration_step = 2 + nextIndex
        moveTargetTo(CALIB_POINTS[pointIndex][3], CALIB_POINTS[nextIndex][3])
    else:
        calibration_step = 0
        calibration_mode = False
        saveCalibration(devpath, inputkey, pCenter, pWindow)
        target.write(ecodes.EV_KEY, ecodes.KEY_CONFIG, 0)
        target.syn()

try:
        while True:
            if poll.poll(1000):
                if calibration_mode:
                        # read positions during calibration
                        for event in input.read():
                            if event.type == ecodes.EV_ABS and event.code == ecodes.ABS_X:
                                pLast[0] = event.value
                            elif event.type == ecodes.EV_ABS and event.code == ecodes.ABS_Y:
                                pLast[1] = event.value
                            elif event.type == ecodes.EV_KEY and event.code == ecodes.BTN_LEFT and event.value == 1:
                                if calibration_step == 1:
                                    # center point
                                    if calibrationFailed(pLast):
                                        calibration_step = 0
                                        calibration_mode = False
                                        failAnimation([outputSize[0]//2, outputSize[1]//2])
                                        target.write(ecodes.EV_KEY, ecodes.KEY_CONFIG, 0)
                                        target.syn()
                                    else:
                                        pCenter = [pLast[0]-(absVals[0][1] - absVals[0][0])//2, pLast[1]-(absVals[1][1] - absVals[1][0])//2]
                                        calibration_retry = False
                                        calibration_step = 2
                                        moveTargetTo([outputSize[0]//2, outputSize[1]//2], CALIB_POINTS[0][3])
                                else:
                                    # one of the CALIB_POINTS edges (top/bottom/left/right), sampled
                                    # independently so asymmetric aiming ranges are captured instead
                                    # of assumed
                                    pointIndex = calibration_step - 2
                                    name, axis, side, primaryTarget, retryTarget = CALIB_POINTS[pointIndex]
                                    if calibrationFailed(pLast):
                                        if not calibration_retry:
                                            # too far / too close for this room: retry closer to the center
                                            calibration_retry = True
                                            moveTargetTo(primaryTarget, retryTarget)
                                        else:
                                            # keep the default window for this side and move on rather
                                            # than aborting the whole calibration over one bad side
                                            calibration_retry = False
                                            advanceToNextPoint(pointIndex)
                                    else:
                                        newWindow = abs(rawCenter(axis) - pLast[axis])
                                        if newWindow != 0: # 0 would mean calibration failed, keep the default
                                            pWindow[axis][side] = newWindow
                                        calibration_retry = False
                                        advanceToNextPoint(pointIndex)
                            else:
                                target.write(event.type, event.code, event.value)
                                target.syn()
                else:
                    if calibration_timeChecker is not None:
                        if time.time() - calibration_timeChecker > 3: # 3 seconds
                            calibration_mode = True
                            calibration_timeChecker  = None
                            calibration_step = 1
                            calibration_retry = False
                            target.write(ecodes.EV_KEY, ecodes.KEY_CONFIG, 1)
                            target.syn()
                            moveTargetTo([outputSize[0]//2, 0], [outputSize[0]//2, outputSize[1]//2])

                    # could be enabled by the timeChecker
                    if calibration_mode is False:
                        # normal event read
                        for event in input.read():
                            if event.type == ecodes.EV_ABS and event.code == ecodes.ABS_X:
                                offset = event.value - rawCenter(0)
                                side = 0 if offset < 0 else 1
                                val = int(outputSize[0]//2 + offset * (outputSize[0]//2) / pWindow[0][side])
                                val = max(0, min(outputSize[0], val)) # clamp instead of dropping: an
                                # out-of-window aim should stick to the screen edge, not freeze the cursor
                                target.write(ecodes.EV_ABS, ecodes.ABS_X, val)
                                needSync = True
                            elif event.type == ecodes.EV_ABS and event.code == ecodes.ABS_Y:
                                offset = event.value - rawCenter(1)
                                side = 0 if offset < 0 else 1
                                val = int(outputSize[1]//2 + offset * (outputSize[1]//2) / pWindow[1][side])
                                val = max(0, min(outputSize[1], val))
                                target.write(ecodes.EV_ABS, ecodes.ABS_Y, val)
                                needSync = True
                            elif event.type == ecodes.EV_SYN:
                                if needSync:
                                    target.syn()
                                    needSync = False
                            elif event.type == ecodes.EV_KEY and event.code == bCalibration:
                                if event.value == 1:
                                    calibration_timeChecker = time.time()
                                    target.write(event.type, event.code, event.value)
                                    needSync = True
                                else:
                                    calibration_timeChecker = None
                                    target.write(event.type, event.code, event.value)
                                    needSync = True
                            elif event.type == ecodes.EV_KEY:
                                target.write(event.type, event.code, event.value)
                                needSync = True
except KeyboardInterrupt:
    poll.unregister(input.fd)
    target.close()
except Exception as e:
    import traceback
    with open('/var/run/gun-calibrator.crash', 'w') as fd:
        fd.write(traceback.format_exc())
    raise e
###
