#!/usr/bin/env bash

if test "$1" = "start"
then
    # kernel option for xbox one controllers
    echo 1 > /sys/module/bluetooth/parameters/disable_ertm
    # xbox one usb dongle: force daemon to start if dongle detected and not already started
    if [[ $(pgrep xow) == "" && $(lsusb | grep "045e:02e6") != "" || $(lsusb | grep "045e:02fe") != "" ]]; then
        nohup /usr/bin/xow-daemon &
    fi
fi
