#!/usr/bin/env python

import os
import subprocess

proc=subprocess.run(["cat /sys/firmware/devicetree/base/model | sed -e s+'[^A-Za-z0-9]'+'_'+g"], shell=True, stdout=subprocess.PIPE)
BOARD_MODEL=proc.stdout.decode('utf-8')

DISPLAY_ORIENTATION={
    "Anbernic_RG552": "270",
    "ODROID_GO_Advance": "270"
}

for board in DISPLAY_ORIENTATION:
    if [board == BOARD_MODEL]:
        os.system("/usr/bin/batocera-resolution setRotation " + DISPLAY_ORIENTATION[board])
