#!/bin/bash

if test -z "${DISPLAY}"
then
    export DISPLAY=:0.0
fi

# $$ is this globally defined somewhere else?
CFGDIR=/userdata/system/configs/vita3k

# check the config folder exists, if not create it & copy files
if [[ ! -e $CFGDIR ]]
then
    mkdir $CFGDIR
    cp -R /usr/bin/vita3k/* $CFGDIR
fi

# $$ how to create a conditional for those who opt into moving app install data in /userdata/saves ?
XDGDATA=$CFGDIR
#XDGDATA=/userdata/saves

# set the environment variables
XDG_CONFIG_HOME=$CFGDIR \
XDG_CACHE_HOME=/userdata/system/cache \
XDG_DATA_HOME=$XDGDATA \
XDG_DATA_DIRS=$XDGDATA \
# now run the emulator
/usr/bin/vita3k/Vita3K -F
