#!/bin/bash

if test -z "${DISPLAY}"
then
    export DISPLAY=:0.0
fi

PATH=$PATH:PATH=$PATH:/usr/wine/lutris/bin
WINEPREFIX=/userdata/saves/cemu wine64 /userdata/system/configs/cemu/Cemu.exe -m z:/userdata/saves/cemu

exit 0
