#!/bin/bash

# when the program is called from a non X environment, handle the mouse
# maybe an other choice is better

if test -z "${DISPLAY}"
then
    export DISPLAY=$(getLocalXDisplay)
fi

XDG_CONFIG_HOME=/userdata/system/configs \
XDG_DATA_HOME=/userdata/saves/3ds \
XDG_CACHE_HOME=/userdata/system/cache \
QT_QPA_PLATFORM=xcb \
SDL_JOYSTICK_HIDAPI=0 \
/usr/bin/azahar

