#!/bin/bash

if [ -n "$WAYLAND_DISPLAY" ]; then
    export SDL_VIDEODRIVER=wayland
    export SDL_VIDEO_WAYLAND_WMCLASS="batocera-config-model2"
else
    export DISPLAY=$(getLocalXDisplay)
fi

batocera-launch -system model2 -rom config

exit 0
