#!/bin/bash

if test -z "${DISPLAY}"
then
	export DISPLAY=:0.0
fi

PATH=$PATH:PATH=$PATH:/usr/wine/lutris/bin
cd /userdata/saves/bigpemu-bottle/bigpemu/

# hum pw 0.2 and 0.3 are hardcoded, not nice
LD_LIBRARY_PATH=/lib32:/usr/wine/lutris/lib/wine \
LIBGL_DRIVERS_PATH=/lib32/dri \
SPA_PLUGIN_DIR="/usr/lib/spa-0.2:/lib32/spa-0.2" \
PIPEWIRE_MODULE_DIR="/usr/lib/pipewire-0.3:/lib32/pipewire-0.3" \
WINEPREFIX=/userdata/saves/bigpemu-bottle \
wine /userdata/saves/bigpemu-bottle/bigpemu/BigPEmu.exe

exit 0
