#!/bin/bash

if [ -n "$WAYLAND_DISPLAY" ]; then
    export SDL_VIDEODRIVER=wayland
    export SDL_VIDEO_WAYLAND_WMCLASS="batocera-config-ppsspp"
else
     export DISPLAY=$(getLocalXDisplay)
fi

XDG_CONFIG_HOME=/userdata/system/configs XDG_DATA_HOME=/userdata/saves /usr/bin/PPSSPP --windowed
