#!/bin/bash

if test -z "${DISPLAY}"
then
	export DISPLAY=:0.0
fi

PATH=$PATH:PATH=$PATH:/usr/wine/lutris/bin

XDG_CONFIG_HOME=/userdata/system/configs XDG_CACHE_HOME=/userdata/system/cache QT_QPA_PLATFORM=xcb /usr/bin/melonDS
