#!/bin/bash

# when the program is called from a non X environment, handle the mouse
# maybe an other choice is better

if test -z "${DISPLAY}"
then
    export DISPLAY=:0.0
fi

XDG_CONFIG_HOME=/userdata/system/configs /usr/PCSX/bin/PCSX2 --gs=/usr/PCSX/bin/plugins/libGSdx.so
