#!/bin/bash

# when the program is called from a non X environment, handle the mouse
# maybe an other choice is better

if test -z "${DISPLAY}"
then
    export DISPLAY=$(getLocalXDisplay)
fi

export XDG_CONFIG_HOME=/userdata/system/configs
export QT_QPA_PLATFORM=xcb

LD_LIBRARY_PATH=/usr/stenzek-shaderc/lib:/usr/lib \
/usr/pcsx2/bin/pcsx2-qt
