#!/bin/bash

if test -z "${DISPLAY}"
then
	export DISPLAY=$(getLocalXDisplay)
fi

/usr/xenia_edge/xenia_edge \
    --storage_root=/userdata/system/configs/xenia_edge \
    --content_root=/userdata/saves/xbox360 \
    --cache_root=/userdata/system/cache/xenia_edge

exit 0
