#!/bin/bash

if test -z "${DISPLAY}"
then
    export DISPLAY=:0.0
fi

if test -e /userdata/system/configs/cemu/settings.xml
then
    cp /userdata/system/configs/cemu/settings.xml /usr/cemu/settings.xml || exit 1
fi
WINEPREFIX=/userdata/saves/cemu wine64 /usr/cemu/Cemu.exe -m z:/userdata/saves/cemu
if test -e /usr/cemu/settings.xml
then
    cp /usr/cemu/settings.xml /userdata/system/configs/cemu/settings.xml || exit 1
fi
exit 0
