#!/bin/bash

if test -z "${DISPLAY}"
then
	export DISPLAY=$(getLocalXDisplay)
fi

export XDG_DATA_HOME=/userdata/system/configs

/usr/bin/xenia-edge/xenia_edge \
    --storage_root=/userdata/system/configs/Xenia \
    --content_root=/userdata/saves/xbox360 \
    --cache_root=/userdata/system/cache/xenia-edge \
    --log_file=/userdata/system/logs/xenia-edge.log

exit 0
