from utils.logger import eslog

def translateInput(input) :
    return str(1 + int(input))
    
def escapedPlayerButton(control,playerPad,default) :
    if playerPad is not None and playerPad.inputs is not None and control in playerPad.inputs :
        return translateInput(playerPad.inputs[control].id)
    else :
        return str(default)
        
def generateControllerConfig(config, playersControllers):    
            
    firstPlayerController, firstPlayerPad = sorted(playersControllers.items())[0]
    secondPlayerController, secondPlayerPad = None, None
    if len(playersControllers.items()) > 1 :
        secondPlayerController, secondPlayerPad = sorted(playersControllers.items())[1]
    # for key in firstPlayerPad.inputs.keys() :
        # print(key)
        # input = firstPlayerPad.inputs[key]
        # print(input.name + ';' + input.type + ';' +input.id  + ';' + input.value+ ';' + input.code)
    # eslog.log('firstPlayerController '+str(firstPlayerPad.index))
    # eslog.log('secondPlayerController '+str(secondPlayerPad.index))

    log = open(config,'w')    
    log.write('[ Global ]  ; Input settings can only be read from the global section!\n')
    log.write('\n')
    log.write('; Network board - experimental build for win32 only\n')
    log.write('EmulateNet = 0\n')
    log.write('port_in = 1970\n')
    log.write('port_out = 1971\n')
    log.write('addr_out = "127.0.0.1"\n')
    log.write('Outputs = net\n')
    log.write('NetOutputsWithLF = 1\n')
    log.write('NetOutputsTCPPort = 8000\n')
    log.write('NetOutputsUDPBroadcastPort = 8001\n')
    log.write('\n')
    log.write('\n')
    log.write('; Common \n')
    log.write('InputStart1 = "KEY_1,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['start'].id)+'"\n')
    log.write('InputStart2 = "KEY_2,JOY2_BUTTON'+escapedPlayerButton('start',secondPlayerPad,9)+'"\n')
    log.write('InputCoin1 = "KEY_3,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['select'].id)+'"\n')
    log.write('InputCoin2 = "KEY_4,JOY2_BUTTON'+escapedPlayerButton('select',secondPlayerPad,10)+'"\n')
    log.write('InputServiceA = "KEY_5"\n')
    log.write('InputServiceB = "KEY_7"\n')
    log.write('InputTestA = "KEY_6"\n')
    log.write('InputTestB = "KEY_8"\n')
    log.write('\n')
    log.write('; 4-way digital joysticks\n')
    log.write('InputJoyUp = "KEY_UP,JOY1_UP"\n')
    log.write('InputJoyDown = "KEY_DOWN,JOY1_DOWN"\n')
    log.write('InputJoyLeft = "KEY_LEFT,JOY1_LEFT"\n')
    log.write('InputJoyRight = "KEY_RIGHT,JOY1_RIGHT"\n')
    log.write('InputJoyUp2 = "JOY2_UP"\n')
    log.write('InputJoyDown2 = "JOY2_DOWN"\n')
    log.write('InputJoyLeft2 = "JOY2_LEFT"\n')
    log.write('InputJoyRight2 = "JOY2_RIGHT"\n')
    log.write('\n')
    log.write('; Fighting game buttons\n')
    log.write('InputPunch = "KEY_A,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['b'].id)+'"\n')
    log.write('InputKick = "KEY_S,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['a'].id)+'"\n')
    log.write('InputGuard = "KEY_D,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['y'].id)+'"\n')
    log.write('InputEscape = "KEY_F,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['x'].id)+'"\n')
    log.write('InputPunch2 = "JOY2_BUTTON'+escapedPlayerButton('b',secondPlayerPad,1)+'"\n')
    log.write('InputKick2 = "JOY2_BUTTON'+escapedPlayerButton('a',secondPlayerPad,2)+'"\n')
    log.write('InputGuard2 = "JOY2_BUTTON'+escapedPlayerButton('y',secondPlayerPad,3)+'"\n')
    log.write('InputEscape2 = "JOY2_BUTTON'+escapedPlayerButton('x',secondPlayerPad,4)+'"\n')
    log.write('\n')
    log.write('; Spikeout buttons\n')
    log.write('InputShift = "KEY_A,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['b'].id)+'"\n')
    log.write('InputBeat = "KEY_S,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['a'].id)+'"\n')
    log.write('InputCharge = "KEY_D,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['y'].id)+'"\n')
    log.write('InputJump = "KEY_F,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['x'].id)+'"\n')
    log.write('\n')
    log.write('; Virtua Striker buttons\n')
    log.write('InputShortPass = "KEY_A,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['b'].id)+'"\n')
    log.write('InputLongPass = "KEY_S,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['a'].id)+'"\n')
    log.write('InputShoot = "KEY_D,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['y'].id)+'"\n')
    log.write('InputShortPass2 = "JOY2_BUTTON'+escapedPlayerButton('b',secondPlayerPad,1)+'"\n')
    log.write('InputLongPass2 = "JOY2_BUTTON'+escapedPlayerButton('a',secondPlayerPad,2)+'"\n')
    log.write('InputShoot2 = "JOY2_BUTTON'+escapedPlayerButton('y',secondPlayerPad,3)+'"\n')
    log.write('\n')
    log.write('; Steering wheel\n')
    log.write('InputSteeringLeft = "KEY_LEFT"      ; digital, turn wheel left\n')
    log.write('InputSteeringRight = "KEY_RIGHT"    ; digital, turn wheel right\n')
    log.write('InputSteering = "JOY1_XAXIS"        ; analog, full steering range\n')
    log.write('\n')
    log.write('; Pedals\n')
    log.write('InputAccelerator = "KEY_UP,JOY1_UP"\n')
    log.write('InputBrake = "KEY_DOWN,JOY1_DOWN"\n')
    log.write('\n')
    log.write('; Up/down shifter manual transmission (all racers)\n')
    log.write('InputGearShiftUp = "KEY_Y"           ; sequential shift up\n')
    log.write('InputGearShiftDown = "KEY_H"         ; sequential shift down\n')
    log.write('\n')
    log.write('; 4-Speed manual transmission (Daytona 2, Sega Rally 2, Scud Race)\n')
    log.write('InputGearShift1 = "KEY_Q,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['pageup'].id)+'"\n')
    log.write('InputGearShift2 = "KEY_W,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['pagedown'].id)+'"\n')
    log.write('InputGearShift3 = "KEY_E,JOY1_BUTTON'+escapedPlayerButton('l2',firstPlayerPad,'11')+'"\n')
    log.write('InputGearShift4 = "KEY_R,JOY1_BUTTON'+escapedPlayerButton('r2',firstPlayerPad,'12')+'"\n')
    log.write('InputGearShiftN = "KEY_T"\n')
    log.write('\n')
    log.write('; VR4 view change buttons (Daytona 2, Le Mans 24, Scud Race)\n')
    log.write('InputVR1 = "KEY_A,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['b'].id)+'"\n')
    log.write('InputVR2 = "KEY_S,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['a'].id)+'"\n')
    log.write('InputVR3 = "KEY_D,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['y'].id)+'"\n')
    log.write('InputVR4 = "KEY_F,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['x'].id)+'"\n')
    log.write('\n')
    log.write('; Single view change button (Dirt Devils, ECA, Harley-Davidson, Sega Rally 2)\n')
    log.write('InputViewChange = "KEY_A,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['b'].id)+'"\n')
    log.write('\n')
    log.write('; Handbrake (Dirt Devils, Sega Rally 2)\n')
    log.write('InputHandBrake = "KEY_S,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['a'].id)+'"\n')
    log.write('\n')
    log.write('; Harley-Davidson controls\n')
    log.write('InputRearBrake = "KEY_S,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['a'].id)+'"\n')
    log.write('InputMusicSelect = "KEY_D,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['y'].id)+'"\n')
    log.write('\n')
    log.write('; Virtual On macros\n')
    log.write('InputTwinJoyTurnLeft = "KEY_Q,JOY1_RXAXIS_NEG"\n')
    log.write('InputTwinJoyTurnRight = "KEY_W,JOY1_RXAXIS_POS"\n')
    log.write('InputTwinJoyForward = "KEY_UP,JOY1_YAXIS_NEG"\n')
    log.write('InputTwinJoyReverse = "KEY_DOWN,JOY1_YAXIS_POS"\n')
    log.write('InputTwinJoyStrafeLeft = "KEY_LEFT,JOY1_XAXIS_NEG"\n')
    log.write('InputTwinJoyStrafeRight = "KEY_RIGHT,JOY1_XAXIS_POS"\n')
    log.write('InputTwinJoyJump = "KEY_E,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['b'].id)+'"\n')
    log.write('InputTwinJoyCrouch = "KEY_R,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['a'].id)+'"\n')
    log.write('\n')
    log.write('; Virtual On individual joystick mapping\n')
    log.write('InputTwinJoyLeft1 = "NONE"\n')
    log.write('InputTwinJoyLeft2 = "NONE"\n')
    log.write('InputTwinJoyRight1 = "NONE"\n')
    log.write('InputTwinJoyRight2 = "NONE"\n')
    log.write('InputTwinJoyUp1 = "NONE"\n')
    log.write('InputTwinJoyUp2 = "NONE"\n')
    log.write('InputTwinJoyDown1 = "NONE"\n')
    log.write('InputTwinJoyDown2 = "NONE"\n')
    log.write('\n')
    log.write('; Virtual On buttons\n')
    log.write('InputTwinJoyShot1 = "KEY_A,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['pageup'].id)+'"\n')
    log.write('InputTwinJoyShot2 = "KEY_S,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['pagedown'].id)+'"\n')
    log.write('InputTwinJoyTurbo1 = "KEY_Z,JOY1_BUTTON'+escapedPlayerButton('l2',firstPlayerPad,'11')+'"\n')
    log.write('InputTwinJoyTurbo2 = "KEY_X,JOY1_BUTTON'+escapedPlayerButton('r2',firstPlayerPad,'12')+'"\n')
    log.write('\n')
    log.write('; Analog joystick (Star Wars Trilogy)\n')
    log.write('InputAnalogJoyLeft = "KEY_LEFT"             ; digital, move left\n')
    log.write('InputAnalogJoyRight = "KEY_RIGHT"           ; digital, move right\n')
    log.write('InputAnalogJoyUp = "KEY_UP"                 ; digital, move up\n')
    log.write('InputAnalogJoyDown = "KEY_DOWN"             ; digital, move down\n')
    log.write('InputAnalogJoyX = "JOY_XAXIS,MOUSE_XAXIS"   ; analog, full X axis\n')
    log.write('InputAnalogJoyY = "JOY_YAXIS,MOUSE_YAXIS"   ; analog, full Y axis\n')
    log.write('InputAnalogJoyTrigger = "KEY_A,JOY_BUTTON1,MOUSE_LEFT_BUTTON"\n')
    log.write('InputAnalogJoyEvent = "KEY_S,JOY_BUTTON2,MOUSE_RIGHT_BUTTON"\n')
    log.write('InputAnalogJoyTrigger2 = "KEY_D,JOY_BUTTON2"\n')
    log.write('InputAnalogJoyEvent2 = "NONE"\n')
    log.write('\n')
    log.write('; Light guns (Lost World)\n')
    log.write('InputGunLeft = "KEY_LEFT"               ; digital, move gun left\n')
    log.write('InputGunRight = "KEY_RIGHT"             ; digital, move gun right\n')
    log.write('InputGunUp = "KEY_UP"                   ; digital, move gun up\n')
    log.write('InputGunDown = "KEY_DOWN"               ; digital, move gun down\n')
    log.write('InputGunX = "MOUSE_XAXIS,JOY1_XAXIS"    ; analog, full X axis\n')
    log.write('InputGunY = "MOUSE_YAXIS,JOY1_YAXIS"    ; analog, full Y axis\n')
    log.write('InputTrigger = "KEY_A,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['b'].id)+',MOUSE_LEFT_BUTTON"\n')
    log.write('InputOffscreen = "KEY_S,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['a'].id)+',MOUSE_RIGHT_BUTTON"    ; point off-screen\n')
    log.write('InputAutoTrigger = 0                    ; automatic reload when off-screen\n')
    log.write('InputGunLeft2 = "NONE"\n')
    log.write('InputGunRight2 = "NONE"\n')
    log.write('InputGunUp2 = "NONE"\n')
    log.write('InputGunDown2 = "NONE"\n')
    log.write('InputGunX2 = "JOY2_XAXIS"\n')
    log.write('InputGunY2 = "JOY2_YAXIS"\n')
    log.write('InputTrigger2 = "JOY2_BUTTON'+escapedPlayerButton('b',secondPlayerPad,1)+'"\n')
    log.write('InputOffscreen2 = "JOY2_BUTTON'+escapedPlayerButton('a',secondPlayerPad,2)+'"\n')
    log.write('InputAutoTrigger2 = 0\n')
    log.write('\n')
    log.write('; Analog guns (Ocean Hunter, LA Machineguns)\n')
    log.write('InputAnalogGunLeft = "KEY_LEFT"               ; digital, move gun left\n')
    log.write('InputAnalogGunRight = "KEY_RIGHT"             ; digital, move gun right\n')
    log.write('InputAnalogGunUp = "KEY_UP"                   ; digital, move gun up\n')
    log.write('InputAnalogGunDown = "KEY_DOWN"               ; digital, move gun down\n')
    log.write('InputAnalogGunX = "MOUSE_XAXIS,JOY1_XAXIS"    ; analog, full X axis\n')
    log.write('InputAnalogGunY = "MOUSE_YAXIS,JOY1_YAXIS"    ; analog, full Y axis\n')
    log.write('InputAnalogTriggerLeft = "KEY_A,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['b'].id)+',MOUSE_LEFT_BUTTON"\n')
    log.write('InputAnalogTriggerRight = "KEY_S,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['a'].id)+',MOUSE_RIGHT_BUTTON"\n')
    log.write('InputAnalogGunLeft2 = "NONE"\n')
    log.write('InputAnalogGunRight2 = "NONE"\n')
    log.write('InputAnalogGunUp2 = "NONE"\n')
    log.write('InputAnalogGunDown2 = "NONE"\n')
    log.write('InputAnalogGunX2 = "NONE"\n')
    log.write('InputAnalogGunY2 = "NONE"\n')
    log.write('InputAnalogTriggerLeft2 = "NONE"\n')
    log.write('InputAnalogTriggerRight2 = "NONE"\n')
    log.write('\n')
    log.write('; Ski Champ controls\n')
    log.write('InputSkiLeft = "KEY_LEFT"\n')
    log.write('InputSkiRight = "KEY_RIGHT"\n')
    log.write('InputSkiUp = "KEY_UP"\n')
    log.write('InputSkiDown = "KEY_DOWN"\n')
    log.write('InputSkiX = "JOY1_XAXIS"\n')
    log.write('InputSkiY = "JOY1_YAXIS"\n')
    log.write('InputSkiPollLeft = "KEY_A,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['b'].id)+'"\n')
    log.write('InputSkiPollRight = "KEY_S,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['a'].id)+'"\n')
    log.write('InputSkiSelect1 = "KEY_Q,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['y'].id)+'"\n')
    log.write('InputSkiSelect2 = "KEY_W,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['x'].id)+'"\n')
    log.write('InputSkiSelect3 = "KEY_E,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['pageup'].id)+'"\n')
    log.write('\n')
    log.write('; Magical Truck Adventure controls\n')
    log.write('InputMagicalLeverUp1 = "KEY_UP"\n')
    log.write('InputMagicalLeverDown1 = "KEY_DOWN"\n')
    log.write('InputMagicalLeverUp2 = "NONE"\n')
    log.write('InputMagicalLeverDown2 = "NONE"\n')
    log.write('InputMagicalLever1 = "JOY1_YAXIS"\n')
    log.write('InputMagicalLever2 = "JOY2_YAXIS"\n')
    log.write('InputMagicalPedal1 = "KEY_A,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['b'].id)+'"\n')
    log.write('InputMagicalPedal2 = "KEY_S,JOY2_BUTTON'+escapedPlayerButton('b',secondPlayerPad,1)+'"\n')
    log.write('\n')
    log.write('; Sega Bass Fishing / Get Bass controls\n')
    log.write('InputFishingRodLeft = "KEY_LEFT"\n')
    log.write('InputFishingRodRight = "KEY_RIGHT"\n')
    log.write('InputFishingRodUp = "KEY_UP"\n')
    log.write('InputFishingRodDown = "KEY_DOWN"\n')
    log.write('InputFishingStickLeft = "KEY_A"\n')
    log.write('InputFishingStickRight = "KEY_D"\n')
    log.write('InputFishingStickUp = "KEY_W"\n')
    log.write('InputFishingStickDown = "KEY_S"\n')
    log.write('InputFishingRodX = "JOY1_XAXIS"\n')
    log.write('InputFishingRodY = "JOY1_YAXIS"\n')
    log.write('InputFishingStickX = "JOY1_RXAXIS"\n')
    log.write('InputFishingStickY = "JOY1_RYAXIS"\n')
    log.write('InputFishingReel = "KEY_SPACE,JOY1_ZAXIS_POS"\n')
    log.write('InputFishingCast = "KEY_Z,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['b'].id)+'"\n')
    log.write('InputFishingSelect = "KEY_X,JOY1_BUTTON'+translateInput(firstPlayerPad.inputs['a'].id)+'"\n')
    log.write('\n')    
    
    log.close()