# Use case configuration for the Anbernic RG 55G1
#
# 2x awinic aw88166 speakers on Senary MI2S and HP via SW.

Syntax 4

SectionUseCase."HiFi" {
	File "/Anbernic/RG55G1/HiFi.conf"
	Comment "HiFi quality Music."
}

BootSequence [
	cset "name='Left PCM Playback Volume' 511"
	cset "name='Right PCM Playback Volume' 511"
	cset "name='RX_RX0 Digital Volume' 84"
	cset "name='RX_RX1 Digital Volume' 84"
	cset "name='HPHL Volume' 20"
	cset "name='HPHR Volume' 20"
	cset "name='ADC2 Volume' 10"
]

LibraryConfig.remap.Config {

	ctl.default.map {
		"name='Speaker Volume'" {
			"name='Left PCM Playback Volume'".vindex.0 0
			"name='Right PCM Playback Volume'".vindex.1 0
		}
	}
}

Include.card-init.File "/lib/card-init.conf"
Include.ctl-remap.File "/lib/ctl-remap.conf"
Include.wcd-init.File "/codecs/wcd937x/init.conf"
