#!/bin/sh

CONFIGFILE=/boot/config.txt
CONFIGMODIFIED=0

setup="# ====== GPi Case setup section =====
display_lcd_rotate=1
extra_transpose_buffer=2
dtoverlay=dpi24_gpicase
overscan_left=0
overscan_right=0
overscan_top=0
overscan_bottom=0
framebuffer_width=320
framebuffer_height=240
enable_dpi_lcd=1
display_default_lcd=1
dpi_group=2
dpi_mode=87
dpi_output_format=0x6016
dpi_timings=240 1 38 10 20 320 1 20 4 4 0 0 0 60 0 6400000 1
dtoverlay=pwm-2chan,pin=18,func=2,pin2=19,func2=2
disable_pvt=1
disable_audio_dither=1
dtoverlay=pwm-audio-pi-zero_gpicase
# ====== GPi Case toggle section =====
# This will preserve always the default GPi settings if enabled, needed if some values were wrong setted by user"

    echo "${setup}" | (
	while read LINE
	do
	    if ! grep -qE "^${LINE}$" "${CONFIGFILE}"
	    then
		test "${CONFIGMODIFIED}" = 0 && mount -o remount,rw /boot
		echo "${LINE}" >> "${CONFIGFILE}"
		CONFIGMODIFIED=1
	    fi
	done

	#Reboot if there was a change in line
	if test "${CONFIGMODIFIED}" = 1
	then
            echo "Rebooting now..."
            shutdown -r now
	fi
    )

exit 0
