#!/bin/bash

MODEL=$(batocera-model)

start() {
    if [[ "$MODEL" == "Gameforce_Ace" ]]; then
        echo "Setting Output 2 volume for GameForce ACE"
        amixer -c 0 set 'Output 2' 18
    fi
}

stop() {
    :
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
