LABEL BATOCERA
  LINUX /linux
  INITRD /initrd.lz4
  FDTDIR /
  ## FDT: don't forget the leading slash, remove all symbols after .dtb (including whitespace)
  # FDT /your-custom-devicetree.dtb
  FDTOVERLAYS /overlays/mipi-panel.dtbo
  APPEND label=BATOCERA console=ttyS2,1500000 console=tty3 quiet loglevel=0 consoleblank=0 vt.global_cursor_default=0 uboot.hwid_adc=${hwid_adc}
