#!/bin/bash

test "$1" != "start" && exit 0
MODEL=$(cat /sys/firmware/devicetree/base/model)
test "${MODEL}" != "Anbernic RG552" && exit 0

# wifi is very unstable to load if loaded too early
# reload it lately. this is a workaround. this is only for rg552.
rmmod rtl8xxxu
modprobe rtl8xxxu
