name: Report a bug
description: Report a bug and help us improve Batocera.
body:
  - type: markdown
    attributes:
      value: "## Welcome!"
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug!
        Bug reports are NOT for feature requests or help with coding / compiling.
        If you need real-time help, join us on Discord - https://discord.gg/rJvJrEpE
  - type: input
    id: batocera_build
    attributes:
      label: Batocera build version
      description: Batocera version used (be precise if using butterfly).
      placeholder: Current stable is v38 2023/10/14 21:43
    validations:
      required: true
  - type: input
    id: arch
    attributes:
      label: Your architecture
      description: Architecture on which Batocera is running.
      placeholder: Rasperry Pi 4 B, PC, Steam Deck, Odroid C4, Orange Pi 5, etc.
    validations:
      required: true
  - type: dropdown
    id: gpu_type
    attributes:
      label: Your Graphic Processor Unit (GPU)
      description: Is your GPU integrated or dedicated?
      options:
        - Integrated (e.g. Intel HD 550; RX Vega 8)
        - Dedicated (e.g. GTX 1050; Radeon R9 380)
  - type: dropdown
    id: gpu_brand
    attributes:
      label: Graphical brand
      description: What is the brand of your GPU?
      options:
        - Intel
        - Nvidia
        - AMD
    validations:
      required: false
  - type: textarea
    id: issue_description
    attributes:
      label: Issue description
      description: A laconic explanation of the issue. Keep this to a single sentence.
      placeholder: I have a black screen after the splash screen when booting Batocera.
    validations:
      required: true
  - type: textarea
    id: expected_result
    attributes:
      label: Expected result
      description: What the intended behavior should have been instead.
    validations:
      required: false
  - type: textarea
    id: reproduce_issue
    attributes:
      label: Reproduction steps
      description: |
        1. Note the steps in the order they are required to be done in order to successfully reproduce this issue.
        2. Include any "but only when" conditions you have discovered.
        3. Describe what happens when the issue occurs, anything to look out for, anything to check the issue has indeed occurred.
    validations:
      required: true
  - type: textarea
    id: logs_and_data
    attributes:
      label: Logs and data
      description: Provide all the relevant logs and information relevant to the issue. Include any information about the stable versions of Batocera the issue is present/not present on, whether the issue is present on a fresh install or not, etc.
      placeholder: Be very clear.
    validations:
      required: false
