################################################################################
#
# openxr-sdk
#
################################################################################
# Version: Commits on Oct 8, 2026
OPENXR_SDK_VERSION = 2b99fec95e9cdf352c1a98e9cb23bf4def1cf8e6
OPENXR_SDK_SITE = $(call github,KhronosGroup,OpenXR-SDK-Source,$(OPENXR_SDK_VERSION))
OPENXR_SDK_LICENSE = Apache-2.0
OPENXR_SDK_LICENSE_FILES = LICENSE
OPENXR_SDK_DEPENDENCIES = host-python3
OPENXR_SDK_SUPPORTS_IN_SOURCE_BUILD = NO
OPENXR_SDK_INSTALL_STAGING = YES

OPENXR_SDK_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
OPENXR_SDK_CONF_OPTS += -DBUILD_WITH_SYSTEM_JSONCPP=OFF
OPENXR_SDK_CONF_OPTS += -DBUILD_TESTS=OFF
OPENXR_SDK_CONF_OPTS += -DBUILD_CONFORMANCE_TESTS=OFF
OPENXR_SDK_CONF_OPTS += -DBUILD_API_LAYERS=OFF
OPENXR_SDK_CONF_OPTS += -DCMAKE_DISABLE_FIND_PACKAGE_OpenGL=ON
OPENXR_SDK_CONF_OPTS += -DCMAKE_DISABLE_FIND_PACKAGE_OpenGLES=ON
OPENXR_SDK_CONF_OPTS += -DDYNAMIC_LOADER=ON

$(eval $(cmake-package))
