#!/bin/bash

# hide mouse cursor
unclutter --noevents -b

# disable dpms to prevent screen from blanking
xset -dpms
xset s off

# uncomment to allow coredumps for ES
# ulimit -c unlimited

openbox --config-file /etc/openbox/rc.xml --startup "emulationstation-standalone"
