#!/bin/bash

NAME="S92switch"
RUN="/usr/bin/rpi_gpioswitch"
BTD_PID=$(ps -eo pid,args | grep "/bin/bash $RUN" | grep -v grep | awk '{print $1}')

# Carry out specific functions when asked to by the system
case "$1" in
    start)
	systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/batoceraSettings.py"
	powerswitch="`$systemsetting  -command load -key system.power.switch`"
	case "${powerswitch}" in
	    ATX_RASPI_R2_6|MAUSBERRY|REMOTEPIBOARD_2003|REMOTEPIBOARD_2005|WITTYPI|PIN56ONOFF|PIN56PUSH|PIN356ONOFFRESET|ONOFFSHIM)
		nice -n 19 $RUN start&
		;;
	esac
    ;;
    stop)
        if [ ! -z "$BTD_PID" ]; then
            kill $BTD_PID
            $RUN stop
        elif test -e "/tmp/poweroff.please"; then
            $RUN stop
        fi
    ;;
    status)
        if [ ! -z "$BTD_PID" ]; then
            echo "Service rpi_gpioswitch ["$BTD_PID"] [ OK ]"
        else
            echo "Service rpi_gpioswitch [ KO ]"
        fi
    ;;
    *)
        echo "Usage: /etc/init.d/S92switch {start | stop | status}"
        exit 1
    ;;
esac

exit 0
