#!/bin/bash

NAME="S92switch"
RUN="/usr/bin/rpi_gpioswitch"
BTD_PID=$(pgrep -f "/bin/bash $RUN")

#Add new devices here and modify /usr/bin/rpi_gpioswitch, too
devices="ATX_RASPI_R2_6 REMOTEPIBOARD_2003 REMOTEPIBOARD_2005 MAUSBERRY WITTYPI ONOFFSHIM RETROFLAG \
         RETROFLAG_ADV RETROFLAG_GPI KINTARO PIN56ONOFF PIN56PUSH PIN356ONOFFRESET ARGONONE"

# Read current config, if no key is set in batocera.conf then try to use
# default value setted by udev-rule
powerswitch="$(batocera-settings --command load --key system.power.switch)"
if [ $? -ne 0 ] && [ -f /var/run/powerswitch-by-udevrule ]; then
    powerswitch="$(cat /var/run/powerswitch-by-udevrule)"
fi
# Read if a GPIO joypad is needed (to init on selected archs)
gpiopad="$(batocera-settings --command load --key controllers.gpio.enabled)"

# Carry out specific functions when asked to by the system
case "$1" in
    start)
        if [ "$gpiopad" == 1 ]; then
            case $(cat /usr/share/batocera/batocera.arch) in
                rpi4)
                    /usr/bin/rpi-gpio-init
                ;;
            esac
	fi
        for i in $devices; do
            if [ "$i" == "$powerswitch" ]; then
                $RUN start "$powerswitch" &
                break
            fi
        done
    ;;

    stop)
        if [ -n "$BTD_PID" ]; then
            kill "$BTD_PID"
            $RUN stop "$powerswitch"
        elif [ -e "/tmp/shutdown.please" ] || [ -e "/tmp/poweroff.please" ]; then
            $RUN stop "$powerswitch"
        fi
    ;;

    status)
        if [ -n "$BTD_PID" ]; then
            echo "Service rpi_gpioswitch [$BTD_PID] [ OK ]"
        else
            echo "Service rpi_gpioswitch [ KO ]"
        fi
    ;;

    setup)
        rpi_gpioswitch
    ;;

    *)
        echo "Usage: /etc/init.d/S92switch {start | stop | status | setup}"
        exit 1
    ;;
esac

exit 0
