def ioctl_devinfo(fd: int, /) -> tuple[int, int, int, int, str, str, str]: ...
def ioctl_capabilities(fd: int, /) -> dict[int, list[int | tuple[int, tuple[int, int, int, int, int, int]]]]: ...
def ioctl_EVIOCGABS(fd: int, ev_code: int, /) -> tuple[int, int, int, int, int, int]: ...
def ioctl_EVIOCSABS(fd: int, ev_code: int, absinfo: tuple[int, int, int, int, int, int], /) -> None: ...
def ioctl_EVIOCGREP(fd: int, /) -> tuple[int, int]: ...
def ioctl_EVIOCSREP(fd: int, delay: int, period: int, /) -> int: ...
def ioctl_EVIOCGVERSION(fd: int, /) -> int: ...
def ioctl_EVIOCGRAB(fd: int, flag: int, /) -> None: ...
def ioctl_EVIOCGEFFECTS(fd: int, /) -> int: ...
def ioctl_EVIOCG_bits(fd: int, evtype: int, /) -> list[int]: ...
def ioctl_EVIOCGPROP(fd: int, /) -> list[int]: ...
def device_read(fd: int, /) -> tuple[int, int, int, int, int] | None: ...
def device_read_many(fd: int, /) -> tuple[tuple[int, int, int, int, int], ...]: ...
def upload_effect(fd: int, effect_data: bytes, /) -> int: ...
def erase_effect(fd: int, ff_id: int, /) -> None: ...
