from typing import Final

maxnamelen: Final[int]

def open(devnode: str, /) -> int: ...
def setup(
    fd: int,
    name: str,
    vendor: int,
    product: int,
    version: int,
    bustype: int,
    absinfo: list[list[int]],
    max_effects: int,
    /,
) -> None: ...
def create(fd: int, /) -> None: ...
def close(fd: int, /) -> None: ...
def write(fd: int, type: int, code: int, value: int, /) -> None: ...
def enable(fd: int, type: int, code: int, /) -> None: ...
def set_phys(fd: int, phys: str, /) -> None: ...
def get_sysname(fd: int, /) -> str: ...
def set_prop(fd: int, prop: int, /) -> None: ...
