import asyncio
from collections.abc import Iterator
from typing import Self

from . import eventio
from .eventio import EvdevError as EvdevError
from .events import InputEvent

class ReadIterator:
    current_batch: Iterator[InputEvent]
    device: EventIO
    def __init__(self, device: EventIO) -> None: ...
    def __iter__(self) -> Self: ...
    def __next__(self) -> InputEvent: ...
    def __aiter__(self) -> Self: ...
    def __anext__(self) -> asyncio.Future[InputEvent]: ...

class EventIO(eventio.EventIO):
    def async_read_one(self) -> asyncio.Future[InputEvent | None]: ...
    def async_read(self) -> asyncio.Future[Iterator[InputEvent]]: ...
    def async_read_loop(self) -> ReadIterator: ...
    def close(self) -> None: ...
