from collections.abc import Iterator

from .events import HasEvent, InputEvent

class EvdevError(Exception): ...

class EventIO:
    fd: int
    path: str | bytes
    def fileno(self) -> int: ...
    def read_loop(self) -> Iterator[InputEvent]: ...
    def read_one(self) -> InputEvent | None: ...
    def read(self) -> Iterator[InputEvent]: ...
    def write_event(self, event: InputEvent | HasEvent) -> None: ...
    def write(self, etype: int, code: int, value: int) -> None: ...
    def syn(self) -> None: ...
    def close(self) -> None: ...
