import os
import re
from _typeshed import StrOrBytesPath
from collections.abc import Iterator, Mapping, Sequence
from typing import overload

from .device import AbsInfo
from .events import AbsEvent, InputEvent, KeyEvent, RelEvent, SynEvent

def list_devices(input_device_dir: str | os.PathLike[str] = '/dev/input') -> list[str]: ...
def is_device(fn: StrOrBytesPath) -> bool: ...
def categorize(event: InputEvent) -> InputEvent | KeyEvent | RelEvent | AbsEvent | SynEvent: ...
def resolve_ecodes_dict(
    typecodemap: Mapping[int, Sequence[int | tuple[int, AbsInfo]]], unknown: str = '?'
) -> Iterator[
    tuple[
        tuple[str | tuple[str, ...], int],
        list[tuple[str | tuple[str, ...], int] | tuple[tuple[str | tuple[str, ...], int], AbsInfo]],
    ]
]: ...
@overload
def resolve_ecodes(  # pyright: ignore[reportOverlappingOverload]
    ecode_dict: Mapping[int, str | tuple[str, ...]], ecode_list: Sequence[int], unknown: str = ...
) -> list[tuple[str | tuple[str, ...], int]]: ...
@overload
def resolve_ecodes(
    ecode_dict: Mapping[int, str | tuple[str, ...]], ecode_list: Sequence[tuple[int, AbsInfo]], unknown: str = ...
) -> list[tuple[tuple[str | tuple[str, ...], int], AbsInfo]]: ...
@overload
def resolve_ecodes(
    ecode_dict: Mapping[int, str | tuple[str, ...]], ecode_list: Sequence[int | tuple[int, AbsInfo]], unknown: str = ...
) -> list[tuple[str | tuple[str, ...], int] | tuple[tuple[str | tuple[str, ...], int], AbsInfo]]: ...
def find_ecodes_by_regex(regex: str | re.Pattern[str]) -> dict[int, list[int]]: ...
