#!/bin/sh
#
# Watch for network adapter
#

case "$1" in
  start)
	/bin/echo /usr/bin/checketh.sh > /proc/sys/kernel/hotplug
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

