#!/bin/bash

do_video()
{
    omx_fnt=""
    omx_opt="--no-keys --layer=10000 --aspect-mode=fill"
    omx_srt="--no-ghost-box --lines=1 --align=left $omx_fnt --font-size=20 --subtitles=/recalbox/system/resources/splash/recalboxintro.srt"
    omxplayer $omx_opt $omx_srt $1
    # Will be replaced when the video will support --loop
    while true; do omxplayer $omx_opt $2; done
}

do_start ()
{
    video1="/recalbox/system/resources/splash/recalboxintro01.mp4"
    video2="/recalbox/system/resources/splash/recalboxintro02.mp4"
    if [[ -f $video1 && -f $video2 ]]; then
        do_video $video1 $video2 &
        pid=$!
        # Wait for emulationstation, but not more than 15 seconds
        count=0
        while [[ ! -f "/tmp/emulationstation.ready" && $count -lt 15 ]] ; do
            sleep 1
            ((count++))
        done
        # Ready flag set or timeout occured; kill all video processes.
        kill $pid
        killall omxplayer.bin
    fi
    fbv -f -i /recalbox/system/resources/splash/logo-version.png
}

case "$1" in
    start)
        do_start &
        ;;
    stop)
	   ;;
    restart|reload)
	   ;;
    *)
esac

exit $?
