#!/bin/sh

if test "$1" != "start"
then
  exit 0
fi

# sixad
mkdir -p /var/lib/sixad/profiles
cp /etc/sixad.profile /var/lib/sixad/profiles/default

# custom network config
mkdir -p "/var/lib/connman"
ln -sf "/recalbox/share/system/network-connman.config" "/var/lib/connman/recalbox-custom.config"
ln -sf "/boot/network-connman.config"                  "/var/lib/connman/recalbox-boot-custom.config"

# bluetooth
mkdir -p /var/lib/bluetooth

# samba
mkdir -p /var/lib/samba/private
chmod 0755 /var/lib/samba
mkdir -p /var/cache

# dbus
mkdir -p /var/lib/dbus

# usbmount
mkdir -p /var/run

# Udev custom rules
mkdir -p /run/udev/

# xorg
mkdir -p /var/log
