#!/bin/sh

# sixad
mkdir -p /var/lib/sixad/profiles
cp /etc/sixad.profile /var/lib/sixad/profiles/default

# ethX and wifi
mkdir -p /var/network
cp /etc/network/interfaces.base /var/network/interfaces

# wifi
cp /etc/wpa_supplicant/wpa_supplicant.conf /var/lib/wpa_supplicant.conf

# bluetooth
mkdir -p /var/lib/bluetooth

# samba
mkdir -p /var/lib/samba/private
chmod 0755 /var/lib/samba

# dbus
mkdir -p /var/lib/dbus

# usbmount
mkdir -p /var/run

# Udev custom rules
mkdir -p /run/udev/
