#!/bin/bash

if test "$1" != "start"
then
  exit 0
fi

IN=/recalbox/share_init
OUT=/recalbox/share
# force the creation of some directories
for DIR in cheats \
           system/.cache \
           system/.config/lirc \
           system/.emulationstation/themes \
           system/bluetooth \
           system/configs \
           system/logs
do
    if test ! -e "$OUT""/""$DIR"
    then
        mkdir -p "$OUT""/""$DIR"
    fi
done

# directories / files to copy when initializing the user data
#
# NO UPDATE IS POSSIBLE ON THESE DIRECTORIES WHEN RECALBOX IS UPDATED
#
# there are almost empty, it's just for the structure
# the user can delete the directory, it will recreate the structure
# the user can delete files, files will not be recreated
for FILE in music bios extractions kodi saves screenshots \
            system/.config/lirc/lircd.conf \
            system/.emulationstation/{es_input.cfg,es_settings.cfg} \
            system/{.hatari,.kodi} \
            system/configs/{fba,moonlight,mupen64,ppsspp,reicast,retroarch,shadersets,xarcade2jstick,dosbox} \
            system/recalbox.conf \
            bios/mame2003
do
    # not wanted for kodi
    test -e "$IN""/""$FILE" && test ! -e "$OUT""/""$FILE" && cp -r "$IN""/""$FILE" "$OUT""/""$FILE"
done

# directories to force directories exists
# files are linked
#
# ONLY NEW DIRECTORIES ARE UPDATED WHEN RECALBOX IS UPDATED
#
# the user can't delete any directory, otherwise, it will recreate it, with link inside
# the user can delete links and add its own files
# to reset the directory or update it, the user has to remove the directory (we are unable to differenciate new files from recalbox update from a file removed by the user)
for DIR in roms roms/mame/mame2003
do
    if test ! -e "$OUT""/""$DIR"
    then
	if mkdir "$OUT""/""$DIR"
	then
	    find "$IN""/""$DIR" -mindepth 1 -maxdepth 1 -type d |
		while read SUBDIR
		do
		    BNAME=$(basename "$SUBDIR")
		    TDIR="$OUT""/""$DIR""/""$BNAME"
		    if test ! -e "$TDIR" # ASSUME THAT PARENTS ARE LISTED BEFORE CHILDREN
		    then
			cp -r "$SUBDIR" "$TDIR"
		    fi
		done
	fi
    fi
done

# ssh : create the ssh key while the -R option of dropbear try a chown or an operation which is not permitted on fat32
if ! test -e /recalbox/share/system/ssh
then
    mkdir -p /recalbox/share/system/ssh
    dropbearkey -t ecdsa -f /recalbox/share/system/ssh/dropbear_ecdsa_host_key
    dropbearkey -t rsa   -f /recalbox/share/system/ssh/dropbear_rsa_host_key
    dropbearkey -t dss   -f /recalbox/share/system/ssh/dropbear_dss_host_key
fi

# bluetooth : copy the bluetooth files stored in /:/_/ (because of vfat)
ls "/recalbox/share/system/bluetooth" |
    while read X
    do
	UX=$(echo "${X}" | sed -e s+"@"+":"+g)
	cp -r "/recalbox/share/system/bluetooth/${X}" "/var/lib/bluetooth/${UX}"
    done
# udev : create a link for rules persistance
mkdir -p /recalbox/share/system/udev/rules.d
rm -rf /run/udev/rules.d
ln -s /recalbox/share/system/udev/rules.d/ /run/udev/

# END
