#!/bin/sh

IN=/recalbox/share_init
OUT=/recalbox/share

# force the creation of some directories
for DIR in cheats system system/.emulationstation system/.emulationstation/themes system/bluetooth system/logs system/ssh system/configs
do
    if test ! -e "$OUT""/""$DIR"
    then
	mkdir "$OUT""/""$DIR"
    fi
done

# directories to copy when initializing the user data
#
# NO UPDATE IS POSSIBLE ON THESE DIRECTORIES WHEN RECALBOX IS UPDATED
#
# there are almost empty, it's just for the structure
# the user can delete the directory, it will recreate the structure
# the user can delete files, files will not be recreated
for DIR in bios extractions kodi saves screenshots system/.kodi system/configs/{fba,mupen64,retroarch,shadersets}
do
    if test ! -e "$OUT""/""$DIR"
    then
	cp -r "$IN""/""$DIR" "$OUT""/""$DIR"
    fi
done

# directories to force directories exists
# files are linked
#
# ONLY NEW DIRECTORIES ARE UPDATED WHEN RECALBOX IS UPDATED
#
# the user can't delete any directory, otherwise, it will recreate it, with link inside
# the user can delete links and add its own files
# to reset the directory or update it, the user has to remove the directory (we are unable to differenciate new files from recalbox update from a file removed by the user)
for DIR in roms
do
    if test ! -e "$OUT""/""$DIR"
    then
	if mkdir "$OUT""/""$DIR"
	then
	    find "$IN""/""$DIR" -type d -mindepth 1 -maxdepth 1 |
		while read SUBDIR
		do
		    BNAME=$(basename "$SUBDIR")
		    TDIR="$OUT""/""$DIR""/""$BNAME"
		    if test ! -e "$TDIR" # ASSUME THAT PARENTS ARE LISTED BEFORE CHILDREN
		    then
			cp -r "$SUBDIR" "$TDIR"
		    fi
		done
	fi
    fi
done

# special directories

# NO UPDATE IS POSSIBLE ON THESE FILES WHEN RECALBOX IS UPDATED
for FILE in system/.emulationstation/{es_input.cfg,es_settings.cfg} system/recalbox.conf
do
    test ! -e "$OUT""/""$FILE" && cp "$IN""/""$FILE" "$OUT""/""$FILE"
done

# ssh : create the ssh key while the -R option of dropbear try a chown or an operation which is not permitted on fat32
if ! test -e /recalbox/share/system/ssh/dropbear_ecdsa_host_key
   then
       dropbearkey -t ecdsa -f /recalbox/share/system/ssh/dropbear_ecdsa_host_key
fi

# END
