#!/bin/sh
#
#

log=/root/recalbox.log
essetting=/recalbox/scripts/essetting.sh

case "$1" in
  start)
	settings_lang="`$essetting get Lang`"
        echo "`date` : starting emulationstation with lang = $settings_lang" >> $log
        command="HOME=/root LANG=\"${settings_lang}.UTF-8\" SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2.so SDL_NOMOUSE=1 /usr/bin/emulationstation"
        echo "`date` : Starting emulationstation with command : " >> $log
        echo "$command" >> $log
        eval $command >> $log &
	;;
  stop)
	killall emulationstation
	;;
  restart|reload)
        "$0" stop
        "$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


