#!/bin/sh
#
#

case "$1" in
  start)
	/recalbox/scripts/emulationstationLauncher.sh &
	;;
  stop)
	killall emulationstation
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

