#!/bin/sh
#
# Watch for network adapter
#

case "$1" in
  start)
	bluetoothd -u
	sleep 2
	killall bluetoothd
	sixad-bin 0 0 0 &
	;;
  stop)
	killall sixad-bin
	killall sixad-sixaxis
	;;
  restart|reload)
        "$0" stop
        "$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


