#!/bin/sh
#
# Start the wifi network if it has been configured
#

case "$1" in
  start)
	sleep 2
        /recalbox/scripts/recalbox-config.sh ethernet start
        /recalbox/scripts/recalbox-config.sh wifi start
        ;;
  stop)
        echo -n "Stopping network..."
        /sbin/ifdown -a
        killall wpa_supplicant
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

