#!/bin/sh
#
# ReStart the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
        sleep 2
        /sbin/ifdown -a
        echo "ReStarting network..."
        wpa_supplicant -iwlan0 -c/etc/wpa_supplicant/wpa_supplicant.conf &
        sleep 5
        /sbin/ifup -a
        ;;
  stop)
        echo -n "Stopping network..."
        /sbin/ifdown -a
        killall wpa_supplicant
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

