#!/bin/sh
# Start/stop recalbox-manager

PIDFILE=/var/run/recalbox-manager.pid
SITEPATH=/usr/recalbox-manager
NAME="S94manager"
RUN_AS=`id -u root`
CMD=/usr/recalbox-manager/manage.py
OPTS="runserver 0.0.0.0:80 --settings=project.settings_production --noreload"

systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/recalboxSettings.pyc"

do_start() {
    start-stop-daemon --start --background --user $RUN_AS --pidfile $PIDFILE --make-pidfile --chuid $RUN_AS --startas $CMD -- $OPTS
}

do_stop() {
    start-stop-daemon --stop --pidfile $PIDFILE
}


case "$1" in
start)
    enabled="`$systemsetting  -command load -key system.manager.enabled`"
    if [ "$enabled" != "0" ];then
        recallog "Starting $NAME"
        do_start
    else
        recallog "Will not start $NAME : system.manager.enabled is set to 0"
    fi

    enabled="`$systemsetting  -command load -key system.security.enabled`"
    if [ "$enabled" == "1" ];then
	recallog "Will not start $NAME : system.security.enabled is set to 1"
    fi
    ;;
stop)
    recallog "Stopping $NAME"
    do_stop
    ;;
restart)
    recallog "Restarting $NAME"
    do_stop
    do_start
    ;;
*)
    echo "Usage: /etc/init.d/S94Manager {start|stop|restart}"
    exit 2
    ;;
esac
exit 0

