#!/bin/sh

#
# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
    [ ! -f "$i" ] && continue

	mkdir -p /var/run/
    echo $(date +%Y-%m-%d_%H:%I:%S)": ${i} - starting" >> /var/run/boot.log

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
     esac

     echo $(date +%Y-%m-%d_%H:%I:%S)": ${i} - started" >> /var/run/boot.log
done
