#!/bin/sh

if test "$1" != "start"
then
	exit 0
fi

. /etc/init.d/functions

# /userdata partition
PART=$(batocera-part "share_internal")
# boot disk
DISK=$(batocera-part prefix "${PART}")
# mount /userdata
batocera-mount "ext4" 1 ${PART} /userdata

if [ -e /userdata/.please_resize_me ] ; then
	rm -f /userdata/.please_resize_me
	sync

	hidecursor

	# get storage partition start
	PART_START=$(parted -s -m ${DISK} unit b print 2>/dev/null | grep -v ^/dev | grep -v BYT | grep ^2: |  cut -f2 -d ":")
	if [ ! -z ${PART_START} ] ; then
		umount ${PART}

		echo "PARTITION RESIZING IN PROGRESS" &>/dev/tty1
		echo "" &>/dev/tty1
		echo "Please do not reboot or turn off your device!" &>/dev/tty1
		echo "" &>/dev/tty1

		# fix any minor issues, such as gpt header not at end of disk
		StartProgress spinner "Checking layout...   " "sgdisk -e ${DISK} &>/dev/null" &>/dev/tty1

		StartProgress spinner "Deleting /userdata... " "parted -s -m ${DISK} rm 2 &>/dev/null" &>/dev/tty1
		StartProgress spinner "Creating /userdata... " "parted -s -m ${DISK} unit b mkpart primary ${PART_START} 100% &>/dev/null" &>/dev/tty1
		StartProgress spinner "Checking /userdata... " "e2fsck -f -p ${PART} &>/dev/null" &>/dev/tty1
		StartProgress spinner "Resizing /userdata... " "resize2fs ${PART} &>/dev/null" &>/dev/tty1

		StartProgress countdown "Rebooting in 5s... " 5 "NOW" &>/dev/tty1
		reboot -f &>/dev/null
	fi
fi

umount /userdata
