#!/bin/bash

# UI Output, dialog valid terminals: linux, vt100, vt102, vt220, xterm, xterm-color
function dialogoutput()
{
    local percent="$1"
    local text="Do not switch off your device!"

    dialog --backtitle "batocera.linux" --title " Resizing Partition " \
           --mixedgauge "$text" 18 50 "$percent" "${arr[@]}" &>/dev/tty1
}

# Executing parameters and watch background pid
# Changes text messages parsed to dialog --mixedgauge
function textoutput()
{
    local cmd="$3"
    local percent="$2"
    local pid ret
    $cmd &>/dev/null &
    ret=$?
    pid=$!
    arr[$1]=7 #msg: In Progress
    dialogoutput "$percent"
    wait $pid
    arr[$1]=$ret #msg: Depends from return value
}


#-------- MAIN --------

if test "$1" != "start"
then
	exit 0
fi

# /userdata partition
PART=$(batocera-part "share_internal")
# boot disk
DISK=$(batocera-part prefix "${PART}")
# mount /userdata
batocera-mount "ext4" 1 ${PART} /userdata

if [ -e /userdata/.please_resize_me ] ; then
    #Colorizing Terminal output
    oldTERM="$TERM"
    TERM=linux

    # Preparing text arrays
    arr=(
         "Removing trigger....." "Pending"
         "Syncing disk data...." "Pending"
         "Unmount /userdata...." "Pending"
         "Checking disk table.." "Pending"
         "Resizing partition..." "Pending"
         "Checking /userdata..." "Pending"
         "Resizing /userdata..." "Pending"
         "Finishing up........." 8
        )

    # fix any minor issues, such as gpt header not at end of disk
    # Function layout:
    # textoutput "arayindex" "start%" "command call"
    for i in 1 3 5 7 9 11 13 15; do
        case $i in
           1) textoutput $i 01 "rm -f /userdata/.please_resize_me";;
           3) textoutput $i 10 "sync";;
           5) textoutput $i 20 "umount /userdata";;
           7) textoutput $i 30 "sgdisk -e ${DISK}";;
           9) textoutput $i 45 "parted -s -m ${DISK} resizepart 2 100%";;
          11) textoutput $i 55 "e2fsck -f -p ${PART}";;
          13) textoutput $i 65 "resize2fs ${PART}";;
          15) textoutput $i 95 "sleep 0.1";;
        esac
    done

    #Cleanup, restore terminal back, set progress of last item to completed and progress to 100%
    arr[-1]=0
    dialogoutput 100
    TERM="$oldTERM"
fi

umount /userdata
