#!/bin/sh

if test "$1" != "start"
then
  exit 0
fi

IN=/usr/share/batocera/datainit
OUT=/userdata
# force the creation of some directories
for DIR in cheats \
           system/.cache \
           system/.config/lirc \
           system/bluetooth \
           system/configs \
           system/pacman \
           system/pacman/db \
           system/pacman/pkg \
           system/pacman/hooks \
           system/logs
do
    if test ! -e "$OUT""/""$DIR"
    then
        mkdir -p "$OUT""/""$DIR"
    fi
done

# directories / files to copy when initializing the user data
#
# NO UPDATE IS POSSIBLE ON THESE DIRECTORIES WHEN batocera.linux IS UPDATED
#
# there are almost empty, it's just for the structure
# the user can delete the directory, it will recreate the structure
# the user can delete files, files will not be recreated
for FILE in music bios extractions kodi library saves screenshots splash \
            system/.config/lirc/lircd.conf \
            system/configs/emulationstation/es_input.cfg \
            system/configs/emulationstation/es_settings.cfg \
            system/.kodi \
            system/configs/amiberry \
            system/configs/cannonball \
            system/configs/dosbox \
            system/configs/mupen64 \
            system/configs/ppsspp \
            system/configs/shadersets \
            system/configs/umtool \
            system/configs/xarcade2jstick \
            system/batocera.conf \
            system/pacman/hooks/batocera-install.hook \
            system/pacman/hooks/batocera-uninstall.hook \
            system/pacman/pacman.conf \
            bios/mame2003
do
    # not wanted for kodi
    test -e "${IN}/${FILE}" && test ! -e "${OUT}/${FILE}" && mkdir -p $(dirname "${OUT}/${FILE}") && cp -r "${IN}/${FILE}" "${OUT}/${FILE}"
done

### specific directories
# decorations - copy only the readme file
mkdir -p "${OUT}/decorations"
test -e "${OUT}/decorations/readme.txt" || cp -r "${IN}/decorations/readme.txt" "${OUT}/decorations/readme.txt"

# themes
mkdir -p "${OUT}/themes"

# directories to force directories exists
# files are linked
#
# ONLY NEW DIRECTORIES ARE UPDATED WHEN batocera.linux IS UPDATED
#
# the user can't delete any directory, otherwise, it will recreate it, with link inside
# the user can delete links and add its own files
# to reset the directory or update it, the user has to remove the directory (we are unable to differenciate new files from batocera.linux update from a file removed by the user)
for DIR in roms roms/mame/mame2003
do
    if mkdir -p "$OUT""/""$DIR"
    then
	find "$IN""/""$DIR" -mindepth 1 -maxdepth 1 -type d |
	    while read SUBDIR
	    do
		BNAME=$(basename "$SUBDIR")
		TDIR="$OUT""/""$DIR""/""$BNAME"
		if test ! -e "$TDIR" # ASSUME THAT PARENTS ARE LISTED BEFORE CHILDREN
		then
		    cp -r "$SUBDIR" "$TDIR"
		fi
	    done
    fi
done

# ssh : create directory, but not keys because lack of entropy, dropbear will automatically generate key on client connection
mkdir -p /userdata/system/ssh

# udev : create a link for rules persistance
mkdir -p /userdata/system/udev/rules.d
rm -rf /run/udev/rules.d
ln -s /userdata/system/udev/rules.d/ /run/udev/

# and add the machine-id
test -e /userdata/system/machine-id || dbus-uuidgen --ensure=/userdata/system/machine-id
ln -sf /userdata/system/machine-id /var/lib/dbus/machine-id
ln -sf /userdata/system/machine-id /etc/machine-id

# save to avoid to redo that all the times
cp /usr/share/batocera/batocera.version /userdata/system/data.version || exit 1

### cleaning old alsa files - 08/07/2021
rm -f /userdata/system/.asoundrc
if test -e /boot/asoundrc
then
    mount -o remount,rw /boot
    rm -f /boot/asoundrc
    mount -o remount,ro /boot
fi
###

exit 0
# END
