#!/bin/sh

case "$1" in
    start)
	systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/recalboxSettings.py"
	enabled="`$systemsetting  -command load -key system.es.atstartup`"
        if [ "$enabled" != "0" ];then
                batocera-resolution minTomaxResolution
		settings_lang="`$systemsetting -command load -key system.language`"
                HOME=/userdata/system LANG="${settings_lang}.UTF-8" SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2.so SDL_VIDEO_EGL_DRIVER=/usr/lib/libGLESv2.so SDL_NOMOUSE=1 /usr/bin/emulationstation &
	fi
	;;
  stop)
	killall emulationstation
	;;
  restart|reload)
        "$0" stop
        "$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

