#!/bin/sh
#
# Auto connect bluetooth controllers
#

systemsetting="batocera-settings"

case "$1" in
  start)
        batocera-bluetooth restore
        enabled="`$systemsetting  -command load -key controllers.bluetooth.enabled`"
        if [ "$enabled" == "1" ];then
		# Start hciattach for applicable boards
		rfkill unblock bluetooth # soft unblock bluetooth
		if [ $(cat /proc/device-tree/compatible | grep -c "rockchip") -ne 0 ]; then
			echo 0 > /sys/class/rfkill/rfkill0/state
			sleep 1
			echo 1 > /sys/class/rfkill/rfkill0/state
			sleep 1
			if [ $(cat /proc/device-tree/compatible | grep -c "rk3399") -ne 0 ]; then
			    /usr/bin/hciattach /dev/ttyS0 bcm43xx 1500000 flow nosleep &
			fi
			if [ $(cat /proc/device-tree/compatible | grep -c "rk3288") -ne 0 ]; then
			    /usr/bin/hciattach -n /dev/ttyS0 rtk_h5 115200 &
			fi
		fi
		if [ $(cat /proc/device-tree/compatible | grep -c "brcm") -ne 0 ]; then
			/usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 & # specific rpi0 and rpi3
	                /usr/bin/hciconfig hci0 up piscan &		 # specific rpi
		fi
		sleep 2 # Give hciattach a few seconds to finish attaching firmware
	        btaddr="`$systemsetting  -command load -key bluetooth.adapter`"
        	settings_version="`$systemsetting -command load -key controllers.ps3.driver`"
        	if [ "$settings_version" != "bluez" ]; then BLUETOOTHD_ARGS="--noplugin=sixaxis"; else  BLUETOOTHD_ARGS="--noplugin=sixaxispair"; fi
		start-stop-daemon -S -q -m -p /var/run/bluetoothd.pid      --exec /usr/libexec/bluetooth/bluetoothd -- $BLUETOOTHD_ARGS &
		if test -n "${btaddr}"
		then
		    start-stop-daemon -S -q -m -p /var/run/bluetooth-agent.pid --exec /usr/bin/batocera-bluetooth-agent -- --device "${btaddr}" &
		else
		    start-stop-daemon -S -q -m -p /var/run/bluetooth-agent.pid --exec /usr/bin/batocera-bluetooth-agent &
		fi
        fi
        ;;
  stop)
	start-stop-daemon -K -q -p /var/run/bluetooth-agent.pid
	start-stop-daemon -K -q -p /var/run/bluetoothd.pid
	killall hciattach
	batocera-bluetooth save
	;;
  restart|reload)
        "$0" stop
        "$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


