#!/bin/bash

NAME="S92switch"
RUN="/recalbox/scripts/powerswitch.sh"
BTD_PID=$(ps -eo pid,args | grep "/bin/bash $RUN" | grep -v grep | awk '{print $1}')

# Carry out specific functions when asked to by the system
case "$1" in
    start)
        nice -n 19 $RUN start&
    ;;
    stop)
        if [ ! -z "$BTD_PID" ]; then
            kill $BTD_PID
            $RUN stop
        elif test -e "/tmp/poweroff.please"; then
            $RUN stop
        fi
    ;;
    status)
        if [ ! -z "$BTD_PID" ]; then
            echo "Service powerswitch.sh ["$BTD_PID"] [ OK ]"
        else
            echo "Service powerswitch.sh [ KO ]"
        fi
    ;;
    *)
        echo "Usage: /etc/init.d/S92switch {start | stop | status}"
        exit 1
    ;;
esac

exit 0
