#!/bin/bash

# custom.sh : deprecated
if test -e "/userdata/system/custom.sh"; then
    #bash interpreter executes scripts without x-flag e.g. for vFAT
    bash /userdata/system/custom.sh $1 &
fi

enabled_services="$(/usr/bin/batocera-settings-get system.services)"

if test -n "${enabled_services}"
then
    for SERVICE in ${enabled_services}
    do
    export __SERVICE__${SERVICE}=1
    done
fi

# user services
# printf removes path data, all non alaphanumeric chars are converted to underscore
pushd /userdata/system/services

find -type f  -printf '%f\n' |
    while read SERVICE
    do
    SANITIZE=${SERVICE//[^0-9A-Za-z]/_}
    if ! test "${SERVICE}" = "${SANITIZE}"; then
        mv "${SERVICE}" "${SANITIZE}"
        SERVICE=${SANITIZE}
    fi
    SRVVAR=__SERVICE__${SERVICE}
    if test "${!SRVVAR}" = 1
    then
        bash "${SERVICE}" "${1}" &
    fi
    done
popd

# system user services
# here the sanitize is not needed, only a-z0-9 allowed for filename
pushd /usr/share/batocera/services

find -type f -printf '%f\n' |
    while read SERVICE
    do
    SRVVAR=__SERVICE__${SERVICE}
    if test "${!SRVVAR}" = 1
    then
        bash "${SERVICE}" "${1}" &
    fi
    done
popd

# wait for scrtips to finish, then shutdown can happen
test "${1}" = "stop" && wait
