#!/bin/bash

# this script can be used by values that can have a default value by board

KEY=$1

# prefer the user value
VALUE=$(batocera-settings-get "${KEY}")
# when value is auto, ignore
if test "$?" = 0 -a "${VALUE}" != "auto"
then
    echo "${VALUE}"
    exit 0
fi

BOARD_MODEL=$(cat /sys/firmware/devicetree/base/model 2>/dev/null | sed -e s+"[^A-Za-z0-9]"+"_"+g)
if test -z "${BOARD_MODEL}"
then
    # give an other chance with dmi
    BOARD_MODEL=$(cat /sys/devices/virtual/dmi/id/board_name 2>/dev/null | sed -e s+"[^A-Za-z0-9]"+"_"+g)
fi

# prefer the board value
if test -e "/usr/share/batocera/sysconfigs/batocera.conf.${BOARD_MODEL}"
then
    VALUE=$(batocera-settings-get -f "/usr/share/batocera/sysconfigs/batocera.conf.${BOARD_MODEL}" "${KEY}")
    # when value is auto, ignore
    if test "$?" = 0 -a "${VALUE}" != "auto"
    then
	echo "${VALUE}"
	exit 0
    fi
fi

# prefer the general value
if test -e "/usr/share/batocera/sysconfigs/batocera.conf"
then
    batocera-settings-get -f "/usr/share/batocera/sysconfigs/batocera.conf" "${KEY}" && exit 0
fi

exit 1
