from __future__ import annotations

from typing import TYPE_CHECKING

from batocera_common.configparser import CaseSensitiveConfigParser
from batocera_common.dataclasses import cached_dataclass, cached_property
from batocera_common.paths import CONFIGS, SAVES, SCREENSHOTS
from batocera_launch import (
    Command,
    Emulator,
    HotkeysContext,
    parse_build_engine_args,
)

if TYPE_CHECKING:
    from pathlib import Path


@cached_dataclass
class EDuke32(Emulator):
    needs_sdl_game_controller_config = True

    @cached_property
    def hotkeygen_context(self) -> HotkeysContext:
        return {
            'name': 'eduke32',
            'keys': {
                'exit': 'killall -9 eduke32; killall -9 fury',
                'menu': 'KEY_ESC',
                'pause': 'KEY_ESC',
                'save_state': 'KEY_F6',
                'restore_state': 'KEY_F9',
                'screenshot': 'KEY_F12',
            },
        }

    @cached_property
    def config_dir(self) -> Path:
        return CONFIGS / self.core

    @cached_property
    def saves_dir(self) -> Path:
        return SAVES / self.core

    async def configure(self) -> Command:
        self.config_dir.mkdir(parents=True, exist_ok=True)

        config_file = self.config_dir / f'{self.core}.cfg'
        script_file = self.config_dir / 'autoexec.cfg'

        if not config_file.exists():
            config_file.touch()

        # https://wiki.eduke32.com/wiki/Configuration_file_options
        # Not all listed options work (e.g. showFPS). Booleans must be integers.
        parser = CaseSensitiveConfigParser(interpolation=None)
        with config_file.open() as config:
            parser.read_file(config)

        if not parser.has_section('Screen Setup'):
            parser.add_section('Screen Setup')
        parser.set('Screen Setup', 'ScreenWidth', str(self.resolution.width))
        parser.set('Screen Setup', 'ScreenHeight', str(self.resolution.height))
        parser.set('Screen Setup', 'ScreenMode', '1')

        with config_file.open('w') as config:
            parser.write(config)

        script_file.write_text(
            '\n'.join(
                [
                    '// This file is automatically generated by batocera-launch',
                    'bind "F12" "screenshot"',
                    f'screenshot_dir "{SCREENSHOTS}"',
                    f'r_showfps "{1 if self.config.show_fps else 0}"',
                    'echo BATOCERA',
                    '',
                ]
            )
        )

        args: list[str | Path] = [self.core, '-cfg', config_file]
        if self.config.get_bool('nologo'):
            args.append('-nologo')

        if self.core == 'fury':
            args.extend(['-gamegrp', self.rom.name, '-j', self.rom.parent])
        else:
            args.extend(parse_build_engine_args(self.rom, existing=args))

        return Command(args)
