#!/bin/bash

test "${ACTION}" = "add" || exit 0
echo "${DEVNAME}" | grep -E "^/dev/input/event[0-9]+$" || exit 0

	# Controller 	Guncon3 		MAP
	# LEFT		TRIGGER			LEFT
	# MIDDLE	A1			MIDDLE
	# RIGHT 	A2 			RIGHT
	# WEST 		A3			BTN_9
	# Z  		B1 			BTN_1
	# TL 		B2 			BTN_4
	# TR 		B3			BTN_10
	# SELECT	C1 			BTN_2
	# START 	C2 			BTN_3
	# TL2 	    	OFFSCREEN 		BTN_11
	# HAT0Y	    	B_HAT_UP		BTN_5
	# HAT0Y 	B_HAT_DOWN		BTN_6
	# HAT0X		B_HAT_LEFT  		BTN_7
	# HAT0X		B_HAT_RIGHT 		BTN_8


DEVHASH=$(echo "${DEVNAME}" | md5sum | cut -c 0-8)
evsieve --input "${DEVNAME}" persist=exit \
	--map btn:west btn:9 \
	--map btn:z btn:1   \
	--map btn:tl btn:4 \
	--map btn:tr btn:tr \
	--map btn:select btn:2 \
	--map btn:start btn:3 \
	--map btn:tl2 btn:tl2 \
	--copy abs:hat0x:38~..~37    btn:7:1     \
        --copy abs:hat0x:~37..38~    btn:7:0     \
        --copy abs:hat0x:~216..217~  btn:8:1     \
        --copy abs:hat0x:217~..~216  btn:8:0     \
        --copy abs:hat0y:38~..~37    btn:5:1     \
        --copy abs:hat0y:~37..38~    btn:5:0     \
        --copy abs:hat0y:~216..217~  btn:6:1     \
        --copy abs:hat0y:217~..~216  btn:6:0     \
	--output name="GunCon3-Gun" >/dev/null 2>"/var/log/guncon3_{DEVHASH}.log" &
