#!/bin/bash

ACTION=$1

ARCH=$(cat /usr/share/batocera/batocera.arch)

get_default_card() {
	# format: sink_id alsa.long_card_name
	case ${ARCH} in
		rockpro64)
			echo "1 HDMI"
			;;
		vim3)
			echo "0 G12-HDMI"
			;;
		*)
		# default to first sink
			echo "0 unknown"
			;;
	esac
}

case "${ACTION}" in
	list)
		echo "auto"
		echo "custom"	
		pactl list sinks | grep alsa.long_card_name | awk '$1 == "alsa.long_card_name" {gsub(/"/, "", $3); print NR-1 " " $3}'
	;;

	get)
		batocera-settings -command load -key audio.device
	;;

	set)
		# auto: get default card per arch
		# custom: do nothing
		# any other: set default sink in pulseadio user file
		ALSA_DEV=$2
		if [ "${ALSA_DEV}" = "custom" ]; then
			exit 0
		fi
		if [ "${ALSA_DEV}" = "auto" ]; then
			ALSA_DEV=$(get_default_card)
		fi
		# get sink_id
		SINK_ID=${ALSA_DEV:0:1}
		PULSE_RUNTIME_PATH=/tmp/pulse pacmd set-default-sink ${SINK_ID}
		# re-route all apps to new sink
		for APP in $(PULSE_RUNTIME_PATH=/tmp/pulse pacmd list-sink-inputs | awk '$1 == "index:" {print $2}'); do
			PULSE_RUNTIME_PATH=/tmp/pulse pacmd move-sink-input ${APP} ${SINK_ID} &>/dev/null
		done
	;;

	test)
		aplay "/usr/share/sounds/Mallet.wav"
	;;
esac
