default:
  options:
    video_threaded: true
    audio_driver: pulse

n64:
  emulator: mupen64plus
  core:     glide64mk2
psp:
  options:
    frameskip: 1
    frameskiptype: 2
    internalresolution: 2

