gamecube:
  emulator: dolphin
  core:     dolphin
  options:
    platform: drm
nds:
  emulator: libretro
  core:     melonds
wii:
  emulator: dolphin
  core:     dolphin
  options:
    platform: drm
fmtowns:
  emulator: libretro
  core:     mess
psx:
  options:
    hud_support: false # duckstation doesn't like it on n2+
