#!/bin/bash

ACTION=$1
PARAM=$2

MODEL=$(cat /sys/firmware/devicetree/base/model)

# specific action related to rg552
if test "${MODEL}" = "Anbernic RG552"
then
    if test "${ACTION}" = "setOutput"
    then
	# force no hdmi if it is unplugged
	NEWCONN=$(cat /var/run/drmConn)
	HDMISTATUS=$(cat /sys/class/gpio/gpio54/value)
	if test "${NEWCONN}" = 1 -a "${HDMISTATUS}" = 1
	then
	    # force 0 which is supposed to be the internal device
	    echo 0 > /var/run/drmConn # force 0 which is supposed to be internal screen
	    echo 0 > /var/run/drmMode # reset the drmMode
	fi

	# force hdmi if hdmi is plugged, connector is on internal screen and mode is auto
	if test "${PARAM}" = "" -o "${PARAM}" = "auto"
	then
	    if test "${NEWCONN}" = 0 -a "${HDMISTATUS}" = 0
	    then
		echo 1 > /var/run/drmConn # force 1 which is supposed to be hdmi
		echo 0 > /var/run/drmMode # reset the drmMode
	    fi
	fi

	# rotation : force rotation for the internal device
	NEWCONN=$(cat /var/run/drmConn)
	if test "${NEWCONN}" = 0
	then
	    touch /var/run/rk-rotation
	    fbv -z -e -i /usr/share/batocera/splash/boot-logo.png
	else
	    rm -f /var/run/rk-rotation
	    fbv -e -i /usr/share/batocera/splash/boot-logo.png
	fi

	# force audio associated with the device
	if test "${NEWCONN}" = 0
	then
	    INTERNAL_AUDIO=$(batocera-audio list | grep -E "^[^ ]* ES8316 " | head -1 | cut -d ' ' -f 1)
	    if test -n "${INTERNAL_AUDIO}"
	    then
		batocera-audio set "${INTERNAL_AUDIO}"
	    fi
	else
	    HDMI_AUDIO=$(batocera-audio list | grep -E "^[^ ]* HDMI " | head -1 | cut -d ' ' -f 1)
	    if test -n "${HDMI_AUDIO}"
	    then
		batocera-audio set "${HDMI_AUDIO}"
	    fi
	fi
    fi
fi
