## ZFAST
default:
  # shader affects retroarch shaders
  shader: crt/zfast-crt
  # scanline affect fba2x
  scanline: true
snes:
  shader: crt/zfast-crt
nes:
  shader: crt/zfast-crt
n64:
  shader: crt/zfast-crt
gba:
  shader: handheld/zfast-lcd
gb:
  shader: handheld/zfast-lcd
gbc:
  shader: handheld/zfast-lcd
fds:
  shader: crt/zfast-crt
virtualboy:
  shader: crt/zfast-crt
# Sega
sg1000:
  shader: crt/zfast-crt
mastersystem:
  shader: crt/zfast-crt
megadrive:
  shader: crt/zfast-crt
gamegear:
  shader: handheld/zfast-lcd
sega32x:
  shader: crt/zfast-crt
segacd:
  shader: crt/zfast-crt
# Arcade
neogeo:
  shader: crt/zfast-crt
neogeocd:
  shader: crt/zfast-crt
mame:
  shader: crt/zfast-crt
fba:
  shader: crt/zfast-crt
naomi:
  shader: crt/zfast-crt
atomiswave:
  shader: crt/zfast-crt
#
ngp:
  shader: handheld/zfast-lcd
ngpc:
  shader: handheld/zfast-lcd
gw:
  shader: crt/zfast-crt
vectrex:
  shader: crt/zfast-crt
lynx:
  shader: handheld/zfast-lcd
lutro:
  shader: crt/zfast-crt
wswan:
  shader: handheld/zfast-lcd
wswanc:
  shader: handheld/zfast-lcd
pcengine:
  shader: crt/zfast-crt
pcenginecd:
  shader: crt/zfast-crt
supergrafx:
  shader: crt/zfast-crt
atari800:
  shader: crt/zfast-crt
atari2600:
  shader: crt/zfast-crt
atari5200:
  shader: crt/zfast-crt
atari7800:
  shader: crt/zfast-crt
prboom:
  shader: crt/zfast-crt
psx:
  shader: crt/zfast-crt
colecovision:
  shader: crt/zfast-crt
# Computers
msx:
  shader: crt/zfast-crt
msx1:
  shader: crt/zfast-crt
msx2:
  shader: crt/zfast-crt
amiga:
  shader: crt/zfast-crt
amstradcpc:
  shader: crt/zfast-crt
atarist:
  shader: crt/zfast-crt
zxspectrum:
  shader: crt/zfast-crt
odyssey2:
  shader: crt/zfast-crt
zx81:
  shader: crt/zfast-crt
pcfx:
  shader: crt/zfast-crt
x68000:
  shader: crt/zfast-crt
