#################################
#       Batocera Settings       #
#################################

# Core Engine
backend = "xrender";
vsync = true;

# Disable all desktop fluff to save GPU cycles for the emulator
shadow = false;
fading = false;
blur-background = false;
corner-radius = 0;

# Performance optimizations
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
use-damage = true;

# If set to true, Picom will suspend itself during fullscreen games
unredir-if-possible = false;
