#!/bin/bash

if test $1 = start
then
  # at 60 degres, put the fan at 20%
  # at 70 degrees, put the fan at 50%
  # at 80 degrees, put the fan at 95%
  # the default noisy value is to do nothing until 68 degrees, and start at 50%
  # the current temperature : /sys/devices/virtual/thermal/thermal_zone0/temp
  # http://forum.odroid.com/viewtopic.php?f=52&t=16308
  echo "1 20 50 95" > /sys/devices/odroid_fan.14/fan_speeds
  echo   "60 70 80" > /sys/devices/odroid_fan.14/temp_levels

  # default values :
  # 1 51 71 91
  #   68 73 85
fi

