#!/bin/sh

ACTION=$1
# device required when enabling
DEVICE=$2
PIDFILE="/var/run/pixelcade.pid"
PIDVAL=
test -e "${PIDFILE}" && PIDVAL=$(cat "${PIDFILE}")

EVENTS="game-selected system-selected game-start game-end screensaver-start screensaver-stop achievements"

case "${ACTION}" in
    "enable")
	# add hooks
	for EVT in ${EVENTS}
	do
	    mkdir -p /var/run/emulationstation/scripts/${EVT} || exit 1
	    ln -sf /usr/share/pixelcade/scripts/${EVT}.sh /var/run/emulationstation/scripts/${EVT}/pixelcade.sh || exit 1
	done

	# batocera image
	mkdir -p "/userdata/system/pixelcade/system" || exit 1
	if ! test -e "/userdata/system/pixelcade/system/batocera.png"
	then
	    cp "/usr/share/pixelcade/images/system/batocera.png" "/userdata/system/pixelcade/system/batocera.png" || exit 1
	fi

	# start the binary
	test -n "${PIDVAL}" && kill -15 "${PIDVAL}"
	BIN=pixelweb
	# prefer the custom bin
	test -e "/userdata/system/pixelcade/pixelweb" && BIN="/userdata/system/pixelcade/pixelweb"
	mkdir -p /userdata/system/pixelcade || exit 1

	if test "${DEVICE}" = demo
	then
	    nohup "${BIN}" -demo -image system/batocera.png -p /userdata/system/pixelcade -delay 1 -startup >/dev/null 2>/dev/null &
	else
	    nohup "${BIN}" -d "${DEVICE}" -image system/batocera.png -p /userdata/system/pixelcade -delay 1 -startup >/dev/null 2>/dev/null &
	fi
	echo "$!" > "${PIDFILE}"
	;;
    "disable")
	# stop the binary
	if test -n "${PIDVAL}"
	then
	    kill -15 "${PIDVAL}"
	    rm -f "${PIDFILE}"
	fi

	# remove hooks
	for EVT in ${EVENTS}
	do
	    unlink /var/run/emulationstation/scripts/${EVT}/pixelcade.sh
	done
	;;
    "update-artwork")
	BIN=pixelweb
	mkdir -p /userdata/system/pixelcade || exit 1
	# prefer the custom bin
	test -e "/userdata/system/pixelcade/pixelweb" && BIN="/userdata/system/pixelcade/pixelweb"
	(cd /userdata/system/pixelcade && "${BIN}" -update-artwork)
	;;
    *)
	echo "${0} enable <device>"
	echo "${0} disable"
	echo "${0} update-artwork"
	;;
esac
