#!/bin/bash

# only at boot
test "$1" != "start" && exit 0

configFile="/boot/config.txt"

# check for an appropriate firmware line
grep -qE '^start_file=start.elf'  "${configFile}" && exit 0

# update the file with preferred firmware if not present
mount -o remount,rw /boot || exit 1
sed -i 's/start_file=start_x.elf/start_file=start.elf/g'    "${configFile}" || exit 0
sed -i 's/fixup_file=fixup_x.dat/fixup_file=fixup.dat/g'    "${configFile}" || exit 0
sed -i '/^[ ]*gpu_mem[ ]*=*.*$/d'                           "${configFile}" || exit 0
mount -o remount,ro /boot || exit 1

echo "Rebooting now..."
shutdown -r now

exit 0
