################################################################################
#
# MUPEN64PLUS-NEXT
#
################################################################################
# Version: Commits on Feb 6, 2019
LIBRETRO_MUPEN64PLUS_NEXT_VERSION = 88a83b80f54a3408321a74c67566f48d2f5d3017
LIBRETRO_MUPEN64PLUS_NEXT_SITE = $(call github,libretro,mupen64plus-libretro-nx,$(LIBRETRO_MUPEN64PLUS_NEXT_VERSION))
LIBRETRO_MUPEN64PLUS_NEXT_LICENSE = "GPLv2"
LIBRETRO_MUPEN64PLUS_NEXT_DEPENDENCIES = retroarch host-nasm

ifeq ($(BR2_PACKAGE_RPI_USERLAND),y)
	LIBRETRO_MUPEN64PLUS_DEPENDENCIES += rpi-userland
endif

LIBRETRO_MUPEN64PLUS_NEXT_SUPP_OPT=

# plateform
LIBRETRO_MUPEN64PLUS_NEXT_PLATFORM=$(LIBRETRO_PLATFORM)
ifeq ($(BR2_PACKAGE_LIBRETRO_MUPEN64PLUS_NEXT_PLATFORM_RPI3),y)
	LIBRETRO_MUPEN64PLUS_NEXT_PLATFORM=rpi3
else ifeq ($(BR2_PACKAGE_LIBRETRO_MUPEN64PLUS_NEXT_PLATFORM_RPI2),y)
	LIBRETRO_MUPEN64PLUS_NEXT_PLATFORM=rpi2
else ifeq ($(BR2_PACKAGE_LIBRETRO_MUPEN64PLUS_NEXT_PLATFORM_ODROIDXU),y)
	LIBRETRO_MUPEN64PLUS_NEXT_PLATFORM=odroid-ODROID-XU
else ifeq ($(BR2_PACKAGE_LIBRETRO_MUPEN64PLUS_NEXT_PLATFORM_ODROIDC),y)
	LIBRETRO_MUPEN64PLUS_NEXT_PLATFORM=odroid-ODROIDC
else ifeq ($(BR2_PACKAGE_LIBRETRO_MUPEN64PLUS_NEXT_PLATFORM_ROCKPRO64),y)
	LIBRETRO_MUPEN64PLUS_NEXT_PLATFORM=rockpro64
endif

# architecture
ifeq ($(BR2_x86_i586),y)
	# Makefile allow dynarec for i686
	LIBRETRO_MUPEN64PLUS_NEXT_SUPP_OPT=ARCH=i686
else ifeq ($(BR2_arm),y)
	# Makefile allow dynarec for arm
	LIBRETRO_MUPEN64PLUS_NEXT_SUPP_OPT=ARCH=arm
else ifeq ($(BR2_aarch64),y)
	LIBRETRO_MUPEN64PLUS_NEXT_SUPP_OPT=ARCH=aarch64
endif

define LIBRETRO_MUPEN64PLUS_NEXT_BUILD_CMDS
	PATH=$(BR_PATH) CFLAGS="$(TARGET_CFLAGS)" CXXFLAGS="$(TARGET_CXXFLAGS)" CPPFLAGS="$(TARGET_CPPFLAGS)" \
		$(MAKE) CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" LD="$(TARGET_LD)" \
		RANLIB="$(TARGET_RANLIB)" AR="$(TARGET_AR)" -C $(@D)/ \
		-f Makefile platform="$(LIBRETRO_MUPEN64PLUS_NEXT_PLATFORM)" \
		$(LIBRETRO_MUPEN64PLUS_NEXT_SUPP_OPT)
endef

define LIBRETRO_MUPEN64PLUS_NEXT_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/mupen64plus_next_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/mupen64plus-next_libretro.so
endef

$(eval $(generic-package))
