SectionDevice."Speaker" {
	Comment "Speaker"

	ConflictingDevice [
		"Headphones"
	]

	EnableSequence [
		cset "name='Output 2 Playback Volume' 18"
		cset "name='Speaker Switch' on"
	]

	DisableSequence [
		cset "name='Speaker Switch' off"
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
	}
}

SectionDevice."Headphones" {
	Comment "Headphones"

	ConflictingDevice [
		"Speaker"
	]

	EnableSequence [
		cset "name='Output 1 Playback Volume' 28"
		cset "name='Headphones Switch' on"
	]

	DisableSequence [
		cset "name='Headphones Switch' off"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"
		JackControl "Headphones Jack"
		JackHWMute "Speaker"
	}
}

SectionDevice."Mic" {
	Comment "Internal Microphone"

	EnableSequence [
		cset "name='Left PGA Mux' 'Line 2'"
		cset "name='Right PGA Mux' 'Line 2'"
	]

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId},0"
	}
}
