# S24_LE plays about 48 dB quiet on the q6 DisplayPort path
monitor.alsa.rules = [
  {
    matches = [
      {
        api.alsa.path = "hw:RetroidPocket,3"
      }
    ]
    actions = {
      update-props = {
        audio.format = "S16LE"
      }
    }
  }
]
