################################################################################
#
# libretro-azahar
#
################################################################################

LIBRETRO_AZAHAR_VERSION = 2125.1.2
LIBRETRO_AZAHAR_SITE = https://github.com/azahar-emu/azahar
LIBRETRO_AZAHAR_SITE_METHOD = git
LIBRETRO_AZAHAR_GIT_SUBMODULES = YES
LIBRETRO_AZAHAR_LICENSE = GPLv2
LIBRETRO_AZAHAR_SUPPORTS_IN_SOURCE_BUILD = NO

LIBRETRO_AZAHAR_DEPENDENCIES += boost fdk-aac ffmpeg fmt host-clang openal sdl2

$(eval $(call register,azahar.libretro.core.yml))

LIBRETRO_AZAHAR_CMAKE_BACKEND = ninja

LIBRETRO_AZAHAR_CONF_OPTS += -DCMAKE_C_COMPILER=$(HOST_DIR)/bin/clang
LIBRETRO_AZAHAR_CONF_OPTS += -DCMAKE_CXX_COMPILER=$(HOST_DIR)/bin/clang++
LIBRETRO_AZAHAR_CONF_OPTS += -DCMAKE_EXE_LINKER_FLAGS="-lm -lstdc++"
LIBRETRO_AZAHAR_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
LIBRETRO_AZAHAR_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_LIBRETRO=ON
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_TESTS=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_ROOM=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DCITRA_WARNINGS_AS_ERRORS=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_WEB_SERVICE=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_SOFTWARE_RENDERER=ON
LIBRETRO_AZAHAR_CONF_OPTS += -DUSE_SYSTEM_OPENAL=ON
LIBRETRO_AZAHAR_CONF_OPTS += -DUSE_SYSTEM_BOOST=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_LTO=ON

ifeq ($(BR2_X86_CPU_HAS_SSE42),y)
    LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_SSE42=ON
else
    LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_SSE42=OFF
endif

ifeq ($(BR2_PACKAGE_BATOCERA_VULKAN),y)
    LIBRETRO_AZAHAR_DEPENDENCIES += vulkan-headers vulkan-loader
    LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_VULKAN=ON
    LIBRETRO_AZAHAR_CONF_OPTS += -DUSE_SYSTEM_VULKAN_HEADERS=ON
else
    LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_VULKAN=OFF
    LIBRETRO_AZAHAR_CONF_OPTS += -DUSE_SYSTEM_VULKAN_HEADERS=OFF
endif

LIBRETRO_AZAHAR_CONF_ENV += LDFLAGS=-lpthread

define LIBRETRO_AZAHAR_INSTALL_TARGET_CMDS
    mkdir -p $(TARGET_DIR)/usr/lib/libretro
	$(INSTALL) -D $(@D)/buildroot-build/bin/Release/azahar_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/azahar_libretro.so
endef

$(eval $(cmake-package))
$(eval $(emulator-info-package))
