from __future__ import annotations

import inspect
import re
from argparse import ArgumentParser
from collections import defaultdict
from pathlib import Path
from typing import TYPE_CHECKING, Annotated, Any, Final, cast, get_args, get_origin
from unittest.mock import Mock

from .common import DBUS_PATH, DBUS_SERVICE
from .service import BaseInterface, Service

if TYPE_CHECKING:
    import functools

    from dbus_fast.annotations import DBusSignature
    from dbus_fast.service import _Method

    class _WrappedMethod(functools._Wrapped[Any, Any, Any, Any]):  # pyright: ignore
        __DBUS_METHOD: _Method


CLIENT_INTERFACES_FILE: Final = Path(__file__).parent / 'client_interfaces.py'
_import_re: Final = re.compile(r'\b(?P<module>(?:[A-Za-z_]\w+\.)*[A-Za-z_]\w+)\.(?P<name>[A-Za-z_]\w+)\b')


def _get_imports(annotation: Any, imports: dict[str, set[str]], /) -> None:
    args = get_args(annotation)

    for arg in args:
        _get_imports(arg, imports)

    if getattr(annotation, '__module__', None) is not None:
        module: str = annotation.__module__

        if module in ('builtins', 'inspect'):
            return

        if module.startswith('hotkeygen.dbus'):
            module = module.removeprefix('hotkeygen.dbus')

        if module.startswith('hotkeygen'):
            module = '..' + module.rsplit('.', 1)[-1]

        imports[module].add(annotation.__name__)


def _get_annotation_data(annotation: Any, imports: dict[str, set[str]], /) -> tuple[Any, DBusSignature | None]:
    metadata: Any | None = None

    if get_origin(annotation) is Annotated:
        metadata = getattr(annotation, '__metadata__', [None])[0]
        annotation = get_args(annotation)[0]

    _get_imports(annotation, imports)

    return annotation, metadata


def _generate_method(method: _WrappedMethod, imports: dict[str, set[str]], /) -> str:
    signature = inspect.signature(method, eval_str=True)

    parameter_data = {
        key: _get_annotation_data(param.annotation, imports) for key, param in signature.parameters.items()
    }
    return_annotation, return_metadata = _get_annotation_data(signature.return_annotation, imports)

    signature = signature.replace(
        parameters=[
            param.replace(annotation=parameter_data[param.name][0]) if key != 'self' else param
            for key, param in signature.parameters.items()
        ],
        return_annotation=return_annotation,
    )

    signature_string = _import_re.sub(r'\2', str(signature))
    method_name = method.__DBUS_METHOD.name
    signature = ''.join(
        [
            'NONE' if dbus_signature is None else dbus_signature.signature
            for name, (_, dbus_signature) in parameter_data.items()
            if name != 'self'
        ]
    )
    body = ', '.join(key for key in parameter_data if key != 'self')

    return f"""\
    async def {method.__name__}{signature_string}:
        return await self._call_method(
            Message(
                destination=self.__dbus_destination__,
                path=self.__dbus_path__,
                interface=self.__dbus_interface_name__,
                member={method_name!r},
                signature={signature!r},
                body=[{body}],
            ),
            {None if return_metadata is None else return_metadata.signature!r},
        )
"""


def _generate_client_interface(interface: BaseInterface, imports: dict[str, set[str]], /) -> str:
    methods = [
        cast('_WrappedMethod', attribute)
        for attribute in vars(interface.__class__).values()
        if callable(attribute) and hasattr(attribute, '__DBUS_METHOD')
    ]

    return f"""\
@dataclass(slots=True)
class Client{interface.__class__.__name__}(BaseClientInterface):
    __dbus_interface_name__: ClassVar[str] = '{interface.__dbus_interface_name__}'

{'\n'.join(_generate_method(method, imports) for method in methods)}
"""


def generate_client_interfaces() -> str:
    service = Mock()
    interfaces = Service.interfaces.func(service)

    imports: dict[str, set[str]] = defaultdict(set)
    imports['dbus_fast.aio.message_bus'].add('MessageBus')

    body = '\n'.join(_generate_client_interface(interface, imports) for interface in interfaces)

    absolute_imports: list[str] = []
    relative_imports: list[str] = []

    for module, export in imports.items():
        (absolute_imports if not module.startswith('.') else relative_imports).append(
            f'from {module} import {", ".join(sorted(export))}'
        )

    return (
        f"""\
# NOTE: This file is auto-generated by `python -m hotkeygen.dbus._generate_client_interfaces`. Do not edit manually.

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, ClassVar

from dbus_fast import Message
from dbus_fast._private.util import replace_idx_with_fds
from dbus_fast.proxy_object import BaseProxyInterface

if TYPE_CHECKING:
    {'\n    '.join(sorted(absolute_imports))}

    {'\n    '.join(sorted(relative_imports))}


@dataclass(slots=True)
class BaseClientInterface:
    __dbus_destination__: ClassVar[str] = '{DBUS_SERVICE}'
    __dbus_path__: ClassVar[str] = '{DBUS_PATH}'
    __dbus_interface_name__: ClassVar[str]

    _bus: MessageBus

    async def _call_method(self, message: Message, return_signature: str | None, /) -> Any:
        reply = await self._bus.call(message)

        BaseProxyInterface._check_method_return(reply, return_signature)

        body = replace_idx_with_fds(reply.signature_tree, reply.body, reply.unix_fds)

        if return_signature is None:
            return None

        return body[0]


{body}
""".strip()
        + '\n'
    )


def main() -> None:
    parser = ArgumentParser()
    parser.add_argument(
        'output_file',
        type=Path,
        default=CLIENT_INTERFACES_FILE,
        nargs='?',
        help='The file to write the generated client interfaces code to.',
    )

    args = parser.parse_args()

    args.output_file.write_text(generate_client_interfaces())


if __name__ == '__main__':
    main()
