# NOTE: This file is auto-generated by `python -m hotkeygen.dbus._generate_client_interfaces`. Do not edit manually.

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, ClassVar

from dbus_fast import Message
from dbus_fast._private.util import replace_idx_with_fds
from dbus_fast.proxy_object import BaseProxyInterface

if TYPE_CHECKING:
    from dbus_fast.aio.message_bus import MessageBus
    from dbus_fast.signature import Variant

    from .common import DBusContextType, DBusDeviceMappingsType


@dataclass(slots=True)
class BaseClientInterface:
    __dbus_destination__: ClassVar[str] = 'org.batocera.Hotkeygen'
    __dbus_path__: ClassVar[str] = '/'
    __dbus_interface_name__: ClassVar[str]

    _bus: MessageBus

    async def _call_method(self, message: Message, return_signature: str | None, /) -> Any:
        reply = await self._bus.call(message)

        BaseProxyInterface._check_method_return(reply, return_signature)

        body = replace_idx_with_fds(reply.signature_tree, reply.body, reply.unix_fds)

        if return_signature is None:
            return None

        return body[0]


@dataclass(slots=True)
class ClientContextInterface(BaseClientInterface):
    __dbus_interface_name__: ClassVar[str] = 'org.batocera.Hotkeygen.Context'

    async def set_context(self, name: str, keys: dict[str, Variant], include_common: bool) -> None:
        return await self._call_method(
            Message(
                destination=self.__dbus_destination__,
                path=self.__dbus_path__,
                interface=self.__dbus_interface_name__,
                member='SetContext',
                signature='sa{sv}b',
                body=[name, keys, include_common],
            ),
            None,
        )

    async def set_default_context(self) -> None:
        return await self._call_method(
            Message(
                destination=self.__dbus_destination__,
                path=self.__dbus_path__,
                interface=self.__dbus_interface_name__,
                member='SetDefaultContext',
                signature='',
                body=[],
            ),
            None,
        )

    async def get_details(self) -> tuple[DBusContextType, DBusDeviceMappingsType]:
        return await self._call_method(
            Message(
                destination=self.__dbus_destination__,
                path=self.__dbus_path__,
                interface=self.__dbus_interface_name__,
                member='GetDetails',
                signature='',
                body=[],
            ),
            '((sa{sv})a((ssss)(a{ts}a{ts})))',
        )

    async def reload(self) -> None:
        return await self._call_method(
            Message(
                destination=self.__dbus_destination__,
                path=self.__dbus_path__,
                interface=self.__dbus_interface_name__,
                member='Reload',
                signature='',
                body=[],
            ),
            None,
        )


@dataclass(slots=True)
class ClientMouseInterface(BaseClientInterface):
    __dbus_interface_name__: ClassVar[str] = 'org.batocera.Hotkeygen.Mouse'

    async def reset(self) -> None:
        return await self._call_method(
            Message(
                destination=self.__dbus_destination__,
                path=self.__dbus_path__,
                interface=self.__dbus_interface_name__,
                member='Reset',
                signature='',
                body=[],
            ),
            None,
        )


@dataclass(slots=True)
class ClientHotkeyInterface(BaseClientInterface):
    __dbus_interface_name__: ClassVar[str] = 'org.batocera.Hotkeygen.Hotkey'

    async def send(self, key: str, delay: int) -> None:
        return await self._call_method(
            Message(
                destination=self.__dbus_destination__,
                path=self.__dbus_path__,
                interface=self.__dbus_interface_name__,
                member='Send',
                signature='st',
                body=[key, delay],
            ),
            None,
        )


@dataclass(slots=True)
class ClientConfigInterace(BaseClientInterface):
    __dbus_interface_name__: ClassVar[str] = 'org.batocera.Hotkeygen.Config'

    async def get_system_default_mapping_config(self) -> tuple[dict[str, str], dict[str, str]]:
        return await self._call_method(
            Message(
                destination=self.__dbus_destination__,
                path=self.__dbus_path__,
                interface=self.__dbus_interface_name__,
                member='GetSystemDefaultMappingConfig',
                signature='',
                body=[],
            ),
            '(a{ss}a{ss})',
        )

    async def get_device_mapping_config(self) -> dict[str, dict[str, str]]:
        return await self._call_method(
            Message(
                destination=self.__dbus_destination__,
                path=self.__dbus_path__,
                interface=self.__dbus_interface_name__,
                member='GetDeviceMappingConfig',
                signature='',
                body=[],
            ),
            'a{sa{ss}}',
        )

    async def set_device_mapping_config(self, filename: str, key: str, action: str) -> None:
        return await self._call_method(
            Message(
                destination=self.__dbus_destination__,
                path=self.__dbus_path__,
                interface=self.__dbus_interface_name__,
                member='SetDeviceMappingConfig',
                signature='sss',
                body=[filename, key, action],
            ),
            None,
        )

    async def remove_device_mapping_config(self, filename: str, key: str) -> None:
        return await self._call_method(
            Message(
                destination=self.__dbus_destination__,
                path=self.__dbus_path__,
                interface=self.__dbus_interface_name__,
                member='RemoveDeviceMappingConfig',
                signature='ss',
                body=[filename, key],
            ),
            None,
        )
