#!/bin/sh

ACTION=$1

do_help() {
    echo "${1} list" >&2
    echo "${1} list_blacklistable" >&2
    echo "${1} trust" >&2
    echo "${1} blacklist <device address> <device name>" >&2
    echo "${1} unblacklist <device address>" >&2
    echo "${1} remove <device address>" >&2
    echo "${1} save" >&2
    echo "${1} restore" >&2
}

do_save() {
    BCK=/userdata/system/bluetooth/bluetooth.tar
    (cd /var/lib && tar cf "${BCK}" bluetooth)
}

do_restore() {
    BCK=/userdata/system/bluetooth/bluetooth.tar
    [ -f "${BCK}" ] && (cd /var/lib && tar xf "${BCK}")
}

do_list() {
    find /var/lib/bluetooth/ -type f -name info |
	while read FILE
	do
	    if grep -qE '^Trusted=true$' "${FILE}"
	    then
		DEVNAME=$(grep -E '^Name=' "${FILE}" | sed -e s+"^Name="++)
		DEVADDR=$(basename $(dirname "${FILE}"))
		echo "${DEVADDR} ${DEVNAME}"
	    fi
	done
}

do_list_blacklistable() {
    (
	cat /var/lib/bluetooth/bluetooth_blacklisted | sed -e s+"^\([^ ]*\) \(.*\)$"+"\1 1 \2"+
	cat /var/run/bluetooth_seen | sed -e s+"^\([^ ]*\) \(.*\)$"+"\1 0 \2"+
    ) | sort -r -t " " -k 1,1 -u
}

do_remove() {
    DEV="${1}"

    # output is never nice
    (echo "untrust ${DEV}" ; echo "remove ${DEV}") | bluetoothctl >/dev/null 2>/dev/null
    find /var/lib/bluetooth -name "${DEV}" | while read X
    do
	rm -rf "${X}"
    done

    do_save # save
    return 0
}

do_blacklist() {
    BLADDR=$1
    BLNAME=$2

    echo "${BLADDR} ${BLNAME}" >> "/var/lib/bluetooth/bluetooth_blacklisted"
    do_remove "${BLADDR}"
    do_save # save
}

do_unblacklist() {
    BLADDR=$1

    grep -vE "^${BLADDR} " "/var/lib/bluetooth/bluetooth_blacklisted" > "/var/lib/bluetooth/bluetooth_blacklisted.tmp"
    mv "/var/lib/bluetooth/bluetooth_blacklisted.tmp" "/var/lib/bluetooth/bluetooth_blacklisted" || return 1
    do_save # save
}

do_trust() {
    NPID=$(cat /var/run/bluetooth-agent.pid)
    test -z "${NPID}" && return 0

    touch "/var/run/bt_status" || retrun 1
    LAST_MSG=$(cat "/var/run/bt_status")
    
    # start discovering
    kill -10 "${NPID}"

    trap "kill -12 ${NPID}" 2 3

    N=60
    while test $N -gt 0
    do
	NEW_MSG=$(cat "/var/run/bt_status")
	if test "${LAST_MSG}" != "${NEW_MSG}"
	then
	    LAST_MSG="${NEW_MSG}"
	    echo "${NEW_MSG}"
	fi
	sleep 1
	N=$((N-1))
    done

    # stop discovering
    kill -12 "${NPID}"

    do_save # save
}

do_starttrust() {
    NPID=$(cat /var/run/bluetooth-agent.pid)
    test -z "${NPID}" && exit 0

    # start discovering
    kill -10 "${NPID}"
}

do_stoptrust() {
    NPID=$(cat /var/run/bluetooth-agent.pid)
    test -z "${NPID}" && exit 0

    # stop discovering
    kill -12 "${NPID}"

    do_save # save
}

case "${ACTION}" in
    "list")
	do_list
	;;
    "list_blacklistable")
	do_list_blacklistable
	;;
    "trust")
	do_trust
	;;
    "blacklist")
	if test $# = 3
	then
	    do_blacklist "${2}" "${3}" || exit 1
	else
	    do_help "${0}"
	    exit 1
	fi
	;;
    "unblacklist")
	if test $# = 2
	then
	    do_unblacklist "${2}" || exit 1
	else
	    do_help "${0}"
	    exit 1
	fi
	;;
    "starttrust")
	do_starttrust
	;;
    "stoptrust")
	do_stoptrust
	;;
    "remove")
	if test $# = 2
	then
	    do_remove "${2}" || exit 1
	else
	    do_help "${0}"
	    exit 1
	fi
	;;
    "save")
	do_save
	;;
    "restore")
	do_restore
	;;
    *)
	do_help "${0}"
	exit 1
esac

exit 0
