#!/usr/bin/env python

import sys
import os

def writeCfgFile(system, filename, init_line, defaults_to_add, controls_to_add, gameResolution):
    if not os.path.isfile(filename):
        os.makedirs(os.path.dirname(filename), exist_ok=True)
        
        with open(filename, 'w') as file:
            file.write(init_line)
            for line in defaults_to_add:
                file.write(line)
            for line in controls_to_add:
                file.write(line)
    else:
        with open(filename, 'r+') as file:
            lines = file.readlines()
            file.seek(0)
            for line in lines:
                ## Set defaults every time
                # resolution
                if line.startswith('seta r_mode'):
                    line = 'seta r_mode "-1"\n'
                elif line.startswith('seta r_customwidth'):
                    line = f'seta r_customwidth "{gameResolution["width"]}"\n'
                elif line.startswith('seta r_customheight'):
                    line = f'seta r_customheight "{gameResolution["height"]}"\n'
                # controllers
                elif line.startswith('seta in_joystickUseAnalog'):
                    line = 'seta in_joystickUseAnalog "1"\n'
                elif line.startswith('seta in_joystick'):
                    line = 'seta in_joystick "1"\n'
                # network downloads
                elif line.startswith('seta cl_allowdownload'):
                    line = 'seta cl_allowDownload "1"\n'
                
                ## User options
                elif line.startswith('seta com_hunkMegs'):
                    if system.isOptSet('ioquake3_mem'):
                        line = f"seta com_hunkMegs \"{system.config['ioquake3_mem']}\"\n"
                    else:
                        line = 'seta com_hunkMegs "256"\n'
                
                file.write(line)

            # Add the missing lines at the end of the file
            for line in defaults_to_add:
                if line not in lines:
                    file.write(line)
            for line in controls_to_add:
                if line not in lines:
                    file.write(line)

def writeCfgFiles(system, rom, playersControllers, gameResolution):
    # create the cfg files for each quake3 rom / mod folder
    roms_directory = "/userdata/roms/quake3"
    base_directory = "/userdata/system/configs/ioquake3"
    files = []

    # get the immediate subdirectories within rom directory
    subdirectories = next(os.walk(roms_directory))[1]

    # add the corresponding config file paths and add them to the `files` list
    for subdirectory in subdirectories:
        config_directory = os.path.join(base_directory, subdirectory)
        config_file = os.path.join(config_directory, "q3config.cfg")
        files.append(config_file)

    init_line = '// generated by quake, do not modify\n'
    # minimum defaults
    defaults_to_add = [
        'seta r_mode "-1"\n',
        f'seta r_customwidth "{gameResolution["width"]}"\n',
        f'seta r_customheight "{gameResolution["height"]}"\n',
        'seta in_joystickUseAnalog "1"\n',
        'seta in_joystick "1"\n',
        'cl_allowdownload "1"\n'
    ]

    # basic controller config
    controls_to_add = [
        'bind PAD0_A "+moveup"\n',
        'bind PAD0_X "+movedown"\n',
        'bind PAD0_Y "+button2"\n',
        'bind PAD0_LEFTSHOULDER "weapnext"\n',
        'bind PAD0_RIGHTSHOULDER "weapprev"\n',
        'bind PAD0_LEFTSTICK_LEFT "+moveleft"\n',
        'bind PAD0_LEFTSTICK_RIGHT "+moveright"\n',
        'bind PAD0_LEFTSTICK_UP "+forward"\n',
        'bind PAD0_LEFTSTICK_DOWN "+back"\n',
        'bind PAD0_RIGHTSTICK_LEFT "+left"\n',
        'bind PAD0_RIGHTSTICK_RIGHT "+right"\n',
        'bind PAD0_RIGHTSTICK_UP "+lookup"\n',
        'bind PAD0_RIGHTSTICK_DOWN "+lookdown"\n',
        'bind PAD0_LEFTTRIGGER "+speed"\n',
        'bind PAD0_RIGHTTRIGGER "+attack"\n'
    ]
    
    for filename in files:
        writeCfgFile(system, filename, init_line, defaults_to_add, controls_to_add, gameResolution)
