################################################################################
#
# xenia-edge
#
################################################################################
XENIA_EDGE_VERSION = b0a1ea5f8ba2de34240f5fb3e8e8da352348b7bc
XENIA_EDGE_SITE = https://github.com/has207/xenia-edge.git
XENIA_EDGE_SITE_METHOD = git
XENIA_EDGE_GIT_SUBMODULES = YES
XENIA_EDGE_LICENSE = BSD
XENIA_EDGE_LICENSE_FILE = LICENSE
XENIA_EDGE_EMULATOR_INFO = xenia-edge.emulator.yml

# wxWidgets (vendored submodule) uses GTK3 — no Qt dependency
XENIA_EDGE_DEPENDENCIES = sdl2 vulkan-headers vulkan-loader lz4 alsa-lib python-toml \
    gtk3 pcre2

XENIA_EDGE_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
XENIA_EDGE_CONF_OPTS += -DXENIA_BUILD_TESTS=OFF
XENIA_EDGE_CONF_OPTS += -DXENIA_BUILD_MISC=OFF
XENIA_EDGE_CONF_OPTS += -DXENIA_ENABLE_LTO=OFF

define XENIA_EDGE_GEN_VERSION_H
	mkdir -p $(@D)
	printf '// Autogenerated by batocera buildroot.\n\
#ifndef GENERATED_VERSION_H_\n\
#define GENERATED_VERSION_H_\n\
#define XE_BUILD_BRANCH "edge"\n\
#define XE_BUILD_COMMIT "$(XENIA_EDGE_VERSION)"\n\
#define XE_BUILD_COMMIT_SHORT "$(shell echo $(XENIA_EDGE_VERSION) | cut -c1-9)"\n\
#define XE_BUILD_DATE __DATE__\n\
#define XE_BUILD_PR_NUMBER 0\n\
#endif  // GENERATED_VERSION_H_\n' > $(@D)/version.h
endef

XENIA_EDGE_PRE_CONFIGURE_HOOKS += XENIA_EDGE_GEN_VERSION_H

define XENIA_EDGE_INSTALL_TARGET_CMDS
	find $(@D) -maxdepth 6 -name "xenia_edge" -type f -perm /111 \
	    | head -1 \
	    | xargs -I{} $(INSTALL) -D -m 0755 {} $(TARGET_DIR)/usr/xenia_edge/xenia_edge

	# game-patches are embedded in the binary at build time (build/data_repos/game-patches)
	# The patches dialog writes enabled patches to storage_root/patches/ on first use
	mkdir -p $(TARGET_DIR)/usr/share/batocera/datainit/system/configs/xenia_edge/patches
endef

$(eval $(cmake-package))
$(eval $(emulator-info-package))
