################################################################################
#
# xenia-edge
#
################################################################################
# Version: Commits on May 2, 2026
XENIA_EDGE_VERSION = 0f2e40c024d59dc088977d0220edd12bac3a3f46
XENIA_EDGE_SITE = https://github.com/has207/xenia-edge.git
XENIA_EDGE_SITE_METHOD = git
XENIA_EDGE_GIT_SUBMODULES = YES
XENIA_EDGE_LICENSE = BSD
XENIA_EDGE_LICENSE_FILE = LICENSE
XENIA_EDGE_EMULATOR_INFO = xenia-edge.emulator.yml

XENIA_EDGE_DEPENDENCIES = sdl2 vulkan-headers vulkan-loader lz4 alsa-lib python-toml \
    qt6base qt6declarative

XENIA_EDGE_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
XENIA_EDGE_CONF_OPTS += -DXENIA_BUILD_TESTS=OFF
XENIA_EDGE_CONF_OPTS += -DXENIA_BUILD_MISC=OFF
# LTO disabled: avoids linker issues and reduces cross-compilation build time
XENIA_EDGE_CONF_OPTS += -DXENIA_ENABLE_LTO=OFF
# xenia-edge requires QT_DIR env var to locate Qt (not CMAKE_PREFIX_PATH)
XENIA_EDGE_CONF_ENV += QT_DIR=$(STAGING_DIR)/usr

# Generate version.h before cmake configuration — xenia-edge requires this
# file in CMAKE_BINARY_DIR; it is normally produced by the xb build script.
define XENIA_EDGE_GEN_VERSION_H
	mkdir -p $(@D)
	printf '// Autogenerated by batocera buildroot.\n\
#ifndef GENERATED_VERSION_H_\n\
#define GENERATED_VERSION_H_\n\
#define XE_BUILD_BRANCH "edge"\n\
#define XE_BUILD_COMMIT "$(XENIA_EDGE_VERSION)"\n\
#define XE_BUILD_COMMIT_SHORT "$(shell echo $(XENIA_EDGE_VERSION) | cut -c1-9)"\n\
#define XE_BUILD_DATE __DATE__\n\
#define XE_BUILD_PR_NUMBER 0\n\
#endif  // GENERATED_VERSION_H_\n' > $(@D)/version.h
endef

XENIA_EDGE_PRE_CONFIGURE_HOOKS += XENIA_EDGE_GEN_VERSION_H

define XENIA_EDGE_INSTALL_TARGET_CMDS
	# Install binary
	find $(@D) -maxdepth 6 -name "xenia_edge" -type f -perm /111 \
	    | head -1 \
	    | xargs -I{} $(INSTALL) -D -m 0755 {} $(TARGET_DIR)/usr/xenia_edge/xenia_edge

	# Install Qt platform plugins required at runtime
	mkdir -p $(TARGET_DIR)/usr/xenia_edge/platforms
	-cp $(STAGING_DIR)/usr/plugins/platforms/libqxcb.so \
	    $(TARGET_DIR)/usr/xenia_edge/platforms/ 2>/dev/null || true

	# Game patches (xenia-edge looks for them at storage_root/patches/)
	# Installed to datainit so they are copied to /userdata on first boot
	mkdir -p $(TARGET_DIR)/usr/share/batocera/datainit/system/configs/xenia_edge/patches
	mkdir -p $(@D)/temp-patches
	( cd $(@D)/temp-patches && $(GIT) init && \
	  $(GIT) remote add origin https://github.com/xenia-canary/game-patches.git && \
	  $(GIT) config core.sparsecheckout true && \
	  echo "patches/*.toml" >> .git/info/sparse-checkout && \
	  $(GIT) pull --depth=1 origin main && \
	  mv -f patches/*.toml \
	      $(TARGET_DIR)/usr/share/batocera/datainit/system/configs/xenia_edge/patches \
	)
	rm -rf $(@D)/temp-patches
endef

$(eval $(cmake-package))
$(eval $(emulator-info-package))
