################################################################################
#
# xenia-edge
#
################################################################################
# Version: Commits on Jun 23, 2026
XENIA_EDGE_VERSION = 65e7f337e928029f4beeede406ace4eca5503456
XENIA_EDGE_SITE = https://github.com/has207/xenia-edge.git
XENIA_EDGE_SITE_METHOD = git
XENIA_EDGE_GIT_SUBMODULES = YES
XENIA_EDGE_LICENSE = BSD
XENIA_EDGE_LICENSE_FILE = LICENSE
XENIA_EDGE_EMULATOR_INFO = xenia-edge.emulator.yml

XENIA_EDGE_DEPENDENCIES += host-clang host-glslang host-shader-slang
XENIA_EDGE_DEPENDENCIES += ffmpeg fmt sdl3 glslang imgui
XENIA_EDGE_DEPENDENCIES += libcurl libgtk3 lz4 python-toml vulkan-headers vulkan-loader

XENIA_EDGE_CMAKE_BACKEND = ninja

XENIA_EDGE_CONF_ENV += SLANGC_PATH=$(HOST_DIR)/bin/slangc

XENIA_EDGE_CONF_OPTS += -DCMAKE_C_COMPILER=$(HOST_DIR)/bin/clang
XENIA_EDGE_CONF_OPTS += -DCMAKE_CXX_COMPILER=$(HOST_DIR)/bin/clang++
XENIA_EDGE_CONF_OPTS += -DCMAKE_EXE_LINKER_FLAGS="-lm -lstdc++"
XENIA_EDGE_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
XENIA_EDGE_CONF_OPTS += -DXENIA_BUILD_TESTS=OFF
XENIA_EDGE_CONF_OPTS += -DXENIA_BUILD_MISC=OFF
XENIA_EDGE_CONF_OPTS += -DXENIA_ENABLE_LTO=OFF
XENIA_EDGE_CONF_OPTS += -DXENIA_USE_SYSTEM_SDL3=ON
XENIA_EDGE_CONF_OPTS += -DXENIA_HOST_SHADER_CC=$(BUILD_DIR)/xenia-edge-$(XENIA_EDGE_VERSION)/host_tools/xenia-shader-cc

# xenia-shader-cc is a build-time host tool (GLSL/XeSL -> SPIR-V -> embedded
# .h). We cross-compile x86_64 on an aarch64 host, so letting the project's
# CMake build it with the target toolchain produces an x86_64 binary that
# can't run during the build (and needlessly recompiles glslang/SPIRV-Tools).
# Instead, compile it natively for the build machine against buildroot's
# host-glslang / host-spirv-tools and import it (003-import-prebuilt-host-shader-cc.patch).
define XENIA_EDGE_BUILD_HOST_SHADER_CC
	mkdir -p $(@D)/host_tools
	$(HOSTCXX) -O2 -std=c++17 \
		-I$(HOST_DIR)/include \
		-I$(HOST_DIR)/include/glslang \
		-I$(@D)/third_party/glslang/StandAlone \
		$(@D)/tools/build/shader_cc.cc \
		-o $(@D)/host_tools/xenia-shader-cc \
		-L$(HOST_DIR)/lib -Wl,-rpath,$(HOST_DIR)/lib \
		-Wl,--no-as-needed \
		-lSPIRV -lglslang-default-resource-limits -lglslang \
		-lSPIRV-Tools-opt -lSPIRV-Tools -lpthread
endef

XENIA_EDGE_PRE_CONFIGURE_HOOKS += XENIA_EDGE_BUILD_HOST_SHADER_CC

define XENIA_EDGE_GEN_VERSION_H
	mkdir -p $(@D)
	printf '// Autogenerated by batocera buildroot.\n\
#ifndef GENERATED_VERSION_H_\n\
#define GENERATED_VERSION_H_\n\
#define XE_BUILD_BRANCH "edge"\n\
#define XE_BUILD_COMMIT "$(XENIA_EDGE_VERSION)"\n\
#define XE_BUILD_COMMIT_SHORT "$(shell echo $(XENIA_EDGE_VERSION) | cut -c1-9)"\n\
#define XE_BUILD_DATE __DATE__\n\
#define XE_BUILD_PR_NUMBER 0\n\
#endif  // GENERATED_VERSION_H_\n' > $(@D)/version.h
endef

XENIA_EDGE_PRE_CONFIGURE_HOOKS += XENIA_EDGE_GEN_VERSION_H

define XENIA_EDGE_INSTALL_TARGET_CMDS
    $(INSTALL) -D -m 0755 $(@D)/bin/Linux/xenia_edge $(TARGET_DIR)/usr/bin/
	# game-patches are embedded in the binary at build time (build/data_repos/game-patches)
	# The patches dialog writes enabled patches to storage_root/patches/ on first use
	mkdir -p $(TARGET_DIR)/usr/share/batocera/datainit/system/configs/xenia_edge/patches
endef
$(eval $(cmake-package))
$(eval $(emulator-info-package))
