TIC80_VERSION = v1.1.2837
TIC80_SITE = $(call github,nesbox,TIC-80,$(TIC80_VERSION))
TIC80_LICENSE = MIT
TIC80_LICENSE_FILES = LICENSE
TIC80_DEPENDENCIES = pipewire sdl2 ruby libcurl libglvnd libglu
ifeq ($(BR2_PACKAGE_WAYLAND),y)
	TIC80_DEPENDENCIES += wayland
endif
ifeq ($(BR2_PACKAGE_LIBFREEGLUT),y)
	TIC80_DEPENDENCIES += libfreeglut
endif

TIC80_CONF_OPTS = -DCMAKE_BUILD_TYPE=Release
TIC80_CONF_OPTS += -DBUILD_SHARED_LIBS=ON
TIC80_CONF_OPTS += -DBUILD_SDLGPU=On
TIC80_CONF_OPTS += -DBUILD_WITH_ALL=On
TIC80_CONF_OPTS += -DBUILD_PRO=TRUE
TIC80_CONF_OPTS += -DBUILD_TOUCH_INPUT=ON

$(eval $(cmake-package))
