TIC80_VERSION = 1.1.2837
TIC80_SITE = $(call github,nesbox,TIC-80,$(TIC80_VERSION))
TIC80_LICENSE = MIT
TIC80_LICENSE_FILES = https://github.com/nesbox/TIC-80/blob/main/LICENSE
TIC80_DEPENDENCIES = pipewire wayland sdl2 ruby libcurl libglvnd libglu freeglut

TIC80_CONF_OPTS = -DBUILD_SDLGPU=On
TIC80_CONF_OPTS += -DBUILD_WITH_ALL=On
TIC80_CONF_OPTS += -DBUILD_PRO=TRUE
TIC80_CONF_OPTS += -DBUILD_TOUCH_INPUT=ON
TIC80_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
TIC80_CONF_OPTS += -DBUILD_SHARED_LIBS=ON

$(eval $(cmake-package))
