#!/bin/sh

# batocera-nvidia applies either the installed production or legacy driver(s)
# driver can be detected 'auto' or also set using batoceta-boot.conf

MODE=$1
LOG="/userdata/system/logs/batocera.log"
LISTDIR=/usr/share/nvidia

if test "${MODE}" = "auto"
then
    echo "Detect if we have a Nvidia GPU"
    NVIDIA_DEV=$(lspci -mn | awk '{ gsub("\"",""); if (($2 ~ "030[0-2]") && ($3 == "10de" || $3 == "12d2")) { print $1 } }')
    if [ "$NVIDIA_DEV" ]
    then
	echo "Detected a NVIDIA GPU" > $LOG
	for d in $NVIDIA_DEV ; do
	    lspci -nn -s $d | sed -e s+"^"+"*** "+
	done
	for d in $NVIDIA_DEV ; do
	    PCIDEVID=$(lspci -mn -s "$d" | awk '{ gsub("\"",""); print $4 }')
        CARDNAME=$(lspci -s "$d" | cut -d "[" -f2 | cut -d "]" -f1;)
        echo "Checking card: $CARDNAME" >> $LOG
        if grep -q -i $PCIDEVID $LISTDIR/production.list 2>/dev/null
        then
            # check card name
            echo "Detected PCI device ID in production list" >> $LOG
            if grep -q -i $CARDNAME $LISTDIR/production.list 2>/dev/null
            then
                echo "Detected card name in production list" >> $LOG
                MODE=production
                break
            else
                echo "Card name not detected in production list" >> $LOG
            fi
        fi
        if grep -q -i $PCIDEVID $LISTDIR/legacy.list 2>/dev/null
        then
            # check card name
            echo "Detected PCI device ID in legacy list" >> $LOG
            if grep -q -i $CARDNAME $LISTDIR/legacy.list 2>/dev/null
		    then
                echo "Detected card name in legacy list" >> $LOG
		        MODE=legacy
                break
            else
                echo "Card name not detected in legacy list" >> $LOG
            fi
        fi
	    if grep -q -i $PCIDEVID $LISTDIR/legacy390.list 2>/dev/null
	    then
            # check card name
            echo "Detected PCI device ID in legacy390 list" >> $LOG
            if grep -q -i $CARDNAME $LISTDIR/legacy.list 2>/dev/null
            then
                echo "Detected card name in legacy390 list" >> $LOG
                MODE=legacy390
                break
            else
                echo "Card name not detected in legacy390 list" >> $LOG
            fi
	    fi
	done
    else
        echo "No NVIDIA GPU detected" > $LOG
        echo "Failing back to OpenSource Mesa Nouveau driver"
        test -e /var/run/nvidia/modprobe/blacklist-nouveau.conf && rm -f /var/run/nvidia/modprobe/blacklist-nouveau.conf
        test -e /var/run/nvidia/modprobe/nvidia-drm.conf        && rm -f /var/run/nvidia/modprobe/nvidia-drm.conf
        exit 0
    fi
fi

LINUX_VER=$(uname -r)

# production driver version
BATOCERA_NVIDIA_DRIVER_VERSION=$(cat /usr/share/nvidia/production.version)
# legacy driver versions
BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION=$(cat /usr/share/nvidia/legacy.version)
BATOCERA_NVIDIA390_LEGACY_DRIVER_VERSION=$(cat /usr/share/nvidia/legacy390.version)

mkdir -p /var/run/nvidia/modprobe || exit 1

if test "${MODE}" = "production"
then
    echo "Using NVIDIA Production driver - ${BATOCERA_NVIDIA_DRIVER_VERSION}" >> $LOG
    echo
    echo "blacklist nouveau" > /var/run/nvidia/modprobe/blacklist-nouveau.conf
    echo "options nvidia-drm modeset=1" > /var/run/nvidia/modprobe/nvidia-drm.conf
    # [symbolic link 64-bit library files]
    mkdir -p /var/run/nvidia/lib
    # libGLX_nvidia.so
    ln -sf /usr/lib/libGLX_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libGLX_nvidia.so
	ln -sf /var/run/nvidia/lib/libGLX_nvidia.so /usr/lib/libGLX_nvidia.so
    ln -sf /usr/lib/libGLX_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libGLX_nvidia.so.0
	ln -sf /var/run/nvidia/lib/libGLX_nvidia.so.0 /usr/lib/libGLX_nvidia.so.0
    # libEGL_nvidia.so
    ln -sf /usr/lib/libEGL_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libEGL_nvidia.so
    ln -sf /var/run/nvidia/lib/libEGL_nvidia.so /usr/lib/libEGL_nvidia.so
    ln -sf /usr/lib/libEGL_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libEGL_nvidia.so.0
    ln -sf /var/run/nvidia/lib/libEGL_nvidia.so.0 /usr/lib/libEGL_nvidia.so.0
    # libGLESv1_CM_nvidia.so
    ln -sf /usr/lib/libGLESv1_CM_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libGLESv1_CM_nvidia.so
    ln -sf /var/run/nvidia/lib/libGLESv1_CM_nvidia.so /usr/lib/libGLESv1_CM_nvidia.so
    ln -sf /usr/lib/libGLESv1_CM_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libGLESv1_CM_nvidia.so.1
    ln -sf /var/run/nvidia/lib/libGLESv1_CM_nvidia.so.1 /usr/lib/libGLESv1_CM_nvidia.so.1
    # libGLESv2_nvidia.so
    ln -sf /usr/lib/libGLESv2_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libGLESv2_nvidia.so
    ln -sf /var/run/nvidia/lib/libGLESv2_nvidia.so /usr/lib/libGLESv2_nvidia.so
    ln -sf /usr/lib/libGLESv2_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libGLESv2_nvidia.so.2
	ln -sf /var/run/nvidia/lib/libGLESv2_nvidia.so.2 /usr/lib/libGLESv2_nvidia.so.2
    # libnvidia-eglcore.so
    ln -sf /usr/lib/libnvidia-eglcore.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libnvidia-eglcore.so
	ln -sf /var/run/nvidia/lib/libnvidia-eglcore.so /usr/lib/libnvidia-eglcore.so
    # libnvidia-glcore.so
    ln -sf /usr/lib/libnvidia-glcore.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libnvidia-glcore.so
	ln -sf /var/run/nvidia/lib/libnvidia-glcore.so /usr/lib/libnvidia-glcore.so
    # libnvidia-glsi.so
    ln -sf /usr/lib/libnvidia-glsi.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libnvidia-glsi.so
	ln -sf /var/run/nvidia/lib/libnvidia-glsi.so /usr/lib/libnvidia-glsi.so
    # libnvidia-tls.so
    ln -sf /usr/lib/libnvidia-tls.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libnvidia-tls.so
    ln -sf /var/run/nvidia/lib/libnvidia-tls.so /usr/lib/libnvidia-tls.so
    # libvdpau_nvidia.so
    ln -sf /usr/lib/libvdpau_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libvdpau_nvidia.so
    ln -sf /var/run/nvidia/lib/libvdpau_nvidia.so /usr/lib/libvdpau_nvidia.so
    ln -sf /usr/lib/libvdpau_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libvdpau_nvidia.so.1
    ln -sf /var/run/nvidia/lib/libvdpau_nvidia.so.1 /usr/lib/libvdpau_nvidia.so.1
    # libnvidia-ml.so
    ln -sf /usr/lib/libnvidia-ml.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libnvidia-ml.so
    ln -sf /var/run/nvidia/lib/libnvidia-ml.so /usr/lib/libnvidia-ml.so
    ln -sf /usr/lib/libnvidia-ml.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libnvidia-ml.so.1
    ln -sf /var/run/nvidia/lib/libnvidia-ml.so.1 /usr/lib/libnvidia-ml.so.1
    # libnvidia-glvkspirv.so
    ln -sf /usr/lib/libnvidia-glvkspirv.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libnvidia-glvkspirv.so
    ln -sf /var/run/nvidia/lib/libnvidia-glvkspirv.so /usr/lib/libnvidia-glvkspirv.so
    
    # [symbolic link 32-bit library files]
    mkdir -p /var/run/nvidia/lib32
    # libGLX_nvidia.so
    ln -sf /lib32/libGLX_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib32/libGLX_nvidia.so
    ln -sf /var/run/nvidia/lib32/libGLX_nvidia.so /lib32/libGLX_nvidia.so
    ln -sf /lib32/libGLX_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib32/libGLX_nvidia.so.0
    ln -sf /var/run/nvidia/lib32/libGLX_nvidia.so.0 /lib32/libGLX_nvidia.so.0
    # libEGL_nvidia.so
    ln -sf /lib32/libEGL_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib32/libEGL_nvidia.so
    ln -sf /var/run/nvidia/lib32/libEGL_nvidia.so /lib32/libEGL_nvidia.so
    ln -sf /lib32/libEGL_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib32/libEGL_nvidia.so.0
    ln -sf /var/run/nvidia/lib32/libEGL_nvidia.so.0 /lib32/libEGL_nvidia.so.0
    # libGLESv1_CM_nvidia.so
    ln -sf /lib32/libGLESv1_CM_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib32/libGLESv1_CM_nvidia.so
    ln -sf /var/run/nvidia/lib32/libGLESv1_CM_nvidia.so /lib32/libGLESv1_CM_nvidia.so
    ln -sf /lib32/libGLESv1_CM_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib32/libGLESv1_CM_nvidia.so.1
    ln -sf /var/run/nvidia/lib32/libGLESv1_CM_nvidia.so.1 /lib32/libGLESv1_CM_nvidia.so.1
    # libGLESv2_nvidia.so
    ln -sf /lib32/libGLESv2_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib32/libGLESv2_nvidia.so
    ln -sf /var/run/nvidia/lib32/libGLESv2_nvidia.so /lib32/libGLESv2_nvidia.so
    ln -sf /lib32/libGLESv2_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib32/libGLESv2_nvidia.so.2
    ln -sf /var/run/nvidia/lib32/libGLESv2_nvidia.so.2 /lib32/libGLESv2_nvidia.so.2
    # libnvidia-eglcore.so
    ln -sf /lib32/libnvidia-eglcore.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib32/libnvidia-eglcore.so
    ln -sf /var/run/nvidia/lib32/libnvidia-eglcore.so /lib32/libnvidia-eglcore.so
    # libnvidia-glcore.so
    ln -sf /lib32/libnvidia-glcore.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib32/libnvidia-glcore.so
    ln -sf /var/run/nvidia/lib32/libnvidia-glcore.so /lib32/libnvidia-glcore.so
    # libnvidia-glsi.so
    ln -sf /lib32/libnvidia-glsi.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib32/libnvidia-glsi.so
    ln -sf /var/run/nvidia/lib32/libnvidia-glsi.so /lib32/libnvidia-glsi.so
    # libnvidia-tls.so
    ln -sf /lib32/libnvidia-tls.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib32/libnvidia-tls.so
    ln -sf /var/run/nvidia/lib32/libnvidia-tls.so /lib32/libnvidia-tls.so
    # libvdpau_nvidia.so
    ln -sf /lib32/libvdpau_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib32/libvdpau_nvidia.so
    ln -sf /var/run/nvidia/lib32/libvdpau_nvidia.so /lib32/libvdpau_nvidia.so
    ln -sf /lib32/libvdpau_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib32/libvdpau_nvidia.so.1
    ln -sf /var/run/nvidia/lib32/libvdpau_nvidia.so.1 /lib32/libvdpau_nvidia.so.1
    # libnvidia-ml.so
    ln -sf /lib32/libnvidia-ml.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib32/libnvidia-ml.so
    ln -sf /var/run/nvidia/lib32/libnvidia-ml.so /lib32/libnvidia-ml.so
    ln -sf /lib32/libnvidia-ml.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib32/libnvidia-ml.so.1
    ln -sf /var/run/nvidia/lib32/libnvidia-ml.so.1 /lib32/libnvidia-ml.so.1
    # libnvidia-glvkspirv.so
    ln -sf /lib32/libnvidia-glvkspirv.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib32/libnvidia-glvkspirv.so
    ln -sf /var/run/nvidia/lib32/libnvidia-glvkspirv.so /lib32/libnvidia-glvkspirv.so
    
    # sym link Xorg libraries too
    ln -sf /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libglxserver_nvidia.so
    ln -sf /var/run/nvidia/lib/libglxserver_nvidia.so /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so
    ln -sf /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so.$BATOCERA_NVIDIA_DRIVER_VERSION /var/run/nvidia/lib/libglxserver_nvidia.so.1
    ln -sf /var/run/nvidia/lib/libglxserver_nvidia.so.1 /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so.1
    
    # link Xorg driver
    ln -sf /usr/lib/xorg/modules/drivers/nvidia_production_drv.so /var/run/nvidia/lib/nvidia_drv.so
    ln -sf /var/run/nvidia/lib/nvidia_drv.so /usr/lib/xorg/modules/drivers/nvidia_drv.so
    
    # link GL config files
    mkdir -p /var/run/nvidia/configs
    ln -sf /usr/share/vulkan/implicit_layer.d/nvidia_production_layers.json /var/run/nvidia/configs/nvidia_layers.json
    ln -sf /var/run/nvidia/configs/nvidia_layers.json /usr/share/vulkan/implicit_layer.d/nvidia_layers.json
    ln -sf /usr/share/glvnd/egl_vendor.d/10_nvidia_production.json /var/run/nvidia/configs/10_nvidia.json
    ln -sf /var/run/nvidia/configs/10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json
    ln -sf /usr/share/X11/xorg.conf.d/10-nvidia-production-drm-outputclass.conf /var/run/nvidia/configs/10-nvidia-drm-outputclass.conf
    ln -sf /var/run/nvidia/configs/10-nvidia-drm-outputclass.conf /usr/share/X11/xorg.conf.d/10-nvidia-drm-outputclass.conf
    
    # link Vulkan icd files
    ln -sf /usr/share/vulkan/nvidia/nvidia_production_icd.x86_64.json /var/run/nvidia/configs/nvidia_icd.x86_64.json
    ln -sf /var/run/nvidia/configs/nvidia_icd.x86_64.json /usr/share/vulkan/icd.d/nvidia_icd.x86_64.json
    ln -sf /usr/share/vulkan/nvidia/nvidia_production_icd.i686.json /var/run/nvidia/configs/nvidia_icd.i686.json
	ln -sf /var/run/nvidia/configs/nvidia_icd.i686.json /usr/share/vulkan/icd.d/nvidia_icd.i686.json
    
    # finally link kernel modules & run them
    mkdir -p /var/run/nvidia/modules
    ln -sf /usr/share/nvidia/modules/nvidia-production.ko /var/run/nvidia/modules/nvidia.ko
    ln -sf /var/run/nvidia/modules/nvidia.ko /lib/modules/$LINUX_VER/extra/nvidia.ko
    ln -sf /usr/share/nvidia/modules/nvidia-modeset-production.ko /var/run/nvidia/modules/nvidia-modeset.ko
    ln -sf /var/run/nvidia/modules/nvidia-modeset.ko /lib/modules/$LINUX_VER/extra/nvidia-modeset.ko
    ln -sf /usr/share/nvidia/modules/nvidia-drm-production.ko /var/run/nvidia/modules/nvidia-drm.ko
    ln -sf /var/run/nvidia/modules/nvidia-drm.ko /lib/modules/$LINUX_VER/extra/nvidia-drm.ko
    ln -sf /usr/share/nvidia/modules/nvidia-uvm-production.ko /var/run/nvidia/modules/nvidia-uvm.ko
    ln -sf /var/run/nvidia/modules/nvidia-uvm.ko /lib/modules/$LINUX_VER/extra/nvidia-uvm.ko
    for m in ipmi_devintf nvidia nvidia_modeset nvidia_uvm nvidia_drm ; do modprobe $m ; done

elif [[ "${MODE}" == *"legacy"* ]]
then
    if [[ "${MODE}" == *"390"* ]]
    then
	    BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION=$BATOCERA_NVIDIA390_LEGACY_DRIVER_VERSION
    fi
    echo "Using NVIDIA Legacy driver version - ${BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION}" >> $LOG
    echo
    echo "blacklist nouveau" > /var/run/nvidia/modprobe/blacklist-nouveau.conf
    echo "options nvidia-drm modeset=1" > /etc/modprobe.d/nvidia-drm.conf
    # [symbolic link 64-bit library files]
    mkdir -p /var/run/nvidia/lib
    # libGLX_nvidia.so
    ln -sf /usr/lib/libGLX_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libGLX_nvidia.so
	ln -sf /var/run/nvidia/lib/libGLX_nvidia.so /usr/lib/libGLX_nvidia.so
    ln -sf /usr/lib/libGLX_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libGLX_nvidia.so.0
	ln -sf /var/run/nvidia/lib/libGLX_nvidia.so.0 /usr/lib/libGLX_nvidia.so.0
    # libEGL_nvidia.so
    ln -sf /usr/lib/libEGL_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libEGL_nvidia.so
    ln -sf /var/run/nvidia/lib/libEGL_nvidia.so /usr/lib/libEGL_nvidia.so
    ln -sf /usr/lib/libEGL_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libEGL_nvidia.so.0
    ln -sf /var/run/nvidia/lib/libEGL_nvidia.so.0 /usr/lib/libEGL_nvidia.so.0
    # libGLESv1_CM_nvidia.so
    ln -sf /usr/lib/libGLESv1_CM_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libGLESv1_CM_nvidia.so
    ln -sf /var/run/nvidia/lib/libGLESv1_CM_nvidia.so /usr/lib/libGLESv1_CM_nvidia.so
    ln -sf /usr/lib/libGLESv1_CM_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libGLESv1_CM_nvidia.so.1
    ln -sf /var/run/nvidia/lib/libGLESv1_CM_nvidia.so.1 /usr/lib/libGLESv1_CM_nvidia.so.1
    # libGLESv2_nvidia.so
    ln -sf /usr/lib/libGLESv2_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libGLESv2_nvidia.so
    ln -sf /var/run/nvidia/lib/libGLESv2_nvidia.so /usr/lib/libGLESv2_nvidia.so
    ln -sf /usr/lib/libGLESv2_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libGLESv2_nvidia.so.2
	ln -sf /var/run/nvidia/lib/libGLESv2_nvidia.so.2 /usr/lib/libGLESv2_nvidia.so.2
    # libnvidia-eglcore.so
    ln -sf /usr/lib/libnvidia-eglcore.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libnvidia-eglcore.so
	ln -sf /var/run/nvidia/lib/libnvidia-eglcore.so /usr/lib/libnvidia-eglcore.so
    # libnvidia-glcore.so
    ln -sf /usr/lib/libnvidia-glcore.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libnvidia-glcore.so
	ln -sf /var/run/nvidia/lib/libnvidia-glcore.so /usr/lib/libnvidia-glcore.so
    # libnvidia-glsi.so
    ln -sf /usr/lib/libnvidia-glsi.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libnvidia-glsi.so
	ln -sf /var/run/nvidia/lib/libnvidia-glsi.so /usr/lib/libnvidia-glsi.so
    # libnvidia-tls.so
    ln -sf /usr/lib/libnvidia-tls.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libnvidia-tls.so
    ln -sf /var/run/nvidia/lib/libnvidia-tls.so /usr/lib/libnvidia-tls.so
    # libvdpau_nvidia.so
    ln -sf /usr/lib/libvdpau_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libvdpau_nvidia.so
    ln -sf /var/run/nvidia/lib/libvdpau_nvidia.so /usr/lib/libvdpau_nvidia.so
    ln -sf /usr/lib/libvdpau_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libvdpau_nvidia.so.1
    ln -sf /var/run/nvidia/lib/libvdpau_nvidia.so.1 /usr/lib/libvdpau_nvidia.so.1
    # libnvidia-ml.so
    ln -sf /usr/lib/libnvidia-ml.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libnvidia-ml.so
    ln -sf /var/run/nvidia/lib/libnvidia-ml.so /usr/lib/libnvidia-ml.so
    ln -sf /usr/lib/libnvidia-ml.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libnvidia-ml.so.1
    ln -sf /var/run/nvidia/lib/libnvidia-ml.so.1 /usr/lib/libnvidia-ml.so.1
    # libnvidia-glvkspirv.so
    ln -sf /usr/lib/libnvidia-glvkspirv.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libnvidia-glvkspirv.so
    ln -sf /var/run/nvidia/lib/libnvidia-glvkspirv.so /usr/lib/libnvidia-glvkspirv.so
    
    # [symbolic link 32-bit library files]
    mkdir -p /var/run/nvidia/lib32
    # libGLX_nvidia.so
    ln -sf /lib32/libGLX_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib32/libGLX_nvidia.so
    ln -sf /var/run/nvidia/lib32/libGLX_nvidia.so /lib32/libGLX_nvidia.so
    ln -sf /lib32/libGLX_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib32/libGLX_nvidia.so.0
    ln -sf /var/run/nvidia/lib32/libGLX_nvidia.so.0 /lib32/libGLX_nvidia.so.0
    # libEGL_nvidia.so
    ln -sf /lib32/libEGL_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib32/libEGL_nvidia.so
    ln -sf /var/run/nvidia/lib32/libEGL_nvidia.so /lib32/libEGL_nvidia.so
    ln -sf /lib32/libEGL_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib32/libEGL_nvidia.so.0
    ln -sf /var/run/nvidia/lib32/libEGL_nvidia.so.0 /lib32/libEGL_nvidia.so.0
    # libGLESv1_CM_nvidia.so
    ln -sf /lib32/libGLESv1_CM_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib32/libGLESv1_CM_nvidia.so
    ln -sf /var/run/nvidia/lib32/libGLESv1_CM_nvidia.so /lib32/libGLESv1_CM_nvidia.so
    ln -sf /lib32/libGLESv1_CM_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib32/libGLESv1_CM_nvidia.so.1
    ln -sf /var/run/nvidia/lib32/libGLESv1_CM_nvidia.so.1 /lib32/libGLESv1_CM_nvidia.so.1
    # libGLESv2_nvidia.so
    ln -sf /lib32/libGLESv2_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib32/libGLESv2_nvidia.so
    ln -sf /var/run/nvidia/lib32/libGLESv2_nvidia.so /lib32/libGLESv2_nvidia.so
    ln -sf /lib32/libGLESv2_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib32/libGLESv2_nvidia.so.2
    ln -sf /var/run/nvidia/lib32/libGLESv2_nvidia.so.2 /lib32/libGLESv2_nvidia.so.2
    # libnvidia-eglcore.so
    ln -sf /lib32/libnvidia-eglcore.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib32/libnvidia-eglcore.so
    ln -sf /var/run/nvidia/lib32/libnvidia-eglcore.so /lib32/libnvidia-eglcore.so
    # libnvidia-glcore.so
    ln -sf /lib32/libnvidia-glcore.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib32/libnvidia-glcore.so
    ln -sf /var/run/nvidia/lib32/libnvidia-glcore.so /lib32/libnvidia-glcore.so
    # libnvidia-glsi.so
    ln -sf /lib32/libnvidia-glsi.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib32/libnvidia-glsi.so
    ln -sf /var/run/nvidia/lib32/libnvidia-glsi.so /lib32/libnvidia-glsi.so
    # libnvidia-tls.so
    ln -sf /lib32/libnvidia-tls.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib32/libnvidia-tls.so
    ln -sf /var/run/nvidia/lib32/libnvidia-tls.so /lib32/libnvidia-tls.so
    # libvdpau_nvidia.so
    ln -sf /lib32/libvdpau_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib32/libvdpau_nvidia.so
    ln -sf /var/run/nvidia/lib32/libvdpau_nvidia.so /lib32/libvdpau_nvidia.so
    ln -sf /lib32/libvdpau_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib32/libvdpau_nvidia.so.1
    ln -sf /var/run/nvidia/lib32/libvdpau_nvidia.so.1 /lib32/libvdpau_nvidia.so.1
    # libnvidia-ml.so
    ln -sf /lib32/libnvidia-ml.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib32/libnvidia-ml.so
    ln -sf /var/run/nvidia/lib32/libnvidia-ml.so /lib32/libnvidia-ml.so
    ln -sf /lib32/libnvidia-ml.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib32/libnvidia-ml.so.1
    ln -sf /var/run/nvidia/lib32/libnvidia-ml.so.1 /lib32/libnvidia-ml.so.1
    # libnvidia-glvkspirv.so
    ln -sf /lib32/libnvidia-glvkspirv.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib32/libnvidia-glvkspirv.so
    ln -sf /var/run/nvidia/lib32/libnvidia-glvkspirv.so /lib32/libnvidia-glvkspirv.so
    
    # sym link Xorg libraries too
    ln -sf /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libglxserver_nvidia.so
    ln -sf /var/run/nvidia/lib/libglxserver_nvidia.so /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so
    ln -sf /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so.$BATOCERA_NVIDIA_LEGACY_DRIVER_VERSION /var/run/nvidia/lib/libglxserver_nvidia.so.1
    ln -sf /var/run/nvidia/lib/libglxserver_nvidia.so.1 /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so.1
   
    # 390 version
    if [[ "${MODE}" == *"390"* ]]
    then
	    # link Xorg driver
        mkdir -p /var/run/nvidia/lib
	    mkdir -p /var/run/nvidia/xorg
	    ln -sf /usr/lib/xorg/modules/drivers/nvidia390_legacy_drv.so /var/run/nvidia/lib/nvidia_drv.so
        ln -sf /var/run/nvidia/lib/nvidia_drv.so /usr/lib/xorg/modules/drivers/nvidia_drv.so
	    ln -sf /usr/lib/xorg/modules/extensions/libglx.so.$BATOCERA_NVIDIA390_LEGACY_DRIVER_VERSION /var/run/nvidia/xorg/libglx.so
        ln -sf /var/run/nvidia/xorg/libglx.so /usr/lib/xorg/modules/extensions/libglx.so
	    
        # link GL config files
	    mkdir -p /var/run/nvidia/configs
	    ln -sf /usr/share/vulkan/implicit_layer.d/nvidia390_legacy_layers.json /var/run/nvidia/configs/nvidia_layers.json
        ln -sf /var/run/nvidia/configs/nvidia_layers.json /usr/share/vulkan/implicit_layer.d/nvidia_layers.json
	    ln -sf /usr/share/glvnd/egl_vendor.d/10_nvidia390_legacy.json /var/run/nvidia/configs/10_nvidia.json
        ln -sf /var/run/nvidia/configs/10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json
	    ln -sf /usr/share/X11/xorg.conf.d/10-nvidia390-legacy-drm-outputclass.conf /var/run/nvidia/configs/10-nvidia-drm-outputclass.conf
        ln -sf /var/run/nvidia/configs/10-nvidia-drm-outputclass.conf /usr/share/X11/xorg.conf.d/10-nvidia-drm-outputclass.conf

	    # link Vulkan icd files
	    ln -sf /usr/share/vulkan/icd.d/nvidia390_legacy_icd.x86_64.json /var/run/nvidia/configs/nvidia_icd.x86_64.json
        ln -sf /var/run/nvidia/configs/nvidia_icd.x86_64.json /usr/share/vulkan/icd.d/nvidia_icd.x86_64.json
	    ln -sf /usr/share/vulkan/icd.d/nvidia390_legacy_icd.i686.json /var/run/nvidia/configs/nvidia_icd.i686.json
	    ln -sf /var/run/nvidia/configs/nvidia_icd.i686.json /usr/share/vulkan/icd.d/nvidia_icd.i686.json
	    
        # finally copy kernel modules & run them
	    mkdir -p /var/run/nvidia/modules
	    ln -sf /usr/share/nvidia/modules/nvidia390-legacy.ko /var/run/nvidia/modules/nvidia.ko
        ln -sf /var/run/nvidia/modules/nvidia.ko /lib/modules/$LINUX_VER/extra/nvidia.ko
	    ln -sf /usr/share/nvidia/modules/nvidia390-modeset-legacy.ko /var/run/nvidia/modules/nvidia-modeset.ko
        ln -sf /var/run/nvidia/modules/nvidia-modeset.ko /lib/modules/$LINUX_VER/extra/nvidia-modeset.ko
	    ln -sf /usr/share/nvidia/modules/nvidia390-drm-legacy.ko /var/run/nvidia/modules/nvidia-drm.ko
        ln -sf /var/run/nvidia/modules/nvidia-drm.ko /lib/modules/$LINUX_VER/extra/nvidia-drm.ko
	    ln -sf /usr/share/nvidia/modules/nvidia390-uvm-legacy.ko /var/run/nvidia/modules/nvidia-uvm.ko
        ln -sf /var/run/nvidia/modules/nvidia-uvm.ko /lib/modules/$LINUX_VER/extra/nvidia-uvm.ko
	    for m in ipmi_devintf nvidia nvidia_modeset nvidia_uvm nvidia_drm ; do modprobe $m ; done
    else
        # 470 version
        # link Xorg driver
        ln -sf /usr/lib/xorg/modules/drivers/nvidia_legacy_drv.so /var/run/nvidia/lib/nvidia_drv.so
        ln -sf /var/run/nvidia/lib/nvidia_drv.so /usr/lib/xorg/modules/drivers/nvidia_drv.so
        
        # link GL config files
        mkdir -p /var/run/nvidia/configs
        ln -sf /usr/share/vulkan/implicit_layer.d/nvidia_legacy_layers.json /var/run/nvidia/configs/nvidia_layers.json
        ln -sf /var/run/nvidia/configs/nvidia_layers.json /usr/share/vulkan/implicit_layer.d/nvidia_layers.json
        ln -sf /usr/share/glvnd/egl_vendor.d/10_nvidia_legacy.json /var/run/nvidia/configs/10_nvidia.json
        ln -sf /var/run/nvidia/configs/10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json
        ln -sf /usr/share/X11/xorg.conf.d/10-nvidia-legacy-drm-outputclass.conf /var/run/nvidia/configs/10-nvidia-drm-outputclass.conf
        ln -sf /var/run/nvidia/configs/10-nvidia-drm-outputclass.conf /usr/share/X11/xorg.conf.d/10-nvidia-drm-outputclass.conf
        
        # link Vulkan icd files
        ln -sf /usr/share/vulkan/nvidia/nvidia_legacy_icd.x86_64.json /var/run/nvidia/configs/nvidia_icd.x86_64.json
        ln -sf /var/run/nvidia/configs/nvidia_icd.x86_64.json /usr/share/vulkan/icd.d/nvidia_icd.x86_64.json
        ln -sf /usr/share/vulkan/nvidia/nvidia_legacy_icd.i686.json /var/run/nvidia/configs/nvidia_icd.i686.json
        ln -sf /var/run/nvidia/configs/nvidia_icd.i686.json /usr/share/vulkan/icd.d/nvidia_icd.i686.json
        
        # finally link the kernel modules & run them
        mkdir -p /var/run/nvidia/modules
        ln -sf /usr/share/nvidia/modules/nvidia-legacy.ko /var/run/nvidia/modules/nvidia.ko
        ln -sf /var/run/nvidia/modules/nvidia.ko /lib/modules/$LINUX_VER/extra/nvidia.ko
        ln -sf /usr/share/nvidia/modules/nvidia-modeset-legacy.ko /var/run/nvidia/modules/nvidia-modeset.ko
        ln -sf /var/run/nvidia/modules/nvidia-modeset.ko /lib/modules/$LINUX_VER/extra/nvidia-modeset.ko
        ln -sf /usr/share/nvidia/modules/nvidia-drm-legacy.ko /var/run/nvidia/modules/nvidia-drm.ko
        ln -sf /var/run/nvidia/modules/nvidia-drm.ko /lib/modules/$LINUX_VER/extra/nvidia-drm.ko
        ln -sf /usr/share/nvidia/modules/nvidia-uvm-legacy.ko /var/run/nvidia/modules/nvidia-uvm.ko
        ln -sf /var/run/nvidia/modules/nvidia-uvm.ko /lib/modules/$LINUX_VER/extra/nvidia-uvm.ko
        for m in ipmi_devintf nvidia nvidia_modeset nvidia_uvm nvidia_drm ; do modprobe $m ; done
    fi

elif test "${MODE}" = "nouveau"
then
    echo "Using OpenSource Mesa Nouveau driver" > $LOG
    test -e /var/run/nvidia/modprobe/blacklist-nouveau.conf && rm -f /var/run/nvidia/modprobe/blacklist-nouveau.conf
    test -e /var/run/nvidia/modprobe/nvidia-drm.conf        && rm -f /var/run/nvidia/modprobe/nvidia-drm.conf
fi
