Syntax 4

SectionUseCase."HiFi" {
	File "/Qualcomm/sm6115/HiFi-MangmiAirX.conf"
	Comment "HiFi quality Music."
}

BootSequence [
	cset "name='SEC_MI2S_RX Audio Mixer MultiMedia1' 1"
	cset "name='MultiMedia3 Mixer SEC_MI2S_TX' 1"
	cset "name='HPVol SPKVol Switch' 1"
	cset "name='DAC Playback Volume' 191"
	cset "name='HPL Playback Volume' 0"
	cset "name='HPR Playback Volume' 0"
	cset "name='ADC Capture Volume' 191"
	cset "name='ADC PGA Gain Volume' 4"
	cset "name='SPK_L PCM Playback Volume' 72"
	cset "name='SPK_R PCM Playback Volume' 72"
	cset "name='SPK_L Profile Set' 0"
	cset "name='SPK_R Profile Set' 0"
]

Include.card-init.File "/lib/card-init.conf"
Include.ctl-remap.File "/lib/ctl-remap.conf"
