context.properties = {
  # Use constrainted (and reasonable) defaults to hold the output node in place.
  # This prevents the output node from being recreated by wireplumber (causing
  # audio drop outs) that can happen when multiple audio source nodes are
  # rapidly destroyed and created. Note that audio source nodes are still free
  # to use smaller quantum and different rates.
  #
  # Test case: enable frontend music, install a theme like RCBX that shows
  # videos in the console selection, then hold left or right to rapidly scroll
  # through consoles. This opens short lived preview movies, each creating an
  # audio source per video. Listen for audio drop-outs and run 'pw-top' and look
  # for growing numbers in the 'ERR' column.
  #
  default.clock.min-quantum = 1024
  default.clock.max-quantum = 1024
  default.clock.allowed-rates = [ 48000 ]

  # allow four streams to be processed simultaneously without congesting the
  # main thread.
  context.num-data-loops = 4

  # Lock and reuse all memory buffers to prevent malloc churn.
  mem.mlock-all = true
}
