## RETRO
default:
  # shader affects retroarch shaders
  shader: retro/sharp-bilinear-simple
  # scanline affect fba2x
  scanline: false
snes:
  shader: retro/sharp-bilinear-simple
nes:
  shader: retro/sharp-bilinear-simple
n64:
  shader: retro/sharp-bilinear-simple
gba:
  shader: handheld/gba-color
gb:
  shader: handheld/gb-palette-dmg
gbc:
  shader: handheld/gbc-color
fds:
  shader: retro/sharp-bilinear-simple
virtualboy:
  shader: retro/sharp-bilinear-simple
# Sega
sg1000:
  shader: retro/sharp-bilinear-simple
mastersystem:
  shader: retro/sharp-bilinear-simple
megadrive:
  shader: retro/sharp-bilinear-simple
gamegear:
  shader: retro/sharp-bilinear-simple
sega32x:
  shader: retro/sharp-bilinear-simple
segacd:
  shader: retro/sharp-bilinear-simple
# Arcade
neogeo:
  shader: retro/sharp-bilinear-simple
neogeocd:
  shader: retro/sharp-bilinear-simple
mame:
  shader: retro/sharp-bilinear-simple
fba:
  shader: retro/sharp-bilinear-simple
naomi:
  shader: retro/sharp-bilinear-simple
atomiswave:
  shader: retro/sharp-bilinear-simple
#
ngp:
  shader: handheld/lcd3x
ngpc:
  shader: handheld/lcd3x
gw:
  shader: retro/sharp-bilinear-simple
vectrex:
  shader:
lynx:
  shader: handheld/lcd3x
lutro:
  shader: retro/sharp-bilinear-simple
wswan:
  shader: handheld/lcd3x
wswanc:
  shader: handheld/lcd3x
pcengine:
  shader: retro/sharp-bilinear-simple
pcenginecd:
  shader: retro/sharp-bilinear-simple
supergrafx:
  shader: retro/sharp-bilinear-simple
atari800:
  shader: retro/sharp-bilinear-simple
atari2600:
  shader: retro/sharp-bilinear-simple
atari5200:
  shader: retro/sharp-bilinear-simple
atari7800:
  shader: retro/sharp-bilinear-simple
prboom:
  shader: retro/sharp-bilinear-simple
psx:
  shader: retro/sharp-bilinear-simple
colecovision:
  shader: retro/sharp-bilinear-simple
# Computers
msx:
  shader: retro/sharp-bilinear-simple
msx1:
  shader: retro/sharp-bilinear-simple
msx2:
  shader: retro/sharp-bilinear-simple
amiga:
  shader: retro/sharp-bilinear-simple
amstradcpc:
  shader: retro/sharp-bilinear-simple
atarist:
  shader: retro/sharp-bilinear-simple
zxspectrum:
  shader: retro/sharp-bilinear-simple
odyssey2:
  shader: retro/sharp-bilinear-simple
zx81:
  shader: retro/sharp-bilinear-simple
pcfx:
  shader: retro/sharp-bilinear-simple
x68000:
  shader: retro/sharp-bilinear-simple
