#!/bin/sh

# hide mouse cursor
unclutter --noevents -b

# set the keyboard
settings_lang="$(/usr/bin/batocera-settings-get system.language)"

# not always true (en_US for us), but it's really better than always english
map_name=$(echo $settings_lang | cut -c 1-2)
setxkbmap "${map_name}"

# disable dpms to prevent screen from blanking
xset -dpms
xset s off

# environment
export HOME=/userdata/system
export LC_ALL="${settings_lang}.UTF-8"
export LANG=${LC_ALL}

# because of xinerama breaking es, enable only one screen at a time
settings_output="$(/usr/bin/batocera-settings-get global.videooutput)"
batocera-resolution setOutput "${settings_output}" # empty or invalid values defaults to the first valid

# dpi override for nvidia gpus
settings_output="$(/usr/bin/batocera-settings-get global.dpi)"
[ ! -z "${settings_output}" ] && batocera-resolution setDPI "${settings_output}"

#####################
## CUSTOMISATIONS ###
# to customize your display, you can copy this file to ~/.xinitrc and then modify it

# rotate the screen
# xrandr -o left
# xrandr -o right
# xrandr -o inverted

# change the resolution
# xrandr -s 640x480

# change the resolution and the Hz
# xrandr -s 640x480 -r 60

#####################
#####################

# set user desired resolution
# nice workaround for displays which tell X11 to use strange resolutions
settings_output="$(/usr/bin/batocera-settings-get global.videomode)"
[ ! -z "${settings_output}" ] && batocera-resolution setMode "${settings_output}"

batocera-resolution minTomaxResolution

# allow coredumps for ES
ulimit -H -c unlimited
ulimit -S -c unlimited emulationstation

# dbus launch is required for the gio/gvfs/trash:///...
eval `dbus-launch --sh-syntax --exit-with-session`

# rotation
display_rotate="$(/usr/bin/batocera-settings-get display.rotate)"
EXTRA_OPTS=
test -n "${display_rotate}" && EXTRA_OPTS="--screenrotate ${display_rotate}"

cd /userdata # es needs a PWD
openbox --config-file /etc/openbox/rc.xml --startup "emulationstation --windowed ${EXTRA_OPTS}"
