#!/bin/sh

matchbox-window-manager -use_cursor no -use_titlebar no -use_desktop_mode no -use_lowlight no &

# set the keyboard
systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/recalboxSettings.pyc"
settings_lang="`$systemsetting -command load -key system.language`"

# not always true (en_US for us), but it's really better than always english
map_name=$(echo $settings_lang | cut -c 1-2)
setxkbmap "${map_name}"

# disable dpms to prevent screen from blanking
xset -dpms
xset s off

#
export HOME=/recalbox/share/system
export LC_ALL="${settings_lang}.UTF-8"
export LANG=${LC_ALL}

# because of xinerama braking es, enable only one screen at a time
systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/recalboxSettings.pyc"
settings_output="`$systemsetting -command load -key global.videooutput`"
/recalbox/scripts/recalbox-config.sh setoutput "${settings_output}"

#####################
## CUSTOMISATIONS ###
# to customize your display, you can copy this file to ~/.xinitrc and then modify it

# rotate the screen
# xrandr -o left
# xrandr -o right
# xrandr -o inverted

# change the resolution
# xrandr -s 640x480

# change the resolution and the Hz
# xrandr -s 640x480 -r 60

#####################
#####################

setMaximumResolution() {
    # maximum resolution: 1920x1080
    MAXWIDTH=1920
    MAXHEIGHT=1080
    CURRENT_RESOLUTION=$(xrandr --listResolutions | grep -E "\*$" | sed -e s+'\*$'++)
    CURRENTWIDTH=$(echo "${CURRENT_RESOLUTION}" | cut -d x -f 1)
    CURRENTHEIGHT=$(echo "${CURRENT_RESOLUTION}" | cut -d x -f 2)

    if test "${CURRENTWIDTH}" -gt "${MAXWIDTH}" -o "${CURRENTHEIGHT}" -gt "${MAXHEIGHT}"
    then
	# select a new one
	# select the first one valid
	# is it the best ? or should we loop to search the first with the same ratio ?
	xrandr --listResolutions | grep -vE "\*$" | tr "x" " " |
	    while read SUGGWIDTH SUGGHEIGHT
	    do
		if test "${SUGGWIDTH}" -le "${MAXWIDTH}" -a "${SUGGHEIGHT}" -le "${MAXHEIGHT}"
		then
		    xrandr -s "${SUGGWIDTH}x${SUGGHEIGHT}"
		    return
		fi
	    done
    fi
}

setMaximumResolution

# without windowed, time must be sleeped to wait that matchbox ended to initialize :-(
if grep -qE "^[ ]*frontend.pegasus[ ]*=[ ]*true[ ]*$" /recalbox/share/system/recalbox.conf
then
	exec pegasus-fe -platform xcb
else
	exec emulationstation --windowed
fi