#!/bin/sh

ratpoison -c remhook deletewindow "execa ratpoison-reset"
ratpoison -c remhook newwindow next
ratpoison -c "fselect 1"
ratpoison -c delete
ratpoison -c removedown
ratpoison -c removeleft
ratpoison -c removeup
ratpoison -c removeright
ratpoison -c switchtodesktop0