#!/bin/sh

case "$1" in
    start)
	systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/batoceraSettings.py"
	enabled="`$systemsetting  -command load -key system.es.atstartup`"
        if [ "$enabled" != "0" ];then
                batocera-resolution minTomaxResolution
		settings_lang="`$systemsetting -command load -key system.language`"
		cd /userdata # es need a PWD
                HOME=/userdata/system LANG="${settings_lang}.UTF-8" SDL_VIDEO_EGL_DRIVER=/usr/lib/libEGL.so SDL_NOMOUSE=1 /usr/bin/emulationstation --no-splash &
	fi
	;;
  stop)
        killall emulationstation
        if [[ $? -eq 0 ]]; then
            sleep 0.25
            while [[ -n $(pidof emulationstation) ]]; do
                sleep 0.5
                if [[ -n $watchdog ]]; then
                    [[ -e /proc/$watchdog ]] || break
                else
                    sleep 20 &
                    watchdog=$!
                fi
            done
            kill -0 $watchdog > /dev/null 2>&1 && kill -9 $watchdog
        fi
        ;;
  restart|reload)
        "$0" stop
        "$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

