#!/bin/sh
BOOTCONF="/boot/batocera-boot.conf"

. /etc/profile.d/xdg.sh
. /etc/profile.d/dbus.sh

case "$1" in
	start)
	    enabled="$(/usr/bin/batocera-settings-get system.es.atstartup)"
	    if [ "$enabled" != "0" ]; then
		%BATOCERA_EMULATIONSTATION_CMD% %BATOCERA_EMULATIONSTATION_POSTFIX%
	    fi
	    ;;

	stop)
        emulationstation-standalone --stop-rebooting
		killall openbox          2>/dev/null # for xorg
		killall sway             2>/dev/null # for wayland
		killall touchegg         2>/dev/null

		# Kill emulationstation and then wait at least 20 seconds for it to exit.
		# The watchdog 'if' block must follow immediately, as it tests the exit code of the killall.
		killall emulationstation 2>/dev/null
		if [ $? -eq 0 ]; then
			sleep 20 &
			watchdog=$!
			while ! [ -z $(pidof emulationstation) ]; do
				sleep 0.25
				$(kill -0 $watchdog) || exit
			done
			kill -9 $watchdog
		fi
		;;

	restart|reload)
		"$0" stop
		"$0" start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?

