#!/bin/sh

case "$1" in
    start)
	systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/batoceraSettings.py"
	enabled="`$systemsetting  -command load -key system.es.atstartup`"
        if [ "$enabled" != "0" ];then
		settings_lang="`$systemsetting -command load -key system.language`"
		export XAUTHORITY=/var/lib/.Xauthority # needed because $HOME/.Xauthority can't be used on fat
		# HOME is important to be able to call ~/.xinitrc
                HOME=/userdata/system startx &
	fi
	;;
  stop)
        killall emulationstation
        if [[ $? -eq 0 ]]; then
            sleep 0.25
            while [[ -n $(pidof emulationstation) ]]; do
                sleep 0.5
                if [[ -n $watchdog ]]; then
                    [[ -e /proc/$watchdog ]] || break
                else
                    sleep 20 &
                    watchdog=$!
                fi
            done
            kill -0 $watchdog > /dev/null 2>&1 && kill -9 $watchdog
        fi
        ;;
  restart|reload)
        "$0" stop
        "$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


