#!/bin/sh

matchbox-window-manager -use_titlebar no -use_cursor no -use_desktop_mode no -use_lowlight no &

# set the keyboard
systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/recalboxSettings.pyc"
settings_lang="`$systemsetting -command load -key system.language`"

# not always true (en_US for us), but it's really better than always english
map_name=$(echo $settings_lang | cut -c 1-2)
setxkbmap "${map_name}"

#
export HOME=/recalbox/share/system
export LC_ALL="${settings_lang}.UTF-8"

# without windowed, time must be sleeped to wait that matchbox ended to initialize :-(
exec emulationstation --windowed
