#!/bin/sh

matchbox-window-manager -use_titlebar no -use_desktop_mode no -use_lowlight no &

# set the keyboard
systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/recalboxSettings.pyc"
settings_lang="`$systemsetting -command load -key system.language`"

# not always true (en_US for us), but it's really better than always english
map_name=$(echo $settings_lang | cut -c 1-2)
setxkbmap "${map_name}"

# disable dpms to prevent screen from blanking
xset -dpms
xset s off

# auto hide the X11 cursor
unclutter -idle 2 &

#
export HOME=/recalbox/share/system
export LC_ALL="${settings_lang}.UTF-8"
export LANG=${LC_ALL}

# because of xinerama braking es, enable only one screen at a time
systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/recalboxSettings.pyc"
settings_output="`$systemsetting -command load -key global.videooutput`"
/recalbox/scripts/recalbox-config.sh setoutput "${settings_output}"

# without windowed, time must be sleeped to wait that matchbox ended to initialize :-(
exec emulationstation --windowed
