name: 'Setup Python Environment'
description: 'Set up Python environment and install dependencies using uv'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: "pyproject.toml"

    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        enable-cache: true

    - name: Install dependencies
      shell: bash
      run: uv sync --locked --all-extras --dev
