#!/bin/bash

# only at boot
test "$1" != "start" && exit 0

# check for an appropriate vc4 overlay line
grep -qE '^dtoverlay=vc4-fkms-v3d,cma-[0-9]*$' /boot/config.txt && exit 0

# update the file with preferred 'full' kms if not present
mount -o remount,rw /boot || exit 1
sed -i '/^[ ]*gpu_mem[ ]*=*.*$/d'       /boot/config.txt || exit 0
sed -i '/^[ ]*dtoverlay[ ]*=[ ]*$/d'	/boot/config.txt || exit 0

(echo "
gpu_mem=32
dtoverlay=vc4-fkms-v3d,cma-128") >> /boot/config.txt || exit 0
mount -o remount,ro /boot || exit 1
shutdown -r now

exit 0
