#!/bin/bash

ACTION=$1

ARCH=$(cat /usr/share/batocera/batocera.arch)

get_default_card() {
	case ${ARCH} in
		rockpro64)
			echo "2,0 ff8a0000.i2s-i2s-hifi i2s-hifi-0 HDMI [HDMI]"
		;;
		*)
			echo "unknown"
		;;
	esac
}

case "${ACTION}" in
	unlock-volume)
	echo "not supported"
	;;

	list)
	# use alsa names for backward compatibility
	LANG=C aplay -l | grep -E '^card [0-9]*:' | sed -e s+'^card \([0-9]*\): \(.*\), device \([0-9]*\): [^\[]* \[\([^]]*\)].*$'+'\1,\3 \4 \2'+
#	pactl list sinks | grep alsa.long_card_name | awk '{gsub(/"/, "", $3); print $3 " ("NR-1")"}'
	echo "auto"
	echo "custom"
	;;

	get)
	batocera-settings -command load -key audio.device
	;;

	set)
	# auto: get default card per arch
	# custom: do nothing
	# any other: set default sink in pulseadio user file
	ALSA_DEV=$2
	if [ "${ALSA_DEV}" = "custom" ]; then
		exit 0
	fi
	if [ "${ALSA_DEV}" = "auto" ]; then
		ALSA_DEV=$(get_default_card)
	fi
	ALSA_ID=$(echo ${ALSA_DEV} | awk '{print $2}')
	PA_IDX=0
	for SINK in $(pactl list sinks | grep alsa.id | awk '$1 == "alsa.id" {gsub(/"/, "", $3); print $3}'); do
		if [ "${ALSA_ID}" = "${SINK}" ]; then
			pacmd set-default-sink ${PA_IDX}
			# re-route all apps to new sink
			for APP in $(pacmd list-sink-inputs | awk '$1 == "index:" {print $2}'); do
				pacmd move-sink-input ${APP} ${PA_IDX} &>/dev/null
			done
			exit 0
		fi
		PA_IDX=$((PA_IDX+1))
	done
	echo "unknown device"
	exit 1
	;;

	set-default-sink)
	;;

	test)
	aplay "/usr/share/sounds/Mallet.wav"
esac
