#!/bin/sh
#
# Starts audio services
#

start_alsa() {
	printf "Starting alsa: "
	mode="$(/usr/bin/batocera-audio get)"
	if ! test -z "${mode}"; then
		/usr/bin/batocera-audio set ${mode} >/dev/null 2>&1
	fi
	echo "OK"
}

stop_alsa() {
	printf "Stopping alsa: "
	mount -o remount,rw /boot
	alsactl store -f /boot/asound.state
	if [ -f /userdata/system/.asoundrc ]; then
		cp /userdata/system/.asoundrc /boot/asoundrc
	else
		rm -f /boot/asoundrc
	fi
	mount -o remount,ro /boot
	echo "OK"
}

start_pulse() {
	printf "Starting pulseaudio: "
	umask 077
	start-stop-daemon -S -b -m -p /var/run/pulse.pid -x \
		/usr/bin/pulseaudio -- \
		--exit-idle-time=-1
	echo "OK"
}

stop_pulse() {
	printf "Stopping pulseaudio: "
	start-stop-daemon -K -p /var/run/pulse.pid
	echo "OK"
}

restart() {
	stop_pulse
	start_pulse
}

case "$1" in
 	start)
		start_pulse
	;;
 	stop)
		stop_pulse
	;;
 	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
