#!/bin/sh
#
# Starts audio services
#

start_alsa() {
    printf "Starting alsa: "
    # nothing to do while alsalib patch reads for /boot/asoundrc
    echo "OK"
}

stop_alsa() {
        # asoundrc is about devs and pcms
        # asound.state is more or less about volume levels

	printf "Stopping alsa: "
	mount -o remount,rw /boot
	alsactl store -f /boot/asound.state

	# in case of customisations, and batocera-audio calls
	if [ -f /userdata/system/.asoundrc ]; then
		cp /userdata/system/.asoundrc /boot/asoundrc
	else
		rm -f /boot/asoundrc
	fi

	mount -o remount,ro /boot
	echo "OK"
}

restart() {
	stop_alsa
	start_alsa
}

case "$1" in
 	start)
		start_alsa
	;;
 	stop)
		stop_alsa
	;;
 	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
