#!/bin/sh
#
# Starts audio services
#

. /etc/profile.d/xdg.sh
. /etc/profile.d/dbus.sh

start_pipewire() {
    printf "Starting pipewire: "
    mkdir -p /var/run # required for pipewire
    pipewire &
    echo "OK"
}

stop_pipewire() {
        printf "Stopping pipewire: "
	killall pipewire
	echo "OK"
}

restart() {
	stop_pipewire
	start_pipewire
}

case "$1" in
 	start)
		start_pipewire
	;;
 	stop)
		stop_pipewire
	;;
 	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
