#!/bin/sh
#
# Starts audio services
#

. /etc/profile.d/xdg.sh
. /etc/profile.d/dbus.sh

start_pipewire() {
    printf "Starting pipewire: "
    mkdir -p /var/run # required for pipewire
    pipewire &
    if [ -f /boot/batocera-boot.conf ]; then
        DEVICE=$(/usr/bin/batocera-settings-get audio.device -f /boot/batocera-boot.conf)
	if test -n "${DEVICE}"
	then
	    /usr/bin/batocera-audio set "${DEVICE}"
	fi
    fi
    echo "OK"
}

stop_pipewire() {
	printf "Stopping pipewire: "
	killall pipewire
	mount -o remount,rw /boot
	# restore is done by an pipewire patch reading this file first
	DEVICE=$(/usr/bin/batocera-settings-get audio.device)
	/usr/bin/batocera-settings-set -f /boot/batocera-boot.conf audio.device "${DEVICE}"
	mount -o remount,ro /boot
	echo "OK"
}

restart() {
	stop_pipewire
	start_pipewire
}

case "$1" in
 	start)
		start_pipewire
	;;
 	stop)
		stop_pipewire
	;;
 	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
