#!/bin/sh
#
# Starts audio services
#

BACKEND=$(batocera-settings -command load -key audio.backend)
if [ "${BACKEND}" == "" ];then
	BACKEND="alsa"
fi

start_alsa() {
	printf "Starting alsa: "
	# remove pulseaudio conf
	rm -f /etc/alsa/conf.d/99-pulseaudio-default.conf
	# batocera-audio
	ln -sf /usr/bin/batocera-audio-alsa /usr/bin/batocera-audio
	# get configured audio device from batocera.conf
	AUDIO_DEV=$(batocera-audio get)
	if [ "${AUDIO_DEV}" == "" ];then
		AUDIO_DEV="auto"
	fi	
	batocera-audio set "${AUDIO_DEV}"
	if [ -f userdata/system/asound.state ]; then
		alsactl restore -f /userdata/system/asound.state
	fi
	echo "OK"
}

stop_alsa() {
	printf "Stopping alsa: "
	alsactl store -f /userdata/system/asound.state
	echo "OK"
}

start_pulseaudio() {
	# batocera-audio
	ln -sf /usr/bin/batocera-audio-pulseaudio /usr/bin/batocera-audio
	# get configured audio device from batocera.conf
	AUDIO_DEV=$(batocera-audio get)
	if [ "${AUDIO_DEV}" == "" ];then
		AUDIO_DEV="auto"
	fi
	# default to pulseaudio
	ln -sf /etc/alsa/conf.d/99-pulseaudio-default.conf.example \
		/etc/alsa/conf.d/99-pulseaudio-default.conf
	if [ ! -f /userdata/system/.config/pulse/default.pa ]; then
		# remove alsa conf
		rm /userdata/system/.asoundrc &>/dev/null
		# custom pulseadio config. if needed
		mkdir -p /userdata/system/.config/pulse
		cat > /userdata/system/.config/pulse/default.pa <<EOF
.include /etc/pulse/default.pa
EOF
	fi
	printf "Starting pulseaudio: "
	umask 077
	PULSE_RUNTIME_PATH=/tmp/pulse HOME=/userdata/system \
		/usr/bin/pulseaudio -D \
			--disallow-exit \
			--exit-idle-time=-1 &> /dev/null
	PULSE_RUNTIME_PATH=/tmp/pulse HOME=/userdata/system batocera-audio set "${AUDIO_DEV}"
	echo "OK"
}

stop_pulseaudio() {
	printf "Stopping pulseaudio: "
	PULSE_RUNTIME_PATH=/tmp/pulse HOME=/userdata/system /usr/bin/pulseaudio --kill
	echo "OK"
}

restart() {
	stop_$BACKEND
	start_$BACKEND
}

case "$1" in
 	start)
		start_$BACKEND
	;;
 	stop)
		stop_$BACKEND
	;;
 	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
