#!/bin/sh

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2009-2014 Stephan Raue (stephan@openelec.tv)
# Copyright (C) 2018-present Team LibreELEC (https://libreelec.tv)

# setup pipewire (especially the mixer config)

mixer() {
	pactl -- set-sink-volume "$1" "$2"
}

(

# set common mixer params
mixer 0 100%

exit 0
)&
