#!/bin/sh

SERVICE=ledspicer
CONFIG_DIR="/userdata/system/configs/ledspicer"
DAEMON="/usr/bin/ledspicerd"
PIDFILE="/var/run/ledspicerd.pid"
DAEMON_ARGS=

start() {
        echo -n "Starting $SERVICE service: "

        # Use an externalized configuration directory for editing
        mkdir -p "$CONFIG_DIR"

        # Externalize /etc/ledspicer.conf, creating from example if it doesn't exist
        if [ ! -f "$CONFIG_DIR/ledspicer.conf" ]; then
                cp "/usr/share/ledspicer/doc/examples/ledspicer.conf" "$CONFIG_DIR/ledspicer.conf"
        fi
        ln -sf "$CONFIG_DIR/ledspicer.conf" "/etc/ledspicer.conf"

        # Externalize /usr/share/ledspicer configs, creating any missing files or directories from init
        find "/usr/share/ledspicer/init/share" -mindepth 1 -maxdepth 1 2>/dev/null |
        while read INIT_CFG; do
                EXT_CFG="$CONFIG_DIR/$(basename $INIT_CFG)"
                TARGET_CFG="/usr/share/ledspicer/$(basename $INIT_CFG)"
                if [ ! -e "$EXT_CFG" ]; then
                        cp -a "$INIT_CFG" "$EXT_CFG"
                fi
                ln -sf "$EXT_CFG" "$TARGET_CFG"
        done

        # Apply udev rule and trigger for any compatible devices already connected
        if [ ! -f "/userdata/system/udev/rules.d/99-ledspicer.rules" ]; then
                mkdir -p "/userdata/system/udev/rules.d"
                cp "/usr/share/ledspicer/init/udev/99-ledspicer.rules" "/userdata/system/udev/rules.d/"
                udevadm control --reload-rules
                udevadm trigger --action=add --attr-match="idVendor=d209"
                udevadm trigger --action=add --attr-match="idVendor=fafa"
                udevadm trigger --action=add --attr-match="idVendor=03eb"

        # Start the LEDSpicer daemon (ledspicerd)
        start-stop-daemon --start --quiet -m --pidfile $PIDFILE --exec $DAEMON --background -- $DAEMON_ARGS
        RETVAL=$?

	echo "done"
        return $RETVAL
}

stop() {
        echo -n "Stopping $SERVICE service: "

        # Stop the LEDSpicer daemon (ledspicerd)
        start-stop-daemon --stop --quiet --pidfile $PIDFILE
	RETVAL=$?
	
        echo "done"
        return $RETVAL
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac

exit $?