#!/bin/bash
##-Default Resolution-##
[640x480]xrandr -display :0.0 --output  [card_display] --mode "640x480"
[768x576]xrandr -display :0.0 --output  [card_display] --mode "768x576"
[1920x240]xrandr -display :0.0 --output  [card_display] --mode "1920x240"
[1920x256]xrandr -display :0.0 --output  [card_display] --mode "1920x256"
