import array as _array
from collections.abc import Callable, Iterable, Sequence
from ctypes import Array, _CData, c_ubyte, c_uint8, c_uint16, c_uint32, c_uint64
from typing import Any

__all__ = ['CTypesView', 'MemoryView', 'create_array', 'to_ctypes', 'to_list', 'to_tuple']

def to_tuple(dataseq: Iterable[Any]) -> tuple[Any, ...]: ...
def to_list(dataseq: Iterable[Any]) -> list[Any]: ...
def to_ctypes(
    dataseq: Iterable[Any] | CTypesView,
    dtype: type[_CData],
    mcount: int = 0,
) -> tuple[Array[Any], int]: ...
def create_array(obj: Iterable[Any], itemsize: int) -> _array.array[Any]: ...

class CTypesView:
    def __init__(
        self,
        obj: Any,
        itemsize: int = 1,
        docopy: bool = False,
        objsize: int | None = None,
    ) -> None: ...
    def __len__(self) -> int: ...
    def to_bytes(self) -> Array[c_uint8]: ...
    def to_uint16(self) -> Array[c_uint16]: ...
    def to_uint32(self) -> Array[c_uint32]: ...
    def to_uint64(self) -> Array[c_uint64]: ...
    @property
    def bytesize(self) -> int: ...
    @property
    def view(self) -> Array[c_ubyte]: ...
    @property
    def is_shared(self) -> bool: ...
    @property
    def object(self) -> Any: ...

class MemoryView:
    def __init__(
        self,
        source: Any,
        itemsize: int,
        strides: Sequence[int],
        getfunc: Callable[[int, int], Any] | None = None,
        setfunc: Callable[[int, int, Any], None] | None = None,
        srcsize: int | None = None,
    ) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __setitem__(self, index: int, value: Any) -> None: ...
    @property
    def size(self) -> int: ...
    @property
    def strides(self) -> Sequence[int]: ...
    @property
    def itemsize(self) -> int: ...
    @property
    def ndim(self) -> int: ...
    @property
    def source(self) -> Any: ...
