from typing import Any

__all__ = [
    'ARGB',
    'COLOR',
    'RGBA',
    'Color',
    'argb_to_color',
    'convert_to_color',
    'is_rgb_color',
    'is_rgba_color',
    'rgba_to_color',
    'string_to_color',
]

class Color:
    def __init__(self, r: int = 255, g: int = 255, b: int = 255, a: int = 255) -> None: ...
    def __copy__(self) -> Color: ...
    def __eq__(self, color: object) -> bool: ...
    def __ne__(self, color: object) -> bool: ...
    def __int__(self) -> int: ...
    def __long__(self) -> int: ...
    def __float__(self) -> float: ...
    def __index__(self) -> int: ...
    def __oct__(self) -> str: ...
    def __hex__(self) -> str: ...
    def __invert__(self) -> Color: ...
    def __mod__(self, color: Color) -> Color: ...
    def __div__(self, color: Color) -> Color: ...
    def __truediv__(self, color: Color) -> Color: ...
    def __mul__(self, color: Color) -> Color: ...
    def __sub__(self, color: Color) -> Color: ...
    def __add__(self, color: Color) -> Color: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __setitem__(self, index: int, val: int) -> None: ...
    @property
    def r(self) -> int: ...
    @r.setter
    def r(self, val: int) -> None: ...
    @property
    def g(self) -> int: ...
    @g.setter
    def g(self, val: int) -> None: ...
    @property
    def b(self) -> int: ...
    @b.setter
    def b(self, val: int) -> None: ...
    @property
    def a(self) -> int: ...
    @a.setter
    def a(self, val: int) -> None: ...
    @property
    def hsva(self) -> tuple[float, float, float, float]: ...
    @hsva.setter
    def hsva(self, value: tuple[float, float, float, float]) -> None: ...
    @property
    def hsla(self) -> tuple[float, float, float, float]: ...
    @hsla.setter
    def hsla(self, value: tuple[float, float, float, float]) -> None: ...
    @property
    def i1i2i3(self) -> tuple[float, float, float]: ...
    @i1i2i3.setter
    def i1i2i3(self, value: tuple[float, float, float]) -> None: ...
    @property
    def cmy(self) -> tuple[float, float, float]: ...
    @cmy.setter
    def cmy(self, value: tuple[float, float, float]) -> None: ...
    def normalize(self) -> tuple[float, float, float, float]: ...

def is_rgb_color(v: Any) -> bool: ...
def is_rgba_color(v: Any) -> bool: ...
def argb_to_color(v: int) -> Color: ...

ARGB = argb_to_color

def rgba_to_color(v: int) -> Color: ...

RGBA = rgba_to_color

def string_to_color(s: str) -> Color: ...
def convert_to_color(v: Any) -> Color: ...

COLOR = convert_to_color
