from sdl2.rect import SDL_Rect
from sdl2.video import SDL_DisplayMode

__all__ = ['DisplayInfo', 'get_displays']

class DisplayInfo:
    index: int
    name: str
    modes: list[SDL_DisplayMode]
    def __init__(self, index: int) -> None: ...
    @property
    def dpi(self) -> float: ...
    @property
    def current_mode(self) -> SDL_DisplayMode: ...
    @property
    def desktop_mode(self) -> SDL_DisplayMode: ...
    @property
    def bounds(self) -> SDL_Rect: ...
    def closest_mode(self, w: int, h: int, hz: int | None = None) -> SDL_DisplayMode: ...
    def has_mode(self, w: int, h: int, hz: int | None = None) -> bool: ...

def get_displays() -> list[DisplayInfo]: ...
