from collections.abc import Generator, Iterable, ValuesView
from typing import Any, Self
from uuid import UUID

__all__ = ['Applicator', 'Entity', 'System', 'World']

class Entity:
    def __new__(cls, world: World, *args: Any, **kwargs: Any) -> Self: ...
    def __hash__(self) -> int: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __delattr__(self, name: str) -> None: ...
    def delete(self) -> None: ...
    @property
    def id(self) -> UUID: ...
    @property
    def world(self) -> World: ...

class World:
    entities: set[Entity]
    components: dict[type[Any], dict[Entity, Any]]
    def __init__(self) -> None: ...
    def combined_components(self, comptypes: Iterable[type[Any]]) -> Generator[tuple[Any, ...]]: ...
    def add_componenttype(self, classtype: type[Any]) -> None: ...
    def delete(self, entity: Entity) -> None: ...
    def delete_entities(self, entities: Iterable[Entity]) -> None: ...
    def get_components(self, componenttype: type[Any]) -> Iterable[Any]: ...
    def get_entities(self, component: Any) -> list[Entity]: ...
    def add_system(self, system: System) -> None: ...
    def insert_system(self, index: int, system: System) -> None: ...
    def remove_system(self, system: System) -> None: ...
    def process(self) -> None: ...
    @property
    def systems(self) -> tuple[System, ...]: ...
    @property
    def componenttypes(self) -> ValuesView[type[Any]]: ...

class System:
    componenttypes: tuple[type[Any], ...]
    def __init__(self) -> None: ...
    def process(self, world: World, components: Iterable[Any]) -> None: ...

class Applicator(System):
    is_applicator: bool
    def __init__(self) -> None: ...
