from collections.abc import Callable
from typing import Any, Self

__all__ = ['EventHandler', 'MPEventHandler']

class EventHandler:
    callbacks: list[Callable[..., Any]]
    sender: Any
    def __init__(self, sender: Any) -> None: ...
    def __call__(self, *args: Any) -> list[Any]: ...
    def __iadd__(self, callback: Callable[..., Any]) -> Self: ...
    def __isub__(self, callback: Callable[..., Any]) -> Self: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Callable[..., Any]: ...
    def __setitem__(self, index: int, value: Callable[..., Any]) -> None: ...
    def __delitem__(self, index: int) -> None: ...
    def add(self, callback: Callable[..., Any]) -> None: ...
    def remove(self, callback: Callable[..., Any]) -> None: ...

class MPEventHandler(EventHandler):
    maxprocs: int | None
    def __init__(self, sender: Any, maxprocs: int | None = None) -> None: ...
    def __call__(self, *args: Any) -> Any: ...  # multiprocessing.pool.MapResult
