from typing import Any

from sdl2.surface import SDL_Surface

__all__ = ['get_image_formats', 'load_bmp', 'load_image', 'load_img', 'load_svg', 'pillow_to_surface', 'save_bmp']

def get_image_formats() -> tuple[str, ...]: ...
def load_bmp(path: str) -> SDL_Surface: ...
def save_bmp(source: Any, path: str, overwrite: bool = False) -> None: ...
def load_img(path: str, as_argb: bool = True) -> SDL_Surface: ...
def load_svg(path: str, width: int = 0, height: int = 0, as_argb: bool = True) -> SDL_Surface: ...
def pillow_to_surface(img: Any, as_argb: bool = True) -> SDL_Surface: ...
def load_image(fname: str, enforce: str | None = None) -> SDL_Surface: ...
