from ctypes import _Pointer

from sdl2.video import SDL_Window

from .window import Window

__all__ = [
    'ButtonState',
    'cursor_hidden',
    'hide_cursor',
    'mouse_button_state',
    'mouse_coords',
    'mouse_delta',
    'show_cursor',
    'warp_mouse',
]

class ButtonState:
    raw: int
    def __init__(self, buttonmask: int) -> None: ...
    def __eq__(self, s2: object) -> bool: ...
    def __ne__(self, s2: object) -> bool: ...
    @property
    def any_pressed(self) -> bool: ...
    @property
    def left(self) -> int: ...
    @property
    def right(self) -> int: ...
    @property
    def middle(self) -> int: ...
    @property
    def x1(self) -> int: ...
    @property
    def x2(self) -> int: ...

def show_cursor() -> None: ...
def hide_cursor() -> None: ...
def cursor_hidden() -> bool: ...
def mouse_coords(desktop: bool = False) -> tuple[int, int]: ...
def mouse_button_state() -> ButtonState: ...
def mouse_delta() -> tuple[int, int]: ...
def warp_mouse(
    x: int,
    y: int,
    window: Window | SDL_Window | _Pointer[SDL_Window] | None = None,
    desktop: bool = False,
) -> None: ...
