from collections.abc import Callable, Iterable
from typing import Any

from .ebs import System, World

__all__ = ['Particle', 'ParticleEngine']

class Particle:
    x: int
    y: int
    life: int
    def __init__(self, x: int, y: int, life: int) -> None: ...
    @property
    def position(self) -> tuple[int, int]: ...
    @position.setter
    def position(self, value: tuple[int, int]) -> None: ...

class ParticleEngine(System):
    componenttypes: tuple[type[Particle], ...]
    def __init__(self) -> None: ...
    def process(self, world: World, components: Iterable[Particle]) -> None: ...
    @property
    def createfunc(self) -> Callable[[World, list[Particle]], Any] | None: ...
    @createfunc.setter
    def createfunc(self, value: Callable[[World, list[Particle]], Any]) -> None: ...
    @property
    def deletefunc(self) -> Callable[[World, list[Particle]], Any] | None: ...
    @deletefunc.setter
    def deletefunc(self, value: Callable[[World, list[Particle]], Any]) -> None: ...
    @property
    def updatefunc(self) -> Callable[[World, set[Particle]], Any] | None: ...
    @updatefunc.setter
    def updatefunc(self, value: Callable[[World, set[Particle]], Any]) -> None: ...
