from collections.abc import Callable, Iterable
from typing import Any

from sdl2.events import SDL_Event
from sdl2.surface import SDL_Surface

from .color import Color
from .ebs import System, World
from .sprite import Sprite
from .spritesystem import SpriteFactory

__all__ = ['BUTTON', 'CHECKBUTTON', 'HOVERED', 'PRESSED', 'RELEASED', 'TEXTENTRY', 'UIFactory', 'UIProcessor']

RELEASED: int
HOVERED: int
PRESSED: int
BUTTON: int
CHECKABLE: int
CHECKBUTTON: int
TEXTENTRY: int

class UIFactory:
    spritefactory: SpriteFactory
    default_args: dict[str, Any]
    def __init__(self, spritefactory: SpriteFactory, **kwargs: Any) -> None: ...
    def from_image(self, uitype: int, fname: str) -> Sprite: ...
    def from_surface(self, uitype: int, surface: SDL_Surface, free: bool = False) -> Sprite: ...
    def from_object(self, uitype: int, obj: Any) -> Sprite: ...
    def from_color(self, uitype: int, color: Color, size: tuple[int, int]) -> Sprite: ...
    def create_button(self, **kwargs: Any) -> Sprite: ...
    def create_checkbutton(self, **kwargs: Any) -> Sprite: ...
    def create_text_entry(self, **kwargs: Any) -> Sprite: ...

class UIProcessor(System):
    componenttypes: tuple[type[object], ...]
    handlers: dict[int, Callable[[Sprite, SDL_Event], None]]
    def __init__(self) -> None: ...
    def activate(self, component: Sprite) -> None: ...
    def deactivate(self, component: Sprite) -> None: ...
    def passevent(self, component: Sprite, event: SDL_Event) -> None: ...
    def textinput(self, component: Sprite, event: SDL_Event) -> None: ...
    def mousemotion(self, component: Sprite, event: SDL_Event) -> None: ...
    def mousedown(self, component: Sprite, event: SDL_Event) -> None: ...
    def mouseup(self, component: Sprite, event: SDL_Event) -> None: ...
    def dispatch(self, obj: World | Sprite | Iterable[Sprite], event: SDL_Event | None) -> None: ...
    def process(self, world: World, components: Iterable[Sprite]) -> None: ...
