// GLSL shader autogenerated by cg2glsl.py.
#if defined(VERTEX)

#if __VERSION__ >= 130
#define COMPAT_VARYING out
#define COMPAT_ATTRIBUTE in
#define COMPAT_TEXTURE texture
#else
#define COMPAT_VARYING varying
#define COMPAT_ATTRIBUTE attribute
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec2 _texCoord;
COMPAT_VARYING     vec4 _color1;
COMPAT_VARYING     vec4 _position1;
COMPAT_VARYING     float _frame_rotation;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct out_vertex {
    vec4 _position1;
    vec4 _color1;
    vec2 _texCoord;
};
out_vertex _ret_0;
vec4 _r0008;
COMPAT_ATTRIBUTE vec4 VertexCoord;
COMPAT_ATTRIBUTE vec4 COLOR;
COMPAT_ATTRIBUTE vec4 TexCoord;
COMPAT_VARYING vec4 COL0;
COMPAT_VARYING vec4 TEX0;
 
uniform mat4 MVPMatrix;
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    _r0008 = VertexCoord.x*MVPMatrix[0];
    _r0008 = _r0008 + VertexCoord.y*MVPMatrix[1];
    _r0008 = _r0008 + VertexCoord.z*MVPMatrix[2];
    _r0008 = _r0008 + VertexCoord.w*MVPMatrix[3];
    _ret_0._position1 = _r0008;
    _ret_0._color1 = COLOR;
    _ret_0._texCoord = TexCoord.xy;
    gl_Position = _r0008;
    COL0 = COLOR;
    TEX0.xy = TexCoord.xy;
    return;
    COL0 = _ret_0._color1;
    TEX0.xy = _ret_0._texCoord;
} 
#elif defined(FRAGMENT)

#if __VERSION__ >= 130
#define COMPAT_VARYING in
#define COMPAT_TEXTURE texture
out vec4 FragColor;
#else
#define COMPAT_VARYING varying
#define FragColor gl_FragColor
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec2 _texCoord;
COMPAT_VARYING     vec4 _color;
COMPAT_VARYING     float _frame_rotation;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct out_vertex {
    vec4 _color;
    vec2 _texCoord;
};
vec4 _TMP52;
vec4 _TMP51;
vec4 _TMP50;
vec4 _TMP49;
float _TMP57;
float _TMP56;
float _TMP55;
float _TMP54;
float _TMP43;
float _TMP41;
float _TMP39;
float _TMP37;
float _TMP35;
float _TMP33;
float _TMP31;
float _TMP29;
float _TMP27;
float _TMP25;
float _TMP23;
float _TMP21;
float _TMP19;
float _TMP17;
float _TMP15;
float _TMP13;
vec4 _TMP42;
vec4 _TMP40;
vec4 _TMP38;
vec4 _TMP36;
vec4 _TMP34;
vec4 _TMP32;
vec4 _TMP30;
vec4 _TMP28;
vec4 _TMP26;
vec4 _TMP24;
vec4 _TMP22;
vec4 _TMP20;
vec4 _TMP18;
vec4 _TMP16;
vec4 _TMP14;
vec4 _TMP12;
float _TMP11;
float _TMP9;
float _TMP7;
float _TMP5;
vec4 _TMP10;
vec4 _TMP8;
vec4 _TMP6;
vec4 _TMP4;
float _TMP3;
float _TMP2;
float _TMP1;
float _TMP0;
uniform sampler2D Texture;
input_dummy _IN1;
float _x0095;
float _x0097;
float _x0099;
float _x0101;
vec2 _c0103;
vec2 _c0107;
vec2 _c0111;
vec2 _c0115;
vec2 _c0119;
vec2 _c0123;
vec2 _c0127;
vec2 _c0131;
vec2 _c0135;
vec2 _c0139;
vec2 _c0143;
vec2 _c0147;
vec2 _c0151;
vec2 _c0155;
vec2 _c0159;
vec2 _c0163;
vec2 _c0167;
vec2 _c0171;
vec2 _c0175;
vec2 _c0179;
vec2 _C0185[2];
vec2 _C0187[2];
vec2 _r0189;
float _TMP198;
float _x0199;
vec2 _c0205;
vec2 _c0207;
vec2 _c0209;
vec2 _c0211;
vec4 _C0213[1];
COMPAT_VARYING vec4 TEX0;
 
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    vec4 _c0;
    vec2 _R[2];
    vec2 _r;
    vec4 _y1;
    vec2 _a;
    vec4 _TMP62[2];
    vec2 _TMP66[2];
    vec2 _TMP68[2];
    vec2 _TMP71[4];
    _c0 = COMPAT_TEXTURE(Texture, TEX0.xy);
    _x0095 = (TEX0.x*TextureSize.x)/2.00000000E+00;
    _TMP0 = fract(_x0095);
    _x0097 = (TEX0.y*TextureSize.y)/2.00000000E+00;
    _TMP1 = fract(_x0097);
    if (_TMP0 < 5.00000000E-01 && _TMP1 < 5.00000000E-01) { 
        FragColor = _c0;
        return;
    } 
    _x0099 = (TEX0.x*TextureSize.x)/2.00000000E+00;
    _TMP2 = fract(_x0099);
    _x0101 = (TEX0.y*TextureSize.y)/2.00000000E+00;
    _TMP3 = fract(_x0101);
    if (_TMP2 > 5.00000000E-01 && _TMP3 > 5.00000000E-01) { 
        FragColor = _c0;
        return;
    } 
    _c0103 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -1.00000000E+00, 0.00000000E+00);
    _TMP4 = COMPAT_TEXTURE(Texture, _c0103);
    _TMP5 = dot(_TMP4.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0107 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 1.00000000E+00, 0.00000000E+00);
    _TMP6 = COMPAT_TEXTURE(Texture, _c0107);
    _TMP7 = dot(_TMP6.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0111 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 0.00000000E+00, 1.00000000E+00);
    _TMP8 = COMPAT_TEXTURE(Texture, _c0111);
    _TMP9 = dot(_TMP8.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0115 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 0.00000000E+00, -1.00000000E+00);
    _TMP10 = COMPAT_TEXTURE(Texture, _c0115);
    _TMP11 = dot(_TMP10.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _y1 = vec4(_TMP5, _TMP7, _TMP9, _TMP11);
    _c0119 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -3.00000000E+00, 0.00000000E+00);
    _TMP12 = COMPAT_TEXTURE(Texture, _c0119);
    _TMP13 = dot(_TMP12.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0123 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 1.00000000E+00, 0.00000000E+00);
    _TMP14 = COMPAT_TEXTURE(Texture, _c0123);
    _TMP15 = dot(_TMP14.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0127 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -1.00000000E+00, 2.00000000E+00);
    _TMP16 = COMPAT_TEXTURE(Texture, _c0127);
    _TMP17 = dot(_TMP16.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0131 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -1.00000000E+00, -2.00000000E+00);
    _TMP18 = COMPAT_TEXTURE(Texture, _c0131);
    _TMP19 = dot(_TMP18.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0135 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -1.00000000E+00, 0.00000000E+00);
    _TMP20 = COMPAT_TEXTURE(Texture, _c0135);
    _TMP21 = dot(_TMP20.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0139 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 3.00000000E+00, 0.00000000E+00);
    _TMP22 = COMPAT_TEXTURE(Texture, _c0139);
    _TMP23 = dot(_TMP22.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0143 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 1.00000000E+00, 2.00000000E+00);
    _TMP24 = COMPAT_TEXTURE(Texture, _c0143);
    _TMP25 = dot(_TMP24.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0147 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 1.00000000E+00, -2.00000000E+00);
    _TMP26 = COMPAT_TEXTURE(Texture, _c0147);
    _TMP27 = dot(_TMP26.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0151 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -2.00000000E+00, 1.00000000E+00);
    _TMP28 = COMPAT_TEXTURE(Texture, _c0151);
    _TMP29 = dot(_TMP28.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0155 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 2.00000000E+00, 1.00000000E+00);
    _TMP30 = COMPAT_TEXTURE(Texture, _c0155);
    _TMP31 = dot(_TMP30.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0159 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 0.00000000E+00, 3.00000000E+00);
    _TMP32 = COMPAT_TEXTURE(Texture, _c0159);
    _TMP33 = dot(_TMP32.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0163 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 0.00000000E+00, -1.00000000E+00);
    _TMP34 = COMPAT_TEXTURE(Texture, _c0163);
    _TMP35 = dot(_TMP34.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0167 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -2.00000000E+00, -1.00000000E+00);
    _TMP36 = COMPAT_TEXTURE(Texture, _c0167);
    _TMP37 = dot(_TMP36.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0171 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 2.00000000E+00, -1.00000000E+00);
    _TMP38 = COMPAT_TEXTURE(Texture, _c0171);
    _TMP39 = dot(_TMP38.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0175 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 0.00000000E+00, 1.00000000E+00);
    _TMP40 = COMPAT_TEXTURE(Texture, _c0175);
    _TMP41 = dot(_TMP40.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0179 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 0.00000000E+00, -3.00000000E+00);
    _TMP42 = COMPAT_TEXTURE(Texture, _c0179);
    _TMP43 = dot(_TMP42.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _TMP71[0] = vec2(_TMP13 + _TMP15, _TMP17 + _TMP19);
    _TMP71[1] = vec2(_TMP21 + _TMP23, _TMP25 + _TMP27);
    _TMP71[2] = vec2(_TMP29 + _TMP31, _TMP33 + _TMP35);
    _TMP71[3] = vec2(_TMP37 + _TMP39, _TMP41 + _TMP43);
    _C0185[0] = _TMP71[0].x*_TMP71[0] + _TMP71[1].x*_TMP71[1] + _TMP71[2].x*_TMP71[2] + _TMP71[3].x*_TMP71[3];
    _C0187[1] = _TMP71[0].y*_TMP71[0] + _TMP71[1].y*_TMP71[1] + _TMP71[2].y*_TMP71[2] + _TMP71[3].y*_TMP71[3];
    _TMP68[0] = _C0185[0];
    _R[1] = _C0187[1];
    _r0189 = _y1.x*_TMP71[0];
    _r0189 = _r0189 + _y1.y*_TMP71[1];
    _r0189 = _r0189 + _y1.z*_TMP71[2];
    _r0189 = _r0189 + _y1.w*_TMP71[3];
    _r = _r0189;
    _c0103 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -2.00000000E+00, -1.00000000E+00);
    _TMP4 = COMPAT_TEXTURE(Texture, _c0103);
    _TMP5 = dot(_TMP4.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0107 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 2.00000000E+00, 1.00000000E+00);
    _TMP6 = COMPAT_TEXTURE(Texture, _c0107);
    _TMP7 = dot(_TMP6.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0111 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -1.00000000E+00, 2.00000000E+00);
    _TMP8 = COMPAT_TEXTURE(Texture, _c0111);
    _TMP9 = dot(_TMP8.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0115 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 1.00000000E+00, -2.00000000E+00);
    _TMP10 = COMPAT_TEXTURE(Texture, _c0115);
    _TMP11 = dot(_TMP10.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _y1 = vec4(_TMP5, _TMP7, _TMP9, _TMP11);
    _c0119 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -4.00000000E+00, -1.00000000E+00);
    _TMP12 = COMPAT_TEXTURE(Texture, _c0119);
    _TMP13 = dot(_TMP12.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0123 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 0.00000000E+00, -1.00000000E+00);
    _TMP14 = COMPAT_TEXTURE(Texture, _c0123);
    _TMP15 = dot(_TMP14.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0127 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -2.00000000E+00, 1.00000000E+00);
    _TMP16 = COMPAT_TEXTURE(Texture, _c0127);
    _TMP17 = dot(_TMP16.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0131 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -2.00000000E+00, -3.00000000E+00);
    _TMP18 = COMPAT_TEXTURE(Texture, _c0131);
    _TMP19 = dot(_TMP18.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0135 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 0.00000000E+00, 1.00000000E+00);
    _TMP20 = COMPAT_TEXTURE(Texture, _c0135);
    _TMP21 = dot(_TMP20.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0139 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 4.00000000E+00, 1.00000000E+00);
    _TMP22 = COMPAT_TEXTURE(Texture, _c0139);
    _TMP23 = dot(_TMP22.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0143 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 2.00000000E+00, 3.00000000E+00);
    _TMP24 = COMPAT_TEXTURE(Texture, _c0143);
    _TMP25 = dot(_TMP24.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0147 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 2.00000000E+00, -1.00000000E+00);
    _TMP26 = COMPAT_TEXTURE(Texture, _c0147);
    _TMP27 = dot(_TMP26.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0151 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -3.00000000E+00, 2.00000000E+00);
    _TMP28 = COMPAT_TEXTURE(Texture, _c0151);
    _TMP29 = dot(_TMP28.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0155 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 1.00000000E+00, 2.00000000E+00);
    _TMP30 = COMPAT_TEXTURE(Texture, _c0155);
    _TMP31 = dot(_TMP30.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0159 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -1.00000000E+00, 4.00000000E+00);
    _TMP32 = COMPAT_TEXTURE(Texture, _c0159);
    _TMP33 = dot(_TMP32.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0163 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -1.00000000E+00, 0.00000000E+00);
    _TMP34 = COMPAT_TEXTURE(Texture, _c0163);
    _TMP35 = dot(_TMP34.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0167 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -1.00000000E+00, -2.00000000E+00);
    _TMP36 = COMPAT_TEXTURE(Texture, _c0167);
    _TMP37 = dot(_TMP36.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0171 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 3.00000000E+00, -2.00000000E+00);
    _TMP38 = COMPAT_TEXTURE(Texture, _c0171);
    _TMP39 = dot(_TMP38.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0175 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 1.00000000E+00, 0.00000000E+00);
    _TMP40 = COMPAT_TEXTURE(Texture, _c0175);
    _TMP41 = dot(_TMP40.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0179 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 1.00000000E+00, -4.00000000E+00);
    _TMP42 = COMPAT_TEXTURE(Texture, _c0179);
    _TMP43 = dot(_TMP42.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _TMP71[0] = vec2(_TMP13 + _TMP15, _TMP17 + _TMP19);
    _TMP71[1] = vec2(_TMP21 + _TMP23, _TMP25 + _TMP27);
    _TMP71[2] = vec2(_TMP29 + _TMP31, _TMP33 + _TMP35);
    _TMP71[3] = vec2(_TMP37 + _TMP39, _TMP41 + _TMP43);
    _C0185[0] = _TMP71[0].x*_TMP71[0] + _TMP71[1].x*_TMP71[1] + _TMP71[2].x*_TMP71[2] + _TMP71[3].x*_TMP71[3];
    _C0187[1] = _TMP71[0].y*_TMP71[0] + _TMP71[1].y*_TMP71[1] + _TMP71[2].y*_TMP71[2] + _TMP71[3].y*_TMP71[3];
    _TMP68[0] = _TMP68[0] + _C0185[0];
    _TMP68[1] = _R[1] + _C0187[1];
    _r0189 = _y1.x*_TMP71[0];
    _r0189 = _r0189 + _y1.y*_TMP71[1];
    _r0189 = _r0189 + _y1.z*_TMP71[2];
    _r0189 = _r0189 + _y1.w*_TMP71[3];
    _r = _r + _r0189;
    _c0103 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -2.00000000E+00, 1.00000000E+00);
    _TMP4 = COMPAT_TEXTURE(Texture, _c0103);
    _TMP5 = dot(_TMP4.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0107 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 2.00000000E+00, -1.00000000E+00);
    _TMP6 = COMPAT_TEXTURE(Texture, _c0107);
    _TMP7 = dot(_TMP6.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0111 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 1.00000000E+00, 2.00000000E+00);
    _TMP8 = COMPAT_TEXTURE(Texture, _c0111);
    _TMP9 = dot(_TMP8.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0115 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -1.00000000E+00, -2.00000000E+00);
    _TMP10 = COMPAT_TEXTURE(Texture, _c0115);
    _TMP11 = dot(_TMP10.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _y1 = vec4(_TMP5, _TMP7, _TMP9, _TMP11);
    _c0119 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -4.00000000E+00, 1.00000000E+00);
    _TMP12 = COMPAT_TEXTURE(Texture, _c0119);
    _TMP13 = dot(_TMP12.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0123 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 0.00000000E+00, 1.00000000E+00);
    _TMP14 = COMPAT_TEXTURE(Texture, _c0123);
    _TMP15 = dot(_TMP14.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0127 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -2.00000000E+00, 3.00000000E+00);
    _TMP16 = COMPAT_TEXTURE(Texture, _c0127);
    _TMP17 = dot(_TMP16.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0131 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -2.00000000E+00, -1.00000000E+00);
    _TMP18 = COMPAT_TEXTURE(Texture, _c0131);
    _TMP19 = dot(_TMP18.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0135 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 0.00000000E+00, -1.00000000E+00);
    _TMP20 = COMPAT_TEXTURE(Texture, _c0135);
    _TMP21 = dot(_TMP20.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0139 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 4.00000000E+00, -1.00000000E+00);
    _TMP22 = COMPAT_TEXTURE(Texture, _c0139);
    _TMP23 = dot(_TMP22.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0143 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 2.00000000E+00, 1.00000000E+00);
    _TMP24 = COMPAT_TEXTURE(Texture, _c0143);
    _TMP25 = dot(_TMP24.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0147 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 2.00000000E+00, -3.00000000E+00);
    _TMP26 = COMPAT_TEXTURE(Texture, _c0147);
    _TMP27 = dot(_TMP26.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0151 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -1.00000000E+00, 2.00000000E+00);
    _TMP28 = COMPAT_TEXTURE(Texture, _c0151);
    _TMP29 = dot(_TMP28.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0155 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 3.00000000E+00, 2.00000000E+00);
    _TMP30 = COMPAT_TEXTURE(Texture, _c0155);
    _TMP31 = dot(_TMP30.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0159 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 1.00000000E+00, 4.00000000E+00);
    _TMP32 = COMPAT_TEXTURE(Texture, _c0159);
    _TMP33 = dot(_TMP32.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0163 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 1.00000000E+00, 0.00000000E+00);
    _TMP34 = COMPAT_TEXTURE(Texture, _c0163);
    _TMP35 = dot(_TMP34.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0167 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -3.00000000E+00, -2.00000000E+00);
    _TMP36 = COMPAT_TEXTURE(Texture, _c0167);
    _TMP37 = dot(_TMP36.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0171 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 1.00000000E+00, -2.00000000E+00);
    _TMP38 = COMPAT_TEXTURE(Texture, _c0171);
    _TMP39 = dot(_TMP38.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0175 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -1.00000000E+00, 0.00000000E+00);
    _TMP40 = COMPAT_TEXTURE(Texture, _c0175);
    _TMP41 = dot(_TMP40.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0179 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -1.00000000E+00, -4.00000000E+00);
    _TMP42 = COMPAT_TEXTURE(Texture, _c0179);
    _TMP43 = dot(_TMP42.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _TMP71[0] = vec2(_TMP13 + _TMP15, _TMP17 + _TMP19);
    _TMP71[1] = vec2(_TMP21 + _TMP23, _TMP25 + _TMP27);
    _TMP71[2] = vec2(_TMP29 + _TMP31, _TMP33 + _TMP35);
    _TMP71[3] = vec2(_TMP37 + _TMP39, _TMP41 + _TMP43);
    _C0185[0] = _TMP71[0].x*_TMP71[0] + _TMP71[1].x*_TMP71[1] + _TMP71[2].x*_TMP71[2] + _TMP71[3].x*_TMP71[3];
    _C0187[1] = _TMP71[0].y*_TMP71[0] + _TMP71[1].y*_TMP71[1] + _TMP71[2].y*_TMP71[2] + _TMP71[3].y*_TMP71[3];
    _TMP68[0] = _TMP68[0] + _C0185[0];
    _TMP68[1] = _TMP68[1] + _C0187[1];
    _r0189 = _y1.x*_TMP71[0];
    _r0189 = _r0189 + _y1.y*_TMP71[1];
    _r0189 = _r0189 + _y1.z*_TMP71[2];
    _r0189 = _r0189 + _y1.w*_TMP71[3];
    _r = _r + _r0189;
    _TMP66[0] = _TMP68[0]/2.40000000E+01;
    _TMP66[1] = _TMP68[1]/2.40000000E+01;
    _r = _r/2.40000000E+01;
    _TMP54 = _r.x*_TMP66[1].y - _r.y*_TMP66[1].x;
    _TMP55 = _TMP66[0].x*_r.y - _TMP66[0].y*_r.x;
    _TMP56 = _TMP66[0].x*_TMP66[1].y - _TMP66[0].y*_TMP66[1].x;
    _a = vec2(_TMP54, _TMP55)/_TMP56;
    _x0199 = _a.x - _a.y;
    _TMP57 = min(1.00000000E+00, _x0199);
    _TMP198 = max(-1.00000000E+00, _TMP57);
    _a = 2.50000000E-01 + vec2( 5.00000000E-01, -5.00000000E-01)*_TMP198;
    _c0205 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( -1.00000000E+00, 0.00000000E+00);
    _TMP49 = COMPAT_TEXTURE(Texture, _c0205);
    _c0207 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 1.00000000E+00, 0.00000000E+00);
    _TMP50 = COMPAT_TEXTURE(Texture, _c0207);
    _c0209 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 0.00000000E+00, 1.00000000E+00);
    _TMP51 = COMPAT_TEXTURE(Texture, _c0209);
    _c0211 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y)*vec2( 0.00000000E+00, -1.00000000E+00);
    _TMP52 = COMPAT_TEXTURE(Texture, _c0211);
    _TMP62[0] = _TMP49 + _TMP50;
    _TMP62[1] = _TMP51 + _TMP52;
    _C0213[0] = _a.x*_TMP62[0] + _a.y*_TMP62[1];
    FragColor = _C0213[0];
    return;
} 
#endif
