// GLSL shader autogenerated by cg2glsl.py.
#if defined(VERTEX)

#if __VERSION__ >= 130
#define COMPAT_VARYING out
#define COMPAT_ATTRIBUTE in
#define COMPAT_TEXTURE texture
#else
#define COMPAT_VARYING varying
#define COMPAT_ATTRIBUTE attribute
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec2 _texCoord;
COMPAT_VARYING     vec4 _color1;
COMPAT_VARYING     vec4 _position1;
COMPAT_VARYING     float _frame_rotation;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct out_vertex {
    vec4 _position1;
    vec4 _color1;
    vec2 _texCoord;
};
out_vertex _ret_0;
vec4 _r0008;
COMPAT_ATTRIBUTE vec4 VertexCoord;
COMPAT_ATTRIBUTE vec4 COLOR;
COMPAT_ATTRIBUTE vec4 TexCoord;
COMPAT_VARYING vec4 COL0;
COMPAT_VARYING vec4 TEX0;
 
uniform mat4 MVPMatrix;
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    _r0008 = VertexCoord.x*MVPMatrix[0];
    _r0008 = _r0008 + VertexCoord.y*MVPMatrix[1];
    _r0008 = _r0008 + VertexCoord.z*MVPMatrix[2];
    _r0008 = _r0008 + VertexCoord.w*MVPMatrix[3];
    _ret_0._position1 = _r0008;
    _ret_0._color1 = COLOR;
    _ret_0._texCoord = TexCoord.xy;
    gl_Position = _r0008;
    COL0 = COLOR;
    TEX0.xy = TexCoord.xy;
    return;
    COL0 = _ret_0._color1;
    TEX0.xy = _ret_0._texCoord;
} 
#elif defined(FRAGMENT)

#if __VERSION__ >= 130
#define COMPAT_VARYING in
#define COMPAT_TEXTURE texture
out vec4 FragColor;
#else
#define COMPAT_VARYING varying
#define FragColor gl_FragColor
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec2 _texCoord;
COMPAT_VARYING     vec4 _color;
COMPAT_VARYING     float _frame_rotation;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct out_vertex {
    vec4 _color;
    vec2 _texCoord;
};
vec4 _TMP50;
vec4 _TMP49;
vec4 _TMP48;
vec4 _TMP47;
float _TMP55;
float _TMP54;
float _TMP53;
float _TMP52;
float _TMP41;
float _TMP39;
float _TMP37;
float _TMP35;
float _TMP33;
float _TMP31;
float _TMP29;
float _TMP27;
float _TMP25;
float _TMP23;
float _TMP21;
float _TMP19;
float _TMP17;
float _TMP15;
float _TMP13;
float _TMP11;
vec4 _TMP40;
vec4 _TMP38;
vec4 _TMP36;
vec4 _TMP34;
vec4 _TMP32;
vec4 _TMP30;
vec4 _TMP28;
vec4 _TMP26;
vec4 _TMP24;
vec4 _TMP22;
vec4 _TMP20;
vec4 _TMP18;
vec4 _TMP16;
vec4 _TMP14;
vec4 _TMP12;
vec4 _TMP10;
float _TMP9;
float _TMP7;
float _TMP5;
float _TMP3;
vec4 _TMP8;
vec4 _TMP6;
vec4 _TMP4;
vec4 _TMP2;
float _TMP1;
float _TMP0;
uniform sampler2D Texture;
input_dummy _IN1;
float _x0093;
float _x0095;
vec2 _c0097;
vec2 _c0101;
vec2 _c0105;
vec2 _c0109;
vec2 _c0113;
vec2 _c0117;
vec2 _c0121;
vec2 _c0125;
vec2 _c0129;
vec2 _c0133;
vec2 _c0137;
vec2 _c0141;
vec2 _c0145;
vec2 _c0149;
vec2 _c0153;
vec2 _c0157;
vec2 _c0161;
vec2 _c0165;
vec2 _c0169;
vec2 _c0173;
vec2 _C0179[2];
vec2 _C0181[2];
vec2 _r0183;
float _TMP192;
float _x0193;
vec2 _c0199;
vec2 _c0201;
vec2 _c0203;
vec2 _c0205;
vec4 _C0207[1];
COMPAT_VARYING vec4 TEX0;
 
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    vec4 _c0;
    vec2 _R[2];
    vec2 _r;
    vec4 _y1;
    vec2 _a;
    vec4 _TMP60[2];
    vec2 _TMP64[2];
    vec2 _TMP66[2];
    vec2 _TMP69[4];
    _c0 = COMPAT_TEXTURE(Texture, TEX0.xy);
    _x0093 = TEX0.x*TextureSize.x;
    _TMP0 = fract(_x0093);
    _x0095 = TEX0.y*TextureSize.y;
    _TMP1 = fract(_x0095);
    if (_TMP0 < 5.00000000E-01 || _TMP1 < 5.00000000E-01) { 
        FragColor = _c0;
        return;
    } 
    _c0097 = TEX0.xy + -vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP2 = COMPAT_TEXTURE(Texture, _c0097);
    _TMP3 = dot(_TMP2.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0101 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP4 = COMPAT_TEXTURE(Texture, _c0101);
    _TMP5 = dot(_TMP4.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0105 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, 1.00000000E+00);
    _TMP6 = COMPAT_TEXTURE(Texture, _c0105);
    _TMP7 = dot(_TMP6.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0109 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, -1.00000000E+00);
    _TMP8 = COMPAT_TEXTURE(Texture, _c0109);
    _TMP9 = dot(_TMP8.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _y1 = vec4(_TMP3, _TMP5, _TMP7, _TMP9);
    _c0113 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, -3.00000000E+00);
    _TMP10 = COMPAT_TEXTURE(Texture, _c0113);
    _TMP11 = dot(_TMP10.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0117 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP12 = COMPAT_TEXTURE(Texture, _c0117);
    _TMP13 = dot(_TMP12.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0121 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, 1.00000000E+00);
    _TMP14 = COMPAT_TEXTURE(Texture, _c0121);
    _TMP15 = dot(_TMP14.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0125 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, -3.00000000E+00);
    _TMP16 = COMPAT_TEXTURE(Texture, _c0125);
    _TMP17 = dot(_TMP16.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0129 = TEX0.xy + -vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP18 = COMPAT_TEXTURE(Texture, _c0129);
    _TMP19 = dot(_TMP18.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0133 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, 3.00000000E+00);
    _TMP20 = COMPAT_TEXTURE(Texture, _c0133);
    _TMP21 = dot(_TMP20.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0137 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, 3.00000000E+00);
    _TMP22 = COMPAT_TEXTURE(Texture, _c0137);
    _TMP23 = dot(_TMP22.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0141 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, -1.00000000E+00);
    _TMP24 = COMPAT_TEXTURE(Texture, _c0141);
    _TMP25 = dot(_TMP24.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0145 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, -1.00000000E+00);
    _TMP26 = COMPAT_TEXTURE(Texture, _c0145);
    _TMP27 = dot(_TMP26.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0149 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, 3.00000000E+00);
    _TMP28 = COMPAT_TEXTURE(Texture, _c0149);
    _TMP29 = dot(_TMP28.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0153 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, 3.00000000E+00);
    _TMP30 = COMPAT_TEXTURE(Texture, _c0153);
    _TMP31 = dot(_TMP30.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0157 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, -1.00000000E+00);
    _TMP32 = COMPAT_TEXTURE(Texture, _c0157);
    _TMP33 = dot(_TMP32.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0161 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, -3.00000000E+00);
    _TMP34 = COMPAT_TEXTURE(Texture, _c0161);
    _TMP35 = dot(_TMP34.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0165 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, 1.00000000E+00);
    _TMP36 = COMPAT_TEXTURE(Texture, _c0165);
    _TMP37 = dot(_TMP36.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0169 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, 1.00000000E+00);
    _TMP38 = COMPAT_TEXTURE(Texture, _c0169);
    _TMP39 = dot(_TMP38.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0173 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, -3.00000000E+00);
    _TMP40 = COMPAT_TEXTURE(Texture, _c0173);
    _TMP41 = dot(_TMP40.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _TMP69[0] = vec2(_TMP11 + _TMP13, _TMP15 + _TMP17);
    _TMP69[1] = vec2(_TMP19 + _TMP21, _TMP23 + _TMP25);
    _TMP69[2] = vec2(_TMP27 + _TMP29, _TMP31 + _TMP33);
    _TMP69[3] = vec2(_TMP35 + _TMP37, _TMP39 + _TMP41);
    _C0179[0] = _TMP69[0].x*_TMP69[0] + _TMP69[1].x*_TMP69[1] + _TMP69[2].x*_TMP69[2] + _TMP69[3].x*_TMP69[3];
    _C0181[1] = _TMP69[0].y*_TMP69[0] + _TMP69[1].y*_TMP69[1] + _TMP69[2].y*_TMP69[2] + _TMP69[3].y*_TMP69[3];
    _TMP66[0] = _C0179[0];
    _R[1] = _C0181[1];
    _r0183 = _y1.x*_TMP69[0];
    _r0183 = _r0183 + _y1.y*_TMP69[1];
    _r0183 = _r0183 + _y1.z*_TMP69[2];
    _r0183 = _r0183 + _y1.w*_TMP69[3];
    _r = _r0183;
    _c0097 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, -1.00000000E+00);
    _TMP2 = COMPAT_TEXTURE(Texture, _c0097);
    _TMP3 = dot(_TMP2.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0101 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, 1.00000000E+00);
    _TMP4 = COMPAT_TEXTURE(Texture, _c0101);
    _TMP5 = dot(_TMP4.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0105 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, 3.00000000E+00);
    _TMP6 = COMPAT_TEXTURE(Texture, _c0105);
    _TMP7 = dot(_TMP6.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0109 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, -3.00000000E+00);
    _TMP8 = COMPAT_TEXTURE(Texture, _c0109);
    _TMP9 = dot(_TMP8.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _y1 = vec4(_TMP3, _TMP5, _TMP7, _TMP9);
    _c0113 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -5.00000000E+00, -3.00000000E+00);
    _TMP10 = COMPAT_TEXTURE(Texture, _c0113);
    _TMP11 = dot(_TMP10.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0117 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, 1.00000000E+00);
    _TMP12 = COMPAT_TEXTURE(Texture, _c0117);
    _TMP13 = dot(_TMP12.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0121 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -5.00000000E+00, 1.00000000E+00);
    _TMP14 = COMPAT_TEXTURE(Texture, _c0121);
    _TMP15 = dot(_TMP14.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0125 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, -3.00000000E+00);
    _TMP16 = COMPAT_TEXTURE(Texture, _c0125);
    _TMP17 = dot(_TMP16.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0129 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, -1.00000000E+00);
    _TMP18 = COMPAT_TEXTURE(Texture, _c0129);
    _TMP19 = dot(_TMP18.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0133 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 5.00000000E+00, 3.00000000E+00);
    _TMP20 = COMPAT_TEXTURE(Texture, _c0133);
    _TMP21 = dot(_TMP20.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0137 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, 3.00000000E+00);
    _TMP22 = COMPAT_TEXTURE(Texture, _c0137);
    _TMP23 = dot(_TMP22.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0141 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 5.00000000E+00, -1.00000000E+00);
    _TMP24 = COMPAT_TEXTURE(Texture, _c0141);
    _TMP25 = dot(_TMP24.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0145 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, 1.00000000E+00);
    _TMP26 = COMPAT_TEXTURE(Texture, _c0145);
    _TMP27 = dot(_TMP26.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0149 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, 5.00000000E+00);
    _TMP28 = COMPAT_TEXTURE(Texture, _c0149);
    _TMP29 = dot(_TMP28.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0153 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, 5.00000000E+00);
    _TMP30 = COMPAT_TEXTURE(Texture, _c0153);
    _TMP31 = dot(_TMP30.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0157 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP32 = COMPAT_TEXTURE(Texture, _c0157);
    _TMP33 = dot(_TMP32.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0161 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, -5.00000000E+00);
    _TMP34 = COMPAT_TEXTURE(Texture, _c0161);
    _TMP35 = dot(_TMP34.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0165 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, -1.00000000E+00);
    _TMP36 = COMPAT_TEXTURE(Texture, _c0165);
    _TMP37 = dot(_TMP36.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0169 = TEX0.xy + -vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP38 = COMPAT_TEXTURE(Texture, _c0169);
    _TMP39 = dot(_TMP38.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0173 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, -5.00000000E+00);
    _TMP40 = COMPAT_TEXTURE(Texture, _c0173);
    _TMP41 = dot(_TMP40.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _TMP69[0] = vec2(_TMP11 + _TMP13, _TMP15 + _TMP17);
    _TMP69[1] = vec2(_TMP19 + _TMP21, _TMP23 + _TMP25);
    _TMP69[2] = vec2(_TMP27 + _TMP29, _TMP31 + _TMP33);
    _TMP69[3] = vec2(_TMP35 + _TMP37, _TMP39 + _TMP41);
    _C0179[0] = _TMP69[0].x*_TMP69[0] + _TMP69[1].x*_TMP69[1] + _TMP69[2].x*_TMP69[2] + _TMP69[3].x*_TMP69[3];
    _C0181[1] = _TMP69[0].y*_TMP69[0] + _TMP69[1].y*_TMP69[1] + _TMP69[2].y*_TMP69[2] + _TMP69[3].y*_TMP69[3];
    _TMP66[0] = _TMP66[0] + _C0179[0];
    _TMP66[1] = _R[1] + _C0181[1];
    _r0183 = _y1.x*_TMP69[0];
    _r0183 = _r0183 + _y1.y*_TMP69[1];
    _r0183 = _r0183 + _y1.z*_TMP69[2];
    _r0183 = _r0183 + _y1.w*_TMP69[3];
    _r = _r + _r0183;
    _c0097 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, 1.00000000E+00);
    _TMP2 = COMPAT_TEXTURE(Texture, _c0097);
    _TMP3 = dot(_TMP2.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0101 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, -1.00000000E+00);
    _TMP4 = COMPAT_TEXTURE(Texture, _c0101);
    _TMP5 = dot(_TMP4.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0105 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, 3.00000000E+00);
    _TMP6 = COMPAT_TEXTURE(Texture, _c0105);
    _TMP7 = dot(_TMP6.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0109 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, -3.00000000E+00);
    _TMP8 = COMPAT_TEXTURE(Texture, _c0109);
    _TMP9 = dot(_TMP8.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _y1 = vec4(_TMP3, _TMP5, _TMP7, _TMP9);
    _c0113 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -5.00000000E+00, -1.00000000E+00);
    _TMP10 = COMPAT_TEXTURE(Texture, _c0113);
    _TMP11 = dot(_TMP10.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0117 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, 3.00000000E+00);
    _TMP12 = COMPAT_TEXTURE(Texture, _c0117);
    _TMP13 = dot(_TMP12.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0121 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -5.00000000E+00, 3.00000000E+00);
    _TMP14 = COMPAT_TEXTURE(Texture, _c0121);
    _TMP15 = dot(_TMP14.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0125 = TEX0.xy + -vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP16 = COMPAT_TEXTURE(Texture, _c0125);
    _TMP17 = dot(_TMP16.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0129 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, -3.00000000E+00);
    _TMP18 = COMPAT_TEXTURE(Texture, _c0129);
    _TMP19 = dot(_TMP18.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0133 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 5.00000000E+00, 1.00000000E+00);
    _TMP20 = COMPAT_TEXTURE(Texture, _c0133);
    _TMP21 = dot(_TMP20.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0137 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP22 = COMPAT_TEXTURE(Texture, _c0137);
    _TMP23 = dot(_TMP22.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0141 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 5.00000000E+00, -3.00000000E+00);
    _TMP24 = COMPAT_TEXTURE(Texture, _c0141);
    _TMP25 = dot(_TMP24.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0145 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, 1.00000000E+00);
    _TMP26 = COMPAT_TEXTURE(Texture, _c0145);
    _TMP27 = dot(_TMP26.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0149 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, 5.00000000E+00);
    _TMP28 = COMPAT_TEXTURE(Texture, _c0149);
    _TMP29 = dot(_TMP28.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0153 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, 5.00000000E+00);
    _TMP30 = COMPAT_TEXTURE(Texture, _c0153);
    _TMP31 = dot(_TMP30.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0157 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, 1.00000000E+00);
    _TMP32 = COMPAT_TEXTURE(Texture, _c0157);
    _TMP33 = dot(_TMP32.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0161 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, -5.00000000E+00);
    _TMP34 = COMPAT_TEXTURE(Texture, _c0161);
    _TMP35 = dot(_TMP34.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0165 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, -1.00000000E+00);
    _TMP36 = COMPAT_TEXTURE(Texture, _c0165);
    _TMP37 = dot(_TMP36.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0169 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, -1.00000000E+00);
    _TMP38 = COMPAT_TEXTURE(Texture, _c0169);
    _TMP39 = dot(_TMP38.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0173 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, -5.00000000E+00);
    _TMP40 = COMPAT_TEXTURE(Texture, _c0173);
    _TMP41 = dot(_TMP40.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _TMP69[0] = vec2(_TMP11 + _TMP13, _TMP15 + _TMP17);
    _TMP69[1] = vec2(_TMP19 + _TMP21, _TMP23 + _TMP25);
    _TMP69[2] = vec2(_TMP27 + _TMP29, _TMP31 + _TMP33);
    _TMP69[3] = vec2(_TMP35 + _TMP37, _TMP39 + _TMP41);
    _C0179[0] = _TMP69[0].x*_TMP69[0] + _TMP69[1].x*_TMP69[1] + _TMP69[2].x*_TMP69[2] + _TMP69[3].x*_TMP69[3];
    _C0181[1] = _TMP69[0].y*_TMP69[0] + _TMP69[1].y*_TMP69[1] + _TMP69[2].y*_TMP69[2] + _TMP69[3].y*_TMP69[3];
    _TMP66[0] = _TMP66[0] + _C0179[0];
    _TMP66[1] = _TMP66[1] + _C0181[1];
    _r0183 = _y1.x*_TMP69[0];
    _r0183 = _r0183 + _y1.y*_TMP69[1];
    _r0183 = _r0183 + _y1.z*_TMP69[2];
    _r0183 = _r0183 + _y1.w*_TMP69[3];
    _r = _r + _r0183;
    _TMP64[0] = _TMP66[0]/2.40000000E+01;
    _TMP64[1] = _TMP66[1]/2.40000000E+01;
    _r = _r/2.40000000E+01;
    _TMP52 = _r.x*_TMP64[1].y - _r.y*_TMP64[1].x;
    _TMP53 = _TMP64[0].x*_r.y - _TMP64[0].y*_r.x;
    _TMP54 = _TMP64[0].x*_TMP64[1].y - _TMP64[0].y*_TMP64[1].x;
    _a = vec2(_TMP52, _TMP53)/_TMP54;
    _x0193 = _a.x - _a.y;
    _TMP55 = min(1.00000000E+00, _x0193);
    _TMP192 = max(-1.00000000E+00, _TMP55);
    _a = 2.50000000E-01 + vec2( 5.00000000E-01, -5.00000000E-01)*_TMP192;
    _c0199 = TEX0.xy + -vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP47 = COMPAT_TEXTURE(Texture, _c0199);
    _c0201 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP48 = COMPAT_TEXTURE(Texture, _c0201);
    _c0203 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, 1.00000000E+00);
    _TMP49 = COMPAT_TEXTURE(Texture, _c0203);
    _c0205 = TEX0.xy + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, -1.00000000E+00);
    _TMP50 = COMPAT_TEXTURE(Texture, _c0205);
    _TMP60[0] = _TMP47 + _TMP48;
    _TMP60[1] = _TMP49 + _TMP50;
    _C0207[0] = _a.x*_TMP60[0] + _a.y*_TMP60[1];
    FragColor = _C0207[0];
    return;
} 
#endif
