#!/bin/sh
#
# GPIO init for RTW88_8821CS SDIO
#

start() {
	echo "Starting RTW88 network services..."
	info_output=$(batocera-info)
	if [[ $info_output == *"Model: RG353V"*]]; then
		echo 5 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio5/direction
		echo 1 > /sys/class/gpio/gpio5/value
	fi
}

stop() {
	echo "Shutting down RTW88 network services..."
	info_output=$(batocera-info)
	if [[ $info_output == *"Model: RG353V"*]]; then
	    echo 0 > /sys/class/gpio/gpio5/value
	fi
}	

restart() {
	echo "Restarting RTW88 network services..."
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
