#!/bin/bash
#
# GPIO init for RTW88_8821CS SDIO
# dmanlfc - updated 13 July 2024
#

start() {
	info_output=$(batocera-info | grep "Model:" | awk -F": " '{print $2}' | head -n 1)
	if [[ $info_output == "RG353V" ]]; then
	    echo "Starting RG353V RTW88 network adaptor..."
	    if [ ! -d /sys/class/gpio/gpio5 ]; then
	        echo 5 > /sys/class/gpio/export
			echo out > /sys/class/gpio/gpio5/direction
			echo 1 > /sys/class/gpio/gpio5/value
			modrpobe rtw88_8821cs
	    fi
	fi
}

stop() {
	info_output=$(batocera-info | grep "Model:" | awk -F": " '{print $2}' | head -n 1)
	if [[ $info_output == "RG353V" ]]; then
	    echo "Shutting down RG353V RTW88 network adaptor..."
	    if [ -d /sys/class/gpio/gpio5 ]; then
	        echo 0 > /sys/class/gpio/gpio5/value
			modrpobe -r rtw88_8821cs
	    fi
	fi
}	

restart() {
	echo "Restarting RTW88 network adaptor..."
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
