#!/bin/sh

if [ "$(/usr/bin/batocera-settings-get -f /boot/config.txt is_gpicase)" = 1 ]; then
    exit 0
fi

mount -o remount,rw /boot

echo "# ====== GPi Case setup section =====
# WARNING: EDITING THIS SECTION MAY RESULT IN BOOT FAILURE
is_gpicase=1
dtoverlay=dpi24_gpicase
dtoverlay=pwm-audio-pi-zero_gpicase
display_rotate=1
overscan_left=0
overscan_right=0
overscan_top=0
overscan_bottom=0
framebuffer_width=320
framebuffer_height=240
enable_dpi_lcd=1
display_default_lcd=1
dpi_group=2
dpi_mode=87
dpi_output_format=0x6016
#hdmi_timings=320 0 28 18 28 480 0 2 2 4 0 0 0 60 0 32000000 6
hdmi_timings=240 1 38 10 20 320 1 20 4 4 0 0 0 60 0 6400000 1
dtoverlay=pwm-2chan_gpicase,pin=18,func=2,pin2=19,func2=2
disable_pvt=1
disable_audio_dither=1
# ====== End of GPi Case setup section =====" >> /boot/config.txt

echo "gpicase settings added. Rebooting now..."
shutdown -r now
