#!/bin/sh

if grep '^include [ ]*gpicase\.txt' /boot/config.txt; then
    exit 0
fi

mount -o remount,rw /boot

cat <<'BOOTCONFIG' > /boot/gpicase.txt
# ====== GPi Case setup
# WARNING: EDITING THIS FILE MAY RESULT IN BOOT FAILURE
dtoverlay=dpi24_gpicase
dtoverlay=pwm-audio-pi-zero_gpicase
display_rotate=1
overscan_left=0
overscan_right=0
overscan_top=0
overscan_bottom=0
framebuffer_width=320
framebuffer_height=240
enable_dpi_lcd=1
display_default_lcd=1
dpi_group=2
dpi_mode=87
dpi_output_format=0x6016
#hdmi_timings=320 0 28 18 28 480 0 2 2 4 0 0 0 60 0 32000000 6
hdmi_timings=240 1 38 10 20 320 1 20 4 4 0 0 0 60 0 6400000 1
dtoverlay=pwm-2chan_gpicase,pin=18,func=2,pin2=19,func2=2
disable_pvt=1
disable_audio_dither=1
BOOTCONFIG

cat <<'BOOTCONFIG' > /boot/config.txt
# WARNING: DO NOT REMOVE THIS LINE:
include gpicase.txt

BOOTCONFIG

echo '/boot/gpicase.txt written, rebooting now...'
shutdown -r now
