#!/bin/sh

case "$1" in
    start)
	systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/batoceraSettings.py"
	enabled="`$systemsetting  -command load -key system.es.atstartup`"
        if [ "$enabled" != "0" ];then
                batocera-resolution minTomaxResolution
		settings_lang="`$systemsetting -command load -key system.language`"
		cd /userdata # es need a PWD
                HOME=/userdata/system LANG="${settings_lang}.UTF-8" SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2.so SDL_VIDEO_EGL_DRIVER=/usr/lib/libGLESv2.so SDL_NOMOUSE=1 /usr/bin/emulationstation --no-splash --resolution 480 320 &
	fi
	;;
  stop)
        killall emulationstation
        if [[ $? -eq 0 ]]; then
            sleep 20 &
            watchdog=$!
            while [[ -n $(pidof emulationstation) ]]; do
                sleep 0.25
                $(kill -0 $watchdog) || exit
            done
            kill -9 $watchdog
        fi
        ;;
  restart|reload)
        "$0" stop
        "$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

