#!/bin/bash
# RetroLX poor man's makedb
# lightweight pacman database creation
# @rtissera
#
# 20210629 - Initial revision

ARCH="$1"
HOST_DIR="$2"

PATH=$(HOST_DIR)/usr/bin:$PATH repo-add retrolx-$ARCH.db.tar.gz *.pkg.tar.zst

