#!/bin/sh
#

case "$1" in
  start)
    alsactl restore -f /userdata/asound.state
    amixer cset name='Playback Path' 'SPK'
    amixer cset name='Master Playback Volume' 100
    ;;
  stop)
    alsactl store -f /userdata/asound.state
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
