#!/bin/sh
#

case "$1" in
  start)
    evsieve --input /dev/input/event0 /dev/input/event1 grab --output name="ps5000-gamepad" &
    ;;
  stop)
    killall evsieve
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
