################################################################################
#
# libspatialaudio
#
################################################################################
# Version: Commits on Oct 8, 2026
LIBSPATIALAUDIO_VERSION = d149ed9744fd399b835c6f2920511f8cbcfce5ea
LIBSPATIALAUDIO_SITE = $(call github,videolan,libspatialaudio,$(LIBSPATIALAUDIO_VERSION))
LIBSPATIALAUDIO_LICENSE = LGPL-2.1+
LIBSPATIALAUDIO_LICENSE_FILES = LICENSE
LIBSPATIALAUDIO_DEPENDENCIES = libmysofa
LIBSPATIALAUDIO_SUPPORTS_IN_SOURCE_BUILD = NO
LIBSPATIALAUDIO_INSTALL_STAGING = YES
LIBSPATIALAUDIO_INSTALL_TARGET = NO

LIBSPATIALAUDIO_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
LIBSPATIALAUDIO_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
LIBSPATIALAUDIO_CONF_OPTS += -DBUILD_TESTING=OFF
LIBSPATIALAUDIO_CONF_OPTS += -DCMAKE_POSITION_INDEPENDENT_CODE=ON
LIBSPATIALAUDIO_CONF_OPTS += -DMYSOFA_INCLUDE_DIRS=$(STAGING_DIR)/usr/include
LIBSPATIALAUDIO_CONF_OPTS += -DMYSOFA_LIBRARIES=$(STAGING_DIR)/usr/lib/libmysofa.a

$(eval $(cmake-package))
