################################################################################
#
# batocera-launch-libretro
#
################################################################################

BATOCERA_LAUNCH_LIBRETRO_SETUP_TYPE=hatch
BATOCERA_LAUNCH_LIBRETRO_DEPENDENCIES = \
	python-batocera-common \
	batocera-launch

BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES =

ifeq ($(BR2_PACKAGE_LIBRETRO_HATARI)$(BR2_PACKAGE_LIBRETRO_HATARIB),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += _hatari_core.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_GENESISPLUSGX)$(BR2_PACKAGE_LIBRETRO_GENESISPLUSGX_EXPANDED)$(BR2_PACKAGE_LIBRETRO_PICODRIVE),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += _megadrive_core.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_MUPEN64PLUS_NEXT)$(BR2_PACKAGE_LIBRETRO_PARALLEL_N64),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += _n64_core.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_SNES9X)$(BR2_PACKAGE_LIBRETRO_SNES9X_NEXT),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += _snes9x_core.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_ATARI800),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += atari800.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_AZAHAR),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += azahar.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_BEETLE_SATURN),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += beetle_saturn.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_BK),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += bk.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_BLUEMSX),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += bluemsx.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_BOOM3),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += boom3.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_BSNES)$(BR2_PACKAGE_LIBRETRO_BSNES_HD),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += bsnes.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_CAP32),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += cap32.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_DESMUME),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += desmume.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_DICE),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += dice.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_DOLPHIN),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += dolphin.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_DOSBOX_PURE),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += dosbox_pure.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_EP128EMU_CORE),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += ep128emu_core.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_FAKE08),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += fake08.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_FBNEO),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += fbneo.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_FCEUMM),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += fceumm.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_FLYCAST)$(BR2_PACKAGE_LIBRETRO_FLYCASTVL),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += flycast.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_FUSE),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += fuse.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_GAMBATTE),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += gambatte.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_GEARCOLECO),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += gearcoleco.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_GENESISPLUSGX)$(BR2_PACKAGE_LIBRETRO_GENESISPLUSGX_EXPANDED),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += genesisplusgx.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_GENESISPLUSGX_WIDE),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += genesisplusgx_wide.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_HANDY),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += handy.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_HATARI),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += hatari.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_HATARIB),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += hatarib.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_KRONOS),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += kronos.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_BEETLE_PSX),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += mednafen_psx.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_BEETLE_SUPERGRAFX),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += mednafen_supergrafx.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_BEETLE_WSWAN),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += mednafen_wswan.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_MELONDS),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += melonds.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_MELONDS_DS),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += melondsds.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_MESEN),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += mesen.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_MESENS),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += mesen_s.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_MGBA),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += mgba.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_MRBOOM),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += mrboom.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_MUPEN64PLUS_NEXT),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += mupen64plus_next.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_NEOCD),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += neocd.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_NESTOPIA),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += nestopia.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_PC98),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += np2kai.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_O2EM),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += o2em.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_OPERA),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += opera.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_PARALLEL_N64),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += parallel_n64.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_BEETLE_PCE)$(BR2_PACKAGE_LIBRETRO_BEETLE_PCE_FAST),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += pce.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_BEETLE_PCFX),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += pcfx.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_PS2),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += pcsx2.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_PCSX),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += pcsx_rearmed.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_PD777),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += pd777.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_PICODRIVE),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += picodrive.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_POKEMINI),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += pokemini.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_POCKETSNES),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += pocketsnes.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_WATARA),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += potator.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_PPSSPP),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += ppsspp.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_PRBOOM),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += prboom.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_PUAE),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += puae.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_PX68K),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += px68k.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_PC88),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += quasi88.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_REMINISCENCE),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += reminiscence.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_SCUMMVM),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += scummvm.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_SNES9X),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += snes9x.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_SNES9X_NEXT),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += snes9x_next.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_STELLA),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += stella.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_SUPERBROSWAR),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += superbroswar.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_SWANSTATION),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += swanstation.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_TGBDUAL),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += tgbdual.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_THEODORE),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += theodore.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_TYRQUAKE),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += tyrquake.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_UAE4ARM),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += uae4arm.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_BEETLE_VB),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += vb.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_VBA_M),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += vba_m.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_VECX),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += vecx.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_VICE),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += vice_x128.py
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += vice_x64.py
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += vice_xpet.py
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += vice_xplus4.py
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += vice_xvic.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_VIRTUALJAGUAR),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += virtualjaguar.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_VITAQUAKE2),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += vitaquake2.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_XRICK),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += xrick.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_YABASANSHIRO),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += yabasanshiro.py
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_81),)
BATOCERA_LAUNCH_LIBRETRO_EXCLUDED_CORE_MODULES += zx81.py
endif

BATOCERA_LAUNCH_LIBRETRO_LOCAL_PYTHON_EXCLUSIONS = $(addprefix batocera_launch_libretro/cores/,$(BATOCERA_LAUNCH_EXCLUDED_CORE_MODULES))

$(eval $(local-python-package))
