[project]
name = "batocera-launch-libretro"
version = '44.0'
dependencies = [
    'batocera-common',
    'batocera-launch',
]

[project.entry-points."batocera_launch.emulators"]
libretro = 'batocera_launch_libretro:Libretro'

[project.entry-points."batocera_launch_libretro.cores"]
81 = 'batocera_launch_libretro.cores.zx81:ZX81'
atari800 = 'batocera_launch_libretro.cores.atari800:Atari800'
azahar = 'batocera_launch_libretro.cores.azahar:Azahar'
beetle-saturn = 'batocera_launch_libretro.cores.beetle_saturn:BeetleSaturn'
bk = 'batocera_launch_libretro.cores.bk:BK'
bluemsx = 'batocera_launch_libretro.cores.bluemsx:BlueMSX'
boom3 = 'batocera_launch_libretro.cores.boom3:Boom3'
bsnes = 'batocera_launch_libretro.cores.bsnes:Bsnes'
bsnes_hd = 'batocera_launch_libretro.cores.bsnes:Bsnes'
cap32 = 'batocera_launch_libretro.cores.cap32:Cap32'
desmume = 'batocera_launch_libretro.cores.desmume:Desmume'
dice = 'batocera_launch_libretro.cores.dice:Dice'
dolphin = 'batocera_launch_libretro.cores.dolphin:Dolphin'
dosbox_pure = 'batocera_launch_libretro.cores.dosbox_pure:DosboxPure'
duckstation = 'batocera_launch_libretro.cores.swanstation:Duckstation'
ep128emu-core = 'batocera_launch_libretro.cores.ep128emu_core:Ep128emuCore'
fake08 = 'batocera_launch_libretro.cores.fake08:Fake08'
fbneo = 'batocera_launch_libretro.cores.fbneo:Fbneo'
fceumm = 'batocera_launch_libretro.cores.fceumm:Fceumm'
flycast = 'batocera_launch_libretro.cores.flycast:Flycast'
flycastvl = 'batocera_launch_libretro.cores.flycast:FlycastVL'
fuse = 'batocera_launch_libretro.cores.fuse:Fuse'
gambatte = 'batocera_launch_libretro.cores.gambatte:Gambatte'
gearcoleco = 'batocera_launch_libretro.cores.gearcoleco:Gearcoleco'
genesisplusgx = 'batocera_launch_libretro.cores.genesisplusgx:GenesisPlusGX'
genesisplusgx-expanded = 'batocera_launch_libretro.cores.genesisplusgx:GenesisPlusGXExpanded'
genesisplusgx-wide = 'batocera_launch_libretro.cores.genesisplusgx_wide:GenesisPlusGXWide'
handy = 'batocera_launch_libretro.cores.handy:Handy'
hatari = 'batocera_launch_libretro.cores.hatari:Hatari'
hatarib = 'batocera_launch_libretro.cores.hatarib:Hatarib'
kronos = 'batocera_launch_libretro.cores.kronos:Kronos'
mednafen_psx = 'batocera_launch_libretro.cores.mednafen_psx:MednafenPsx'
mednafen_supergrafx = 'batocera_launch_libretro.cores.mednafen_supergrafx:MednafenSupergrafx'
mednafen_wswan = 'batocera_launch_libretro.cores.mednafen_wswan:MednafenWswan'
melonds = 'batocera_launch_libretro.cores.melonds:MelonDS'
melondsds = 'batocera_launch_libretro.cores.melondsds:MelonDSDS'
mesen = 'batocera_launch_libretro.cores.mesen:Mesen'
mesen-s = 'batocera_launch_libretro.cores.mesen_s:MesenS'
mgba = 'batocera_launch_libretro.cores.mgba:Mgba'
mrboom = 'batocera_launch_libretro.cores.mrboom:Mrboom'
mupen64plus-next = 'batocera_launch_libretro.cores.mupen64plus_next:Mupen64PlusNext'
neocd = 'batocera_launch_libretro.cores.neocd:Neocd'
nestopia = 'batocera_launch_libretro.cores.nestopia:Nestopia'
np2kai = 'batocera_launch_libretro.cores.np2kai:Np2kai'
o2em = 'batocera_launch_libretro.cores.o2em:O2em'
opera = 'batocera_launch_libretro.cores.opera:Opera'
parallel_n64 = 'batocera_launch_libretro.cores.parallel_n64:ParallelN64'
pce = 'batocera_launch_libretro.cores.pce:Pce'
pce_fast = 'batocera_launch_libretro.cores.pce:Pce'
pcfx = 'batocera_launch_libretro.cores.pcfx:Pcfx'
pcsx2 = 'batocera_launch_libretro.cores.pcsx2:Pcsx2'
pcsx_rearmed = 'batocera_launch_libretro.cores.pcsx_rearmed:PcsxRearmed'
pd777 = 'batocera_launch_libretro.cores.pd777:Pd777'
picodrive = 'batocera_launch_libretro.cores.picodrive:Picodrive'
pokemini = 'batocera_launch_libretro.cores.pokemini:Pokemini'
pocketsnes = 'batocera_launch_libretro.cores.pocketsnes:Pocketsnes'
potator = 'batocera_launch_libretro.cores.potator:Potator'
ppsspp = 'batocera_launch_libretro.cores.ppsspp:Ppsspp'
prboom = 'batocera_launch_libretro.cores.prboom:Prboom'
puae = 'batocera_launch_libretro.cores.puae:Puae'
px68k = 'batocera_launch_libretro.cores.px68k:Px68k'
quasi88 = 'batocera_launch_libretro.cores.quasi88:Quasi88'
reminiscence = 'batocera_launch_libretro.cores.reminiscence:Reminiscence'
scummvm = 'batocera_launch_libretro.cores.scummvm:ScummVM'
snes9x = 'batocera_launch_libretro.cores.snes9x:Snes9x'
snes9x_next = 'batocera_launch_libretro.cores.snes9x_next:Snes9xNext'
stella = 'batocera_launch_libretro.cores.stella:Stella'
superbroswar = 'batocera_launch_libretro.cores.superbroswar:Superbroswar'
swanstation = 'batocera_launch_libretro.cores.swanstation:Swanstation'
tgbdual = 'batocera_launch_libretro.cores.tgbdual:TGBDual'
theodore = 'batocera_launch_libretro.cores.theodore:Theodore'
tyrquake = 'batocera_launch_libretro.cores.tyrquake:Tyrquake'
uae4arm = 'batocera_launch_libretro.cores.uae4arm:Uae4arm'
vb = 'batocera_launch_libretro.cores.vb:Vb'
vba-m = 'batocera_launch_libretro.cores.vba_m:VbaM'
vecx = 'batocera_launch_libretro.cores.vecx:Vecx'
vice_x64 = 'batocera_launch_libretro.cores.vice_x64:ViceX64'
vice_x64sc = 'batocera_launch_libretro.cores.vice_x64:ViceX64sc'
vice_x128 = 'batocera_launch_libretro.cores.vice_x128:ViceX128'
vice_xpet = 'batocera_launch_libretro.cores.vice_xpet:ViceXpet'
vice_xplus4 = 'batocera_launch_libretro.cores.vice_xplus4:ViceXplus4'
vice_xscpu64 = 'batocera_launch_libretro.cores.vice_x64:ViceX64sc'
vice_xvic = 'batocera_launch_libretro.cores.vice_xvic:ViceXvic'
virtualjaguar = 'batocera_launch_libretro.cores.virtualjaguar:VirtualJaguar'
vitaquake2 = 'batocera_launch_libretro.cores.vitaquake2:Vitaquake2'
xrick = 'batocera_launch_libretro.cores.xrick:Xrick'
yabasanshiro = 'batocera_launch_libretro.cores.yabasanshiro:YabaSanshiro'

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
include = ["/batocera_launch_libretro"]
