#!/bin/sh

do_usage() {
	echo "$1 list"
	echo "$1 get"
	echo "$1 set {auto|<device>}"
	echo "$1 test"
}	

do_select_audiodevice() {
	if echo "${MODE}" | grep -qE '^[0-9]*'; then
		SINK_ID="$(echo "$MODE" | sed -e"s/^\([0-9]*\).*/\1/")"
		pactl set-default-sink "${SINK_ID}"
	else
		# No valid device selected
		return 1
	fi
}

ACTION="$1"

case "${ACTION}" in
	list)
	    printf '%s\n' "auto"
	    # on 2nd step, keep only name after the last . if it exists (custom sinks may have no .)
	    pactl list short sinks | sed -e s+"^\([0-9]*\)\t\([^\t]*\)\t.*$"+"\1 \2"+ -e s+"^\([0-9]*\) .*\.\([^\.]*\)$"+'\1 \2'+
	;;

	get)
	    /usr/bin/batocera-settings-get audio.device
	;;

	set)
		MODE="$2"
		case "${MODE}" in
			auto)
				# do nothing!
			;;
			*)
				do_select_audiodevice
		esac
		;;

	getSystemVolume)
	    DEFAULT_SINK=$(pactl info | grep -E '^Default Sink: ' | sed -e s+"^Default Sink: "+""+ | head -1)
	    pactl list sinks-raw | grep -E '^[^ ]* name='"${DEFAULT_SINK}"' ' | sed -e s+"^.* Volume="++
	    ;;

	setSystemVolume)
	    VOLUME="$2"
	    case "${VOLUME}" in
		"mute")
		    pactl set-sink-mute @DEFAULT_SINK@ 1
		    ;;
		"unmute")
		    pactl set-sink-mute @DEFAULT_SINK@ 0
		    ;;
		"mute-toggle")
		    pactl set-sink-mute @DEFAULT_SINK@ toggle
		    ;;
		*)
		    if echo "${VOLUME}" | grep -qE '^[+-]?[0-9]*$'
		    then
			pactl set-sink-volume @DEFAULT_SINK@ "${VOLUME}%"
		    else
			echo "invalid volume value" >&2
		    fi
	    esac
	    ;;

	test)
		aplay "/usr/share/sounds/Mallet.wav"
	;;
	*)
		do_usage $(basename $0)
esac
