#!/bin/sh

ACTION="$1"

case "${ACTION}" in
	list)
		printf '%s\n' auto speakers headphone
	;;

	get)
		/usr/bin/batocera-settings-get audio.device
	;;

	set)
		MODE="$2"
		case "${MODE}" in
			auto | speakers)
				sed -e "s;%CARDNO%;0;g" -e "s;%DEVICENO%;0;g" /usr/share/batocera/alsa/asoundrc-dmix+softvol > /userdata/system/.asoundrc
				amixer cset name='Playback Path' SPK
			;;

			headphone)
				sed -e "s;%CARDNO%;0;g" -e "s;%DEVICENO%;0;g" /usr/share/batocera/alsa/asoundrc-dmix+softvol > /userdata/system/.asoundrc
				amixer cset name='Playback Path' HP
			;;
		esac
	;;

	test)
		aplay "/usr/share/sounds/Mallet.wav"
	;;
esac
