#!/bin/bash	

ACTION=$1	

case "${ACTION}" in	
	"unlock-volume")
		echo "obsolete"
	;;	

	"list")	
		echo "auto"	
		echo "hdmi"
		echo "headphones"
		echo "custom"
	;;	

	"get")	
		batocera-settings -r audio.device	
	;;	

	"set")	
		MODE=$2	
		case "${MODE}" in	
			"auto" | "hdmi")
				# card 2: HDMI [HDMI], device 0: ff8a0000.i2s-i2s-hifi i2s-hifi-0 [ff8a0000.i2s-i2s-hifi i2s-hifi-0]
				sed -e "s;%CARDNO%;2;g" -e "s;%DEVICENO%;0;g" /usr/share/batocera/alsa/asoundrc-dmix+softvol > /userdata/system/.asoundrc
			;;

			"headphones")
				# card 0: ES8316 [ES8316], device 0: ff890000.i2s-ES8316 HiFi ES8316 HiFi-0 [ff890000.i2s-ES8316 HiFi ES8316 HiFi-0]
				sed -e "s;%CARDNO%;0;g" -e "s;%DEVICENO%;0;g" /usr/share/batocera/alsa/asoundrc-dmix+softvol > /userdata/system/.asoundrc
			;;

			"custom")
				# do nothing!
			;;
		esac	
	;;

	test)
		aplay "/usr/share/sounds/Mallet.wav"
	;;
esac
