#!/bin/bash

soundDisabled() {
    grep -qE "^[ ]*splashsound[ ]*=[ ]*false[ ]*$" /boot/batocera-boot.conf
}

do_start ()
{
    if ls /boot/*.mp4 >/dev/null 2>/dev/null
    then
        do_videostart "$(ls /boot/*.mp4 | sed -e "$((RANDOM%$(ls -1 /boot/*.mp4 | wc -l)+1))!d")"
    elif [[ $(ls /boot/*.{jpg,png}  2>/dev/null) ]]
    then
        do_imagestart "$(ls /boot/*.{jpg,png} | sed -e "$((RANDOM%$(ls -1 /boot/*.{jpg,png} | wc -l)+1))!d")"
    else
        do_videostart "/usr/share/batocera/splash/splash.mp4"
    fi
}

do_imagestart()
{
    image="$1"
    # on some sytems, fb0 is not immediatly loaded, so, keep a chance by waiting a bit
    N=0
    while ! test -e /dev/fb0 -o $N -gt 15
    do
        sleep 1
        let N++
    done
    test -e /dev/fb0 && fbv -f -i "${image}"
    sleep infinity
    wait $!
}

do_videostart ()
{
    video="$1"
    # Launch the video
    omx_fnt="--font=/usr/share/fonts/dejavu/DejaVuSans-BoldOblique.ttf"
    omx_opt="--no-keys --layer=10000 --aspect-mode=fill"
    omx_srt="--no-ghost-box --lines=1 --align=left $omx_fnt --font-size=20 --subtitles=/usr/share/batocera/splash/splash.srt"

    omx_nosound=
    if soundDisabled
    then
        omx_nosound="-n -1"
    fi

    /usr/bin/omxplayer -o both $omx_opt $omx_srt $omx_nosound "$video" &
    wait $!    
}


case "$1" in
    start)
	grep -qE '^[ ]*autoresize[ ]*=[ ]*true[ ]*$' "/boot/batocera-boot.conf" && exit 0
	#We use that later to disable splash at all
        #grep -qE '^[ ]*bootsplash[ ]*=[ ]*true[ ]*$' "/boot/batocera-boot.conf" || exit 0
        do_start &
        ;;
    stop)
        echo "Executing /etc/init/S29abortsplash"
        /etc/init.d/S29abortsplash stop
        ;;
    restart|reload)
        ;;
    *)
esac

exit $?
