#!/bin/bash

soundDisabled() {
    grep -qE "^[ ]*splashsound[ ]*=[ ]*false[ ]*$" /boot/batocera-boot.conf
}

do_start ()
{
    if ls /boot/*.mp4 >/dev/null 2>/dev/null
    then
        do_videostart "$(ls /boot/*.mp4 | sed -e "$((RANDOM%$(ls -1 /boot/*.mp4 | wc -l)+1))!d")"
    elif ls /boot/*.png >/dev/null 2>/dev/null
    then
        do_imagestart "$(ls /boot/*.png | sed -e "$((RANDOM%$(ls -1 /boot/*.png | wc -l)+1))!d")"
    else
        do_videostart "/usr/share/batocera/splash/splash.mp4"
    fi
}

do_imagestart()
{
    image="$1"
    # on some sytems, fb0 is not immediatly loaded, so, keep a chance by waiting a bit
    N=0
    while ! test -e /dev/fb0 -o $N -gt 15
    do
        sleep 1
        let N++
    done
    test -e /dev/fb0 && fbv -f -i "${image}"
}

do_videostart ()
{
    video="$1"
    # Initialize dbus session
    OMXPLAYER_DBUS_ADDR="/tmp/omxplayerdbus.root"
    OMXPLAYER_DBUS_PID="/tmp/omxplayerdbus.root.pid"
    exec 5> "$OMXPLAYER_DBUS_ADDR"
    exec 6> "$OMXPLAYER_DBUS_PID"
    dbus-daemon --fork --print-address 5 --print-pid 6 --session
    until [ -s "$OMXPLAYER_DBUS_ADDR" ]; do
        echo "waiting for dbus address to appear" >&2
        sleep .2
    done
    DBUS_SESSION_BUS_ADDRESS=`cat $OMXPLAYER_DBUS_ADDR`
    DBUS_SESSION_BUS_PID=`cat $OMXPLAYER_DBUS_PID`
    export DBUS_SESSION_BUS_ADDRESS
    export DBUS_SESSION_BUS_PID

    # Launch the video
    omx_fnt="--font=/usr/share/fonts/dejavu/DejaVuSans-BoldOblique.ttf"
    omx_opt="--no-keys --layer=10000 --aspect-mode=fill"
    omx_srt="--no-ghost-box --lines=1 --align=left $omx_fnt --font-size=20 --subtitles=/usr/share/batocera/splash/splash.srt"

    omx_nosound=
    if soundDisabled
    then
        omx_nosound="-n -1"
    fi

    # -911 = Volume set to 35% (On omxplayer)
    # 1/(10^(911/2000)) = 0.35034828830157

    /usr/bin/omxplayer -o both --vol -2500 $omx_opt $omx_srt $omx_nosound "$video" &
    PID=$!

    # Stop the video when ready
    if [[ $? -eq 0 ]]; then
        # Wait for emulationstation or Kodi, but not more than 20 seconds
        count=0
        while [[ ! -f "/tmp/emulationstation.ready" && ! -e "/var/run/kodi.msg" && $count -lt 400 ]]; do
            sleep 0.1
            ((count++))
        done
        # Finish with a one second fade out.
        audio_fade=1
        video_fade=250
        while [[ $video_fade -gt 0 ]]; do
            sleep .02
            dbus-send --print-reply=literal --session --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Volume double:$audio_fade >/dev/null
            dbus-send --print-reply=literal --session --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.SetAlpha objpath:/not/used int64:$video_fade >/dev/null
            audio_fade=`echo "$audio_fade .02" | awk '{printf "%.2f", $1-$2}'`
            ((video_fade=video_fade-5))
        done
        # Ready flag set or timeout occured; stop video process.
        dbus-send --print-reply=literal --session --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Action int32:15 >/dev/null
    fi
}

case "$1" in
    start)
	grep -qE '^[ ]*autoresize[ ]*=[ ]*true[ ]*$' "/boot/batocera-boot.conf" && exit 0
        do_start &
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
esac

exit $?
