#!/bin/sh

DAEMON="splash"

soundDisabled() {
    grep -qE "^[ ]*splash.screen.sound[ ]*=[ ]*0[ ]*$" /boot/batocera-boot.conf
}

do_start ()
{
    if ls /boot/splash/*.mp4 >/dev/null 2>/dev/null
    then
        do_videostart "$(ls /boot/splash/*.mp4 | sed -e "$((RANDOM%$(ls -1 /boot/splash/*.mp4 | wc -l)+1))!d")"
    elif [[ $(ls /boot/splash/*.{jpg,png}  2>/dev/null) ]]
    then
        do_imagestart "$(ls /boot/splash/*.{jpg,png} | sed -e "$((RANDOM%$(ls -1 /boot/splash/*.{jpg,png} | wc -l)+1))!d")"
    else
        do_videostart "/usr/share/batocera/splash/splash.mp4"
    fi
}

do_imagestart()
{
    image="$1"
    # on some sytems, fb0 is not immediatly loaded, so, keep a chance by waiting a bit
    N=0
    while ! test -e /dev/fb0 -o $N -gt 15
    do
        sleep 1
        let N++
    done
    test -e /dev/fb0 && fbv -f -i "${image}"
    sleep infinity
    wait $!
}

do_videostart ()
{
    video="$1"
    mpv_opt=
    if soundDisabled
    then
        mpv_opt=--no-audio
    fi
    /usr/bin/mpv --really-quiet --no-config $mpv_opt "$video" &
    wait $!
}

case "$1" in
    start)
        printf 'Starting %s: ' "$DAEMON"
        grep -qE '^[ ]*splash.screen.enabled[ ]*=[ ]*0[ ]*$' "/boot/batocera-boot.conf" && exit 0
        do_start &
        echo "OK"
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
esac

exit $?
