#!/bin/bash
FM_PICTURE=".*\.\(jpg\|jpeg\|png\)"
FM_VIDEO=".*\.\(mp4\)"
SPLASH_DIR="/boot/splash"
DEFAULT="/usr/share/batocera/splash/splash.mp4"

do_filerandomize ()
{
    [ -d "$SPLASH_DIR" ] || return 1
    readarray -t array < <(find $SPLASH_DIR -regex "$1" -maxdepth 1 -type f)
    if [[ ${#array[@]} -gt 0 ]]; then
        echo "${array[$RANDOM % ${#array[@]}]}"
        return 0
    else
        return 1
    fi
}

soundDisabled() {
    grep -qE "^[ ]*splashsound[ ]*=[ ]*false[ ]*$" /boot/batocera-boot.conf
}

do_start ()
{
    file=$(do_filerandomize "$FM_PICTURE")
    if [[ $? -eq 0 ]]; then
        do_imagestart "$file"
    else
        file=$(do_filerandomize "$FM_VIDEO")
        [[ $? -eq 0 ]] || file="$DEFAULT"
	do_videostart "$file"
    fi
}

do_imagestart()
{
    image="$1"
    # on some sytems, fb0 is not immediatly loaded, so, keep a chance by waiting a bit
    N=0
    while ! test -e /dev/fb0 -o $N -gt 15
    do
        sleep 1
        let N++
    done
    test -e /dev/fb0 && fbv -f -i "${image}"
}

do_videostart ()
{
    video="$1"
    mpv_opt=
    if soundDisabled
    then
        mpv_opt=--no-audio
    fi
    /usr/bin/mpv --no-config $mpv_opt "$video" &
    PID=$!
    # Wait for emulationstation or Kodi, but not more than 20 seconds
    count=0
    while [[ ! -f "/tmp/emulationstation.ready" && ! -e "/var/run/kodi.msg" && $count -lt 400 ]]; do
        sleep 0.1
        ((count++))
    done
    kill -9 "${PID}"
}

case "$1" in
    start)
	grep -qE '^[ ]*autoresize[ ]*=[ ]*true[ ]*$' "/boot/batocera-boot.conf" && exit 0
	do_start &
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
esac

exit $?
