#!/bin/bash

soundDisabled() {
    grep -qE "^[ ]*splashsound[ ]*=[ ]*false[ ]*$" /boot/batocera-boot.conf
}

do_start ()
{
    if ls /boot/*.mp4 >/dev/null 2>/dev/null
    then
        do_videostart "$(ls /boot/*.mp4 | sed -e "$((RANDOM%$(ls -1 /boot/*.mp4 | wc -l)+1))!d")"
    elif [[ $(ls /boot/*.{jpg,png}  2>/dev/null) ]]
    then
        do_imagestart "$(ls /boot/*.{jpg,png} | sed -e "$((RANDOM%$(ls -1 /boot/*.{jpg,png} | wc -l)+1))!d")"
    else
        do_videostart "/usr/share/batocera/splash/splash.mp4"
    fi
}

do_imagestart()
{
    image="$1"
    # on some sytems, fb0 is not immediatly loaded, so, keep a chance by waiting a bit
    N=0
    while ! test -e /dev/fb0 -o $N -gt 15
    do
        sleep 1
        let N++
    done
    test -e /dev/fb0 && fbv -f -i "${image}"
    sleep infinity
    wait $!
}

do_videostart ()
{
    video="$1"
    ffplay_opt=
    if soundDisabled
    then
        ffplay_opt=-an
    fi
    /usr/bin/ffplay $ffplay_opt -autoexit -loglevel 0 "$video" &
    wait $! 
}

case "$1" in
    start)
	grep -qE '^[ ]*autoresize[ ]*=[ ]*true[ ]*$' "/boot/batocera-boot.conf" && exit 0
        do_start &
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
esac

exit $?
