#!/bin/bash

do_start ()
{
    if ls /boot/*.png /boot/*.jpg >/dev/null 2>/dev/null
    then
        image="$(ls /boot/*.png /boot/*.jpg | sed -e "$((RANDOM%$(ls -1 /boot/*.png /boot/*.jpg | wc -l)+1))!d")"
    else
        image="/usr/share/batocera/splash/logo-version.png"
    fi

    # on some sytems, fb0 is not immediatly loaded, so, keep a chance by waiting a bit
    N=0
    while ! test -e /dev/fb0 -o $N -gt 15
    do
        sleep 1
        let N++
    done
    test -e /dev/fb0 && fbv -f -i "${image}"
}

case "$1" in
    start)
	grep -qE '^[ ]*autoresize[ ]*=[ ]*true[ ]*$' "/boot/batocera-boot.conf" && exit 0
        do_start &
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
esac

exit $?
