#!/bin/bash

soundDisabled() {
    grep -qE "^[ ]*splashsound[ ]*=[ ]*false[ ]*$" /boot/batocera-boot.conf
}

do_start ()
{
    if ls /boot/*.mp4 >/dev/null 2>/dev/null
    then
        do_videostart "$(ls /boot/*.mp4 | sed -e "$((RANDOM%$(ls -1 /boot/*.mp4 | wc -l)+1))!d")"
    elif [[ $(ls /boot/*.{jpg,png}  2>/dev/null) ]]
    then
        do_imagestart "$(ls /boot/*.{jpg,png} | sed -e "$((RANDOM%$(ls -1 /boot/*.{jpg,png} | wc -l)+1))!d")"
    else
        do_videostart "/usr/share/batocera/splash/splash.mp4"
    fi
}

do_imagestart()
{
    image="$1"
    # on some sytems, fb0 is not immediatly loaded, so, keep a chance by waiting a bit
    N=0
    while ! test -e /dev/fb0 -o $N -gt 15
    do
        sleep 1
        let N++
    done
    test -e /dev/fb0 && fbv -f -i "${image}"
}

do_videostart ()
{
    video="$1"
    # Initialize dbus session ----- WE DO not need imho
#    OMXPLAYER_DBUS_ADDR="/tmp/omxplayerdbus.root"
#    OMXPLAYER_DBUS_PID="/tmp/omxplayerdbus.root.pid"
#    exec 5> "$OMXPLAYER_DBUS_ADDR"
#    exec 6> "$OMXPLAYER_DBUS_PID"
#    dbus-daemon --fork --print-address 5 --print-pid 6 --session
#    until [ -s "$OMXPLAYER_DBUS_ADDR" ]; do
#        echo "waiting for dbus address to appear" >&2
#        sleep .2
#    done
#    DBUS_SESSION_BUS_ADDRESS=`cat $OMXPLAYER_DBUS_ADDR`
#    DBUS_SESSION_BUS_PID=`cat $OMXPLAYER_DBUS_PID`
#    export DBUS_SESSION_BUS_ADDRESS
#    export DBUS_SESSION_BUS_PID

    # Launch the video
    omx_fnt="--font=/usr/share/fonts/dejavu/DejaVuSans-BoldOblique.ttf"
    omx_opt="--no-keys --layer=10000 --aspect-mode=fill"
    omx_srt="--no-ghost-box --lines=1 --align=left $omx_fnt --font-size=20 --subtitles=/usr/share/batocera/splash/splash.srt"

    omx_nosound=
    if soundDisabled
    then
        omx_nosound="-n -1"
    fi

    # -911 = Volume set to 35% (On omxplayer)
    # 1/(10^(911/2000)) = 0.35034828830157

    # Later we remove the volume ... the user/video creator is responsible for audio volume
    /usr/bin/omxplayer -o both --vol -2500 $omx_opt $omx_srt $omx_nosound "$video" &
    
    # Here we create the videoplay.pid --- we should do the same for picture (just to divide if a picture was loaded with success)
    PID=$! 
    echo $PID > /tmp/videoplayer.pid
    wait $PID
    rm -f /tmp/videoplayer.pid
}


case "$1" in
    start)
	grep -qE '^[ ]*autoresize[ ]*=[ ]*true[ ]*$' "/boot/batocera-boot.conf" && exit 0
	#We use that later to disable splash at all
        #grep -qE '^[ ]*bootsplash[ ]*=[ ]*true[ ]*$' "/boot/batocera-boot.conf" || exit 0
        do_start &
        ;;
    stop)
        echo "Executing /etc/init/S29abortsplash"
        /etc/init.d/S29abortsplash stop
        ;;
    restart|reload)
        ;;
    *)
esac

exit $?
