#!/bin/bash

DAEMON="splash-ffplay"
DEFAULT="/usr/share/batocera/splash/splash.mp4"
SPLASH_DIR=/userdata/splash

FM_IMAGE=".*\.\(jpg\|jpeg\|png\)"
FM_VIDEO=".*\.\(mp4\|MP4\)"

. /etc/profile.d/xdg.sh
. /etc/profile.d/dbus.sh

soundDisabled()
{
    grep -qE "^[ ]*splash.screen.sound[ ]*=[ ]*0[ ]*$" /boot/batocera-boot.conf
}

do_filerandomize ()
{
    local array
    [[ -d "$SPLASH_DIR" ]] || return 1
    readarray -t array < <(find "$SPLASH_DIR" -regex "$1" -maxdepth 1 -type f)
    if [[ ${#array[@]} -gt 0 ]]; then
        echo "${array[$RANDOM % ${#array[@]}]}"
    fi
}

do_start()
{
    video_file=$(do_filerandomize "$FM_VIDEO")
    image_file=$(do_filerandomize "$FM_IMAGE")

    if [[ -n "$video_file" ]]; then
        do_videostart "$video_file"
    elif [[ -n "$image_file" ]]; then
        do_imagestart "$image_file"
    else
        do_videostart "$DEFAULT"
    fi
}

do_imagestart()
{
    image="$1"
    printf 'Image: %s: ' "$image"
    if test -e /dev/fb0
    then
        start-stop-daemon -S -b -q -m -p /var/run/user-splash-image.pid --exec fbv -- -f -i "$image"
    fi
}

do_videostart ()
{
    video="$1"
    printf 'Video: %s: ' "$video"
    ffplay_opt=
    if soundDisabled
    then
        ffplay_opt=-an
    fi
    start-stop-daemon -S -b -q -m -p /var/run/user-splash.pid --exec /usr/bin/ffplay -- $ffplay_opt -sync video -autoexit -vcodec h264_v4l2m2m -i "$video"
}

case "$1" in
    start)
        printf 'Starting %s: ' "$DAEMON"
        if grep -qE '^[ ]*splash.screen.enabled[ ]*=[ ]*0[ ]*$' "/boot/batocera-boot.conf"
        then
            echo "SKIPPED"
            exit 0
        fi
        do_start
        echo "OK"
        ;;
    stop)
        start-stop-daemon -K -q -p /var/run/user-splash.pid
        ;;
    restart|reload)
        ;;
    *)
esac

exit $?