## ENHANCED
default:
  # shader affects retroarch shaders
  shader: anti-aliasing/advanced-aa
  # scanline affect fba2x
  scanline: false
snes:
  shader: anti-aliasing/advanced-aa
nes:
  shader: anti-aliasing/advanced-aa
n64:
  shader: anti-aliasing/advanced-aa
gba:
  shader: handheld/zfast-lcd
gb:
  shader: handheld/zfast-lcd
gbc:
  shader: handheld/zfast-lcd
fds:
  shader: handheld/zfast-lcd
virtualboy:
  shader: handheld/zfast-lcd
# Sega
sg1000:
  shader: anti-aliasing/advanced-aa
mastersystem:
  shader: anti-aliasing/advanced-aa
megadrive:
  shader: anti-aliasing/advanced-aa
gamegear:
  shader: handheld/zfast-lcd
sega32x:
  shader: anti-aliasing/advanced-aa
segacd:
  shader: anti-aliasing/advanced-aa
# Arcade
neogeo:
  shader: scalehq/2xScaleHQ
neogeocd:
  shader: scalehq/2xScaleHQ
mame:
  shader: scalehq/2xScaleHQ
fba:
  shader: scalehq/2xScaleHQ
naomi:
  shader: scalehq/2xScaleHQ
atomiswave:
  shader: scalehq/2xScaleHQ
#
ngp:
  shader: handheld/zfast-lcd
ngpc:
  shader: handheld/zfast-lcd
gw:
  shader: anti-aliasing/advanced-aa
vectrex:
  shader: handheld/zfast-lcd
lynx:
  shader: handheld/zfast-lcd
lutro:
  shader: anti-aliasing/advanced-aa
wswan:
  shader: handheld/zfast-lcd
wswanc:
  shader: handheld/zfast-lcd
pcengine:
  shader: anti-aliasing/advanced-aa
pcenginecd:
  shader: anti-aliasing/advanced-aa
supergrafx:
  shader: anti-aliasing/advanced-aa
atari800:
  shader: anti-aliasing/advanced-aa
atari2600:
  shader: anti-aliasing/advanced-aa
atari5200:
  shader: anti-aliasing/advanced-aa
atari7800:
  shader: anti-aliasing/advanced-aa
prboom:
  shader: anti-aliasing/advanced-aa
psx:
  shader: scalehq/2xScaleHQ
colecovision:
  shader: anti-aliasing/advanced-aa
# Computers
msx:
  shader: anti-aliasing/advanced-aa
msx1:
  shader: anti-aliasing/advanced-aa
msx2:
  shader: anti-aliasing/advanced-aa
amiga:
  shader: anti-aliasing/advanced-aa
amstradcpc:
  shader: anti-aliasing/advanced-aa
atarist:
  shader: anti-aliasing/advanced-aa
zxspectrum:
  shader: anti-aliasing/advanced-aa
odyssey2:
  shader: anti-aliasing/advanced-aa
zx81:
  shader: anti-aliasing/advanced-aa
pcfx:
  shader: anti-aliasing/advanced-aa
x68000:
  shader: anti-aliasing/advanced-aa
