#!/bin/sh
#
# hciattach service
#

case "$1" in
  start)
	# allow bluetooth to reset
	echo 0 > /sys/class/rfkill/rfkill0/state
	sleep 1
	echo 1 > /sys/class/rfkill/rfkill0/state
	sleep 1

	# tinkerboard specific
	/usr/bin/hciattach -n /dev/ttyS0 rtk_h5 115200
        ;;
  stop)
	killall hciattach
	;;
  restart|reload)
        "$0" stop
        "$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


