#!/bin/bash

# shutdown-delay 1 => ask to stop. stop will be effective if no shutdown-delay 0 is done during the same time
# this is basically to be called with triggerhappy to shutdown only if a key remain pressed during 1 second
STATE=$1

if test "${STATE}" = "1"
then
    FLAGN=$$
    if echo "${FLAGN}" > /var/run/shutdown-delay.flag
    then
	# wait
	sleep 1

	# and see if flag is still there
	if test -e /var/run/shutdown-delay.flag
	then
	    # same content, aka, no released then repushed
	    REFLAGN=$(cat /var/run/shutdown-delay.flag)
	    if test "${FLAGN}" = "${REFLAGN}"
	    then
		shutdown -h now
	    fi
	fi
    fi
fi

if test "${STATE}" = "0"
then
    rm /var/run/shutdown-delay.flag
fi
