#! /bin/sh
#
# Start virtual-gamepads
#

systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/recalboxSettings.py"

case "$1" in
  start)
    enabled="`$systemsetting  -command load -key system.virtual-gamepads.enabled`"
    if [ "$enabled" == "0" ];then
      echo "Virtual-gamepads services: disabled"
      exit 0
    fi

    enabled="`$systemsetting  -command load -key system.security.enabled`"
    if [ "$enabled" == "1" ];then
      echo "Virtual-gamepads services: disabled (security)"
      exit 0
    fi
    
    echo "Starting virtual-gamepads server"
    cd /usr/node-virtual-gamepads/ 
    node main.js &
    ;;
  stop)
    echo -n "Stoping virtual-gamepads server"
    ps -ef | grep node | grep -v grep | awk '{print $1}' | xargs kill
    ;;
  restart|reload)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
    ;;
esac

exit 0

