LABEL batocera.linux
    LINUX /boot/linux
    FDT /boot/rk3562-kickpi-k3b.dtb
    FDTOVERLAYS /boot/overlays/rk3562-kickpi-k3b-demo-dsi-panel.dtbo
    APPEND initrd=/boot/initrd.lz4 label=BATOCERA rootwait quiet loglevel=0 console=tty3 console=ttyS0,1500000n8 vt.global_cursor_default=0
