#!/bin/bash

test "${ACTION}" = "add" || exit 0
echo "${DEVNAME}" | grep -E "^/dev/input/event[0-9]+$" || exit 0

WIIMOTEMODE=$(batocera-settings-get controllers.wiimote.mode)
test "${WIIMOTEMODE}" == 'gun' || exit 0 # gun mode not enabled

USBPATHHASH=$(echo "${ID_PATH}" | sed -e s+"\.[0-9]*$"++ | md5sum | cut -c 0-8)
NDEVS=$(cat "/var/run/virtual-wii-mouse-devices.${USBPATHHASH}" | wc -l)

echo "${DEVNAME} ${USBPATHHASH} ${ID_PATH}" >> /var/run/virtual-wii-mouse-devices.seen || exit 1

if test "${NDEVS}" = 1
then
    DEV1=$(head -1 "/var/run/virtual-wii-mouse-devices.${USBPATHHASH}")
    rm "/var/run/virtual-wii-mouse-devices.${USBPATHHASH}" || exit 1

    nohup evsieve --input "${DEV1}" "${DEVNAME}" grab persist=exit --map abs:hat0x abs:x --map abs:hat0y abs:y --map btn:mode btn:middle --map btn:east btn:left --map btn:south btn:right --output name="virtual wii mouse bar" 2>"/var/log/virtual-wii-mouse-devices.${USBPATHHASH}.log" &
else
    echo "${DEVNAME}" >> "/var/run/virtual-wii-mouse-devices.${USBPATHHASH}" || exit 1
fi
