LABEL batocera.linux
  LINUX /boot/linux
  FDT /boot/rk3576-anbernic-rg-vita-pro.dtb
  APPEND initrd=/boot/initrd.lz4 label=BATOCERA rootwait quiet loglevel=0 console=ttyFIQ0 console=tty3 coherent_pool=2M vt.global_cursor_default=0
