ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_RK3588)$(BR2_PACKAGE_BATOCERA_TARGET_RK3588_SDIO)$(BR2_PACKAGE_BATOCERA_TARGET_RK3562),y)

define LINUX_BATOCERA_INSTALL_IMAGES_DTBOVERLAYS
	mkdir -p $(BINARIES_DIR)/dtbos
	cp -p $(@D)/arch/arm64/boot/dts/rockchip/overlay/*.dtbo $(BINARIES_DIR)/dtbos
endef
LINUX_POST_INSTALL_IMAGES_HOOKS += LINUX_BATOCERA_INSTALL_IMAGES_DTBOVERLAYS

endif
