#!/bin/sh

case "$1" in
  start)
    echo "Setting Master volume to 255..."
    /usr/bin/amixer -c 1 set 'Master' 255 > /dev/null 2>&1
    ;;
  stop|restart|reload|force-reload)
    # Nothing to do here
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac

exit 0
