################################################################################
#
# ROCKCHIP MPP
#
################################################################################

ROCKCHIP_MPP_VERSION = fefa75939d51f32a70684c5106bd2b28715b4756
ROCKCHIP_MPP_SITE =  $(call github,HermanChen,mpp,$(ROCKCHIP_MPP_VERSION))
ROCKCHIP_MPP_INSTALL_STAGING = YES
ROCKCHIP_MPP_DEPENDENCIES = libdrm

ifneq (,$(findstring rk3328,$(BR2_LINUX_KERNEL_INTREE_DTS_NAME)))
	ROCKCHIP_MPP_CONF_OPTS +=-DENABLE_VP9D=ON
else
	ifneq (,$(findstring rk3399,$(BR2_LINUX_KERNEL_INTREE_DTS_NAME)))
		ROCKCHIP_MPP_CONF_OPTS +=-DENABLE_VP9D=ON
	else
		ROCKCHIP_MPP_CONF_OPTS +=-DENABLE_VP9D=OFF
	endif
endif

ROCKCHIP_MPP_CONF_OPTS += -DRKPLATFORM=ON -DENABLE_AVSD=OFF -DENABLE_H263D=OFF \
	-DENABLE_H264D=ON -DENABLE_H265D=ON -DENABLE_MPEG2D=ON -DENABLE_MPEG4D=ON \
	-DENABLE_VP8D=ON -DENABLE_JPEGD=OFF -DHAVE_DRM=ON

$(eval $(cmake-package))
