#!/bin/bash

for path in /sys/bus/sdio/devices/*; do
    if grep -q 0xc821 "$path/device"; then
        # get highest numbered available serial tty, which is probably going to stay unused.
        # lsof checks if its currently used
        for tty in $(printf "%s\n" /dev/ttyS* | /usr/bin/sort -V); do
            if ! /usr/bin/lsof | /bin/grep -q $tty ; then
                export BT_TTY_DEV=$tty
            fi
        done
        /usr/bin/bt_load_rtk_firmware;
        break
    fi
done
