#!/bin/bash

# stop rumble the rg351p
if test "${1}" = "start"
then
    echo 0 > /sys/class/pwm/pwmchip0/export
    echo 1000000 > /sys/class/pwm/pwmchip0/pwm0/period
    echo 1 > /sys/class/pwm/pwmchip0/pwm0/enable
    echo 1000000 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
fi
